/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import VersoManual
import AclGeom

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option pp.rawOnError true

#doc (Manual) "The hard kernel: loci, relocation, and correspondences" =>

%%%
tag := "hard-kernel"
%%%

The technical heart of the reconstruction theorem (blueprint §8, milestone
M3) shows that the additive and multiplicative structure of the field can be
recovered from the dependence geometry: any two-way finite correspondence
that commutes with addition on independent generic points is, after
normalization by additive polynomials, a power of Frobenius. This chapter
presents the stable lower layers of that argument. Everything here works
*elementwise with tuples* — a locus is the vanishing ideal of a tuple of
field elements, and no scheme-theoretic machinery is involved.

# Additive polynomials
%%%
tag := "additive-polynomials"
%%%

A polynomial is *additive* when it commutes with addition of points:

{docstring AclGeom.IsAdditive}

In characteristic zero additive polynomials are linear, while in
characteristic $`p` their support is concentrated on powers of $`p` — the
two classification facts feeding the endgame of the correspondence theorem:

{docstring AclGeom.IsAdditive.eq_C_mul_X}

{docstring AclGeom.IsAdditive.coeff_eq_zero_of_ne_pow}

The characteristic-$`p` statement rests on a Lucas-theorem argument
identifying the natural numbers all of whose lower binomial coefficients
vanish mod $`p`:

{docstring AclGeom.eq_pow_of_forall_dvd_choose}

The simultaneous-coset endgame also needs a support statement for polynomial
identities of binomial type:

{docstring AclGeom.eq_monomial_of_eq_smul_binomial}

# The loci dictionary
%%%
tag := "loci"
%%%

The locus $`\mathrm{Loc}_k(a)` of a tuple $`a` of elements of an extension
$`\Omega/k` is, in this formalization, its vanishing ideal:

{docstring AclGeom.idealOf}

{docstring AclGeom.idealOf_eq_bot_iff}

Vanishing ideals are equivariant under embeddings of the ambient field, and —
crucially for the genericity bookkeeping — they control the *relative*
dependence geometry of the coordinates. Two tuples with the same vanishing
ideal have coordinates in exactly the same `racl`-relations:

{docstring AclGeom.idealOf_comp_algHom}

{docstring AclGeom.mem_racl_image_of_idealOf_eq}

{docstring AclGeom.transcendental_of_idealOf_eq}

# Relocation of generic points
%%%
tag := "relocation"
%%%

Blueprint Lemma 8.1(b) provides *independent generic points*: inside an
algebraically closed ambient field, a finitely generated subextension embeds
over $`k` with prescribed images for a transcendence basis. The formalization
splits this into a purely transcendental part and an algebraic extension
part:

{docstring AclGeom.adjoinTranscendentalAlgHom}

{docstring AclGeom.exists_extension_of_isAlgebraic}

{docstring AclGeom.exists_relocation}

The joint form relocates one tuple over the field generated by another,
preserving all joint polynomial relations — this replaces the fiber-product
constructions of the classical argument:

{docstring AclGeom.exists_joint_relocation}

Relocations interact with the additive structure through substitution: a
joint-relation-preserving relocation preserves the loci of componentwise sums
and differences.

{docstring AclGeom.idealOf_add_eq_of_joint}

{docstring AclGeom.idealOf_sub_eq_of_joint}

# The additive correspondence theorem: state of the argument
%%%
tag := "additive-correspondence"
%%%

The hypothesis block of blueprint Theorem 8.8 packages two finite
correspondences with independent generic points and interalgebraic sums:

{docstring AclGeom.AddCorrSetup}

The fused curve-coset chain proceeds by relocating the second pair over the
base $`k(x_1, y_1)`:

{docstring AclGeom.AddCorrSetup.exists_pair_relocation}

The relocated pair inherits the entire correspondence structure — it is
still a two-way finite correspondence, its first coordinate is still generic
over the base, and its sum pair is a generic point of the *same*
one-dimensional sum locus:

{docstring AclGeom.AddCorrSetup.JointRel.snd_mem}

{docstring AclGeom.AddCorrSetup.JointRel.sum_snd_mem}

{docstring AclGeom.AddCorrSetup.JointRel.sum_fst_transcendental}

Finally, the δ-side genericity count: with the fresh element chosen
independent of $`\{x_1, x_2\}`, the relocated sum point remains generic over
the field generated by the translation element $`\delta = c_2 - c_2'`. This
is the input to the generic-translation-invariance step of the argument.

{docstring AclGeom.AddCorrSetup.JointRel.sum_fst_notMem_delta}

# The curve ideal and base change
%%%
tag := "curve-ideal"
%%%

The sum locus is a plane curve, and its vanishing ideal is generated by a
single prime polynomial — a height-one prime of $`k[X,Y]`, located between
the zero ideal and a maximal ideal in a ring of Krull dimension two:

{docstring AclGeom.exists_prime_span_idealOf}

The delicate point is that the generator stays prime after extending
scalars to the field $`k(\delta)` generated by the translation element.
This *base-change irreducibility* is proved without any tensor-product
regularity: the minimal polynomial over the extended field descends
coefficientwise, by a Gauss-lemma integrality argument combined with a
specialization brick — over an infinite field algebraically closed in
`K`, an element of `K(u)` algebraic over `k(u)` already lies in `k(u)`:

{docstring AclGeom.mem_adjoin_base_of_isAlgebraic}

{docstring AclGeom.minpoly_coeff_mem}

{docstring AclGeom.idealOf_map_eq_span}

# The exact translation identity
%%%
tag := "translation-identity"
%%%

A translation substitution perturbs a polynomial only strictly below its
top total degree, so a translation that fixes the ideal generated by `F`
fixes `F` itself:

{docstring AclGeom.translate_eq_self_of_span_eq}

Combining base-change irreducibility at both sum points with the transport
of vanishing ideals along translations yields the exact identity for the
sum-locus generator over $`k(\delta)`:

{docstring AclGeom.AddCorrSetup.JointRel.translate_deltaVec_eq}

The identity then descends from the generic point to every point of the
translation locus, whose coordinates are interalgebraic — the locus is a
genuine curve:

{docstring AclGeom.translate_eq_of_idealOf_le}

{docstring AclGeom.not_algebraicIndependent_of_translate_eq}

{docstring AclGeom.AddCorrSetup.JointRel.exists_prime_span_delta}

# The multiplicative correspondence theorem: state of the argument
%%%
tag := "multiplicative-correspondence"
%%%

The multiplicative chain (blueprint Theorem 8.9) runs in parallel with the
additive one — products replace sums, and the ratio element
$`\rho = c_2 / c_2'` replaces the translation element $`\delta`:

{docstring AclGeom.MulCorrSetup}

{docstring AclGeom.MulCorrSetup.exists_pair_relocation}

{docstring AclGeom.MulCorrSetup.exists_prime_span_mul}

The genericity counts go through with division playing the role of
subtraction, and the same base-change machinery applies over $`k(\rho)`.
The structural difference appears at the rigidity step: a scaling
substitution multiplies each monomial coefficient by the monomial value of
the scaling vector, so instead of an exact fixed-point identity the chain
produces *monomial relations* on $`\rho`:

{docstring AclGeom.scale}

{docstring AclGeom.monomial_prod_eq_of_span_scale_eq}

{docstring AclGeom.MulCorrSetup.JointRel.monomial_prod_rhoVec_eq}

These relations are nontrivial — a single monomial cannot vanish at the
nowhere-zero product point — which forces the coordinates of $`\rho` to be
interalgebraic: the ratio locus is a genuine curve.

{docstring AclGeom.exists_support_pair_of_aeval_eq_zero}

{docstring AclGeom.MulCorrSetup.JointRel.rho_snd_mem}

{docstring AclGeom.MulCorrSetup.JointRel.exists_prime_span_rho}

# The multiplicative endgame
%%%
tag := "multiplicative-endgame"
%%%

The classical endgame identifies the one-dimensional stabilizer subgroup
with the kernel of a character of $`\mathbb G_m^2` and reads off the coset
equations. The formalization takes a shorter, purely elementwise route.
The scaling relation at a support difference $`d = m - m'` of the
product-locus generator says exactly that the monomial value
$`\mu = (x_1x_2)^{d_0}(y_1y_2)^{d_1}` is *invariant under relocation* of
the second pair. An element algebraic over two independent extensions of a
common base is algebraic over the base — an exchange argument:

{docstring AclGeom.mem_racl_of_mem_racl_insert}

Applying this twice — against the fresh transcendental direction, then
against the generic direction of the product point itself — drops $`\mu`
into $`k`:

{docstring AclGeom.MulCorrSetup.JointRel.zpow_rho_support_eq_one}

{docstring AclGeom.MulCorrSetup.JointRel.exists_algebraMap_eq_zpow_mul}

Splitting $`\mu` along the independence of the two correspondence pairs
and descending each factor the same way yields both coset equations with
the same exponents, which are nonzero because algebraicity descends along
nonzero integer powers:

{docstring AclGeom.mem_racl_empty_of_zpow}

{docstring AclGeom.MulCorrSetup.exists_coset_equations}

This completes the multiplicative correspondence theorem (blueprint
Theorem 8.9).

# The additive endgame
%%%
tag := "additive-endgame"
%%%

The additive side classifies the δ-curve itself. Its generator is
canonical — independent of the relocation used to construct it — by
joint-type determination along the correspondence curve:

{docstring AclGeom.joint_idealOf_eq}

{docstring AclGeom.AddCorrSetup.delta_idealOf_eq_of_two_relocations}

A second, independent relocation then produces an independent generic
point of the *same* curve, and the exact translation identity at the
correspondence curve pushes their sum back onto it — the group chunk —
while a transfer to the diagonal puts the origin on the curve:

{docstring AclGeom.AddCorrSetup.JointRel.translate_pair_eq}

{docstring AclGeom.AddCorrSetup.JointRel.chunk_add}

{docstring AclGeom.AddCorrSetup.JointRel.constantCoeff_delta_gen}

The chunk upgrades to the Hopf identity in exact form — the generator is
fixed by translation by its own generic point — and then to full
additivity by the division argument: the additivity defect is a multiple
of the generator in each variable block, the block extensions are coprime
primes, and the total degree leaves no room for their product.

{docstring AclGeom.AddCorrSetup.JointRel.translate_delta_self_eq}

{docstring AclGeom.mem_span_rename_inl_of_aevalFst_eq_zero}

{docstring AclGeom.AddCorrSetup.JointRel.addSubst_delta_gen_eq}

The coset constants descend to `k` by the same relocation-invariance and
double-exchange argument as in the multiplicative endgame, and splitting
the generator into its one-variable specializations produces the additive
polynomials of the classification:

{docstring AclGeom.AddCorrSetup.JointRel.exists_coset_constants}

{docstring AclGeom.AddCorrSetup.exists_coset_equations}

This is the two-pair core of the additive correspondence theorem
(blueprint Theorem 8.8). The three-pair statement, the simultaneous-coset
lemma, and the rigidity of `j` (blueprint 8.10) are the remaining steps of
the hard kernel; progress is tracked on the project's issue tracker.
