/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import VersoManual
import AclGeom

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option pp.rawOnError true

#doc (Manual) "The hard kernel: loci, relocation, and correspondences" =>

%%%
tag := "hard-kernel"
%%%

The technical heart of the reconstruction theorem (blueprint §8, milestone
M3) shows that the additive and multiplicative structure of the field can be
recovered from the dependence geometry: any two-way finite correspondence
that commutes with addition on independent generic points is, after
normalization by additive polynomials, a power of Frobenius. This chapter
presents the stable lower layers of that argument. Everything here works
*elementwise with tuples* — a locus is the vanishing ideal of a tuple of
field elements, and no scheme-theoretic machinery is involved.

# Additive polynomials
%%%
tag := "additive-polynomials"
%%%

A polynomial is *additive* when it commutes with addition of points:

{docstring AclGeom.IsAdditive}

In characteristic zero additive polynomials are linear, while in
characteristic $`p` their support is concentrated on powers of $`p` — the
two classification facts feeding the endgame of the correspondence theorem:

{docstring AclGeom.IsAdditive.eq_C_mul_X}

{docstring AclGeom.IsAdditive.coeff_eq_zero_of_ne_pow}

The characteristic-$`p` statement rests on a Lucas-theorem argument
identifying the natural numbers all of whose lower binomial coefficients
vanish mod $`p`:

{docstring AclGeom.eq_pow_of_forall_dvd_choose}

The simultaneous-coset endgame also needs a support statement for polynomial
identities of binomial type:

{docstring AclGeom.eq_monomial_of_eq_smul_binomial}

# The loci dictionary
%%%
tag := "loci"
%%%

The locus $`\mathrm{Loc}_k(a)` of a tuple $`a` of elements of an extension
$`\Omega/k` is, in this formalization, its vanishing ideal:

{docstring AclGeom.idealOf}

{docstring AclGeom.idealOf_eq_bot_iff}

Vanishing ideals are equivariant under embeddings of the ambient field, and —
crucially for the genericity bookkeeping — they control the *relative*
dependence geometry of the coordinates. Two tuples with the same vanishing
ideal have coordinates in exactly the same `racl`-relations:

{docstring AclGeom.idealOf_comp_algHom}

{docstring AclGeom.mem_racl_image_of_idealOf_eq}

{docstring AclGeom.transcendental_of_idealOf_eq}

# Relocation of generic points
%%%
tag := "relocation"
%%%

Blueprint Lemma 8.1(b) provides *independent generic points*: inside an
algebraically closed ambient field, a finitely generated subextension embeds
over $`k` with prescribed images for a transcendence basis. The formalization
splits this into a purely transcendental part and an algebraic extension
part:

{docstring AclGeom.adjoinTranscendentalAlgHom}

{docstring AclGeom.exists_extension_of_isAlgebraic}

{docstring AclGeom.exists_relocation}

The joint form relocates one tuple over the field generated by another,
preserving all joint polynomial relations — this replaces the fiber-product
constructions of the classical argument:

{docstring AclGeom.exists_joint_relocation}

Relocations interact with the additive structure through substitution: a
joint-relation-preserving relocation preserves the loci of componentwise sums
and differences.

{docstring AclGeom.idealOf_add_eq_of_joint}

{docstring AclGeom.idealOf_sub_eq_of_joint}

# The additive correspondence theorem: state of the argument
%%%
tag := "additive-correspondence"
%%%

The hypothesis block of blueprint Theorem 8.8 packages two finite
correspondences with independent generic points and interalgebraic sums:

{docstring AclGeom.AddCorrSetup}

The fused curve-coset chain proceeds by relocating the second pair over the
base $`k(x_1, y_1)`:

{docstring AclGeom.AddCorrSetup.exists_pair_relocation}

The relocated pair inherits the entire correspondence structure — it is
still a two-way finite correspondence, its first coordinate is still generic
over the base, and its sum pair is a generic point of the *same*
one-dimensional sum locus:

{docstring AclGeom.AddCorrSetup.JointRel.snd_mem}

{docstring AclGeom.AddCorrSetup.JointRel.sum_snd_mem}

{docstring AclGeom.AddCorrSetup.JointRel.sum_fst_transcendental}

Finally, the δ-side genericity count: with the fresh element chosen
independent of $`\{x_1, x_2\}`, the relocated sum point remains generic over
the field generated by the translation element $`\delta = c_2 - c_2'`. This
is the input to the generic-translation-invariance step of the argument.

{docstring AclGeom.AddCorrSetup.JointRel.sum_fst_notMem_delta}

# The curve ideal and base change
%%%
tag := "curve-ideal"
%%%

The sum locus is a plane curve, and its vanishing ideal is generated by a
single prime polynomial — a height-one prime of $`k[X,Y]`, located between
the zero ideal and a maximal ideal in a ring of Krull dimension two:

{docstring AclGeom.exists_prime_span_idealOf}

The delicate point is that the generator stays prime after extending
scalars to the field $`k(\delta)` generated by the translation element.
This *base-change irreducibility* is proved without any tensor-product
regularity: the minimal polynomial over the extended field descends
coefficientwise, by a Gauss-lemma integrality argument combined with a
specialization brick — over an infinite field algebraically closed in
`K`, an element of `K(u)` algebraic over `k(u)` already lies in `k(u)`:

{docstring AclGeom.mem_adjoin_base_of_isAlgebraic}

{docstring AclGeom.minpoly_coeff_mem}

{docstring AclGeom.idealOf_map_eq_span}

# The exact translation identity
%%%
tag := "translation-identity"
%%%

A translation substitution perturbs a polynomial only strictly below its
top total degree, so a translation that fixes the ideal generated by `F`
fixes `F` itself:

{docstring AclGeom.translate_eq_self_of_span_eq}

Combining base-change irreducibility at both sum points with the transport
of vanishing ideals along translations yields the exact identity for the
sum-locus generator over $`k(\delta)`:

{docstring AclGeom.AddCorrSetup.JointRel.translate_deltaVec_eq}

The identity then descends from the generic point to every point of the
translation locus, whose coordinates are interalgebraic — the locus is a
genuine curve:

{docstring AclGeom.translate_eq_of_idealOf_le}

{docstring AclGeom.not_algebraicIndependent_of_translate_eq}

{docstring AclGeom.AddCorrSetup.JointRel.exists_prime_span_delta}

# The multiplicative correspondence theorem: state of the argument
%%%
tag := "multiplicative-correspondence"
%%%

The multiplicative chain (blueprint Theorem 8.9) runs in parallel with the
additive one — products replace sums, and the ratio element
$`\rho = c_2 / c_2'` replaces the translation element $`\delta`:

{docstring AclGeom.MulCorrSetup}

{docstring AclGeom.MulCorrSetup.exists_pair_relocation}

{docstring AclGeom.MulCorrSetup.exists_prime_span_mul}

The genericity counts go through with division playing the role of
subtraction, and the same base-change machinery applies over $`k(\rho)`.
The structural difference appears at the rigidity step: a scaling
substitution multiplies each monomial coefficient by the monomial value of
the scaling vector, so instead of an exact fixed-point identity the chain
produces *monomial relations* on $`\rho`:

{docstring AclGeom.scale}

{docstring AclGeom.monomial_prod_eq_of_span_scale_eq}

{docstring AclGeom.MulCorrSetup.JointRel.monomial_prod_rhoVec_eq}

These relations are nontrivial — a single monomial cannot vanish at the
nowhere-zero product point — which forces the coordinates of $`\rho` to be
interalgebraic: the ratio locus is a genuine curve.

{docstring AclGeom.exists_support_pair_of_aeval_eq_zero}

{docstring AclGeom.MulCorrSetup.JointRel.rho_snd_mem}

{docstring AclGeom.MulCorrSetup.JointRel.exists_prime_span_rho}

The remaining endgames — the classification of the translation-invariant
generator through the additive-polynomial library on the additive side, and
the exponent-lattice argument extracting the binomial equation
$`X^mY^n = c` on the multiplicative side — are under construction; their
progress is tracked on the project's issue tracker.
