/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import VersoManual
import AclGeom

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option pp.rawOnError true

#doc (Manual) "Transfer to arbitrary fields" =>

%%%
tag := "transfer"
%%%

Gismatullin's transfer principle (blueprint §9, milestone M5) moves the
correctness of the geometric relations from algebraically closed fields to
arbitrary perfect fields with a relatively algebraically closed base. The
statements the proof transfers are Boolean combinations of
closure-membership assertions, so no first-order syntax is formalized: the
entire principle reduces to three pieces of field theory about the
closures `racl k A` inside a fixed algebraically closed overfield.

# A field is not a finite union of proper subfields
%%%
tag := "no-field-cover"
%%%

The pigeonhole underlying the transfer (blueprint Lemma no-field-cover) is
proved from mathlib's B. H. Neumann coset-cover theorem applied to the
additive subgroups: some covering subfield has finite additive index; a
proper *infinite* subfield of finite index is impossible, because
multiplication by an outside element injects it into the quotient; and a
finite subfield of finite index forces the whole field to be finite, where
cyclicity of the unit group hands the covering to a single subfield.

{docstring AclGeom.exists_eq_top_of_subfield_cover}

{docstring AclGeom.exists_notMem_of_ne_top}

# Finite generators for intersections
%%%
tag := "intersection-generators"
%%%

The transfer needs intersections `racl k A ⊓ racl k B` to again be
finitely generated closures, with generators inside any prescribed field
`K₁` containing `A` and `B` (blueprint Lemma
finite-intersection-generator). The formalization diverges from the
blueprint proof twice, in both cases replacing infrastructure by a
computation:

* the transcendence-degree bookkeeping runs through mathlib's
  *algebraic-independence matroid*, whose closure operator is exactly
  `racl` — a matroid basis of the intersection's carrier is finite because
  it is an independent set inside the closure of the finite set `A`;

{docstring AclGeom.mem_matroidClosure_iff}

* the blueprint extends `K₁`-embeddings to automorphisms of `Ω` to see
  that the conjugates of a basis element stay in the intersection; the
  formal proof instead uses divisibility of minimal polynomials — an
  annihilator over `k(A)` with coefficients in `K₁` is divisible by the
  `K₁`-minimal polynomial, so all conjugates satisfy it:

{docstring AclGeom.conjugate_mem_racl}

The generators are then the coefficients of the minimal polynomials of the
basis elements: they lie in `K₁` by construction, and in the intersection
because a monic split polynomial's coefficients live wherever its roots
do.

{docstring AclGeom.coeff_mem_of_roots_mem}

{docstring AclGeom.exists_finite_inter_generator}

Only one of the two sets needs to be finite, a slight strengthening of the
blueprint statement that costs nothing.

# Strict-inclusion transfer
%%%
tag := "strict-transfer"
%%%

Properness of an inclusion of traced closures transfers between any two
fields `K₁ ≤ K₂` over which the data is defined (blueprint Lemma
strict-transfer): downward, a witness in `K₂` would have its `k(B)`-minimal
polynomial's coefficients trapped in the trace equality on `K₁`, making it
algebraic over the smaller closure.

{docstring AclGeom.inf_lt_inf_iff_of_le}

# The one-quantifier transfer
%%%
tag := "one-quantifier"
%%%

The three bricks assemble into the transfer principle (blueprint Theorem
one-quantifier-transfer). A disjunct of the normal form is a conjunction
of memberships `z ∈ racl k (Aᵢ)` and non-memberships `z ∉ racl k (Bⱼ)`;
iterating the intersection generator fuses the memberships into a single
closure `racl k C`, on which each excluded closure traces as another
finitely generated closure:

{docstring AclGeom.exists_finite_iInter_generator}

A witness in `K` exists exactly when the subfield `racl k C ⊓ K` is not
covered by the traced subfields — the relative no-field-cover:

{docstring AclGeom.exists_intermediateField_eq_of_subset_iUnion}

Each covering equality is the negation of a strict inclusion, which
transfers between `K₁` and `K₂`. As long as at least one membership
conjunct is present, no transcendence-degree hypothesis is needed:

{docstring AclGeom.one_quantifier_transfer}

The no-membership case has two branches, exactly as in blueprint (9.4).
For equal finite transcendence degrees, a transcendence basis of the smaller
field is finite and is also a basis of the larger field, producing one
finite relative-algebraic envelope for both:

{docstring AclGeom.exists_finite_racl_envelope_of_trdeg_eq}

If both degrees are infinite, every excluded closure generated by a finite
set is proper by cardinality, and finite-subfield avoidance supplies a
common point:

{docstring AclGeom.exists_avoid_finite_racl_of_aleph0_le_trdeg}

Combining the main case with these two branches gives the full theorem for
an arbitrary finite list of positive and negative conjuncts:

{docstring AclGeom.one_quantifier_transfer_full}

# Transcendence degree supplies freshness
%%%
tag := "trdeg-freshness"
%%%

The configuration and descent proofs initially expose their use of fresh
elements as a small oracle.  The blueprint's rank-five hypothesis discharges
that oracle uniformly: if a finite parameter set had no element outside its
relative algebraic closure, the whole ambient field would be algebraic over
the ring generated by that set, forcing transcendence degree at most its
cardinality.

{docstring AclGeom.exists_notMem_racl_of_mk_lt_trdeg}

{docstring AclGeom.fresh_four_of_five_le_trdeg}

Consequently the soundness arrows for all three configuration predicates
now have their final rank-five statements, including the `(1) ⇒ (4)` arrow
of the descent theorem:

{docstring AclGeom.qGeom_of_qSem_of_five_le_trdeg}

{docstring AclGeom.q'Geom_of_q'Sem_of_five_le_trdeg}

{docstring AclGeom.jGeom_of_jSem_of_five_le_trdeg}

# Toward descent
%%%
tag := "descent-foundation"
%%%

The remaining piece of this layer is the application to the geometric
`J`-predicate (blueprint §9's descent theorem), whose foundations are in
place. The opening line of the blueprint's proof — the point geometry of a
subextension embeds in that of the ambient field — is the ambient
invariance of `racl`, proved by transporting ambient-coefficient
annihilators along the inclusion:

{docstring AclGeom.coe_mem_racl_image_iff}

The `(2) ⇒ (1)` arrow (descent of a semantic `j`-tuple to a perfect
subfield) is prepared by a *finite Galois* replacement for the blueprint's
automorphism argument: instead of extending conjugations to automorphisms
of `Ω` and iterating against an infinite orbit, a finite-order `σ` with
j-rigidity output `(σx)^{q^v} = x^{q^u}` telescopes through one full
period to `x^{q^{rv}} = x^{q^{ru}}`, forcing the exponents to agree and
`σ` to fix `x` outright:

{docstring AclGeom.orbit_exponent_eq}

{docstring AclGeom.ringHom_fix_of_pow_orbit}

The brick is packaged at the level of an abstract finite Galois
extension — every automorphism has finite order, so an element on which
the whole group acts by Frobenius twists is fixed pointwise and lies in
the base field:

{docstring AclGeom.mem_bot_of_forall_algEquiv_frobenius}

Two more foundations close the gap to the assembly. Closures are
insensitive to enlarging the base by algebraic elements — this is how
statements over `k̄` (where j-rigidity lives) and over `k` (where the
Galois conjugation lives) exchange freely, and it makes pair independence
transfer as well:

{docstring AclGeom.mem_racl_base_iff_of_algebraic}

{docstring AclGeom.algebraicIndependent_pair_base_of_algebraic}

And any two elements algebraic over a perfect subfield lie in a finite
Galois subextension — the splitting field of the product of their minimal
polynomials, with separability supplied by perfectness:

{docstring AclGeom.exists_finiteDimensional_isGalois_mem}

The assembly is complete: if all five coordinates of a j-value are
interalgebraic with elements of a perfect subfield, the underlying pair
descends. Every automorphism of the envelope preserves the five
coordinate closures (conjugation transport through the fixed
representatives), so j-rigidity applies over the algebraically closed
base — reachable by base insensitivity — and hands each automorphism's
action to the fixing brick:

{docstring AclGeom.conj_relation_of_fixed}

{docstring AclGeom.mem_of_j_represented}

The rank-five public interface derives the two fresh elements directly
from transcendence degree:

{docstring AclGeom.mem_of_j_represented_of_five_le_trdeg}

This completes the `(2) ⇒ (1)` arrow of the blueprint's descent theorem; the
`(1) ⇒ (4)` arrow is the soundness half of the configuration layer
(proved over any infinite base), and the equivalence `(2) ⇔ (3)` is the
ACF-correctness of `J`, whose completeness half is the remaining open
engine of the configuration milestone.
