/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Closure.Basic
import AclGeom.Closure.Ambient
import AclGeom.Closure.ClosedLattice
import AclGeom.Geometry.Points
import AclGeom.Geometry.Equivalence
import AclGeom.Geometry.FiniteRank
import AclGeom.Perfection.Subfield
import AclGeom.Perfection.Lattice
import AclGeom.Correspondence.AddPolynomial
import AclGeom.Correspondence.FunctionField
import AclGeom.Correspondence.Regular
import AclGeom.Correspondence.GenericPoints
import AclGeom.Correspondence.Composition
import AclGeom.Correspondence.FiniteCover
import AclGeom.Correspondence.AlgebraicClosureTransport
import AclGeom.Correspondence.FiniteNormalTransport
import AclGeom.Correspondence.BranchGroupoid
import AclGeom.Correspondence.Family
import AclGeom.Correspondence.RankTwoMultiplication
import AclGeom.Correspondence.FamilyNormalization
import AclGeom.Correspondence.FamilyGroupoid
import AclGeom.Correspondence.PartialQuadrangle
import AclGeom.Correspondence.Moebius
import AclGeom.Correspondence.CurveIdeal
import AclGeom.Correspondence.BaseChange
import AclGeom.Correspondence.Binomial
import AclGeom.Correspondence.TranslationDescent
import AclGeom.Correspondence.GroupChunk
import AclGeom.Correspondence.AlgebraicGroup
import AclGeom.Correspondence.WeilGluing
import AclGeom.Correspondence.FiniteExtensionChart
import AclGeom.Correspondence.BirationalGluing
import AclGeom.Correspondence.GroupConfiguration
import AclGeom.Correspondence.AffineAction
import AclGeom.Correspondence.Additive
import AclGeom.Curves.Adeles
import AclGeom.Curves.Approximation
import AclGeom.Curves.Canonical
import AclGeom.Curves.DegreeBound
import AclGeom.Curves.Derivations
import AclGeom.Curves.Differentials
import AclGeom.Curves.Divisors
import AclGeom.Curves.Genus
import AclGeom.Curves.GlobalResidue
import AclGeom.Curves.InfinitesimalAutomorphisms
import AclGeom.Curves.Places
import AclGeom.Curves.Rational
import AclGeom.Curves.RationalAutomorphisms
import AclGeom.Curves.Residues
import AclGeom.Curves.RiemannRoch
import AclGeom.Curves.Specialty
import AclGeom.Curves.TateResidue
import AclGeom.Tate.FinitePotent
import AclGeom.Correspondence.Multiplicative
import AclGeom.Correspondence.JRigidity
import AclGeom.Config.Language
import AclGeom.Config.Semantic
import AclGeom.Config.Psi
import AclGeom.Config.CompositionIdentity
import AclGeom.Config.ChunkProjection
import AclGeom.Config.ChunkBranchCover
import AclGeom.Config.ChunkAlgebraicChart
import AclGeom.Config.ChunkRelationCover
import AclGeom.Config.ChunkNormalizedChart
import AclGeom.Config.ChunkFieldAction
import AclGeom.Config.ChunkFiniteFieldAction
import AclGeom.Config.WitnessTable
import AclGeom.Config.Quadrangle
import AclGeom.Config.MeetEquations
import AclGeom.Config.AtomClause
import AclGeom.Config.Soundness
import AclGeom.Config.AffineGrid
import AclGeom.Config.MulDiagramCheck
import AclGeom.Config.Multiplication
import AclGeom.Transfer.FiniteUnion
import AclGeom.Transfer.Intersections
import AclGeom.Transfer.OneQuantifier
import AclGeom.Transfer.Transcendence
import AclGeom.Transfer.Descent
import AclGeom.Config.Correctness
import AclGeom.Interpretation.FrobClass
import AclGeom.Interpretation.GenericOps
import AclGeom.Interpretation.Ratio
import AclGeom.Interpretation.Field
import AclGeom.Reconstruct.Base
import AclGeom.Reconstruct.Points
import AclGeom.Reconstruct.Kernel
import AclGeom.Functorial.Literal
import AclGeom.Functorial.FrobeniusQuotient
import AclGeom.Main
import AclGeom.MathlibAudit
import AclGeom.Test.RationalFunctionField
import AclGeom.Test.ConfigRank
