/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import VersoManual
import AclGeom.Config.ChunkCurveCommonSourceComparison
import AclGeom.Config.ChunkCurveCommonSourceExistence
import AclGeom.Config.ChunkCurveCommonSourceRebasing

/-!
Focused section of the configuration book (#18). This preserves the frozen
M4a declaration record; the group/action and extraction conclusions remain
open as described by its parent section and issues #12/#19/#21/#22.
-/

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option pp.rawOnError true

#doc (Manual) "Common source covers and coefficient presentations" =>

%%%
tag := "configuration-record-common-source-covers"
%%%

The selected composition triangle can now be moved over an arbitrary point
of the rank-two parameter multiplication locus without relocating its three
curve branches independently.  After choosing one source generic over the
six displayed parameters, the complete nine-coordinate
`(a,b,c,x,y,z)` tuple is relocated at once.  Its three restrictions retain
the selected `A`, `B`, and `C` family prime loci, so their source, middle,
and target coordinates match literally:

{docstring AclGeom.QWitness.psiCurveCompositionTuple}

{docstring AclGeom.QWitness.psiSelectedCurveCompositionTuple_mem_parameterSource_racl}

{docstring AclGeom.QWitness.exists_psiCurveCompositionRealization}

{docstring AclGeom.QWitness.PsiCurveCompositionRealization.aFamilyLocus}

{docstring AclGeom.QWitness.PsiCurveCompositionRealization.bFamilyLocus}

{docstring AclGeom.QWitness.PsiCurveCompositionRealization.cFamilyLocus}

Equal family loci can now be promoted back to generic family members in
every parameter dimension, not only in the earlier one-parameter special
case:

{docstring AclGeom.FiniteCorrespondenceFamilyMember.ofTupleIdealEq}

Generic family members and their complete loci also transport along ambient
field embeddings.  Conversely, complete-locus equality already transfers
the independent parameter/source prefix, so callers need not reconstruct
that independence separately:

{docstring AclGeom.FiniteCorrespondenceFamilyMember.map}

{docstring AclGeom.FiniteCorrespondenceFamilyMember.ofTupleIdealEqOnly}

For the relocated Ψ triangle this packages all three restrictions as
rank-two family members and then as finite-correspondence pairs over the
one field generated by all six parameters.  A reusable normalization
construction enlarges the source cover by the left branch, the pulled-back
right branch, and the direct branch.  The vertical deck defect restricts by
normality, yielding a literal finite-cover identity:

{docstring AclGeom.FiniteCorrespondencePair.FiniteCoverTriangle.strictComposition}

{docstring AclGeom.QWitness.PsiCurveCompositionRealization.aCorrespondenceFamilyMember}

{docstring AclGeom.QWitness.PsiCurveCompositionRealization.bCorrespondenceFamilyMember}

{docstring AclGeom.QWitness.PsiCurveCompositionRealization.cCorrespondenceFamilyMember}

{docstring AclGeom.QWitness.PsiCurveCompositionRealization.finiteCoverStrictComposition}

For the four-arrow difference component, the original eight-coordinate
genericity hypothesis supplies an explicit fresh curve source on every
edge: one unused ambient input coordinate.  The three intermediate
eight-tuples remain independent after each finite parameter replacement,
so all four curve triangles can be constructed together:

{docstring AclGeom.RankTwoFiniteCorrespondenceMultiplication.FourArrowDifferenceDiagram.s_sA_a_uB_independent}

{docstring AclGeom.QWitness.exists_psiCurveFourArrowRealizations}

{docstring AclGeom.QWitness.PsiCurveFourArrowRealizations.finiteCoverStrictCompositions}

Those edgewise sources cannot be used after enlarging coefficients to the
whole eight-input field, because each is itself one of the eight inputs.  A
single genuinely fresh coordinate is obtained by passing to the algebraic
closure of the rational-function field over the original ambient field.
Its formal variable is transcendental over that entire field and therefore
generic over every embedded parameter edge:

{docstring AclGeom.CommonCurveAmbient}

{docstring AclGeom.commonCurveSource_transcendental}

{docstring AclGeom.commonCurveSource_notMem_racl}

Ambient invariance transports the complete selected Ψ locus along the
canonical embedding.  The same relocation theorem then fixes the mapped
edge parameters together with the one formal source.  Applying it four
times produces four complete curve triangles whose sources agree literally,
which is the first coefficient-compatible cross-edge identification:

{docstring AclGeom.QWitness.exists_psiCurveCompositionBaseChangeRealization}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations}

{docstring AclGeom.QWitness.exists_psiCurveFourArrowCommonSourceRealizations}

The embedded A/B/C restrictions are genuine generic members of the mapped
families.  Although the selected auxiliary blocks `u`, `sA`, `uB`, and `c`
need not belong to the eight-input field, all their coordinates are
algebraic over it.  This is exactly enough to regard every branch as a
finite correspondence over one common coefficient field.  The middle
coordinate remains generic there because it is interalgebraic with the
formal source:

{docstring AclGeom.QWitness.PsiCurveCompositionBaseChangeRealization.aCorrespondenceFamilyMember}

{docstring AclGeom.QWitness.PsiCurveCompositionBaseChangeRealization.CommonBaseData}

{docstring AclGeom.QWitness.PsiCurveCompositionBaseChangeRealization.CommonBaseData.middle_generic}

Each of the four faces therefore has a strict deck-corrected finite-cover
composition triangle over the same eight-input coefficient field, with the
same literal source coordinate:

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seFiniteCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAaFiniteCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sbFiniteCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAcFiniteCoverCompositionTriangle}

Strict composition is stable under enlarging the source normalization: any
finite normal source cover can be transported through the left branch and
the two-step chain, and the same deck correction gives a literal triangle.
Taking the compositum of the four facewise source covers therefore produces
one finite normal field that contains every selected branch normalization.
All four actions are now transported from that exact same source field:

{docstring AclGeom.FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonFiniteSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seFiniteSourceCover_le_common}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAaFiniteSourceCover_le_common}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sbFiniteSourceCover_le_common}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAcFiniteSourceCover_le_common}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seCommonCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAaCommonCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sbCommonCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAcCommonCoverCompositionTriangle}

The repeated-locus comparison retains more than an abstract endpoint-field
isomorphism.  For a generic family member, the complete `(parameter,
source,target)` field is finite over `(parameter,source)`.  Equality of
complete family loci canonically identifies this extension coordinate by
coordinate, lifts it to the concrete normal closures, and applies one deck
correction so that the literal selected branch is preserved:

{docstring AclGeom.FiniteCorrespondenceFamilyMember.parameterSourceField}

{docstring AclGeom.FiniteCorrespondenceFamilyMember.familyOverParameterSource_finiteDimensional}

{docstring AclGeom.FiniteCorrespondenceFamilyMember.extensionEquivOfIdealEq}

{docstring AclGeom.FiniteCorrespondenceFamilyMember.extensionEquivOfIdealEq_base_apply}

{docstring AclGeom.FiniteCorrespondenceFamilyMember.normalCoverEquivOfIdealEq_algebraMap}

{docstring AclGeom.FiniteCorrespondenceFamilyMember.basedBranchEquivOfIdealEq_selected}

The independently relocated occurrences of `s`, `sA`, `u`, and `uB` have
equal complete family loci.  They consequently carry four such based,
coefficient-aware comparisons before scalar extension to the entire
eight-input field:

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seAFamily_ideal_eq_sbAFamily}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAaAFamily_ideal_eq_sAcAFamily}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seCFamily_ideal_eq_sAaCFamily}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sbCFamily_ideal_eq_sAcCFamily}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSBasedBranchEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSABasedBranchEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBasedBranchEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBBasedBranchEquiv}

Complete-locus equality also descends one level further, to the actual
two-variable curve ideal over the field generated by the shared parameter
tuple.  The induced complete function-field equivalence fixes that
coefficient field generator by generator and carries both endpoint
coordinates.  Thus all four repeated labels already define the same curve
relation over their literal rank-two parameter fields; extending these
equalities across the other six independent inputs is now the remaining
scalar-extension step:

{docstring AclGeom.pairIdeal_eq_over_commonParameter_of_familyIdeal_eq}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSPairIdeal_eq_over_parameterField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAPairIdeal_eq_over_parameterField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUPairIdeal_eq_over_parameterField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBPairIdeal_eq_over_parameterField}

Independent scalar extension is handled at the function-field level.  A
base equivalence extends across matching algebraically independent tuples,
fixing each new coordinate.  If the new tuple is independent over both
complete endpoint fields, equality of the endpoint curve ideals therefore
survives over the enlarged coefficient field.  Algebraicity of the family
target does not destroy this independence:

{docstring AclGeom.adjoinIndependentEquivOfEquiv_generator}

{docstring AclGeom.auxiliary_independent_over_parameterPairField}

{docstring AclGeom.pairIdeal_eq_over_independentExtension_of_pairIdeal_eq}

The four alternative independent eight-coordinate presentations provide
the six complementary coordinates for `s`, `sA`, `u`, and `uB`.  Thus all
four repeated curve relations are equal after full independent scalar
extension.  For `s`, this enlarged field is literally the original common
eight-input coefficient field, giving the first repeated-arrow relation on
the exact common base:

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSPairIdeal_eq_over_independentInputField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAPairIdeal_eq_over_independentInputField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUPairIdeal_eq_over_independentInputField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBPairIdeal_eq_over_independentInputField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSPairIdeal_eq_over_commonInputField}

Equality of a selected two-variable curve ideal also identifies the finite
extension from its source-coordinate field to its full branch field.  This
comparison lifts to the concrete normal closures and admits a deck
correction preserving the literal selected branch.  Applying it to the
exact common-base `s` ideal gives the first faithful selected-normal-cover
anchor, rather than merely an abstract chart equivalence:

{docstring AclGeom.FiniteCorrespondencePair.extensionEquivOfIdealEq}

{docstring AclGeom.FiniteCorrespondencePair.normalCoverEquivOfIdealEq_algebraMap}

{docstring AclGeom.FiniteCorrespondencePair.basedBranchEquivOfIdealEq_selected}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSCommonCorrespondencePair_ideal_eq}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSCommonBasedBranchEquiv_selected}

The other three coefficient changes are finite, not transcendental.  One
field adjoins the actual `sA`, `u`, and `uB` blocks to the common inputs;
it is finite over the common field, and its normal closure contains all
three named alternative eight-input fields.  Joint independence also
packages each repeated relation as a genuine finite correspondence over
its own alternative field.  Their equal ideals therefore yield three more
selected-branch-preserving normal-cover comparisons before transport into
the common normal coefficient field:

{docstring AclGeom.source_notMem_racl_independentExtension}

{docstring AclGeom.FiniteCorrespondenceFamilyMember.pairOverIndependentExtension}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientOverInput_finiteDimensional}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientNormalField_normal}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAAlternativeInputField_le_normalField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUAlternativeInputField_le_normalField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBAlternativeInputField_le_normalField}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedAlternativeBasedBranchEquiv_selected}

The finite comparison field is finite over each alternative base as well
as over the original common inputs.  Ambient closure equality survives an
embedding; applied to the three alternative eight-tuples, it shows that
all common and replacement coefficients are algebraic over each named
alternative field.  Finite adjoining and the tower law then make the same
common coefficient normal field a finite extension of all three bases.
This is the precise finiteness input for taking pairwise normal closures
after the formal source and the common source cover are adjoined, without
assuming that a curve ideal stays prime under algebraic base change:

{docstring AclGeom.algHom_racl_image_eq_of_racl_eq}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonInput_racl_eq_repeatedSAInput}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonInput_racl_eq_repeatedUInput}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonInput_racl_eq_repeatedUBInput}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientOverRepeatedSA_finiteDimensional}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientOverRepeatedU_finiteDimensional}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientOverRepeatedUB_finiteDimensional}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientNormalOverRepeatedSA_finiteDimensional}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientNormalOverRepeatedU_finiteDimensional}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonCoefficientNormalOverRepeatedUB_finiteDimensional}

A reusable finite-compositum construction now adjoins such a coefficient
extension and two correspondence branches with the same source, then takes
their normal closure over that source-coordinate field.  It proves the
result finite and normal and records all three literal containments.  The
three alternative `sA`, `u`, and `uB` comparisons instantiate this
construction, producing pairwise normal ambient fields.  Equality of the
selected pair ideals also gives a source-linear equivalence between the two
literal branch fields.  Normality extends that embedding to a deck
transformation of the joint field, and the extension is proved to carry the
first displayed target to the second.  All three alternative comparisons
now instantiate these coefficient-bearing branch automorphisms:

{docstring AclGeom.FiniteCoefficientBranchCompositum.normalField_finiteDimensional}

{docstring AclGeom.FiniteCoefficientBranchCompositum.normalField_normal}

{docstring AclGeom.FiniteCoefficientBranchCompositum.coefficientExtension_le_normalField}

{docstring AclGeom.FiniteCoefficientBranchCompositum.firstBranch_le_normalField}

{docstring AclGeom.FiniteCoefficientBranchCompositum.secondBranch_le_normalField}

{docstring AclGeom.FiniteCoefficientBranchCompositum.branchEquivOfIdealEq}

{docstring AclGeom.FiniteCoefficientBranchCompositum.branchAutomorphismOfIdealEq}

{docstring AclGeom.FiniteCoefficientBranchCompositum.branchAutomorphismOfIdealEq_target}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACoefficientBranchNormalField_normal}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACoefficientBranchNormalField_contains}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCoefficientBranchNormalField_normal}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCoefficientBranchNormalField_contains}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCoefficientBranchNormalField_normal}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCoefficientBranchNormalField_contains}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSABranchAutomorphism}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBranchAutomorphism}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBBranchAutomorphism}

The alternative source fields are algebraically related to, but not nested
with, the literal common input field.  The comparison fields are therefore
renormalized once more over the common coefficient field with the same
formal source adjoined.  A finite-basis compositum proves finiteness over
this new base without pretending the two bases are nested; a second normal
closure supplies a canonical finite normal cover in the exact algebraic
closure used by the four strict triangles.  The two literal target branches
embed in that canonical cover.  The three rebased covers are joined to the
existing simultaneous source cover, and all four composition triangles are
then rebuilt, still strictly, on the enlarged source:

{docstring AclGeom.FiniteCoefficientBranchCompositum.normalField_finiteDimensional_over_coefficientSource}

{docstring AclGeom.FiniteCoefficientBranchCompositum.rebasedCanonicalCover}

{docstring AclGeom.FiniteCoefficientBranchCompositum.firstBranchEmbeddingInRebasedCanonical}

{docstring AclGeom.FiniteCoefficientBranchCompositum.secondBranchEmbeddingInRebasedCanonical}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSARebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedURebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.branchComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seBranchComparisonCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAaBranchComparisonCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sbBranchComparisonCoverCompositionTriangle}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAcBranchComparisonCoverCompositionTriangle}

The canonical models used above now remember which conjugate came from the
literal ambient branch.  The ambient extension is included in its concrete
normal closure and transported to the canonical model; the inverse
comparison recovers the original inclusion.  The common composition source
cover exposes the selected left and direct branch normalizations, and these
distinguished embeddings are inherited by every larger source cover.  In
particular, all eight selected left/direct occurrences in the four-arrow
diagram now live in `branchComparisonSourceCover`:

{docstring AclGeom.FiniteCover.canonicalSelectedEmbedding}

{docstring AclGeom.FiniteCover.normalClosureOverEquivCanonical_symm_comp_selectedEmbedding}

{docstring AclGeom.finiteCoverCanonicalSelectedBranchIn}

{docstring AclGeom.FiniteCorrespondencePair.FiniteCoverTriangle.leftSourceFiniteNormalCover_le_sourceCover}

{docstring AclGeom.FiniteCorrespondencePair.FiniteCoverTriangle.directSourceFiniteNormalCover_le_sourceCover}

{docstring AclGeom.FiniteCorrespondencePair.FiniteCoverTriangle.selectedLeftBranchIn}

{docstring AclGeom.FiniteCorrespondencePair.FiniteCoverTriangle.selectedDirectBranchIn}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seSelectedLeftBranchInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAaSelectedLeftBranchInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sbSelectedLeftBranchInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAcSelectedLeftBranchInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.seSelectedDirectBranchInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAaSelectedDirectBranchInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sbSelectedDirectBranchInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.sAcSelectedDirectBranchInComparisonSourceCover}

Branch comparison now has a chosen, coefficient-linear deck adjustment
rather than only an existential transitivity statement.  An equivalence of
branch domains first reparametrizes the second embedding; anchoring the
temporary algebra structure at the first embedding then extends the second
embedding to a distinguished deck transformation.  The exact common-base
`s` ideal supplies such a domain equivalence.  Its induced automorphism of
`branchComparisonSourceCover` fixes the full eight-input coefficient/source
field, carries the selected first `s` branch to the selected second branch,
and sends the displayed first middle coordinate to the displayed second
middle coordinate.  Rebased pairwise branches can likewise be inherited by
any larger canonical cover once the remaining coefficient-compatible domain
identifications are constructed:

{docstring AclGeom.NormalBranchEmbedding.reparametrize}

{docstring AclGeom.NormalBranchEmbedding.alignmentAut}

{docstring AclGeom.NormalBranchEmbedding.alignmentAut_smul_reparametrize}

{docstring AclGeom.FiniteCoefficientBranchCompositum.firstBranchEmbeddingInRebasedCanonicalIn}

{docstring AclGeom.FiniteCoefficientBranchCompositum.secondBranchEmbeddingInRebasedCanonicalIn}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSCommonBranchEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSBranchAlignmentAut}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSBranchAlignmentAut_selectedTarget}

The first algebraic coefficient change is transported over the literal
common source and its native coefficient field. For the repeated `sA` block,
an explicit equivalence of the raw rebased source with that common source
extends to their algebraic closures. A coherent embedding of the entire
pairwise total field into the rebased canonical cover restricts to the
literal branch fields of the `sA·a=u` and `sA·c=uB` faces. After inclusion in
`branchComparisonSourceCover`, two distinguished deck transformations remove
the remaining normal-closure choices. Their action equations compare the
actual selected face branches with the coefficient-comparison branches over
the full common coefficient/source field:

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSARebasedSourceEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSARebasedClosureTransport}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSARawRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAFirstBranchEmbeddingInRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSASecondBranchEmbeddingInRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAFirstBranchEmbeddingInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSASecondBranchEmbeddingInComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAFirstClosureAlignmentAut_smul}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSASecondClosureAlignmentAut_smul}

The identical construction for the repeated direct output `u` uses the
strict composite pairs of the first two faces. A carrier-invariance lemma
for adjoining one ambient generator identifies the raw branches with the
literal selected direct branches. Both literal branches are restrictions of
one coherent whole-total-field embedding into the rebased canonical cover.
Two further deck transformations give their exact alignment equations in the
common cover:

{docstring IntermediateField.adjoin_singleton_carrier_eq_of_carrier_eq}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedURebasedSourceEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedURebasedClosureTransport}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedURawRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUFirstBranchEmbeddingInRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUSecondBranchEmbeddingInRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUFirstClosureAlignmentAut_smul}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUSecondClosureAlignmentAut_smul}

Finally, the two strict composite pairs ending at `uB` use the same
whole-total-field embedding and its restrictions to their literal branches.
The resulting equations align the selected direct branches of the `s·b=uB`
and `sA·c=uB` faces with their coefficient-comparison copies. Hence all four
repeated labels are represented by coefficient-linear selected-branch
equations on one finite normal source cover:

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBRebasedSourceEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBRebasedClosureTransport}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBRawRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBFirstBranchEmbeddingInRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBSecondBranchEmbeddingInRebasedCanonicalCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBFirstClosureAlignmentAut_smul}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBSecondClosureAlignmentAut_smul}

The three alternative-base branch automorphisms are deliberately not
misidentified as deck transformations over the literal common source.  Each
is linear over its own alternative source presentation and can therefore
move coefficients that occur only in the original eight-input presentation.
The literal common source is included in the corresponding comparison normal
field, its image under the restricted ground-field automorphism is retained
as a named intermediate field, and the resulting source equivalence records
that semilinear coefficient change.  All three charts fix the formal curve
coordinate pointwise; only its coefficient presentation is allowed to move:

{docstring IntermediateField.algHomIntoOfLeRestrictScalars}

{docstring IntermediateField.imageUnderAutomorphism}

{docstring IntermediateField.equivImageUnderAutomorphism}

{docstring IntermediateField.equivImageUnderAutomorphism_eq_of_eq_algebraMap}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.commonSourceGenerator}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonSourceImageEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCommonSourceImageEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCommonSourceImageEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonSourceImageEquiv_generator}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCommonSourceImageEquiv_generator}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCommonSourceImageEquiv_generator}

These source equivalences extend to the chosen algebraic closures and hence
restrict to semilinear charts on the entire enlarged common source cover.
The restriction square is explicit on every base-field element, so the three
formal-generator equations survive unchanged at finite-cover level:

{docstring AclGeom.AlgebraicClosureTransport.FiniteNormalCover.mapEquiv_algebraMap}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonSourceImageClosureTransport}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAImageBranchComparisonSourceCover}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAImageSourceChart}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSAImageSourceChart_commonSourceGenerator}

The branch-faithful lift retains more data than the source square alone.
Each image source is mapped back into the original curve ambient, where it
and the original source both lie in the same pairwise normal field.  The
base equivalence and the actual alternative-base automorphism of that whole
field form one equivalence of nested extensions.  Its normal-closure lift
therefore retains the total-field comparison as well as the moved base:

{docstring IntermediateField.ambientImageUnderAutomorphism}

{docstring IntermediateField.extensionEquivUnderAutomorphism}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonSourceExtensionEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCommonSourceExtensionEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCommonSourceExtensionEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonSourceNormalExtensionEquiv}

Finiteness transports across the full extension square.  Passing from the
canonical models back to the concrete normal closures gives a semilinear
normal-cover equivalence over the moved source.  As with the earlier
selected curve branches, a target deck correction is essential: it makes
the comparison preserve the literal embedded copy of the entire pairwise
total field.  The three alternative comparisons now expose these based
normal-cover transports and their exact selected-branch equations:

{docstring IntermediateField.ambientImageUnderAutomorphism_finiteDimensional}

{docstring AclGeom.FiniteCover.normalCoverEquivUnderAutomorphism}

{docstring AclGeom.FiniteCover.basedBranchEquivUnderAutomorphism}

{docstring AclGeom.FiniteCover.basedBranchEquivUnderAutomorphism_selected}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACoefficientBranchNormalField_finiteDimensional_overCommonSource}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonSourceBasedBranchEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCommonSourceBasedBranchEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCommonSourceBasedBranchEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedCommonSourceBasedBranchEquiv_selected}

The concrete based comparisons and the canonical comparison covers meet
through an explicit equality-based bridge over the native coefficient field.
The literal common source and the raw rebased source have equal intermediate
fields in this presentation, while the pairwise total field stays fixed.
Carrier equivalences transport finiteness from the earlier presentation.
The normal lift followed by the chosen raw-to-common algebraic-closure
transport identifies the direct canonical normal closure with the named
rebased cover, already a subcover of the simultaneous source compositum:

{docstring AclGeom.FiniteCover.finiteDimensional_of_eq}

{docstring AclGeom.FiniteCover.finiteDimensional_of_carrier_eq}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonToRawRebasedExtensionEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCommonToRawRebasedExtensionEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCommonToRawRebasedExtensionEquiv}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedSACommonCanonicalCoverEquivRebased}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUCommonCanonicalCoverEquivRebased}

{docstring AclGeom.QWitness.PsiCurveFourArrowCommonSourceRealizations.repeatedUBCommonCanonicalCoverEquivRebased}

The bridge also remembers its base algebra map.  Equality-induced extension
equivalences compute to the canonical equality transport; composing that
map with the inverse raw-to-common source transport is literally the
identity.  The mapped normal-lift interface packages this cancellation as an
algebra equivalence and then transports the distinguished embedding of the
entire finite extension:

{docstring AclGeom.FiniteCover.ExtensionEquiv.ofEq_baseEquiv}

{docstring AclGeom.FiniteCover.NormalExtensionEquiv.mappedNormalEquiv}

{docstring AclGeom.FiniteCover.NormalExtensionEquiv.mappedNormalEquiv_algebraMap}

{docstring AclGeom.FiniteCover.NormalExtensionEquiv.mappedNormalAlgEquiv}

{docstring AclGeom.FiniteCover.ExtensionEquiv.mappedNormalEquiv}

{docstring AclGeom.FiniteCover.ExtensionEquiv.mappedNormalAlgEquiv}

{docstring AclGeom.FiniteCover.ExtensionEquiv.mappedCanonicalSelectedEmbedding}

{docstring AclGeom.FiniteCover.ExtensionEquiv.mappedCanonicalSelectedEmbedding_algebraMap}
