/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Geometry.Points

/-!
# Independent tuples and finite-rank predicates

Geometric finite rank: `RankLE n E` (below a join of `n` atoms) and
`RankEq n E` (generated by an independent `n`-tuple of atoms), defined without
cardinal arithmetic; agreement with `Algebra.trdeg` is deferred until the
configuration API is stable (blueprint end of §Foundation II).

**Status:** skeleton (M0); contents arrive with M1 (checklist F6).

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.
-/

namespace AclGeom

end AclGeom
