/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Closure.ClosedLattice

/-!
# Atoms, principal closures, and atomisticity

The points of the combinatorial geometry attached to `𝒢(K/k)` are its atoms.
This file proves the two structural facts of blueprint §Foundation II:

* `ClosedIF.isAtom_point`: for `x ∉ ⊥`, the principal closure
  `point k x = racl k {x}` is an atom, and conversely every atom is a
  principal closure (`ClosedIF.IsAtom.exists_eq_point`) — blueprint
  Lemma `principal-atom`;
* `ClosedIF.instIsAtomistic`: every closed intermediate field is the supremum
  of the atoms below it — blueprint Lemma `atomistic`, provided as mathlib's
  `IsAtomistic` class so its API applies.

Everything here is relative to the lattice bottom `⊥ : ClosedIF k K` (the
relative algebraic closure of the image of `k`); no standing hypothesis on
`k` is needed. Under the blueprint's hypothesis that `k` is relatively
algebraically closed in `K`, the bottom is exactly (the image of) `k`.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M1, checklist F4).
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k : Type*} {K : Type*} [Field k] [Field K] [Algebra k K]

namespace ClosedIF

variable (k) in
/-- The principal closed intermediate field generated by an element:
`P_x = racl k {x}`. For `x ∉ ⊥` this is an atom of `𝒢(K/k)`, a *point* of
the associated combinatorial geometry. -/
def point (x : K) : ClosedIF k K :=
  ⟨racl k {x}, isRAC_racl _⟩

@[simp] theorem coe_point (x : K) :
    ((point k x).1 : IntermediateField k K) = racl k {x} := rfl

@[simp] theorem mem_point {x y : K} : y ∈ point k x ↔ y ∈ racl k {x} := Iff.rfl

instance : IsConcreteLE (ClosedIF k K) K where
  coe_subset_coe' {E F} :=
    (SetLike.coe_subset_coe (S := E.1) (T := F.1)).trans le_iff.symm

theorem mem_point_self (x : K) : x ∈ point k x :=
  subset_racl k {x} rfl

/-- The set underlying a principal closure. -/
theorem coe_set_point (x : K) :
    ((point k x : ClosedIF k K) : Set K) = (racl k {x} : Set K) := rfl

/-- The universal property of the principal closure: `point k x ≤ E` iff
`x ∈ E`. -/
theorem point_le_iff {x : K} {E : ClosedIF k K} : point k x ≤ E ↔ x ∈ E := by
  constructor
  · intro h
    exact (le_iff.1 h) (mem_point_self x)
  · intro h
    rw [le_iff, coe_point, ← isRAC_iff_racl_eq.1 E.2]
    exact racl_mono (Set.singleton_subset_iff.2 h)

theorem point_eq_bot_iff {x : K} : point k x = ⊥ ↔ x ∈ (⊥ : ClosedIF k K) := by
  constructor
  · intro h
    rw [← h]
    exact mem_point_self x
  · intro h
    exact le_antisymm (point_le_iff.2 h) bot_le

/-- Exchange in point form: if `y ∈ P_x` but `y ∉ ⊥`, then `x ∈ P_y`
(the engine of blueprint Lemma `principal-atom`). -/
theorem mem_point_symm {x y : K} (hy : y ∈ point k x)
    (hy' : y ∉ (⊥ : ClosedIF k K)) : x ∈ point k y := by
  -- Reduce to `racl_exchange` over `S = ∅`.
  have hyx : y ∈ racl k (insert x (∅ : Set K)) := by
    simpa using hy
  have hyb : y ∉ racl k (∅ : Set K) := fun hmem ↦ hy' <| by
    change y ∈ (⊥ : ClosedIF k K).1
    rw [coe_bot]
    exact racl_mono (Set.empty_subset _) hmem
  have := racl_exchange hyx hyb
  simpa using this

/-- Principal closures of elements outside the bottom are atoms
(blueprint Lemma `principal-atom`, forward direction). -/
theorem isAtom_point {x : K} (hx : x ∉ (⊥ : ClosedIF k K)) :
    IsAtom (point k x) := by
  constructor
  · intro h
    exact hx (point_eq_bot_iff.1 h)
  · intro b hb
    by_contra hb0
    -- A nontrivial `b < point k x` contains some `y ∉ ⊥`; exchange puts `x`
    -- back into `racl k {y} ≤ b`, contradicting strictness.
    obtain ⟨y, hyb, hy0⟩ := SetLike.exists_of_lt (bot_lt_iff_ne_bot.2 hb0)
    have hy_point : y ∈ point k x := (le_iff.1 hb.le) hyb
    have hx_mem : x ∈ point k y := mem_point_symm hy_point hy0
    have : point k x ≤ b := point_le_iff.2 <| (le_iff.1 (point_le_iff.2 hyb)) hx_mem
    exact absurd (lt_of_le_of_lt this hb) (lt_irrefl _)

/-- Every atom of `𝒢(K/k)` is a principal closure (blueprint Lemma
`principal-atom`, converse direction). -/
theorem IsAtom.exists_eq_point {P : ClosedIF k K} (hP : IsAtom P) :
    ∃ x : K, x ∉ (⊥ : ClosedIF k K) ∧ P = point k x := by
  obtain ⟨x, hxP, hx0⟩ := SetLike.exists_of_lt (bot_lt_iff_ne_bot.2 hP.1)
  refine ⟨x, hx0, ?_⟩
  have h1 : point k x ≤ P := point_le_iff.2 hxP
  rcases eq_or_lt_of_le h1 with h | h
  · exact h.symm
  · exact absurd (hP.2 _ h) fun hbot ↦ hx0 (point_eq_bot_iff.1 hbot)

/-- Two principal closures agree iff their generators are mutually algebraic
(blueprint Lemma `principal-atom`, last clause). -/
theorem point_eq_point_iff {x y : K} :
    point k x = point k y ↔ x ∈ point k y ∧ y ∈ point k x := by
  constructor
  · intro h
    exact ⟨h ▸ mem_point_self x, h.symm ▸ mem_point_self y⟩
  · rintro ⟨hx, hy⟩
    exact le_antisymm (point_le_iff.2 hx) (point_le_iff.2 hy)

/-- The lattice of closed intermediate fields is atomistic: every element is
the least upper bound of the atoms below it (blueprint Lemma `atomistic`). -/
instance : IsAtomistic (ClosedIF k K) := by
  refine ⟨fun E ↦ ⟨{P | IsAtom P ∧ P ≤ E}, ⟨fun P hP ↦ hP.2, fun F hF ↦ ?_⟩,
    fun P hP ↦ hP.1⟩⟩
  -- Least upper bound, elementwise: each `x ∈ E` lies in any upper bound `F`,
  -- via the atom `point k x` when `x ∉ ⊥` and via `⊥ ≤ F` otherwise.
  intro x hxE
  by_cases hx0 : x ∈ (⊥ : ClosedIF k K)
  · exact (le_iff.1 (bot_le (a := F))) hx0
  · have hle : point k x ≤ F := hF ⟨isAtom_point hx0, point_le_iff.2 hxE⟩
    exact (le_iff.1 hle) (mem_point_self x)

end ClosedIF

end

end AclGeom
