/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import Mathlib.RingTheory.Valuation.ValuationSubring
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Toward places of a one-variable function field

First bricks of the curve-theory library (project issue #13, per the
design steer on #12), following the classical function-field route: for a
valuation subring `O` of `F/k` and an element `z ≠ 0` of its maximal
ideal,

* base-field constants are units (`valuation_algebraMap_eq_one`);
* a `k`-polynomial with nonzero constant term evaluates at `z` to a unit
  of `O` (`valuation_aeval_eq_one`);
* consequently every nonzero value of a `k`-polynomial at `z` is a
  natural power of `v z` (`exists_valuation_aeval_eq_pow`), and every
  nonzero element of the subfield `k(z)` has value an integer power of
  `v z` (`exists_valuation_eq_zpow_of_mem_adjoin`).

The last statement says the value group of `O` restricted to `k(z)` is
the cyclic group generated by `v z` — the first half of the fundamental
inequality showing that valuation subrings of one-variable function
fields are discrete valuation rings (Stichtenoth, Theorem 1.1.6).

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M4b, issue #13, brick P1).
-/

namespace AclGeom

open Polynomial

noncomputable section

variable {k F : Type*} [Field k] [Field F] [Algebra k F]
variable {O : ValuationSubring F}

/-- Base-field constants are units of every valuation subring containing
the base field. -/
theorem valuation_algebraMap_eq_one
    (hk : ∀ c : k, algebraMap k F c ∈ O) {c : k} (hc : c ≠ 0) :
    O.valuation (algebraMap k F c) = 1 := by
  have h1 : O.valuation (algebraMap k F c) ≤ 1 :=
    O.valuation_le_one ⟨_, hk c⟩
  have h2 : (O.valuation (algebraMap k F c))⁻¹ ≤ 1 := by
    rw [← map_inv₀, ← map_inv₀]
    exact O.valuation_le_one ⟨_, hk c⁻¹⟩
  have h0 : O.valuation (algebraMap k F c) ≠ 0 := by
    rw [Valuation.ne_zero_iff]
    exact (map_ne_zero (algebraMap k F)).2 hc
  refine le_antisymm h1 ?_
  rwa [inv_le_one₀ (by exact zero_lt_iff.2 h0)] at h2

/-- Polynomial values at elements of a valuation subring stay in it. -/
theorem aeval_mem (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F}
    (hzO : z ∈ O) (p : Polynomial k) : aeval z p ∈ O := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add]; exact add_mem hp hq
  | monomial n c =>
    rw [aeval_monomial]
    exact mul_mem (hk c) (pow_mem hzO n)

/-- A `k`-polynomial with nonzero constant term evaluates to a unit at
any element of the maximal ideal: the constant dominates. -/
theorem valuation_aeval_eq_one (hk : ∀ c : k, algebraMap k F c ∈ O)
    {z : F} (hz : O.valuation z < 1) {p : Polynomial k}
    (hp0 : p.coeff 0 ≠ 0) : O.valuation (aeval z p) = 1 := by
  have hzO : z ∈ O := O.mem_of_valuation_le_one z hz.le
  have hsplit : aeval z p = algebraMap k F (p.coeff 0) + z * aeval z p.divX := by
    conv_lhs => rw [← Polynomial.X_mul_divX_add p]
    rw [map_add, map_mul, aeval_X, aeval_C]
    ring
  have hsmall : O.valuation (z * aeval z p.divX) <
      O.valuation (algebraMap k F (p.coeff 0)) := by
    rw [valuation_algebraMap_eq_one hk hp0, Valuation.map_mul]
    calc O.valuation z * O.valuation (aeval z p.divX)
        ≤ O.valuation z * 1 := by
          gcongr
          exact O.valuation_le_one ⟨_, aeval_mem hk hzO _⟩
      _ = O.valuation z := mul_one _
      _ < 1 := hz
  rw [hsplit, Valuation.map_add_eq_of_lt_left _ hsmall,
    valuation_algebraMap_eq_one hk hp0]

/-- Every nonzero `k`-polynomial value at a maximal-ideal element `z` has
value a natural power of `v z`: factor out the root multiplicity at `0`. -/
theorem exists_valuation_aeval_eq_pow
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F}
    (hz : O.valuation z < 1) {p : Polynomial k} (hp : p ≠ 0) :
    ∃ m : ℕ, O.valuation (aeval z p) = O.valuation z ^ m := by
  obtain ⟨q, hq, hqnd⟩ :=
    p.exists_eq_pow_rootMultiplicity_mul_and_not_dvd hp 0
  rw [map_zero, sub_zero] at hq hqnd
  have hq0 : q.coeff 0 ≠ 0 := fun h ↦ hqnd (Polynomial.X_dvd_iff.2 h)
  refine ⟨p.rootMultiplicity 0, ?_⟩
  conv_lhs => rw [hq]
  rw [map_mul, map_pow, aeval_X, Valuation.map_mul, Valuation.map_pow,
    valuation_aeval_eq_one hk hz hq0, mul_one]

/-- **The restricted value group is cyclic** (first half of Stichtenoth
Theorem 1.1.6): every nonzero element of the subfield `k(z)`, for `z` a
nonzero element of the maximal ideal, has value an integer power of
`v z`. -/
theorem exists_valuation_eq_zpow_of_mem_adjoin
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1) {w : F}
    (hw : w ∈ IntermediateField.adjoin k ({z} : Set F)) (hw0 : w ≠ 0) :
    ∃ m : ℤ, O.valuation w = O.valuation z ^ m := by
  rw [IntermediateField.mem_adjoin_simple_iff] at hw
  obtain ⟨p, q, hpq⟩ := hw
  have hq0 : aeval z q ≠ 0 := by
    intro h0
    rw [hpq, h0, div_zero] at hw0
    exact hw0 rfl
  have hp0 : aeval z p ≠ 0 := by
    intro h0
    rw [hpq, h0, zero_div] at hw0
    exact hw0 rfl
  have hpne : p ≠ 0 := fun h ↦ hp0 (by rw [h, map_zero])
  have hqne : q ≠ 0 := fun h ↦ hq0 (by rw [h, map_zero])
  obtain ⟨m₁, hm₁⟩ := exists_valuation_aeval_eq_pow hk hz hpne
  obtain ⟨m₂, hm₂⟩ := exists_valuation_aeval_eq_pow hk hz hqne
  have hzv : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  refine ⟨(m₁ : ℤ) - (m₂ : ℤ), ?_⟩
  rw [hpq, map_div₀, hm₁, hm₂, zpow_sub₀ hzv, zpow_natCast, zpow_natCast]

/-- Ultrametric sums: a finite sum with a strictly dominating term has the
dominating term's value. -/
theorem valuation_sum_eq_of_forall_lt {ι : Type*} {s : Finset ι}
    {f : ι → F} {j : ι} (hj : j ∈ s)
    (hmax : ∀ i ∈ s, i ≠ j → O.valuation (f i) < O.valuation (f j)) :
    O.valuation (∑ i ∈ s, f i) = O.valuation (f j) := by
  classical
  by_cases h0 : O.valuation (f j) = 0
  · have hs : s = {j} := by
      refine Finset.eq_singleton_iff_unique_mem.2 ⟨hj, fun i hi ↦ ?_⟩
      by_contra hij
      have h1 := hmax i hi hij
      rw [h0] at h1
      exact zero_le.not_gt h1
    rw [hs, Finset.sum_singleton]
  · rw [← Finset.add_sum_erase s f hj]
    refine Valuation.map_add_eq_of_lt_left _ ?_
    exact O.valuation.map_sum_lt h0 fun i hi ↦
      hmax i (Finset.mem_of_mem_erase hi) (Finset.ne_of_mem_erase hi)

open IntermediateField in
/-- **Coset independence** (the counting half of Stichtenoth Theorem
1.1.6): elements of `F` whose values lie in pairwise distinct cosets of
the cyclic group `⟨v z⟩` are linearly independent over the subfield
`k(z)`. Consequently the index of `⟨v z⟩` in the value group is bounded
by `[F : k(z)]`. -/
theorem linearIndependent_of_pairwise_valuation_ne {ι : Type*} [Fintype ι]
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1) {w : ι → F} (hw0 : ∀ i, w i ≠ 0)
    (hne : ∀ i j : ι, i ≠ j → ∀ m : ℤ,
      O.valuation (w i) ≠ O.valuation (w j) * O.valuation z ^ m) :
    LinearIndependent (↥(adjoin k ({z} : Set F))) w := by
  classical
  have hzv : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  rw [Fintype.linearIndependent_iff]
  intro g hsum i₀
  by_contra hg₀
  set s : Finset ι := Finset.univ.filter (fun i ↦ g i ≠ 0) with hsdef
  have hi₀s : i₀ ∈ s := by simp [hsdef, hg₀]
  -- Each summand is a nonzero value.
  have hcoe0 : ∀ i ∈ s, ((g i : F)) ≠ 0 := by
    intro i hi
    rw [hsdef, Finset.mem_filter] at hi
    simpa using hi.2
  have hval : ∀ i ∈ s, O.valuation ((g i : F) * w i) ≠ 0 := by
    intro i hi
    rw [Valuation.ne_zero_iff]
    exact mul_ne_zero (hcoe0 i hi) (hw0 i)
  -- Distinct summands have distinct values: the coefficients only move
  -- values inside a coset of `⟨v z⟩`.
  have hdist : ∀ i ∈ s, ∀ j ∈ s, i ≠ j →
      O.valuation ((g i : F) * w i) ≠ O.valuation ((g j : F) * w j) := by
    intro i hi j hj hij heq
    obtain ⟨mi, hmi⟩ := exists_valuation_eq_zpow_of_mem_adjoin hk hz0 hz
      (SetLike.coe_mem (g i)) (hcoe0 i hi)
    obtain ⟨mj, hmj⟩ := exists_valuation_eq_zpow_of_mem_adjoin hk hz0 hz
      (SetLike.coe_mem (g j)) (hcoe0 j hj)
    rw [Valuation.map_mul, Valuation.map_mul, hmi, hmj] at heq
    refine hne i j hij (mj - mi) ?_
    have h2 : O.valuation z ^ mi ≠ 0 := zpow_ne_zero _ hzv
    calc O.valuation (w i)
        = (O.valuation z ^ mi)⁻¹ *
          (O.valuation z ^ mi * O.valuation (w i)) := by
          rw [inv_mul_cancel_left₀ h2]
      _ = (O.valuation z ^ mi)⁻¹ *
          (O.valuation z ^ mj * O.valuation (w j)) := by rw [heq]
      _ = O.valuation (w j) * O.valuation z ^ (mj - mi) := by
          rw [zpow_sub₀ hzv, div_eq_mul_inv,
            mul_comm (O.valuation z ^ mj) (O.valuation (w j)),
            mul_left_comm ((O.valuation z ^ mi)⁻¹) (O.valuation (w j))
              (O.valuation z ^ mj),
            mul_comm ((O.valuation z ^ mi)⁻¹) (O.valuation z ^ mj)]
  -- Pick the summand of maximal value; it strictly dominates.
  obtain ⟨j, hjs, hjmax⟩ := s.exists_max_image
    (fun i ↦ O.valuation ((g i : F) * w i)) ⟨i₀, hi₀s⟩
  have hstrict : ∀ i ∈ s, i ≠ j →
      O.valuation ((g i : F) * w i) < O.valuation ((g j : F) * w j) :=
    fun i hi hij ↦ lt_of_le_of_ne (hjmax i hi) (hdist i hi j hjs hij)
  -- The support sum is the full sum, which vanishes.
  have hss : ∑ i ∈ s, (g i : F) * w i = 0 := by
    rw [← hsum]
    rw [show ∑ i : ι, g i • w i = ∑ i : ι, (g i : F) * w i from
      Finset.sum_congr rfl fun i _ ↦ by rw [Algebra.smul_def]; rfl]
    refine Finset.sum_subset (Finset.subset_univ s) fun i _ hi ↦ ?_
    rw [hsdef, Finset.mem_filter, not_and, not_not] at hi
    rw [hi (Finset.mem_univ i), ZeroMemClass.coe_zero, zero_mul]
  have h0 := valuation_sum_eq_of_forall_lt hjs hstrict
  rw [hss, Valuation.map_zero] at h0
  exact hval j hjs h0.symm

end

end AclGeom
