/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import Mathlib.RingTheory.Valuation.ValuationSubring
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Toward places of a one-variable function field

First bricks of the curve-theory library (project issue #13, per the
design steer on #12), following the classical function-field route: for a
valuation subring `O` of `F/k` and an element `z ≠ 0` of its maximal
ideal,

* base-field constants are units (`valuation_algebraMap_eq_one`);
* a `k`-polynomial with nonzero constant term evaluates at `z` to a unit
  of `O` (`valuation_aeval_eq_one`);
* consequently every nonzero value of a `k`-polynomial at `z` is a
  natural power of `v z` (`exists_valuation_aeval_eq_pow`), and every
  nonzero element of the subfield `k(z)` has value an integer power of
  `v z` (`exists_valuation_eq_zpow_of_mem_adjoin`).

The last statement says the value group of `O` restricted to `k(z)` is
the cyclic group generated by `v z` — the first half of the fundamental
inequality showing that valuation subrings of one-variable function
fields are discrete valuation rings (Stichtenoth, Theorem 1.1.6).

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M4b, issue #13, brick P1).
-/

namespace AclGeom

open Polynomial

noncomputable section

variable {k F : Type*} [Field k] [Field F] [Algebra k F]
variable {O : ValuationSubring F}

/-- Base-field constants are units of every valuation subring containing
the base field. -/
theorem valuation_algebraMap_eq_one
    (hk : ∀ c : k, algebraMap k F c ∈ O) {c : k} (hc : c ≠ 0) :
    O.valuation (algebraMap k F c) = 1 := by
  have h1 : O.valuation (algebraMap k F c) ≤ 1 :=
    O.valuation_le_one ⟨_, hk c⟩
  have h2 : (O.valuation (algebraMap k F c))⁻¹ ≤ 1 := by
    rw [← map_inv₀, ← map_inv₀]
    exact O.valuation_le_one ⟨_, hk c⁻¹⟩
  have h0 : O.valuation (algebraMap k F c) ≠ 0 := by
    rw [Valuation.ne_zero_iff]
    exact (map_ne_zero (algebraMap k F)).2 hc
  refine le_antisymm h1 ?_
  rwa [inv_le_one₀ (by exact zero_lt_iff.2 h0)] at h2

/-- Polynomial values at elements of a valuation subring stay in it. -/
theorem aeval_mem (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F}
    (hzO : z ∈ O) (p : Polynomial k) : aeval z p ∈ O := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add]; exact add_mem hp hq
  | monomial n c =>
    rw [aeval_monomial]
    exact mul_mem (hk c) (pow_mem hzO n)

/-- A `k`-polynomial with nonzero constant term evaluates to a unit at
any element of the maximal ideal: the constant dominates. -/
theorem valuation_aeval_eq_one (hk : ∀ c : k, algebraMap k F c ∈ O)
    {z : F} (hz : O.valuation z < 1) {p : Polynomial k}
    (hp0 : p.coeff 0 ≠ 0) : O.valuation (aeval z p) = 1 := by
  have hzO : z ∈ O := O.mem_of_valuation_le_one z hz.le
  have hsplit : aeval z p = algebraMap k F (p.coeff 0) + z * aeval z p.divX := by
    conv_lhs => rw [← Polynomial.X_mul_divX_add p]
    rw [map_add, map_mul, aeval_X, aeval_C]
    ring
  have hsmall : O.valuation (z * aeval z p.divX) <
      O.valuation (algebraMap k F (p.coeff 0)) := by
    rw [valuation_algebraMap_eq_one hk hp0, Valuation.map_mul]
    calc O.valuation z * O.valuation (aeval z p.divX)
        ≤ O.valuation z * 1 := by
          gcongr
          exact O.valuation_le_one ⟨_, aeval_mem hk hzO _⟩
      _ = O.valuation z := mul_one _
      _ < 1 := hz
  rw [hsplit, Valuation.map_add_eq_of_lt_left _ hsmall,
    valuation_algebraMap_eq_one hk hp0]

/-- Every nonzero `k`-polynomial value at a maximal-ideal element `z` has
value a natural power of `v z`: factor out the root multiplicity at `0`. -/
theorem exists_valuation_aeval_eq_pow
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F}
    (hz : O.valuation z < 1) {p : Polynomial k} (hp : p ≠ 0) :
    ∃ m : ℕ, O.valuation (aeval z p) = O.valuation z ^ m := by
  obtain ⟨q, hq, hqnd⟩ :=
    p.exists_eq_pow_rootMultiplicity_mul_and_not_dvd hp 0
  rw [map_zero, sub_zero] at hq hqnd
  have hq0 : q.coeff 0 ≠ 0 := fun h ↦ hqnd (Polynomial.X_dvd_iff.2 h)
  refine ⟨p.rootMultiplicity 0, ?_⟩
  conv_lhs => rw [hq]
  rw [map_mul, map_pow, aeval_X, Valuation.map_mul, Valuation.map_pow,
    valuation_aeval_eq_one hk hz hq0, mul_one]

/-- **The restricted value group is cyclic** (first half of Stichtenoth
Theorem 1.1.6): every nonzero element of the subfield `k(z)`, for `z` a
nonzero element of the maximal ideal, has value an integer power of
`v z`. -/
theorem exists_valuation_eq_zpow_of_mem_adjoin
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1) {w : F}
    (hw : w ∈ IntermediateField.adjoin k ({z} : Set F)) (hw0 : w ≠ 0) :
    ∃ m : ℤ, O.valuation w = O.valuation z ^ m := by
  rw [IntermediateField.mem_adjoin_simple_iff] at hw
  obtain ⟨p, q, hpq⟩ := hw
  have hq0 : aeval z q ≠ 0 := by
    intro h0
    rw [hpq, h0, div_zero] at hw0
    exact hw0 rfl
  have hp0 : aeval z p ≠ 0 := by
    intro h0
    rw [hpq, h0, zero_div] at hw0
    exact hw0 rfl
  have hpne : p ≠ 0 := fun h ↦ hp0 (by rw [h, map_zero])
  have hqne : q ≠ 0 := fun h ↦ hq0 (by rw [h, map_zero])
  obtain ⟨m₁, hm₁⟩ := exists_valuation_aeval_eq_pow hk hz hpne
  obtain ⟨m₂, hm₂⟩ := exists_valuation_aeval_eq_pow hk hz hqne
  have hzv : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  refine ⟨(m₁ : ℤ) - (m₂ : ℤ), ?_⟩
  rw [hpq, map_div₀, hm₁, hm₂, zpow_sub₀ hzv, zpow_natCast, zpow_natCast]

end

end AclGeom
