/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import Mathlib.RingTheory.Valuation.ValuationSubring
import Mathlib.RingTheory.Valuation.LocalSubring
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import AclGeom.Closure.Basic

/-!
# Toward places of a one-variable function field

First bricks of the curve-theory library (project issue #13, per the
design steer on #12), following the classical function-field route: for a
valuation subring `O` of `F/k` and an element `z ≠ 0` of its maximal
ideal,

* base-field constants are units (`valuation_algebraMap_eq_one`);
* a `k`-polynomial with nonzero constant term evaluates at `z` to a unit
  of `O` (`valuation_aeval_eq_one`);
* consequently every nonzero value of a `k`-polynomial at `z` is a
  natural power of `v z` (`exists_valuation_aeval_eq_pow`), and every
  nonzero element of the subfield `k(z)` has value an integer power of
  `v z` (`exists_valuation_eq_zpow_of_mem_adjoin`).

The last statement says the value group of `O` restricted to `k(z)` is
the cyclic group generated by `v z` — the first half of the fundamental
inequality showing that valuation subrings of one-variable function
fields are discrete valuation rings (Stichtenoth, Theorem 1.1.6).

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M4b, issue #13, brick P1).
-/

namespace AclGeom

open Polynomial

noncomputable section

variable {k F : Type*} [Field k] [Field F] [Algebra k F]
variable {O : ValuationSubring F}

/-- Base-field constants are units of every valuation subring containing
the base field. -/
theorem valuation_algebraMap_eq_one
    (hk : ∀ c : k, algebraMap k F c ∈ O) {c : k} (hc : c ≠ 0) :
    O.valuation (algebraMap k F c) = 1 := by
  have h1 : O.valuation (algebraMap k F c) ≤ 1 :=
    O.valuation_le_one ⟨_, hk c⟩
  have h2 : (O.valuation (algebraMap k F c))⁻¹ ≤ 1 := by
    rw [← map_inv₀, ← map_inv₀]
    exact O.valuation_le_one ⟨_, hk c⁻¹⟩
  have h0 : O.valuation (algebraMap k F c) ≠ 0 := by
    rw [Valuation.ne_zero_iff]
    exact (map_ne_zero (algebraMap k F)).2 hc
  refine le_antisymm h1 ?_
  rwa [inv_le_one₀ (by exact zero_lt_iff.2 h0)] at h2

/-- Polynomial values at elements of a valuation subring stay in it. -/
theorem aeval_mem (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F}
    (hzO : z ∈ O) (p : Polynomial k) : aeval z p ∈ O := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add]; exact add_mem hp hq
  | monomial n c =>
    rw [aeval_monomial]
    exact mul_mem (hk c) (pow_mem hzO n)

/-- A `k`-polynomial with nonzero constant term evaluates to a unit at
any element of the maximal ideal: the constant dominates. -/
theorem valuation_aeval_eq_one (hk : ∀ c : k, algebraMap k F c ∈ O)
    {z : F} (hz : O.valuation z < 1) {p : Polynomial k}
    (hp0 : p.coeff 0 ≠ 0) : O.valuation (aeval z p) = 1 := by
  have hzO : z ∈ O := O.mem_of_valuation_le_one z hz.le
  have hsplit : aeval z p = algebraMap k F (p.coeff 0) + z * aeval z p.divX := by
    conv_lhs => rw [← Polynomial.X_mul_divX_add p]
    rw [map_add, map_mul, aeval_X, aeval_C]
    ring
  have hsmall : O.valuation (z * aeval z p.divX) <
      O.valuation (algebraMap k F (p.coeff 0)) := by
    rw [valuation_algebraMap_eq_one hk hp0, Valuation.map_mul]
    calc O.valuation z * O.valuation (aeval z p.divX)
        ≤ O.valuation z * 1 := by
          gcongr
          exact O.valuation_le_one ⟨_, aeval_mem hk hzO _⟩
      _ = O.valuation z := mul_one _
      _ < 1 := hz
  rw [hsplit, Valuation.map_add_eq_of_lt_left _ hsmall,
    valuation_algebraMap_eq_one hk hp0]

/-- Every nonzero `k`-polynomial value at a maximal-ideal element `z` has
value a natural power of `v z`: factor out the root multiplicity at `0`. -/
theorem exists_valuation_aeval_eq_pow
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F}
    (hz : O.valuation z < 1) {p : Polynomial k} (hp : p ≠ 0) :
    ∃ m : ℕ, O.valuation (aeval z p) = O.valuation z ^ m := by
  obtain ⟨q, hq, hqnd⟩ :=
    p.exists_eq_pow_rootMultiplicity_mul_and_not_dvd hp 0
  rw [map_zero, sub_zero] at hq hqnd
  have hq0 : q.coeff 0 ≠ 0 := fun h ↦ hqnd (Polynomial.X_dvd_iff.2 h)
  refine ⟨p.rootMultiplicity 0, ?_⟩
  conv_lhs => rw [hq]
  rw [map_mul, map_pow, aeval_X, Valuation.map_mul, Valuation.map_pow,
    valuation_aeval_eq_one hk hz hq0, mul_one]

/-- **The restricted value group is cyclic** (first half of Stichtenoth
Theorem 1.1.6): every nonzero element of the subfield `k(z)`, for `z` a
nonzero element of the maximal ideal, has value an integer power of
`v z`. -/
theorem exists_valuation_eq_zpow_of_mem_adjoin
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1) {w : F}
    (hw : w ∈ IntermediateField.adjoin k ({z} : Set F)) (hw0 : w ≠ 0) :
    ∃ m : ℤ, O.valuation w = O.valuation z ^ m := by
  rw [IntermediateField.mem_adjoin_simple_iff] at hw
  obtain ⟨p, q, hpq⟩ := hw
  have hq0 : aeval z q ≠ 0 := by
    intro h0
    rw [hpq, h0, div_zero] at hw0
    exact hw0 rfl
  have hp0 : aeval z p ≠ 0 := by
    intro h0
    rw [hpq, h0, zero_div] at hw0
    exact hw0 rfl
  have hpne : p ≠ 0 := fun h ↦ hp0 (by rw [h, map_zero])
  have hqne : q ≠ 0 := fun h ↦ hq0 (by rw [h, map_zero])
  obtain ⟨m₁, hm₁⟩ := exists_valuation_aeval_eq_pow hk hz hpne
  obtain ⟨m₂, hm₂⟩ := exists_valuation_aeval_eq_pow hk hz hqne
  have hzv : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  refine ⟨(m₁ : ℤ) - (m₂ : ℤ), ?_⟩
  rw [hpq, map_div₀, hm₁, hm₂, zpow_sub₀ hzv, zpow_natCast, zpow_natCast]

/-- Ultrametric sums: a finite sum with a strictly dominating term has the
dominating term's value. -/
theorem valuation_sum_eq_of_forall_lt {ι : Type*} {s : Finset ι}
    {f : ι → F} {j : ι} (hj : j ∈ s)
    (hmax : ∀ i ∈ s, i ≠ j → O.valuation (f i) < O.valuation (f j)) :
    O.valuation (∑ i ∈ s, f i) = O.valuation (f j) := by
  classical
  by_cases h0 : O.valuation (f j) = 0
  · have hs : s = {j} := by
      refine Finset.eq_singleton_iff_unique_mem.2 ⟨hj, fun i hi ↦ ?_⟩
      by_contra hij
      have h1 := hmax i hi hij
      rw [h0] at h1
      exact zero_le.not_gt h1
    rw [hs, Finset.sum_singleton]
  · rw [← Finset.add_sum_erase s f hj]
    refine Valuation.map_add_eq_of_lt_left _ ?_
    exact O.valuation.map_sum_lt h0 fun i hi ↦
      hmax i (Finset.mem_of_mem_erase hi) (Finset.ne_of_mem_erase hi)

open IntermediateField in
/-- **Coset independence** (the counting half of Stichtenoth Theorem
1.1.6): elements of `F` whose values lie in pairwise distinct cosets of
the cyclic group `⟨v z⟩` are linearly independent over the subfield
`k(z)`. Consequently the index of `⟨v z⟩` in the value group is bounded
by `[F : k(z)]`. -/
theorem linearIndependent_of_pairwise_valuation_ne {ι : Type*} [Fintype ι]
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1) {w : ι → F} (hw0 : ∀ i, w i ≠ 0)
    (hne : ∀ i j : ι, i ≠ j → ∀ m : ℤ,
      O.valuation (w i) ≠ O.valuation (w j) * O.valuation z ^ m) :
    LinearIndependent (↥(adjoin k ({z} : Set F))) w := by
  classical
  have hzv : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  rw [Fintype.linearIndependent_iff]
  intro g hsum i₀
  by_contra hg₀
  set s : Finset ι := Finset.univ.filter (fun i ↦ g i ≠ 0) with hsdef
  have hi₀s : i₀ ∈ s := by simp [hsdef, hg₀]
  -- Each summand is a nonzero value.
  have hcoe0 : ∀ i ∈ s, ((g i : F)) ≠ 0 := by
    intro i hi
    rw [hsdef, Finset.mem_filter] at hi
    simpa using hi.2
  have hval : ∀ i ∈ s, O.valuation ((g i : F) * w i) ≠ 0 := by
    intro i hi
    rw [Valuation.ne_zero_iff]
    exact mul_ne_zero (hcoe0 i hi) (hw0 i)
  -- Distinct summands have distinct values: the coefficients only move
  -- values inside a coset of `⟨v z⟩`.
  have hdist : ∀ i ∈ s, ∀ j ∈ s, i ≠ j →
      O.valuation ((g i : F) * w i) ≠ O.valuation ((g j : F) * w j) := by
    intro i hi j hj hij heq
    obtain ⟨mi, hmi⟩ := exists_valuation_eq_zpow_of_mem_adjoin hk hz0 hz
      (SetLike.coe_mem (g i)) (hcoe0 i hi)
    obtain ⟨mj, hmj⟩ := exists_valuation_eq_zpow_of_mem_adjoin hk hz0 hz
      (SetLike.coe_mem (g j)) (hcoe0 j hj)
    rw [Valuation.map_mul, Valuation.map_mul, hmi, hmj] at heq
    refine hne i j hij (mj - mi) ?_
    have h2 : O.valuation z ^ mi ≠ 0 := zpow_ne_zero _ hzv
    calc O.valuation (w i)
        = (O.valuation z ^ mi)⁻¹ *
          (O.valuation z ^ mi * O.valuation (w i)) := by
          rw [inv_mul_cancel_left₀ h2]
      _ = (O.valuation z ^ mi)⁻¹ *
          (O.valuation z ^ mj * O.valuation (w j)) := by rw [heq]
      _ = O.valuation (w j) * O.valuation z ^ (mj - mi) := by
          rw [zpow_sub₀ hzv, div_eq_mul_inv,
            mul_comm (O.valuation z ^ mj) (O.valuation (w j)),
            mul_left_comm ((O.valuation z ^ mi)⁻¹) (O.valuation (w j))
              (O.valuation z ^ mj),
            mul_comm ((O.valuation z ^ mi)⁻¹) (O.valuation z ^ mj)]
  -- Pick the summand of maximal value; it strictly dominates.
  obtain ⟨j, hjs, hjmax⟩ := s.exists_max_image
    (fun i ↦ O.valuation ((g i : F) * w i)) ⟨i₀, hi₀s⟩
  have hstrict : ∀ i ∈ s, i ≠ j →
      O.valuation ((g i : F) * w i) < O.valuation ((g j : F) * w j) :=
    fun i hi hij ↦ lt_of_le_of_ne (hjmax i hi) (hdist i hi j hjs hij)
  -- The support sum is the full sum, which vanishes.
  have hss : ∑ i ∈ s, (g i : F) * w i = 0 := by
    rw [← hsum]
    rw [show ∑ i : ι, g i • w i = ∑ i : ι, (g i : F) * w i from
      Finset.sum_congr rfl fun i _ ↦ by rw [Algebra.smul_def]; rfl]
    refine Finset.sum_subset (Finset.subset_univ s) fun i _ hi ↦ ?_
    rw [hsdef, Finset.mem_filter, not_and, not_not] at hi
    rw [hi (Finset.mem_univ i), ZeroMemClass.coe_zero, zero_mul]
  have h0 := valuation_sum_eq_of_forall_lt hjs hstrict
  rw [hss, Valuation.map_zero] at h0
  exact hval j hjs h0.symm

open IntermediateField in
/-- **Pigeonhole through the coset bound**: when `F` is finite over
`k(z)`, some positive power `d ≤ [F : k(z)]` of every nonzero value lands
in the cyclic group `⟨v z⟩`. -/
theorem exists_pow_valuation_eq_zpow
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1)
    [FiniteDimensional (↥(adjoin k ({z} : Set F))) F]
    {w : F} (hw0 : w ≠ 0) :
    ∃ d : ℕ, 0 < d ∧
      d ≤ Module.finrank (↥(adjoin k ({z} : Set F))) F ∧
      ∃ m : ℤ, O.valuation w ^ d = O.valuation z ^ m := by
  classical
  set n := Module.finrank (↥(adjoin k ({z} : Set F))) F with hn
  by_contra hcon
  push Not at hcon
  have hvw : O.valuation w ≠ 0 := (Valuation.ne_zero_iff _).2 hw0
  have hvz : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  -- Cancellation kernel: a coset relation between two powers yields the
  -- claimed relation for the difference of exponents.
  have hkey : ∀ i j : ℕ, i < j → j ≤ n → ∀ m : ℤ,
      O.valuation w ^ j = O.valuation w ^ i * O.valuation z ^ m →
      False := by
    intro i j hij hjn m heq
    refine hcon (j - i) (by omega) (by omega) m ?_
    have h1 : O.valuation w ^ i * O.valuation w ^ (j - i) =
        O.valuation w ^ i * O.valuation z ^ m := by
      rw [← pow_add, Nat.add_sub_cancel' hij.le]
      exact heq
    exact mul_left_cancel₀ (pow_ne_zero i hvw) h1
  -- Otherwise all powers of `w` lie in distinct cosets: independence.
  have hne : ∀ i j : Fin (n + 1), i ≠ j → ∀ m : ℤ,
      O.valuation (w ^ (i : ℕ)) ≠
        O.valuation (w ^ (j : ℕ)) * O.valuation z ^ m := by
    intro i j hij m heq
    rw [Valuation.map_pow, Valuation.map_pow] at heq
    rcases Nat.lt_or_ge (i : ℕ) (j : ℕ) with hlt | hge
    · refine hkey i j hlt (by omega) (-m) ?_
      rw [heq, mul_assoc, ← zpow_add₀ hvz, add_neg_cancel, zpow_zero,
        mul_one]
    · have hgt : (j : ℕ) < (i : ℕ) :=
        lt_of_le_of_ne hge fun h ↦ hij (Fin.ext h.symm)
      exact hkey j i hgt (by omega) m heq
  have hind := linearIndependent_of_pairwise_valuation_ne hk hz0 hz
    (w := fun i : Fin (n + 1) ↦ w ^ (i : ℕ))
    (fun i ↦ pow_ne_zero _ hw0) hne
  have hcard := hind.fintype_card_le_finrank
  rw [Fintype.card_fin] at hcard
  omega

/-- Integer powers of a fixed base strictly between `0` and `1` are
injective in the exponent. -/
theorem zpow_left_injective_of_lt_one {Γ : Type*}
    [LinearOrderedCommGroupWithZero Γ] {a : Γ} (h0 : 0 < a) (h1 : a < 1)
    {m n : ℤ} (h : a ^ m = a ^ n) : m = n := by
  by_contra hc
  rcases Int.lt_or_gt_of_ne hc with hlt | hgt
  · exact (zpow_lt_zpow_right_of_lt_one₀ h0 h1 hlt).ne h.symm
  · exact (zpow_lt_zpow_right_of_lt_one₀ h0 h1 hgt).ne h

open IntermediateField in
/-- **Uniform exponent**: raising to the `[F : k(z)]!`-th power lands
every small nonzero value in `⟨v z⟩`, with a positive exponent. -/
theorem exists_pow_factorial_valuation_eq
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1)
    [FiniteDimensional (↥(adjoin k ({z} : Set F))) F]
    {w : F} (hw0v : O.valuation w ≠ 0) (hwlt : O.valuation w < 1) :
    ∃ M : ℕ, 0 < M ∧
      O.valuation w ^
          (Module.finrank (↥(adjoin k ({z} : Set F))) F).factorial =
        O.valuation z ^ (M : ℤ) := by
  set n := Module.finrank (↥(adjoin k ({z} : Set F))) F with hn
  have hvz : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  have hvzpos : 0 < O.valuation z := zero_lt_iff.2 hvz
  have hw0 : w ≠ 0 := fun h ↦ hw0v (by rw [h, Valuation.map_zero])
  obtain ⟨d, hd0, hdn, m, hm⟩ :=
    exists_pow_valuation_eq_zpow hk hz0 hz hw0
  obtain ⟨e, he⟩ : d ∣ n.factorial := Nat.dvd_factorial hd0 hdn
  have h1 : O.valuation w ^ n.factorial =
      O.valuation z ^ (m * (e : ℤ)) := by
    rw [he, pow_mul, hm, zpow_mul, zpow_natCast]
  have h2 : O.valuation z ^ (m * (e : ℤ)) < 1 := by
    rw [← h1]
    have hlt1 : O.valuation w ^ n.factorial < 1 ^ n.factorial :=
      pow_lt_pow_left₀ hwlt zero_le n.factorial_ne_zero
    rwa [one_pow] at hlt1
  have h3 : 0 < m * (e : ℤ) := by
    by_contra hc
    push Not at hc
    have h4 : (1 : _) ≤ O.valuation z ^ (m * (e : ℤ)) := by
      calc (1 : _) = O.valuation z ^ (0 : ℤ) := by simp
        _ ≤ O.valuation z ^ (m * (e : ℤ)) :=
          zpow_le_zpow_right_of_le_one₀ hvzpos hz.le hc
    exact h4.not_gt h2
  exact ⟨(m * (e : ℤ)).toNat, by omega, by
    rw [h1, Int.toNat_of_nonneg h3.le]⟩

open IntermediateField in
/-- **Uniformizer existence** (the discreteness core of Stichtenoth
Theorem 1.1.6): when `F` is finite over `k(z)` for a nonzero
maximal-ideal element `z`, the values below `1` attain a maximum — the
value of a uniformizer. -/
theorem exists_valuation_uniformizer
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1)
    [FiniteDimensional (↥(adjoin k ({z} : Set F))) F] :
    ∃ t : F, O.valuation t ≠ 0 ∧ O.valuation t < 1 ∧
      ∀ w : F, O.valuation w ≠ 0 → O.valuation w < 1 →
        O.valuation w ≤ O.valuation t := by
  classical
  set n := Module.finrank (↥(adjoin k ({z} : Set F))) F with hn
  have hvz : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  have hvzpos : 0 < O.valuation z := zero_lt_iff.2 hvz
  have huni := fun (w : F) (hw0v : O.valuation w ≠ 0)
    (hwlt : O.valuation w < 1) ↦
    exists_pow_factorial_valuation_eq hk hz0 hz hw0v hwlt
  -- The attained exponents form a nonempty set of naturals; take the min.
  set A : Set ℕ := {M | 0 < M ∧ ∃ w : F, O.valuation w ≠ 0 ∧
    O.valuation w < 1 ∧
    O.valuation w ^ n.factorial = O.valuation z ^ (M : ℤ)} with hA
  have hAne : A.Nonempty := by
    obtain ⟨M, hM0, hMz⟩ := huni z hvz hz
    exact ⟨M, hM0, z, hvz, hz, hMz⟩
  obtain ⟨-, t, ht0, htlt, htM⟩ := Nat.sInf_mem hAne
  refine ⟨t, ht0, htlt, fun w hw0v hwlt ↦ ?_⟩
  obtain ⟨M, hM0, hMw⟩ := huni w hw0v hwlt
  have hle : sInf A ≤ M := Nat.sInf_le ⟨hM0, w, hw0v, hwlt, hMw⟩
  -- Compare through the `n!`-th powers.
  have h2 : O.valuation w ^ n.factorial ≤ O.valuation t ^ n.factorial := by
    rw [hMw, htM]
    exact zpow_le_zpow_right_of_le_one₀ hvzpos hz.le (by exact_mod_cast hle)
  by_contra hc
  push Not at hc
  exact ((pow_lt_pow_left₀ hc zero_le n.factorial_ne_zero).not_ge h2).elim

open IntermediateField in
/-- **Value classification**: below `1`, every nonzero value is a positive
power of the uniformizer's value. Strong induction on the uniform
exponent: dividing by the uniformizer strictly decreases it. -/
theorem valuation_eq_pow_uniformizer
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1)
    [FiniteDimensional (↥(adjoin k ({z} : Set F))) F]
    {t : F} (ht0 : O.valuation t ≠ 0) (htlt : O.valuation t < 1)
    (htmax : ∀ w : F, O.valuation w ≠ 0 → O.valuation w < 1 →
      O.valuation w ≤ O.valuation t)
    {w : F} (hw0 : O.valuation w ≠ 0) (hwlt : O.valuation w < 1) :
    ∃ j : ℕ, 0 < j ∧ O.valuation w = O.valuation t ^ j := by
  classical
  have hvz : O.valuation z ≠ 0 := (Valuation.ne_zero_iff _).2 hz0
  have hvzpos : 0 < O.valuation z := zero_lt_iff.2 hvz
  have htpos : 0 < O.valuation t := zero_lt_iff.2 ht0
  have htF : t ≠ 0 := fun h ↦ ht0 (by rw [h, Valuation.map_zero])
  obtain ⟨Mt, hMt0, hMt⟩ :=
    exists_pow_factorial_valuation_eq hk hz0 hz ht0 htlt
  obtain ⟨Mw, hMw0, hMw⟩ :=
    exists_pow_factorial_valuation_eq hk hz0 hz hw0 hwlt
  clear hMw0
  -- Strong induction over the uniform exponent.
  induction Mw using Nat.strong_induction_on generalizing w with
  | _ Mw ih =>
    have hle := htmax w hw0 hwlt
    rcases eq_or_lt_of_le hle with heq | hlt
    · exact ⟨1, one_pos, by rw [pow_one, heq]⟩
    · -- Divide by the uniformizer and recurse.
      have hw'0 : O.valuation (w / t) ≠ 0 := by
        rw [map_div₀]
        exact (div_ne_zero_iff.2 ⟨hw0, ht0⟩)
      have hw'lt : O.valuation (w / t) < 1 := by
        rw [map_div₀, div_lt_one₀ htpos]
        exact hlt
      obtain ⟨M', hM'0, hM'⟩ :=
        exists_pow_factorial_valuation_eq hk hz0 hz hw'0 hw'lt
      -- Identify the exponent: `M' = Mw - Mt`.
      have hrel : O.valuation z ^ (M' : ℤ) =
          O.valuation z ^ ((Mw : ℤ) - Mt) := by
        rw [← hM', map_div₀, div_pow, hMw, hMt, ← zpow_sub₀ hvz]
      have hM'eq : (M' : ℤ) = (Mw : ℤ) - Mt :=
        zpow_left_injective_of_lt_one hvzpos hz hrel
      have hM'lt : M' < Mw := by omega
      obtain ⟨j', hj'0, hj'⟩ := ih M' hM'lt hw'0 hw'lt hM'
      refine ⟨j' + 1, by omega, ?_⟩
      have hwt : w = w / t * t := (div_mul_cancel₀ w htF).symm
      rw [hwt, Valuation.map_mul, hj', pow_succ]

set_option maxRecDepth 4000 in
set_option maxHeartbeats 1000000 in
-- The ideal-lattice instance chain over the subtype `↥O` is deep: both
-- recursion depth and heartbeats are raised for this single theorem.
open IntermediateField in
/-- **Valuation subrings of one-variable function fields are discrete
valuation rings** (Stichtenoth Theorem 1.1.6): a valuation subring of
`F/k` whose maximal ideal contains a nonzero `z` with `F` finite over
`k(z)` is a DVR. Every ideal is generated by any element of maximal
value, values being powers of the uniformizer's. -/
theorem isDiscreteValuationRing_of_valuationSubring
    (hk : ∀ c : k, algebraMap k F c ∈ O) {z : F} (hz0 : z ≠ 0)
    (hz : O.valuation z < 1)
    [FiniteDimensional (↥(adjoin k ({z} : Set F))) F] :
    IsDiscreteValuationRing (↥O) := by
  classical
  obtain ⟨t, ht0, htlt, htmax⟩ := exists_valuation_uniformizer hk hz0 hz
  -- Every proper nonzero ideal is principal.
  have hpid : IsPrincipalIdealRing (↥O) := by
    constructor
    intro I
    by_cases hI0 : I = ⊥
    · refine ⟨⟨0, ?_⟩⟩
      rw [hI0]
      exact (Ideal.span_singleton_eq_bot.2 rfl).symm
    by_cases hItop : I = ⊤
    · refine ⟨⟨1, ?_⟩⟩
      rw [hItop]
      exact (Ideal.span_singleton_one).symm
    -- Classified values of nonzero ideal elements.
    have hmemval : ∀ x : ↥O, x ∈ I → x ≠ 0 → ∃ j : ℕ, 0 < j ∧
        O.valuation ↑x = O.valuation t ^ j := by
      intro x hxI hx0
      have hxv0 : O.valuation ↑x ≠ 0 := by
        rw [Valuation.ne_zero_iff]
        exact fun h ↦ hx0 (Subtype.ext h)
      have hxlt : O.valuation ↑x < 1 := by
        rcases O.valuation_lt_one_or_eq_one x with h | h
        · exact h
        · exact absurd (Ideal.eq_top_of_isUnit_mem I hxI
            ((O.valuation_eq_one_iff x).2 h)) hItop
      exact valuation_eq_pow_uniformizer hk hz0 hz ht0 htlt htmax hxv0 hxlt
    -- The least attained exponent yields a generator.
    set S : Set ℕ := {j | 0 < j ∧ ∃ x : ↥O, x ∈ I ∧ x ≠ 0 ∧
        O.valuation ↑x = O.valuation t ^ j} with hS
    have hSne : S.Nonempty := by
      obtain ⟨x, hxI, hx0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hI0
      obtain ⟨j, hj0, hj⟩ := hmemval x hxI hx0
      exact ⟨j, hj0, x, hxI, hx0, hj⟩
    obtain ⟨hj₀0, w₀, hw₀I, hw₀0, hw₀⟩ := Nat.sInf_mem hSne
    have hw₀F : (↑w₀ : F) ≠ 0 := fun h ↦ hw₀0 (Subtype.ext h)
    refine ⟨⟨w₀, ?_⟩⟩
    ext x
    rw [Ideal.mem_span_singleton']
    constructor
    · intro hxI
      by_cases hx0 : x = 0
      · exact ⟨0, by rw [hx0, zero_mul]⟩
      obtain ⟨j, hj0, hj⟩ := hmemval x hxI hx0
      have hjge : sInf S ≤ j := Nat.sInf_le ⟨hj0, x, hxI, hx0, hj⟩
      have hle : O.valuation ↑x ≤ O.valuation ↑w₀ := by
        rw [hj, hw₀]
        exact pow_le_pow_right_of_le_one' htlt.le hjge
      have hdiv : ((↑x : F) / ↑w₀) ∈ O := by
        refine O.mem_of_valuation_le_one _ ?_
        rw [map_div₀, div_le_one₀ (zero_lt_iff.2 ?_)]
        · exact hle
        · rw [Valuation.ne_zero_iff]
          exact hw₀F
      refine ⟨⟨_, hdiv⟩, Subtype.ext ?_⟩
      exact div_mul_cancel₀ (↑x : F) hw₀F
    · rintro ⟨a, rfl⟩
      exact I.mul_mem_left a hw₀I
  haveI := hpid
  refine { not_a_field' := ?_ }
  intro hbot
  have hzO : z ∈ O := O.mem_of_valuation_le_one z hz.le
  have hzmem : (⟨z, hzO⟩ : ↥O) ∈ IsLocalRing.maximalIdeal (↥O) :=
    (O.valuation_lt_one_iff _).2 hz
  rw [hbot, Submodule.mem_bot] at hzmem
  exact hz0 (by simpa using congrArg Subtype.val hzmem)

section FunctionField

open IntermediateField

variable (k F) in
/-- A **function field of one variable** over `k`: some element
transcendental over `k` over whose simple extension `F` is finite. -/
class IsFunctionFieldOneVar : Prop where
  /-- Some element is transcendental over `k` with `F` finite over its
  simple extension. -/
  exists_transcendental_finite : ∃ x : F, Transcendental k x ∧
    FiniteDimensional (↥(adjoin k ({x} : Set F))) F

set_option maxHeartbeats 1000000 in
-- The mixed-base adjoin tower makes the `isDefEq` checks between the
-- `restrictScalars` and `toSubfield` presentations expensive.
/-- Abstract tower step: if `F` is finite over `k(x₀)` and `x₀` is
integral over an intermediate field `E`, then `F` is finite over `E`.
Kept abstract in `E`: instantiating the nested adjoin tower at a concrete
adjoin makes instance elaboration diverge. -/
theorem finiteDimensional_of_isIntegral_of_adjoin_finite
    {E : IntermediateField k F} {x₀ : F}
    [FiniteDimensional (↥(adjoin k ({x₀} : Set F))) F]
    (hint : IsIntegral (↥E) x₀) : FiniteDimensional (↥E) F := by
  have hx₀mem : x₀ ∈ adjoin (↥E) ({x₀} : Set F) :=
    subset_adjoin (↥E) ({x₀} : Set F) rfl
  have hx₀mem' : x₀ ∈ (adjoin (↥E) ({x₀} : Set F)).restrictScalars k :=
    (mem_restrictScalars k).2 hx₀mem
  have hle : adjoin k ({x₀} : Set F) ≤
      (adjoin (↥E) ({x₀} : Set F)).restrictScalars k := by
    rw [adjoin_le_iff]
    exact Set.singleton_subset_iff.2 hx₀mem'
  have hsub : (adjoin k ({x₀} : Set F)).toSubfield ≤
      (adjoin (↥E) ({x₀} : Set F)).toSubfield := by
    intro y hy
    have h1 := hle ((mem_toSubfield _ _).1 hy)
    exact (mem_toSubfield _ _).2 ((mem_restrictScalars k).1 h1)
  letI : Algebra (↥(adjoin k ({x₀} : Set F)))
      (↥(adjoin (↥E) ({x₀} : Set F))) :=
    (Subfield.inclusion hsub).toAlgebra
  haveI : IsScalarTower (↥(adjoin k ({x₀} : Set F)))
      (↥(adjoin (↥E) ({x₀} : Set F))) F :=
    IsScalarTower.of_algebraMap_eq' rfl
  haveI h1 : FiniteDimensional (↥(adjoin (↥E) ({x₀} : Set F))) F :=
    FiniteDimensional.right (↥(adjoin k ({x₀} : Set F))) _ _
  haveI h2 : FiniteDimensional (↥E) ↥(adjoin (↥E) ({x₀} : Set F)) :=
    IntermediateField.adjoin.finiteDimensional hint
  exact FiniteDimensional.trans (↥E) (↥(adjoin (↥E) ({x₀} : Set F))) F

/-- In a one-variable function field, `F` is finite over `k(z)` for
*every* transcendental `z`: the exchange property of the closure
pregeometry relocates the finiteness witness. -/
theorem finiteDimensional_adjoin_of_transcendental
    [IsFunctionFieldOneVar k F] {z : F} (hz : Transcendental k z) :
    FiniteDimensional (↥(adjoin k ({z} : Set F))) F := by
  classical
  obtain ⟨x₀, hx₀, hfin⟩ :=
    IsFunctionFieldOneVar.exists_transcendental_finite (k := k) (F := F)
  haveI := hfin
  -- Everything is algebraic over `k(x₀)`; exchange puts `x₀` over `k(z)`.
  have hzx : z ∈ racl k (insert x₀ (∅ : Set F)) := by
    have h0 : z ∈ racl k ({x₀} : Set F) := by
      rw [mem_racl_iff]
      exact (IsIntegral.of_finite (↥(adjoin k ({x₀} : Set F))) z).isAlgebraic
    simpa using h0
  have hx₀z : x₀ ∈ racl k ({z} : Set F) := by
    have h1 := racl_exchange hzx (notMem_racl_empty_of_transcendental hz)
    simpa using h1
  exact finiteDimensional_of_isIntegral_of_adjoin_finite
    (isAlgebraic_iff_isIntegral.1 ((mem_racl_iff k).1 hx₀z))

/-- Over a relatively algebraically closed base, nonzero maximal-ideal
elements of a valuation subring are transcendental. -/
theorem transcendental_of_valuation_lt_one
    (hk : ∀ c : k, algebraMap k F c ∈ O)
    (hrac : ∀ y : F, IsAlgebraic k y → ∃ c : k, algebraMap k F c = y)
    {z : F} (hz0 : z ≠ 0) (hz : O.valuation z < 1) :
    Transcendental k z := by
  intro halg
  obtain ⟨c, hc⟩ := hrac z halg
  have hc0 : c ≠ 0 := fun h ↦ hz0 (by rw [← hc, h, map_zero])
  have h1 := valuation_algebraMap_eq_one hk hc0
  rw [hc] at h1
  exact hz.ne h1

/-- **Places of a one-variable function field are discrete valuation
rings** — the packaged form of Stichtenoth Theorem 1.1.6, with the
finiteness hypothesis discharged from the function-field axioms. -/
theorem isDiscreteValuationRing_of_isFunctionField
    [IsFunctionFieldOneVar k F]
    (hk : ∀ c : k, algebraMap k F c ∈ O)
    (hrac : ∀ y : F, IsAlgebraic k y → ∃ c : k, algebraMap k F c = y)
    {z : F} (hz0 : z ≠ 0) (hz : O.valuation z < 1) :
    IsDiscreteValuationRing (↥O) := by
  have htr := transcendental_of_valuation_lt_one hk hrac hz0 hz
  haveI := finiteDimensional_adjoin_of_transcendental (k := k) htr
  exact isDiscreteValuationRing_of_valuationSubring hk hz0 hz

end FunctionField

section PlaceStructure

open IntermediateField

/-- Over an algebraically closed base, algebraic elements descend to the
base: the element-level relative algebraic closedness used throughout the
curve library. -/
theorem exists_algebraMap_eq_of_isAlgebraic [IsAlgClosed k] {y : F}
    (hy : IsAlgebraic k y) : ∃ c : k, algebraMap k F c = y := by
  have h1 : y ∈ adjoin k ({y} : Set F) := subset_adjoin k _ rfl
  haveI : Algebra.IsAlgebraic k ↥(adjoin k ({y} : Set F)) :=
    isAlgebraic_adjoin_simple hy.isIntegral
  rw [IntermediateField.eq_bot_of_isAlgClosed_of_isAlgebraic
    (adjoin k ({y} : Set F)), IntermediateField.mem_bot] at h1
  exact h1

/-- A nontrivial valuation subring has a nonzero maximal-ideal element:
the inverse of anything outside it. -/
theorem exists_valuation_lt_one_of_ne_top (hO : O ≠ ⊤) :
    ∃ z : F, z ≠ 0 ∧ O.valuation z < 1 := by
  obtain ⟨x, hx⟩ : ∃ x : F, x ∉ O := by
    by_contra hc
    push Not at hc
    exact hO (by ext y; simpa using hc y)
  have hx0 : x ≠ 0 := fun h ↦ hx (h ▸ zero_mem O)
  have hmem : x⁻¹ ∈ O := by
    rcases O.mem_or_inv_mem x with h | h
    · exact absurd h hx
    · exact h
  refine ⟨x⁻¹, inv_ne_zero hx0, ?_⟩
  rcases O.valuation_lt_one_or_eq_one ⟨x⁻¹, hmem⟩ with h | h
  · exact h
  · exfalso
    refine hx (O.mem_of_valuation_le_one x ?_)
    have h2 : O.valuation x * O.valuation x⁻¹ = 1 := by
      rw [← Valuation.map_mul, mul_inv_cancel₀ hx0, Valuation.map_one]
    have h3 : O.valuation x⁻¹ = 1 := h
    rw [h3, mul_one] at h2
    exact h2.le

variable (k F) in
/-- A **place** of `F/k`: a nontrivial valuation subring of `F` containing
the base field. Over a one-variable function field these are exactly the
discrete valuation rings of `F/k` (`Place.isDiscreteValuationRing`). -/
structure Place where
  /-- The underlying valuation subring. -/
  val : ValuationSubring F
  /-- Base-field elements belong to the subring. -/
  algebraMap_mem' : ∀ c : k, algebraMap k F c ∈ val
  /-- The subring is proper. -/
  ne_top' : val ≠ ⊤

namespace Place

variable {P : Place k F}

theorem algebraMap_mem (P : Place k F) (c : k) :
    algebraMap k F c ∈ P.val := P.algebraMap_mem' c

theorem ne_top (P : Place k F) : P.val ≠ ⊤ := P.ne_top'

/-- The valuation attached to a place. -/
def valuation (P : Place k F) := P.val.valuation

/-- Every place of a one-variable function field over an algebraically
closed base is a discrete valuation ring (Stichtenoth Theorem 1.1.6). -/
instance isDiscreteValuationRing [IsAlgClosed k] [IsFunctionFieldOneVar k F]
    (P : Place k F) : IsDiscreteValuationRing (↥P.val) := by
  obtain ⟨z, hz0, hz⟩ := exists_valuation_lt_one_of_ne_top P.ne_top
  exact isDiscreteValuationRing_of_isFunctionField P.algebraMap_mem
    (fun y hy ↦ exists_algebraMap_eq_of_isAlgebraic hy) hz0 hz

end Place

/-- **Every transcendental element has a zero place** (place-existence
via mathlib's Chevalley dominance): the ideal `(f)` of `k[f]` is proper —
invertibility of `f` in `k[f]` would make it algebraic — and a valuation
subring absorbing `k[f]` with `f` a nonunit is a place. -/
theorem exists_place_valuation_lt_one {f : F} (hf : Transcendental k f) :
    ∃ P : Place k F, P.val.valuation f < 1 := by
  classical
  have hf0 : f ≠ 0 := fun h ↦ hf (h ▸ isAlgebraic_zero)
  set A : Subring F := (Algebra.adjoin k ({f} : Set F)).toSubring with hA
  have hfA : f ∈ A := Algebra.subset_adjoin rfl
  have hInetop : Ideal.span {(⟨f, hfA⟩ : A)} ≠ ⊤ := by
    intro htop
    rw [Ideal.span_singleton_eq_top, isUnit_iff_exists_inv] at htop
    obtain ⟨b, hb⟩ := htop
    -- The inverse of `f` in `k[f]` is a polynomial in `f`.
    have hbmem : (b : F) ∈ Algebra.adjoin k ({f} : Set F) := b.2
    rw [Algebra.adjoin_singleton_eq_range_aeval] at hbmem
    obtain ⟨p, hp⟩ := hbmem
    have hp' : Polynomial.aeval f p = (b : F) := hp
    have hb' : f * Polynomial.aeval f p = 1 := by
      have h1 := congrArg (Subtype.val) hb
      push_cast at h1
      rw [hp']
      exact_mod_cast h1
    refine hf ⟨Polynomial.X * p - 1, ?_, ?_⟩
    · intro h0
      have h1 := congrArg (fun q ↦ Polynomial.coeff q 0) h0
      simp only [Polynomial.coeff_sub, Polynomial.mul_coeff_zero,
        Polynomial.coeff_X_zero, Polynomial.coeff_one_zero, zero_mul,
        zero_sub, Polynomial.coeff_zero] at h1
      exact (neg_ne_zero.2 one_ne_zero) h1
    · rw [map_sub, map_mul, Polynomial.aeval_X, map_one, hb', sub_self]
  obtain ⟨B, hAB, hIB⟩ :=
    Ideal.image_subset_nonunits_valuationSubring _ hInetop
  have hfB : f ∈ B.nonunits :=
    hIB ⟨⟨f, hfA⟩, Ideal.subset_span rfl, rfl⟩
  refine ⟨⟨B, fun c ↦ hAB ?_, ?_⟩, ?_⟩
  · exact (Algebra.adjoin k ({f} : Set F)).algebraMap_mem c
  · intro htop
    rcases B.mem_nonunits_iff_or.1 hfB with h1 | h1
    · exact hf0 h1
    · rw [htop] at h1
      exact h1 trivial
  · exact B.mem_nonunits_iff.1 hfB

/-- Every transcendental element has a pole place. -/
theorem exists_place_one_lt_valuation {f : F} (hf : Transcendental k f) :
    ∃ P : Place k F, 1 < P.val.valuation f := by
  have hfinv : Transcendental k f⁻¹ := fun halg ↦
    hf (IsAlgebraic.inv_iff.1 halg)
  obtain ⟨P, hP⟩ := exists_place_valuation_lt_one hfinv
  refine ⟨P, ?_⟩
  have hf0 : f ≠ 0 := fun h ↦ hf (h ▸ isAlgebraic_zero)
  rwa [map_inv₀, inv_lt_one₀
    (zero_lt_iff.2 ((Valuation.ne_zero_iff _).2 hf0))] at hP

/-- **Elements without poles are constants** (Stichtenoth Corollary
1.1.20 over an algebraically closed base). -/
theorem exists_algebraMap_eq_of_forall_valuation_le_one [IsAlgClosed k]
    {f : F} (h : ∀ P : Place k F, P.val.valuation f ≤ 1) :
    ∃ c : k, algebraMap k F c = f := by
  by_contra hnc
  push Not at hnc
  have htr : Transcendental k f := by
    intro halg
    obtain ⟨c, hc⟩ := exists_algebraMap_eq_of_isAlgebraic halg
    exact hnc c hc
  obtain ⟨P, hP⟩ := exists_place_one_lt_valuation htr
  exact (h P).not_gt hP

end PlaceStructure

end

end AclGeom
