/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.ChunkCurveCommonSourceComparison
import AclGeom.Config.ChunkCurveReferenceBridge

/-!
# Semantic right-branch charts in the reference bridge

The charted semantic right curve branches and their factorization through the selected
graph. Split from `AclGeom.Config.ChunkCurveReferenceBridge` (#18).
-/

namespace AclGeom

open IntermediateField

noncomputable section

universe u

namespace QWitness.PsiCurveFourArrowCommonSourceRealizations

/- These chart types use named intermediate-field and normal-cover aliases.
Lean 4.34's default backward transparency does not unfold those aliases in
rewrites or instance comparisons. This setting is scoped to this bridge;
it affects elaboration only, and the resulting terms are kernel-checked. -/
section ReferenceFieldAliases
set_option backward.isDefEq.respectTransparency false

variable {k K : Type u} [Field k] [Field K] [Algebra k K]
  {w : QWitness k K} {hψ : w.Psi}
  {s a b e : Fin 2 → K}
  {D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e}
  (R : w.PsiCurveFourArrowCommonSourceRealizations hψ D)
  (L : w.PsiChunkFourArrowEdgeLifts hψ D)

/-- Literal inclusion of the common-base `a` right branch. -/
noncomputable def sAaSemanticRightBranchToSelectedNormalRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ).branchOverSource →+*
      R.selectedSemanticReferenceNormalField L hind :=
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ
  Q.branchOverSourceToIntermediateFieldRingHom
    (R.selectedSemanticReferenceNormalField L hind)
    (fun _ hz ↦ R.fourSemanticRightBranches_le_selectedSemanticReferenceNormalField
      L hind |>.2.1 hz)

/-- Literal inclusion of the common-base `b` right branch. -/
noncomputable def sbSemanticRightBranchToSelectedNormalRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ).branchOverSource →+*
      R.selectedSemanticReferenceNormalField L hind :=
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ
  Q.branchOverSourceToIntermediateFieldRingHom
    (R.selectedSemanticReferenceNormalField L hind)
    (fun _ hz ↦ R.fourSemanticRightBranches_le_selectedSemanticReferenceNormalField
      L hind |>.2.2.1 hz)

/-- Literal inclusion of the common-base `c` right branch. -/
noncomputable def sAcSemanticRightBranchToSelectedNormalRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ).branchOverSource →+*
      R.selectedSemanticReferenceNormalField L hind :=
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ
  Q.branchOverSourceToIntermediateFieldRingHom
    (R.selectedSemanticReferenceNormalField L hind)
    (fun _ hz ↦ R.fourSemanticRightBranches_le_selectedSemanticReferenceNormalField
      L hind |>.2.2.2 hz)

/-- Canonicalize the selected semantic `a` branch. -/
noncomputable def sAaSemanticRightBranchToSelectedSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.ambientSelectedSemanticReferenceNormalFieldToSourceCover L hind).toRingHom.comp
    (R.sAaSemanticRightBranchToSelectedNormalRingHom L hind)

/-- Canonicalize the selected semantic `b` branch. -/
noncomputable def sbSemanticRightBranchToSelectedSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.ambientSelectedSemanticReferenceNormalFieldToSourceCover L hind).toRingHom.comp
    (R.sbSemanticRightBranchToSelectedNormalRingHom L hind)

/-- Canonicalize the selected semantic `c` branch. -/
noncomputable def sAcSemanticRightBranchToSelectedSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.ambientSelectedSemanticReferenceNormalFieldToSourceCover L hind).toRingHom.comp
    (R.sAcSemanticRightBranchToSelectedNormalRingHom L hind)

/-- The literal common curve source is contained in the finite extension
generated by all selected semantic face coordinates. -/
theorem semanticCommonSourceField_le_selectedSemanticBranchExtension :
    R.semanticCommonSourceField ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k := by
  intro z hz
  exact (R.selectedSemanticBranchExtension L).algebraMap_mem ⟨z, hz⟩

/-- The common eight-input coefficient field is already contained in the
selected semantic face extension. -/
theorem commonCoefficientField_le_selectedSemanticBranchExtension :
    R.seCommonBaseData.coefficientField ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k := by
  rw [← R.mappedReferenceInputField_eq_commonCoefficientField L]
  exact (R.mappedReferenceInputField_le_semanticCommonSourceField L).trans
    (R.semanticCommonSourceField_le_selectedSemanticBranchExtension L)

set_option maxHeartbeats 800000 in
-- Expanding the two-generator branch field through the ten-coordinate adjoin is expensive.
/-- The full common-base semantic `e` right branch is contained in the one
selected semantic face extension, before normal closure. -/
theorem seSemanticRightBranch_le_selectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ).branchField.restrictScalars k ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k := by
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ
  let hA : R.seCommonBaseData.coefficientField ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k :=
    R.commonCoefficientField_le_selectedSemanticBranchExtension L
  have hQ : Q.branchField ≤ extendScalars hA := by
    unfold FiniteCorrespondencePair.branchField
    apply adjoin_le_iff.2
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · change R.se.middle ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨2, rfl⟩
    · change R.se.target ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨3, rfl⟩
  intro z hz
  exact hQ hz

set_option maxHeartbeats 800000 in
-- Expanding the two-generator branch field through the ten-coordinate adjoin is expensive.
/-- The full common-base semantic `a` right branch lies in the same face
extension. -/
theorem sAaSemanticRightBranch_le_selectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ).branchField.restrictScalars k ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k := by
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ
  let hA : R.sAaCommonBaseData.coefficientField ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k :=
    R.commonCoefficientField_le_selectedSemanticBranchExtension L
  have hQ : Q.branchField ≤ extendScalars hA := by
    unfold FiniteCorrespondencePair.branchField
    apply adjoin_le_iff.2
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · change R.sAa.middle ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨4, rfl⟩
    · change R.sAa.target ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨5, rfl⟩
  intro z hz
  exact hQ hz

set_option maxHeartbeats 800000 in
-- Expanding the two-generator branch field through the ten-coordinate adjoin is expensive.
/-- The full common-base semantic `b` right branch lies in the same face
extension. -/
theorem sbSemanticRightBranch_le_selectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ).branchField.restrictScalars k ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k := by
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ
  let hA : R.sbCommonBaseData.coefficientField ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k :=
    R.commonCoefficientField_le_selectedSemanticBranchExtension L
  have hQ : Q.branchField ≤ extendScalars hA := by
    unfold FiniteCorrespondencePair.branchField
    apply adjoin_le_iff.2
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · change R.sb.middle ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨6, rfl⟩
    · change R.sb.target ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨7, rfl⟩
  intro z hz
  exact hQ hz

set_option maxHeartbeats 800000 in
-- Expanding the two-generator branch field through the ten-coordinate adjoin is expensive.
/-- The full common-base semantic `c` right branch, including its algebraic
parameter presentation, lies in the same face extension. -/
theorem sAcSemanticRightBranch_le_selectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ).branchField.restrictScalars k ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k := by
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ
  let hA : R.sAcCommonBaseData.coefficientField ≤
      (R.selectedSemanticBranchExtension L).restrictScalars k :=
    R.commonCoefficientField_le_selectedSemanticBranchExtension L
  have hQ : Q.branchField ≤ extendScalars hA := by
    unfold FiniteCorrespondencePair.branchField
    apply adjoin_le_iff.2
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · change R.sAc.middle ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨8, rfl⟩
    · change R.sAc.target ∈ R.selectedSemanticBranchExtension L
      exact subset_adjoin _ _ ⟨9, rfl⟩
  intro z hz
  exact hQ hz

/-- Literal inclusion of the semantic `e` branch in the coherent whole-face
extension. -/
noncomputable def seSemanticRightBranchToSelectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ).branchOverSource →+*
      R.selectedSemanticBranchExtension L :=
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ
  Q.branchOverSourceToIntermediateFieldRingHom
    (R.selectedSemanticBranchExtension L)
    (fun _ hz ↦
      R.seSemanticRightBranch_le_selectedSemanticBranchExtension L hz)

/-- Literal inclusion of the semantic `a` branch in the coherent whole-face
extension. -/
noncomputable def sAaSemanticRightBranchToSelectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ).branchOverSource →+*
      R.selectedSemanticBranchExtension L :=
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ
  Q.branchOverSourceToIntermediateFieldRingHom
    (R.selectedSemanticBranchExtension L)
    (fun _ hz ↦
      R.sAaSemanticRightBranch_le_selectedSemanticBranchExtension L hz)

/-- Literal inclusion of the semantic `b` branch in the coherent whole-face
extension. -/
noncomputable def sbSemanticRightBranchToSelectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ).branchOverSource →+*
      R.selectedSemanticBranchExtension L :=
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ
  Q.branchOverSourceToIntermediateFieldRingHom
    (R.selectedSemanticBranchExtension L)
    (fun _ hz ↦
      R.sbSemanticRightBranch_le_selectedSemanticBranchExtension L hz)

/-- Literal inclusion of the semantic `c` branch in the coherent whole-face
extension. -/
noncomputable def sAcSemanticRightBranchToSelectedSemanticBranchExtension :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ).branchOverSource →+*
      R.selectedSemanticBranchExtension L :=
  let Q :=
    PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ
  Q.branchOverSourceToIntermediateFieldRingHom
    (R.selectedSemanticBranchExtension L)
    (fun _ hz ↦
      R.sAcSemanticRightBranch_le_selectedSemanticBranchExtension L hz)

/-- The selected common-base semantic `a` branch in the graph source. -/
noncomputable def sAaSemanticRightBranchToSelectedGraphSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.selectedSemanticReferenceSourceCoverToSelectedGraphSourceCover
      L hind).toRingHom.comp
    (R.sAaSemanticRightBranchToSelectedSourceRingHom L hind)

/-- The selected common-base semantic `b` branch in the graph source. -/
noncomputable def sbSemanticRightBranchToSelectedGraphSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.selectedSemanticReferenceSourceCoverToSelectedGraphSourceCover
      L hind).toRingHom.comp
    (R.sbSemanticRightBranchToSelectedSourceRingHom L hind)

/-- The selected common-base semantic `c` branch in the graph source. -/
noncomputable def sAcSemanticRightBranchToSelectedGraphSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.selectedSemanticReferenceSourceCoverToSelectedGraphSourceCover
      L hind).toRingHom.comp
    (R.sAcSemanticRightBranchToSelectedSourceRingHom L hind)

/-- Before the shared canonicalization, the semantic `e` branch inclusion
factors through the coherent whole-face extension. -/
theorem seSemanticRightBranchToSelectedNormal_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.seSemanticRightBranchToSelectedNormalRingHom L hind =
      (IntermediateField.inclusion
        (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
          L hind)).toRingHom.comp
        (R.seSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  unfold seSemanticRightBranchToSelectedNormalRingHom
    seSemanticRightBranchToSelectedSemanticBranchExtension
  exact
    FiniteCorrespondencePair.branchOverSourceToIntermediateFieldRingHom_trans
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.se) R.seCommonBaseData hψ)
      (R.selectedSemanticBranchExtension L)
      (R.selectedSemanticReferenceNormalField L hind)
      (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
        L hind)
      (fun _ hz ↦
        R.seSemanticRightBranch_le_selectedSemanticBranchExtension L hz)
      (fun _ hz ↦
        R.fourSemanticRightBranches_le_selectedSemanticReferenceNormalField
          L hind |>.1 hz)

/-- The semantic `a` branch uses the same whole-face extension before
canonicalization. -/
theorem sAaSemanticRightBranchToSelectedNormal_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.sAaSemanticRightBranchToSelectedNormalRingHom L hind =
      (IntermediateField.inclusion
        (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
          L hind)).toRingHom.comp
        (R.sAaSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  unfold sAaSemanticRightBranchToSelectedNormalRingHom
    sAaSemanticRightBranchToSelectedSemanticBranchExtension
  exact
    FiniteCorrespondencePair.branchOverSourceToIntermediateFieldRingHom_trans
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.sAa) R.sAaCommonBaseData hψ)
      (R.selectedSemanticBranchExtension L)
      (R.selectedSemanticReferenceNormalField L hind)
      (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
        L hind)
      (fun _ hz ↦
        R.sAaSemanticRightBranch_le_selectedSemanticBranchExtension L hz)
      (fun _ hz ↦
        R.fourSemanticRightBranches_le_selectedSemanticReferenceNormalField
          L hind |>.2.1 hz)

/-- The semantic `b` branch uses the same whole-face extension before
canonicalization. -/
theorem sbSemanticRightBranchToSelectedNormal_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.sbSemanticRightBranchToSelectedNormalRingHom L hind =
      (IntermediateField.inclusion
        (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
          L hind)).toRingHom.comp
        (R.sbSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  unfold sbSemanticRightBranchToSelectedNormalRingHom
    sbSemanticRightBranchToSelectedSemanticBranchExtension
  exact
    FiniteCorrespondencePair.branchOverSourceToIntermediateFieldRingHom_trans
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.sb) R.sbCommonBaseData hψ)
      (R.selectedSemanticBranchExtension L)
      (R.selectedSemanticReferenceNormalField L hind)
      (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
        L hind)
      (fun _ hz ↦
        R.sbSemanticRightBranch_le_selectedSemanticBranchExtension L hz)
      (fun _ hz ↦
        R.fourSemanticRightBranches_le_selectedSemanticReferenceNormalField
          L hind |>.2.2.1 hz)

/-- The algebraic semantic `c` branch uses the same whole-face extension
before canonicalization. -/
theorem sAcSemanticRightBranchToSelectedNormal_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.sAcSemanticRightBranchToSelectedNormalRingHom L hind =
      (IntermediateField.inclusion
        (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
          L hind)).toRingHom.comp
        (R.sAcSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  unfold sAcSemanticRightBranchToSelectedNormalRingHom
    sAcSemanticRightBranchToSelectedSemanticBranchExtension
  exact
    FiniteCorrespondencePair.branchOverSourceToIntermediateFieldRingHom_trans
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.sAc) R.sAcCommonBaseData hψ)
      (R.selectedSemanticBranchExtension L)
      (R.selectedSemanticReferenceNormalField L hind)
      (R.selectedSemanticBranchExtension_le_selectedSemanticReferenceNormalField
        L hind)
      (fun _ hz ↦
        R.sAcSemanticRightBranch_le_selectedSemanticBranchExtension L hz)
      (fun _ hz ↦
        R.fourSemanticRightBranches_le_selectedSemanticReferenceNormalField
          L hind |>.2.2.2 hz)

/-- In the unified selected graph, the entire semantic `e` branch is a
restriction of the single coherent whole-face anchor. -/
theorem seSemanticRightBranchToSelectedGraph_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.seSemanticRightBranchToSelectedGraphSourceRingHom L hind =
      (R.selectedSemanticBranchExtensionToSelectedGraphSource
        L hind).toRingHom.comp
        (R.seSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  apply RingHom.ext
  intro z
  unfold seSemanticRightBranchToSelectedGraphSourceRingHom
    selectedSemanticReferenceSourceCoverToSelectedGraphSourceCover
    seSemanticRightBranchToSelectedSourceRingHom
    ambientSelectedSemanticReferenceNormalFieldToSourceCover
    selectedSemanticBranchExtensionToSelectedGraphSource
  simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe]
  have hz := DFunLike.congr_fun
    (R.seSemanticRightBranchToSelectedNormal_factor_extension L hind) z
  exact congrArg (fun y ↦
    (IntermediateField.inclusion
      (R.selectedSemanticReferenceSourceCover_le_selectedGraphSourceCover
        L hind))
      (R.selectedSemanticReferenceNormalEquivSourceCover L hind y)) hz

/-- In the same graph, the entire semantic `a` branch is a restriction of
the same coherent whole-face anchor. -/
theorem sAaSemanticRightBranchToSelectedGraph_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.sAaSemanticRightBranchToSelectedGraphSourceRingHom L hind =
      (R.selectedSemanticBranchExtensionToSelectedGraphSource
        L hind).toRingHom.comp
        (R.sAaSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  apply RingHom.ext
  intro z
  unfold sAaSemanticRightBranchToSelectedGraphSourceRingHom
    selectedSemanticReferenceSourceCoverToSelectedGraphSourceCover
    sAaSemanticRightBranchToSelectedSourceRingHom
    ambientSelectedSemanticReferenceNormalFieldToSourceCover
    selectedSemanticBranchExtensionToSelectedGraphSource
  simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe]
  have hz := DFunLike.congr_fun
    (R.sAaSemanticRightBranchToSelectedNormal_factor_extension L hind) z
  exact congrArg (fun y ↦
    (IntermediateField.inclusion
      (R.selectedSemanticReferenceSourceCover_le_selectedGraphSourceCover
        L hind))
      (R.selectedSemanticReferenceNormalEquivSourceCover L hind y)) hz

/-- In the same graph, the entire semantic `b` branch is a restriction of
the same coherent whole-face anchor. -/
theorem sbSemanticRightBranchToSelectedGraph_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.sbSemanticRightBranchToSelectedGraphSourceRingHom L hind =
      (R.selectedSemanticBranchExtensionToSelectedGraphSource
        L hind).toRingHom.comp
        (R.sbSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  apply RingHom.ext
  intro z
  unfold sbSemanticRightBranchToSelectedGraphSourceRingHom
    selectedSemanticReferenceSourceCoverToSelectedGraphSourceCover
    sbSemanticRightBranchToSelectedSourceRingHom
    ambientSelectedSemanticReferenceNormalFieldToSourceCover
    selectedSemanticBranchExtensionToSelectedGraphSource
  simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe]
  have hz := DFunLike.congr_fun
    (R.sbSemanticRightBranchToSelectedNormal_factor_extension L hind) z
  exact congrArg (fun y ↦
    (IntermediateField.inclusion
      (R.selectedSemanticReferenceSourceCover_le_selectedGraphSourceCover
        L hind))
      (R.selectedSemanticReferenceNormalEquivSourceCover L hind y)) hz

/-- In the same graph, the entire algebraic semantic `c` branch is a
restriction of the same coherent whole-face anchor. -/
theorem sAcSemanticRightBranchToSelectedGraph_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.sAcSemanticRightBranchToSelectedGraphSourceRingHom L hind =
      (R.selectedSemanticBranchExtensionToSelectedGraphSource
        L hind).toRingHom.comp
        (R.sAcSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  apply RingHom.ext
  intro z
  unfold sAcSemanticRightBranchToSelectedGraphSourceRingHom
    selectedSemanticReferenceSourceCoverToSelectedGraphSourceCover
    sAcSemanticRightBranchToSelectedSourceRingHom
    ambientSelectedSemanticReferenceNormalFieldToSourceCover
    selectedSemanticBranchExtensionToSelectedGraphSource
  simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe]
  have hz := DFunLike.congr_fun
    (R.sAcSemanticRightBranchToSelectedNormal_factor_extension L hind) z
  exact congrArg (fun y ↦
    (IntermediateField.inclusion
      (R.selectedSemanticReferenceSourceCover_le_selectedGraphSourceCover
        L hind))
      (R.selectedSemanticReferenceNormalEquivSourceCover L hind y)) hz

/-- Simultaneously, all four complete semantic right branches are
restrictions of one coherent whole-face embedding into the selected graph. -/
theorem fourSemanticRightBranchesToSelectedGraph_factor_extension
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    R.seSemanticRightBranchToSelectedGraphSourceRingHom L hind =
        (R.selectedSemanticBranchExtensionToSelectedGraphSource
          L hind).toRingHom.comp
          (R.seSemanticRightBranchToSelectedSemanticBranchExtension L) ∧
      R.sAaSemanticRightBranchToSelectedGraphSourceRingHom L hind =
        (R.selectedSemanticBranchExtensionToSelectedGraphSource
          L hind).toRingHom.comp
          (R.sAaSemanticRightBranchToSelectedSemanticBranchExtension L) ∧
      R.sbSemanticRightBranchToSelectedGraphSourceRingHom L hind =
        (R.selectedSemanticBranchExtensionToSelectedGraphSource
          L hind).toRingHom.comp
          (R.sbSemanticRightBranchToSelectedSemanticBranchExtension L) ∧
      R.sAcSemanticRightBranchToSelectedGraphSourceRingHom L hind =
        (R.selectedSemanticBranchExtensionToSelectedGraphSource
          L hind).toRingHom.comp
          (R.sAcSemanticRightBranchToSelectedSemanticBranchExtension L) := by
  exact ⟨R.seSemanticRightBranchToSelectedGraph_factor_extension L hind,
    R.sAaSemanticRightBranchToSelectedGraph_factor_extension L hind,
    R.sbSemanticRightBranchToSelectedGraph_factor_extension L hind,
    R.sAcSemanticRightBranchToSelectedGraph_factor_extension L hind⟩

/-- The coefficient-faithful semantic source cover embeds in the combined
reference/semantic cover. -/
theorem branchComparisonSourceCover_le_referenceSemanticSourceCover
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (R.branchComparisonSourceCover hind).field ≤
      (R.referenceSemanticSourceCover L hind).field :=
  le_sup_left

/-- The literal inclusion of the semantic branch-comparison cover in the
combined semantic/reference source cover. -/
def branchComparisonSourceCoverToReferenceSemanticSourceCover
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (↥(R.branchComparisonSourceCover hind).field) →ₐ[k]
      (↥(R.referenceSemanticSourceCover L hind).field) :=
  IntermediateField.inclusion (show
    (R.branchComparisonSourceCover hind).field.restrictScalars k ≤
      (R.referenceSemanticSourceCover L hind).field.restrictScalars k from
    R.branchComparisonSourceCover_le_referenceSemanticSourceCover L hind)

/-! ### One finite normal codomain for the four semilinear source charts -/

/-- The complete selected right `e` curve branch, acted on by the semantic
right arrow and included in the combined semantic/reference source. -/
noncomputable def seSemanticRightCurveBranchToReferenceSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ).branchOverSource →+*
      (R.referenceSemanticSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToReferenceSemanticSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightE.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).seY.toRingHom.comp
        (R.seSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

/-- Pointwise, the preceding complete-branch map is the charted semantic
right arrow followed by the literal final-cover inclusion. -/
theorem seSemanticRightCurveBranchToReferenceSourceRingHom_apply
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b))
    (z :
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.se) R.seCommonBaseData hψ).branchOverSource) :
    R.seSemanticRightCurveBranchToReferenceSourceRingHom L hind z =
      R.branchComparisonSourceCoverToReferenceSemanticSourceCover L hind
        ((R.coefficientFourArrowDiagram hind).rightE
          ((R.coefficientFourTriangleReference hind).seY
            ((R.seSelectedRightBranchInComparisonMiddleCover
              hind).toAlgHom z))) :=
  rfl

/-- The complete selected right `a` curve branch after its semantic right
arrow, in the same combined source. -/
noncomputable def sAaSemanticRightCurveBranchToReferenceSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ).branchOverSource →+*
      (R.referenceSemanticSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToReferenceSemanticSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightA.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).sAaY.toRingHom.comp
        (R.sAaSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

/-- Pointwise description of the charted semantic `a` arrow on its complete
curve branch field. -/
theorem sAaSemanticRightCurveBranchToReferenceSourceRingHom_apply
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b))
    (z :
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.sAa) R.sAaCommonBaseData hψ).branchOverSource) :
    R.sAaSemanticRightCurveBranchToReferenceSourceRingHom L hind z =
      R.branchComparisonSourceCoverToReferenceSemanticSourceCover L hind
        ((R.coefficientFourArrowDiagram hind).rightA
          ((R.coefficientFourTriangleReference hind).sAaY
            ((R.sAaSelectedRightBranchInComparisonMiddleCover
              hind).toAlgHom z))) :=
  rfl

/-- The complete selected right `b` curve branch after its semantic right
arrow, in the combined source. -/
noncomputable def sbSemanticRightCurveBranchToReferenceSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ).branchOverSource →+*
      (R.referenceSemanticSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToReferenceSemanticSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightB.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).sbY.toRingHom.comp
        (R.sbSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

/-- Pointwise description of the charted semantic `b` arrow on its complete
curve branch field. -/
theorem sbSemanticRightCurveBranchToReferenceSourceRingHom_apply
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b))
    (z :
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.sb) R.sbCommonBaseData hψ).branchOverSource) :
    R.sbSemanticRightCurveBranchToReferenceSourceRingHom L hind z =
      R.branchComparisonSourceCoverToReferenceSemanticSourceCover L hind
        ((R.coefficientFourArrowDiagram hind).rightB
          ((R.coefficientFourTriangleReference hind).sbY
            ((R.sbSelectedRightBranchInComparisonMiddleCover
              hind).toAlgHom z))) :=
  rfl

/-- The complete selected right `c` curve branch after its semantic right
arrow, in the combined source. -/
noncomputable def sAcSemanticRightCurveBranchToReferenceSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ).branchOverSource →+*
      (R.referenceSemanticSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToReferenceSemanticSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightC.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).sAcY.toRingHom.comp
        (R.sAcSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

/-- Pointwise description of the charted semantic `c` arrow on its complete
curve branch field. -/
theorem sAcSemanticRightCurveBranchToReferenceSourceRingHom_apply
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b))
    (z :
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
        (R := R.sAc) R.sAcCommonBaseData hψ).branchOverSource) :
    R.sAcSemanticRightCurveBranchToReferenceSourceRingHom L hind z =
      R.branchComparisonSourceCoverToReferenceSemanticSourceCover L hind
        ((R.coefficientFourArrowDiagram hind).rightC
          ((R.coefficientFourTriangleReference hind).sAcY
            ((R.sAcSelectedRightBranchInComparisonMiddleCover
              hind).toAlgHom z))) :=
  rfl

/-- The charted semantic `e` branch in the selected graph source.  Its
codomain now also contains the once-canonicalized relocated branch and its
intrinsic coefficient embedding. -/
noncomputable def seChartedSemanticRightBranchToSelectedGraphSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ).branchOverSource →+*
      (R.selectedGraphSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToSelectedGraphSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightE.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).seY.toRingHom.comp
        (R.seSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

/-- The charted semantic `a` branch in the same selected graph source. -/
noncomputable def sAaChartedSemanticRightBranchToSelectedGraphSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ).branchOverSource →+*
      (R.selectedGraphSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToSelectedGraphSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightA.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).sAaY.toRingHom.comp
        (R.sAaSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

/-- The charted semantic `b` branch in the same selected graph source. -/
noncomputable def sbChartedSemanticRightBranchToSelectedGraphSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ).branchOverSource →+*
      (R.selectedGraphSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToSelectedGraphSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightB.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).sbY.toRingHom.comp
        (R.sbSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

/-- The charted semantic `c` branch in the same selected graph source. -/
noncomputable def sAcChartedSemanticRightBranchToSelectedGraphSourceRingHom
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ).branchOverSource →+*
      (R.selectedGraphSourceCover L hind).field :=
  (R.branchComparisonSourceCoverToSelectedGraphSourceCover
      L hind).toRingHom.comp
    ((R.coefficientFourArrowDiagram hind).rightC.toRingHom.comp
      ((R.coefficientFourTriangleReference hind).sAcY.toRingHom.comp
        (R.sAcSelectedRightBranchInComparisonMiddleCover
          hind).toAlgHom.toRingHom))

end ReferenceFieldAliases

end QWitness.PsiCurveFourArrowCommonSourceRealizations

end

end AclGeom
