/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Closure.Ambient
import AclGeom.Config.ChunkCurveFourArrow
import Mathlib.FieldTheory.RatFunc.AsPolynomial

/-!
# A common formal curve source for the four Ψ edges

The edgewise curve triangles constructed previously use different unused
coordinates of the eight-parameter input tuple.  They therefore cannot be
rebased directly to the field generated by all eight inputs: each chosen
source already belongs to that field.

This file adjoins one formal rational-function variable to the original
ambient field and passes to its algebraic closure.  The image of `X` is
transcendental over the whole original ambient field, hence generic over
every parameter tuple coming from it.  Ambient invariance transports the
selected Ψ locus and all algebraicity data along the canonical embedding.
The complete nine-coordinate locus can consequently be relocated over each
of the four parameter edges while fixing the same formal source literally.
-/

namespace AclGeom

open IntermediateField

noncomputable section

universe u

variable {k K Ω : Type u} [Field k] [Field K] [Algebra k K]
  [Field Ω] [Algebra k Ω]

/-- The algebraically closed ambient field obtained by adjoining one formal
curve coordinate to `K`. -/
abbrev CommonCurveAmbient (K : Type u) [Field K] :=
  AlgebraicClosure (RatFunc K)

/-- The canonical ground-field embedding of the original ambient field into
the common curve ambient field. -/
def commonCurveEmbedding : K →ₐ[k] CommonCurveAmbient K :=
  IsScalarTower.toAlgHom k K (CommonCurveAmbient K)

/-- The common formal curve source, namely the image of the rational-function
variable in the algebraic closure of `K(X)`. -/
def commonCurveSource : CommonCurveAmbient K :=
  algebraMap (RatFunc K) (CommonCurveAmbient K) RatFunc.X

/-- The common formal curve source is transcendental even over the entire
original ambient field. -/
theorem commonCurveSource_transcendental :
    Transcendental K (commonCurveSource (K := K)) := by
  rw [commonCurveSource, transcendental_algebraMap_iff
    (algebraMap (RatFunc K) (CommonCurveAmbient K)).injective]
  exact RatFunc.transcendental_X

/-- Consequently the formal source is generic over the image of every finite
tuple from the original ambient field. -/
theorem commonCurveSource_notMem_racl {n : ℕ} (q : Fin n → K) :
    commonCurveSource (K := K) ∉ racl k
      (Set.range (commonCurveEmbedding (k := k) (K := K) ∘ q)) := by
  intro hmem
  let ι : K →ₐ[k] CommonCurveAmbient K :=
    commonCurveEmbedding (k := k) (K := K)
  let E : IntermediateField k (CommonCurveAmbient K) :=
    adjoin k (Set.range (ι ∘ q))
  let F : IntermediateField k (CommonCurveAmbient K) :=
    (⊤ : IntermediateField k K).map ι
  have hEF : E ≤ F := by
    apply adjoin_le_iff.2
    rintro _ ⟨j, rfl⟩
    exact (IntermediateField.map_mem_map
      (S := (⊤ : IntermediateField k K)) ι).2 trivial
  have hE : IsAlgebraic E (commonCurveSource (K := K)) :=
    (mem_racl_iff k).1 hmem
  letI : Algebra E F := (IntermediateField.inclusion hEF).toAlgebra
  haveI : IsScalarTower E F (CommonCurveAmbient K) :=
    .of_algebraMap_eq fun _ ↦ rfl
  have hF : IsAlgebraic F (commonCurveSource (K := K)) :=
    hE.tower_top F
  let eK0 : K ≃ₐ[k] ((⊤ : IntermediateField k K).map ι) :=
    IntermediateField.topEquiv.symm.trans
      ((⊤ : IntermediateField k K).equivMap ι)
  let eK : K ≃ₐ[k] F := eK0
  have hcomm :
      RingHom.comp (algebraMap F (CommonCurveAmbient K))
          eK.toRingEquiv.toRingHom =
        RingHom.comp (RingHom.id (CommonCurveAmbient K))
          (algebraMap K (CommonCurveAmbient K)) := by
    ext x
    change (ι x : CommonCurveAmbient K) =
      algebraMap K (CommonCurveAmbient K) x
    rfl
  have halgK : IsAlgebraic K (commonCurveSource (K := K)) :=
    (isAlgebraic_ringHom_iff_of_comp_eq eK.toRingEquiv
      (RingHom.id (CommonCurveAmbient K)) Function.injective_id hcomm).1 hF
  exact commonCurveSource_transcendental halgK

namespace QWitness

variable (w : QWitness k K)

/-- The parameter-and-curve tuple, with its ambient field independent of the
ambient field containing the original Ψ witness. -/
def psiCurveCompositionTupleOver (_w : QWitness k K) (a b c : Fin 2 → Ω)
    (x y z : Ω) : Fin 9 → Ω :=
  ![a 0, a 1, b 0, b 1, c 0, c 1, x, y, z]

/-- The six displayed parameters followed by a curve source, in an arbitrary
ambient field. -/
def psiCurveParameterSourceTupleOver (_w : QWitness k K) (a b c : Fin 2 → Ω)
    (x : Ω) : Fin 7 → Ω :=
  Fin.snoc (compositionParameterTuple a b c) x

/-- Mapping a parameter-and-curve tuple is the same as constructing the tuple
from the mapped coordinates. -/
@[simp] theorem psiCurveCompositionTupleOver_map
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → K) (x y z : K) :
    w.psiCurveCompositionTupleOver (ι ∘ a) (ι ∘ b) (ι ∘ c)
        (ι x) (ι y) (ι z) =
      ι ∘ w.psiCurveCompositionTuple a b c x y z := by
  funext i
  fin_cases i <;> rfl

/-- Mapping the parameter/source prefix is the same as constructing it from
the mapped coordinates. -/
@[simp] theorem psiCurveParameterSourceTupleOver_map
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → K) (x : K) :
    w.psiCurveParameterSourceTupleOver (ι ∘ a) (ι ∘ b) (ι ∘ c) (ι x) =
      ι ∘ psiCurveParameterSourceTuple a b c x := by
  funext i
  fin_cases i <;> rfl

/-- A realization of the selected Ψ curve-composition locus after embedding
the original witness ambient field into a new algebraically closed field. -/
structure PsiCurveCompositionBaseChangeRealization
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → Ω) where
  /-- Shared source coordinate of the first and direct branches. -/
  source : Ω
  /-- Shared middle coordinate of the first two branches. -/
  middle : Ω
  /-- Shared target coordinate of the second and direct branches. -/
  target : Ω
  /-- The complete relocated locus equals the embedded selected Ψ locus. -/
  locus :
    idealOf k (w.psiCurveCompositionTupleOver a b c source middle target) =
      idealOf k (ι ∘ w.psiSelectedCurveCompositionTuple)

/-- The selected Ψ curve locus relocates along any ambient embedding while
fixing mapped parameters and any source generic over those parameters. -/
theorem exists_psiCurveCompositionBaseChangeRealization [IsAlgClosed Ω]
    (ι : K →ₐ[k] Ω) (hψ : w.Psi) {a b c : Fin 2 → K}
    (hrel : w.psiFamilyCompositionRelation a b c) {x : Ω}
    (hx : x ∉ racl k
      (Set.range (ι ∘ compositionParameterTuple a b c))) :
    ∃ R : w.PsiCurveCompositionBaseChangeRealization ι
        (ι ∘ a) (ι ∘ b) (ι ∘ c),
      R.source = x := by
  have hparameter :
      idealOf k (ι ∘ compositionParameterTuple a b c) =
        idealOf k (ι ∘ w.abcReps) := by
    calc
      idealOf k (ι ∘ compositionParameterTuple a b c) =
          idealOf k (compositionParameterTuple a b c) :=
        idealOf_comp_algHom k ι _
      _ = idealOf k w.abcReps := by
        simpa [psiFamilyCompositionRelation] using hrel
      _ = idealOf k (ι ∘ w.abcReps) :=
        (idealOf_comp_algHom k ι _).symm
  have hsource :
      ι w.X.rep ∉ racl k (Set.range (ι ∘ w.abcReps)) := by
    intro hmem
    rw [Set.range_comp] at hmem
    exact w.X_rep_notMem_racl_abcReps hψ
      ((algHom_mem_racl_image_iff ι).1 hmem)
  have hfixed :
      idealOf k (w.psiCurveParameterSourceTupleOver
          (ι ∘ a) (ι ∘ b) (ι ∘ c) x) =
        idealOf k (ι ∘ psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep) := by
    rw [← w.psiCurveParameterSourceTupleOver_map]
    change idealOf k (Fin.snoc
        (compositionParameterTuple (ι ∘ a) (ι ∘ b) (ι ∘ c)) x) =
      idealOf k (Fin.snoc
        (compositionParameterTuple (ι ∘ w.aReps) (ι ∘ w.bReps)
          (ι ∘ w.cReps)) (ι w.X.rep))
    have hmapParameters :
        compositionParameterTuple (ι ∘ a) (ι ∘ b) (ι ∘ c) =
          ι ∘ compositionParameterTuple a b c := by
      funext i
      fin_cases i <;> rfl
    have hmapSelected :
        compositionParameterTuple (ι ∘ w.aReps) (ι ∘ w.bReps)
            (ι ∘ w.cReps) =
          ι ∘ w.abcReps := by
      funext i
      fin_cases i <;> rfl
    rw [hmapParameters, hmapSelected]
    exact idealOf_snoc_eq_of_idealOf_eq_of_generic
      hparameter hx hsource
  have hselectedAlgebraic (j : Fin 9) :
      (ι ∘ w.psiSelectedCurveCompositionTuple) j ∈ racl k
        (Set.range (ι ∘ psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep)) := by
    rw [Set.range_comp]
    exact (algHom_mem_racl_image_iff ι).2
      (w.psiSelectedCurveCompositionTuple_mem_parameterSource_racl hψ j)
  obtain ⟨v, hv, hfix⟩ := exists_tuple_relocation_fixing_locus
    hfixed
    (u := ι ∘ w.psiSelectedCurveCompositionTuple)
    (e := psiCurveParameterSourceIndex)
    (fun i ↦ by
      change ι (w.psiSelectedCurveCompositionTuple
          (psiCurveParameterSourceIndex i)) =
        ι (psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep i)
      congr 1
      exact congrFun
        (w.psiCurveCompositionTuple_comp_parameterSourceIndex
          w.aReps w.bReps w.cReps w.X.rep w.Y.rep w.Z.rep) i)
    hselectedAlgebraic
  let y : Ω := v 7
  let z : Ω := v 8
  have htotal :
      w.psiCurveCompositionTupleOver
          (ι ∘ a) (ι ∘ b) (ι ∘ c) x y z = v := by
    funext i
    fin_cases i
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 0).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 1).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 2).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 3).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 4).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 5).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 6).symm
    · rfl
    · rfl
  let R : w.PsiCurveCompositionBaseChangeRealization ι
      (ι ∘ a) (ι ∘ b) (ι ∘ c) :=
    { source := x
      middle := y
      target := z
      locus := by rw [htotal]; exact hv }
  exact ⟨R, rfl⟩

namespace PsiCurveCompositionBaseChangeRealization

variable {w : QWitness k K} {ι : K →ₐ[k] Ω}
  {a b c : Fin 2 → Ω}
  (R : w.PsiCurveCompositionBaseChangeRealization ι a b c)

/-- The complete tuple of an ambient-base-changed realization. -/
abbrev totalTuple : Fin 9 → Ω :=
  w.psiCurveCompositionTupleOver a b c R.source R.middle R.target

/-- Its `A` branch is the corresponding restriction of the complete
tuple. -/
@[simp] theorem totalTuple_comp_aFamilyIndex :
    R.totalTuple ∘ PsiCurveCompositionRealization.aFamilyIndex =
      Fin.snoc (Fin.snoc a R.source) R.middle := by
  funext i
  fin_cases i <;> rfl

/-- Its `B` branch is the corresponding restriction of the complete
tuple. -/
@[simp] theorem totalTuple_comp_bFamilyIndex :
    R.totalTuple ∘ PsiCurveCompositionRealization.bFamilyIndex =
      Fin.snoc (Fin.snoc b R.middle) R.target := by
  funext i
  fin_cases i <;> rfl

/-- Its direct `C` branch is the corresponding restriction of the complete
tuple. -/
@[simp] theorem totalTuple_comp_cFamilyIndex :
    R.totalTuple ∘ PsiCurveCompositionRealization.cFamilyIndex =
      Fin.snoc (Fin.snoc c R.source) R.target := by
  funext i
  fin_cases i <;> rfl

/-- The embedded selected tuple restricts to the embedded selected `A`
family member. -/
@[simp] theorem selectedTuple_comp_aFamilyIndex (hψ : w.Psi) :
    (ι ∘ w.psiSelectedCurveCompositionTuple) ∘
        PsiCurveCompositionRealization.aFamilyIndex =
      ((w.xyCorrespondenceFamilyMember hψ).map ι).tuple := by
  funext i
  fin_cases i <;> rfl

/-- The embedded selected tuple restricts to the embedded selected `B`
family member. -/
@[simp] theorem selectedTuple_comp_bFamilyIndex (hψ : w.Psi) :
    (ι ∘ w.psiSelectedCurveCompositionTuple) ∘
        PsiCurveCompositionRealization.bFamilyIndex =
      ((w.yzCorrespondenceFamilyMember hψ).map ι).tuple := by
  funext i
  fin_cases i <;> rfl

/-- The embedded selected tuple restricts to the embedded selected `C`
family member. -/
@[simp] theorem selectedTuple_comp_cFamilyIndex (hψ : w.Psi) :
    (ι ∘ w.psiSelectedCurveCompositionTuple) ∘
        PsiCurveCompositionRealization.cFamilyIndex =
      ((w.xzCorrespondenceFamilyMember hψ).map ι).tuple := by
  funext i
  fin_cases i <;> rfl

/-- The relocated `A` branch has exactly the embedded selected `A` family
locus. -/
theorem aFamilyLocus (hψ : w.Psi) :
    idealOf k (Fin.snoc (Fin.snoc a R.source) R.middle) =
      ((w.xyCorrespondenceFamilyMember hψ).map ι).ideal := by
  have h := idealOf_comp_eq_of_idealOf_eq R.locus
    PsiCurveCompositionRealization.aFamilyIndex
  change idealOf k (Fin.snoc (Fin.snoc a R.source) R.middle) =
    idealOf k ((w.xyCorrespondenceFamilyMember hψ).map ι).tuple
  rw [← R.totalTuple_comp_aFamilyIndex,
    ← selectedTuple_comp_aFamilyIndex (w := w) (ι := ι) hψ]
  exact h

/-- The relocated `B` branch has exactly the embedded selected `B` family
locus. -/
theorem bFamilyLocus (hψ : w.Psi) :
    idealOf k (Fin.snoc (Fin.snoc b R.middle) R.target) =
      ((w.yzCorrespondenceFamilyMember hψ).map ι).ideal := by
  have h := idealOf_comp_eq_of_idealOf_eq R.locus
    PsiCurveCompositionRealization.bFamilyIndex
  change idealOf k (Fin.snoc (Fin.snoc b R.middle) R.target) =
    idealOf k ((w.yzCorrespondenceFamilyMember hψ).map ι).tuple
  rw [← R.totalTuple_comp_bFamilyIndex,
    ← selectedTuple_comp_bFamilyIndex (w := w) (ι := ι) hψ]
  exact h

/-- The relocated direct `C` branch has exactly the embedded selected `C`
family locus. -/
theorem cFamilyLocus (hψ : w.Psi) :
    idealOf k (Fin.snoc (Fin.snoc c R.source) R.target) =
      ((w.xzCorrespondenceFamilyMember hψ).map ι).ideal := by
  have h := idealOf_comp_eq_of_idealOf_eq R.locus
    PsiCurveCompositionRealization.cFamilyIndex
  change idealOf k (Fin.snoc (Fin.snoc c R.source) R.target) =
    idealOf k ((w.xzCorrespondenceFamilyMember hψ).map ι).tuple
  rw [← R.totalTuple_comp_cFamilyIndex,
    ← selectedTuple_comp_cFamilyIndex (w := w) (ι := ι) hψ]
  exact h

/-- The relocated embedded `A` restriction is a genuine generic member of
the mapped selected family. -/
def aCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) 2 :=
  ((w.xyCorrespondenceFamilyMember hψ).map ι).ofTupleIdealEqOnly
    (R.aFamilyLocus hψ)

/-- The relocated embedded `B` restriction is a genuine generic member of
the mapped selected family. -/
def bCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) 2 :=
  ((w.yzCorrespondenceFamilyMember hψ).map ι).ofTupleIdealEqOnly
    (R.bFamilyLocus hψ)

/-- The relocated embedded `C` restriction is a genuine generic member of
the mapped selected family. -/
def cCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) 2 :=
  ((w.xzCorrespondenceFamilyMember hψ).map ι).ofTupleIdealEqOnly
    (R.cFamilyLocus hψ)

/-- Data witnessing that an embedded curve triangle can be regarded over a
larger common coefficient field.  Its three displayed parameter blocks may
be algebraic, rather than rational, over that field. -/
structure CommonBaseData {n : ℕ} (base : Fin n → Ω) where
  /-- The source coordinate used literally in all common-base pairs. -/
  source : Ω
  /-- The relocated source equals the displayed common source. -/
  source_eq : R.source = source
  /-- The common source is generic over the larger coefficient tuple. -/
  source_generic : source ∉ racl k (Set.range base)
  /-- Every `A` parameter coordinate is algebraic over the common base. -/
  a_mem : ∀ i, a i ∈ racl k (Set.range base)
  /-- Every `B` parameter coordinate is algebraic over the common base. -/
  b_mem : ∀ i, b i ∈ racl k (Set.range base)
  /-- Every `C` parameter coordinate is algebraic over the common base. -/
  c_mem : ∀ i, c i ∈ racl k (Set.range base)

namespace CommonBaseData

variable {n : ℕ} {base : Fin n → Ω}
  (H : R.CommonBaseData base)

/-- The common coefficient field generated by the larger base tuple. -/
def coefficientField (_H : R.CommonBaseData base) :
    IntermediateField k Ω :=
  adjoin k (Set.range base)

private theorem lift_insert_dependency
    (_H : R.CommonBaseData base) {p : Fin 2 → Ω} {x y : Ω}
    (hy : y ∈ racl k (insert x (Set.range p)))
    (hp : ∀ i, p i ∈ racl k (Set.range base)) :
    y ∈ racl k (insert x (Set.range base)) := by
  refine racl_le_of_subset_racl ?_ hy
  intro z hz
  rw [Set.mem_insert_iff] at hz
  rcases hz with rfl | ⟨i, rfl⟩
  · exact subset_racl k _ (Set.mem_insert _ _)
  · exact racl_mono (Set.subset_insert x _) (hp i)

private theorem descend_generic
    (_H : R.CommonBaseData base) {p : Fin 2 → Ω} {x y : Ω}
    (hx : x ∉ racl k (Set.range base))
    (hxy : x ∈ racl k (insert y (Set.range p)))
    (hp : ∀ i, p i ∈ racl k (Set.range base)) :
    y ∉ racl k (Set.range base) := by
  intro hy
  apply hx
  refine racl_le_of_subset_racl ?_ hxy
  intro z hz
  rw [Set.mem_insert_iff] at hz
  rcases hz with rfl | ⟨i, rfl⟩
  · exact hy
  · exact hp i

/-- The embedded `A` branch as a finite correspondence over the larger
common coefficient field. -/
def aCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥H.coefficientField) Ω where
  source := H.source
  target := R.middle
  source_generic := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact H.source_generic
  target_mem_source := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.aCorrespondenceFamilyMember hψ)
      |>.target_mem_parameter_source
    change R.middle ∈ racl k (insert R.source (Set.range a)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.a_mem
  source_mem_target := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.aCorrespondenceFamilyMember hψ)
      |>.source_mem_parameter_target
    change R.source ∈ racl k (insert R.middle (Set.range a)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.a_mem

/-- The middle coordinate is generic over the larger common coefficient
field because it is interalgebraic there with the common formal source. -/
theorem middle_generic (H : R.CommonBaseData base) (hψ : w.Psi) :
    R.middle ∉ racl k (Set.range base) := by
  have h := (R.aCorrespondenceFamilyMember hψ)
    |>.source_mem_parameter_target
  change R.source ∈ racl k (insert R.middle (Set.range a)) at h
  rw [H.source_eq] at h
  exact descend_generic (R := R) H H.source_generic h H.a_mem

/-- The embedded `B` branch as a finite correspondence over the same
larger common coefficient field. -/
def bCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥H.coefficientField) Ω where
  source := R.middle
  target := R.target
  source_generic := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact middle_generic (R := R) H hψ
  target_mem_source := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.bCorrespondenceFamilyMember hψ)
      |>.target_mem_parameter_source
    change R.target ∈ racl k (insert R.middle (Set.range b)) at h
    exact lift_insert_dependency (R := R) H h H.b_mem
  source_mem_target := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.bCorrespondenceFamilyMember hψ)
      |>.source_mem_parameter_target
    change R.middle ∈ racl k (insert R.target (Set.range b)) at h
    exact lift_insert_dependency (R := R) H h H.b_mem

/-- The embedded direct `C` branch as a finite correspondence over the
same larger common coefficient field. -/
def cCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥H.coefficientField) Ω where
  source := H.source
  target := R.target
  source_generic := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact H.source_generic
  target_mem_source := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.cCorrespondenceFamilyMember hψ)
      |>.target_mem_parameter_source
    change R.target ∈ racl k (insert R.source (Set.range c)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.c_mem
  source_mem_target := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.cCorrespondenceFamilyMember hψ)
      |>.source_mem_parameter_target
    change R.source ∈ racl k (insert R.target (Set.range c)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.c_mem

/-- The two successive common-base pairs share their middle coordinate
definitionally. -/
@[simp] theorem aPair_target_eq_bPair_source (hψ : w.Psi) :
    (aCorrespondencePair (R := R) H hψ).target =
      (bCorrespondencePair (R := R) H hψ).source := rfl

/-- The common finite normal source cover of the larger-base triangle. -/
noncomputable def finiteSourceCover (hψ : w.Psi) :=
  FiniteCorrespondencePair.FiniteCoverTriangle.sourceCover
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)

/-- The common finite normal middle cover of the larger-base triangle. -/
noncomputable def finiteMiddleCover (hψ : w.Psi) :=
  FiniteCorrespondencePair.FiniteCoverTriangle.middleCover
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)

/-- The common finite normal target cover of the larger-base triangle. -/
noncomputable def finiteTargetCover (hψ : w.Psi) :=
  FiniteCorrespondencePair.FiniteCoverTriangle.targetCover
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)

/-- The deck-corrected finite-cover action of the common-base triangle. -/
noncomputable def finiteCoverCompositionTriangle (hψ : w.Psi) :
    FieldEquiv.CompositionTriangle
      (↥(finiteSourceCover (R := R) H hψ).field)
      (↥(finiteMiddleCover (R := R) H hψ).field)
      (↥(finiteTargetCover (R := R) H hψ).field) where
  left := FiniteCorrespondencePair.FiniteCoverTriangle.leftEquiv
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)
  right := FiniteCorrespondencePair.FiniteCoverTriangle.rightEquiv
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)
  direct := FiniteCorrespondencePair.FiniteCoverTriangle.strictDirectEquiv
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)
  composition :=
    FiniteCorrespondencePair.FiniteCoverTriangle.strictComposition
      (aCorrespondencePair (R := R) H hψ)
      (bCorrespondencePair (R := R) H hψ)
      (aPair_target_eq_bPair_source (R := R) H hψ)

end CommonBaseData

end PsiCurveCompositionBaseChangeRealization

/-- Four embedded Ψ curve triangles with one literal common formal source. -/
structure PsiCurveFourArrowCommonSourceRealizations
    (hψ : w.Psi) {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) where
  /-- Curve triangle above `s·e=u`. -/
  se : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ s)
    (commonCurveEmbedding (k := k) (K := K) ∘ e)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
  /-- Its source is the common formal coordinate. -/
  se_source : se.source = commonCurveSource (K := K)
  /-- Curve triangle above `sA·a=u`. -/
  sAa : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
    (commonCurveEmbedding (k := k) (K := K) ∘ a)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
  /-- Its source is the same common formal coordinate. -/
  sAa_source : sAa.source = commonCurveSource (K := K)
  /-- Curve triangle above `s·b=uB`. -/
  sb : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ s)
    (commonCurveEmbedding (k := k) (K := K) ∘ b)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
  /-- Its source is the same common formal coordinate. -/
  sb_source : sb.source = commonCurveSource (K := K)
  /-- Curve triangle above `sA·c=uB`. -/
  sAc : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.c)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
  /-- Its source is the same common formal coordinate. -/
  sAc_source : sAc.source = commonCurveSource (K := K)

/-- The formal rational-function coordinate supplies a single common source
for all four edges of every Ψ parameter difference diagram. -/
theorem exists_psiCurveFourArrowCommonSourceRealizations
    (hψ : w.Psi) {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) :
    Nonempty (w.PsiCurveFourArrowCommonSourceRealizations hψ D) := by
  let ι : K →ₐ[k] CommonCurveAmbient K :=
    commonCurveEmbedding (k := k) (K := K)
  have hse : w.psiFamilyCompositionRelation s e D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s e D.u).2 D.se_u
  have hsAa : w.psiFamilyCompositionRelation D.sA a D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA a D.u).2 D.sA_a_u
  have hsb : w.psiFamilyCompositionRelation s b D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s b D.uB).2
      D.s_b_uB
  have hsAc : w.psiFamilyCompositionRelation D.sA D.c D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA D.c D.uB).2 D.sA_c_uB
  obtain ⟨Rse, hRse⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hse
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple s e D.u))
  obtain ⟨RsAa, hRsAa⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsAa
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple D.sA a D.u))
  obtain ⟨Rsb, hRsb⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsb
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple s b D.uB))
  obtain ⟨RsAc, hRsAc⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsAc
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple D.sA D.c D.uB))
  exact ⟨⟨Rse, hRse, RsAa, hRsAa, Rsb, hRsb, RsAc, hRsAc⟩⟩

namespace PsiCurveFourArrowCommonSourceRealizations

variable {w : QWitness k K} {hψ : w.Psi}
  {s a b e : Fin 2 → K}
  {D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e}
  (R : w.PsiCurveFourArrowCommonSourceRealizations hψ D)

/-- The mapped eight-input tuple used as the one coefficient base for all
four embedded curve triangles. -/
def commonInputTuple (_R : w.PsiCurveFourArrowCommonSourceRealizations hψ D) :
    Fin 8 → CommonCurveAmbient K :=
  commonCurveEmbedding (k := k) (K := K) ∘
    rankTwoFourTuple s e a b

private theorem map_mem_input_racl {x : K}
    (hx : x ∈ racl k (Set.range (rankTwoFourTuple s e a b))) :
    commonCurveEmbedding (k := k) (K := K) x ∈ racl k
      (Set.range R.commonInputTuple) := by
  rw [commonInputTuple, Set.range_comp]
  exact (algHom_mem_racl_image_iff
    (commonCurveEmbedding (k := k) (K := K))).2 hx

/-- The mapped `s` coordinates belong to the closure of the common input
tuple. -/
theorem s_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (s i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨0, rfl⟩
  · exact subset_racl k _ ⟨1, rfl⟩

/-- The mapped `e` coordinates belong to the closure of the common input
tuple. -/
theorem e_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (e i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨2, rfl⟩
  · exact subset_racl k _ ⟨3, rfl⟩

/-- The mapped `a` coordinates belong to the closure of the common input
tuple. -/
theorem a_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (a i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨4, rfl⟩
  · exact subset_racl k _ ⟨5, rfl⟩

/-- The mapped `b` coordinates belong to the closure of the common input
tuple. -/
theorem b_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (b i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨6, rfl⟩
  · exact subset_racl k _ ⟨7, rfl⟩

/-- The mapped selected output `u` is algebraic over the common input
tuple. -/
theorem u_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.u i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.u_mem_input_racl i)

/-- The mapped selected quotient `sA` is algebraic over the common input
tuple. -/
theorem sA_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.sA i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.sA_mem_input_racl i)

/-- The mapped selected output `uB` is algebraic over the common input
tuple. -/
theorem uB_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.uB i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.uB_mem_input_racl i)

/-- The mapped difference output `c` is algebraic over the common input
tuple. -/
theorem c_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.c i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.c_mem_input_racl i)

/-- Common-base data for the face `s·e=u`. -/
def seCommonBaseData : R.se.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.se_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.s_mem_commonInput_racl
  b_mem := R.e_mem_commonInput_racl
  c_mem := R.u_mem_commonInput_racl

/-- Common-base data for the face `sA·a=u`. -/
def sAaCommonBaseData : R.sAa.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.sAa_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.sA_mem_commonInput_racl
  b_mem := R.a_mem_commonInput_racl
  c_mem := R.u_mem_commonInput_racl

/-- Common-base data for the face `s·b=uB`. -/
def sbCommonBaseData : R.sb.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.sb_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.s_mem_commonInput_racl
  b_mem := R.b_mem_commonInput_racl
  c_mem := R.uB_mem_commonInput_racl

/-- Common-base data for the face `sA·c=uB`. -/
def sAcCommonBaseData : R.sAc.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.sAc_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.sA_mem_commonInput_racl
  b_mem := R.c_mem_commonInput_racl
  c_mem := R.uB_mem_commonInput_racl

/-- The strict finite-cover composition triangle for `s·e=u`, now over the
common eight-input coefficient field. -/
noncomputable def seFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.se) R.seCommonBaseData hψ

/-- The strict finite-cover composition triangle for `sA·a=u`, over the
same common coefficient field. -/
noncomputable def sAaFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.sAa) R.sAaCommonBaseData hψ

/-- The strict finite-cover composition triangle for `s·b=uB`, over the
same common coefficient field. -/
noncomputable def sbFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.sb) R.sbCommonBaseData hψ

/-- The strict finite-cover composition triangle for `sA·c=uB`, over the
same common coefficient field. -/
noncomputable def sAcFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.sAc) R.sAcCommonBaseData hψ

/-- The source cover selected by the `s·e=u` face before simultaneous
enlargement. -/
noncomputable def seFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.se) R.seCommonBaseData hψ

/-- The source cover selected by the `sA·a=u` face before simultaneous
enlargement. -/
noncomputable def sAaFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.sAa) R.sAaCommonBaseData hψ

/-- The source cover selected by the `s·b=uB` face before simultaneous
enlargement. -/
noncomputable def sbFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.sb) R.sbCommonBaseData hψ

/-- The source cover selected by the `sA·c=uB` face before simultaneous
enlargement. -/
noncomputable def sAcFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.sAc) R.sAcCommonBaseData hψ

/-- One finite normal source compositum containing the branch
normalizations required by all four common-base faces.  The four source
coordinate fields are definitionally the same because their coefficient
field and formal source coordinate are literally shared. -/
noncomputable def commonFiniteSourceCover :=
  (((R.seFiniteSourceCover.sup R.sAaFiniteSourceCover).sup
      R.sbFiniteSourceCover).sup R.sAcFiniteSourceCover)

/-- The `s·e=u` source normalization lies in the simultaneous source
compositum. -/
theorem seFiniteSourceCover_le_common :
    R.seFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.seFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact (le_sup_left.trans le_sup_left).trans le_sup_left

/-- The `sA·a=u` source normalization lies in the simultaneous source
compositum. -/
theorem sAaFiniteSourceCover_le_common :
    R.sAaFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.sAaFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact (le_sup_right.trans le_sup_left).trans le_sup_left

/-- The `s·b=uB` source normalization lies in the simultaneous source
compositum. -/
theorem sbFiniteSourceCover_le_common :
    R.sbFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.sbFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact le_sup_right.trans le_sup_left

/-- The `sA·c=uB` source normalization lies in the simultaneous source
compositum. -/
theorem sAcFiniteSourceCover_le_common :
    R.sAcFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.sAcFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact le_sup_right

/-- The strict `s·e=u` action after enlarging its source to the
simultaneous four-face compositum. -/
noncomputable def seCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.se) R.seCommonBaseData hψ)
    R.commonFiniteSourceCover

/-- The strict `sA·a=u` action on the same simultaneous source
compositum. -/
noncomputable def sAaCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.sAa) R.sAaCommonBaseData hψ)
    R.commonFiniteSourceCover

/-- The strict `s·b=uB` action on the same simultaneous source
compositum. -/
noncomputable def sbCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.sb) R.sbCommonBaseData hψ)
    R.commonFiniteSourceCover

/-- The strict `sA·c=uB` action on the same simultaneous source
compositum. -/
noncomputable def sAcCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.sAc) R.sAcCommonBaseData hψ)
    R.commonFiniteSourceCover

end PsiCurveFourArrowCommonSourceRealizations

end QWitness

end

end AclGeom
