/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Closure.Ambient
import AclGeom.Config.ChunkCurveFourArrow
import AclGeom.Correspondence.FamilyCover
import Mathlib.FieldTheory.RatFunc.AsPolynomial

/-!
# A common formal curve source for the four Ψ edges

The edgewise curve triangles constructed previously use different unused
coordinates of the eight-parameter input tuple.  They therefore cannot be
rebased directly to the field generated by all eight inputs: each chosen
source already belongs to that field.

This file adjoins one formal rational-function variable to the original
ambient field and passes to its algebraic closure.  The image of `X` is
transcendental over the whole original ambient field, hence generic over
every parameter tuple coming from it.  Ambient invariance transports the
selected Ψ locus and all algebraicity data along the canonical embedding.
The complete nine-coordinate locus can consequently be relocated over each
of the four parameter edges while fixing the same formal source literally.
-/

namespace AclGeom

open IntermediateField

noncomputable section

universe u

variable {k K Ω : Type u} [Field k] [Field K] [Algebra k K]
  [Field Ω] [Algebra k Ω]

/-- The algebraically closed ambient field obtained by adjoining one formal
curve coordinate to `K`. -/
abbrev CommonCurveAmbient (K : Type u) [Field K] :=
  AlgebraicClosure (RatFunc K)

/-- The canonical ground-field embedding of the original ambient field into
the common curve ambient field. -/
def commonCurveEmbedding : K →ₐ[k] CommonCurveAmbient K :=
  IsScalarTower.toAlgHom k K (CommonCurveAmbient K)

/-- The common formal curve source, namely the image of the rational-function
variable in the algebraic closure of `K(X)`. -/
def commonCurveSource : CommonCurveAmbient K :=
  algebraMap (RatFunc K) (CommonCurveAmbient K) RatFunc.X

/-- The common formal curve source is transcendental even over the entire
original ambient field. -/
theorem commonCurveSource_transcendental :
    Transcendental K (commonCurveSource (K := K)) := by
  rw [commonCurveSource, transcendental_algebraMap_iff
    (algebraMap (RatFunc K) (CommonCurveAmbient K)).injective]
  exact RatFunc.transcendental_X

/-- Consequently the formal source is generic over the image of every finite
tuple from the original ambient field. -/
theorem commonCurveSource_notMem_racl {n : ℕ} (q : Fin n → K) :
    commonCurveSource (K := K) ∉ racl k
      (Set.range (commonCurveEmbedding (k := k) (K := K) ∘ q)) := by
  intro hmem
  let ι : K →ₐ[k] CommonCurveAmbient K :=
    commonCurveEmbedding (k := k) (K := K)
  let E : IntermediateField k (CommonCurveAmbient K) :=
    adjoin k (Set.range (ι ∘ q))
  let F : IntermediateField k (CommonCurveAmbient K) :=
    (⊤ : IntermediateField k K).map ι
  have hEF : E ≤ F := by
    apply adjoin_le_iff.2
    rintro _ ⟨j, rfl⟩
    exact (IntermediateField.map_mem_map
      (S := (⊤ : IntermediateField k K)) ι).2 trivial
  have hE : IsAlgebraic E (commonCurveSource (K := K)) :=
    (mem_racl_iff k).1 hmem
  letI : Algebra E F := (IntermediateField.inclusion hEF).toAlgebra
  haveI : IsScalarTower E F (CommonCurveAmbient K) :=
    .of_algebraMap_eq fun _ ↦ rfl
  have hF : IsAlgebraic F (commonCurveSource (K := K)) :=
    hE.tower_top F
  let eK0 : K ≃ₐ[k] ((⊤ : IntermediateField k K).map ι) :=
    IntermediateField.topEquiv.symm.trans
      ((⊤ : IntermediateField k K).equivMap ι)
  let eK : K ≃ₐ[k] F := eK0
  have hcomm :
      RingHom.comp (algebraMap F (CommonCurveAmbient K))
          eK.toRingEquiv.toRingHom =
        RingHom.comp (RingHom.id (CommonCurveAmbient K))
          (algebraMap K (CommonCurveAmbient K)) := by
    ext x
    change (ι x : CommonCurveAmbient K) =
      algebraMap K (CommonCurveAmbient K) x
    rfl
  have halgK : IsAlgebraic K (commonCurveSource (K := K)) :=
    (isAlgebraic_ringHom_iff_of_comp_eq eK.toRingEquiv
      (RingHom.id (CommonCurveAmbient K)) Function.injective_id hcomm).1 hF
  exact commonCurveSource_transcendental halgK

/-- Mapping an independent ambient tuple into the common curve ambient and
then adjoining the formal source preserves algebraic independence. -/
theorem mappedTuple_snoc_commonCurveSource_independent {n : ℕ}
    {q : Fin n → K} (hq : AlgebraicIndependent k q) :
    AlgebraicIndependent k
      (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ q)
        (commonCurveSource (K := K))) :=
  algebraicIndependent_snoc
    (hq.map' (commonCurveEmbedding (k := k) (K := K)).injective)
    (commonCurveSource_notMem_racl (k := k) (K := K) q)

namespace QWitness

variable (w : QWitness k K)

/-- The parameter-and-curve tuple, with its ambient field independent of the
ambient field containing the original Ψ witness. -/
def psiCurveCompositionTupleOver (_w : QWitness k K) (a b c : Fin 2 → Ω)
    (x y z : Ω) : Fin 9 → Ω :=
  ![a 0, a 1, b 0, b 1, c 0, c 1, x, y, z]

/-- The six displayed parameters followed by a curve source, in an arbitrary
ambient field. -/
def psiCurveParameterSourceTupleOver (_w : QWitness k K) (a b c : Fin 2 → Ω)
    (x : Ω) : Fin 7 → Ω :=
  Fin.snoc (compositionParameterTuple a b c) x

/-- Mapping a parameter-and-curve tuple is the same as constructing the tuple
from the mapped coordinates. -/
@[simp] theorem psiCurveCompositionTupleOver_map
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → K) (x y z : K) :
    w.psiCurveCompositionTupleOver (ι ∘ a) (ι ∘ b) (ι ∘ c)
        (ι x) (ι y) (ι z) =
      ι ∘ w.psiCurveCompositionTuple a b c x y z := by
  funext i
  fin_cases i <;> rfl

/-- Mapping the parameter/source prefix is the same as constructing it from
the mapped coordinates. -/
@[simp] theorem psiCurveParameterSourceTupleOver_map
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → K) (x : K) :
    w.psiCurveParameterSourceTupleOver (ι ∘ a) (ι ∘ b) (ι ∘ c) (ι x) =
      ι ∘ psiCurveParameterSourceTuple a b c x := by
  funext i
  fin_cases i <;> rfl

/-- A realization of the selected Ψ curve-composition locus after embedding
the original witness ambient field into a new algebraically closed field. -/
structure PsiCurveCompositionBaseChangeRealization
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → Ω) where
  /-- Shared source coordinate of the first and direct branches. -/
  source : Ω
  /-- Shared middle coordinate of the first two branches. -/
  middle : Ω
  /-- Shared target coordinate of the second and direct branches. -/
  target : Ω
  /-- The complete relocated locus equals the embedded selected Ψ locus. -/
  locus :
    idealOf k (w.psiCurveCompositionTupleOver a b c source middle target) =
      idealOf k (ι ∘ w.psiSelectedCurveCompositionTuple)

/-- The selected Ψ curve locus relocates along any ambient embedding while
fixing mapped parameters and any source generic over those parameters. -/
theorem exists_psiCurveCompositionBaseChangeRealization [IsAlgClosed Ω]
    (ι : K →ₐ[k] Ω) (hψ : w.Psi) {a b c : Fin 2 → K}
    (hrel : w.psiFamilyCompositionRelation a b c) {x : Ω}
    (hx : x ∉ racl k
      (Set.range (ι ∘ compositionParameterTuple a b c))) :
    ∃ R : w.PsiCurveCompositionBaseChangeRealization ι
        (ι ∘ a) (ι ∘ b) (ι ∘ c),
      R.source = x := by
  have hparameter :
      idealOf k (ι ∘ compositionParameterTuple a b c) =
        idealOf k (ι ∘ w.abcReps) := by
    calc
      idealOf k (ι ∘ compositionParameterTuple a b c) =
          idealOf k (compositionParameterTuple a b c) :=
        idealOf_comp_algHom k ι _
      _ = idealOf k w.abcReps := by
        simpa [psiFamilyCompositionRelation] using hrel
      _ = idealOf k (ι ∘ w.abcReps) :=
        (idealOf_comp_algHom k ι _).symm
  have hsource :
      ι w.X.rep ∉ racl k (Set.range (ι ∘ w.abcReps)) := by
    intro hmem
    rw [Set.range_comp] at hmem
    exact w.X_rep_notMem_racl_abcReps hψ
      ((algHom_mem_racl_image_iff ι).1 hmem)
  have hfixed :
      idealOf k (w.psiCurveParameterSourceTupleOver
          (ι ∘ a) (ι ∘ b) (ι ∘ c) x) =
        idealOf k (ι ∘ psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep) := by
    rw [← w.psiCurveParameterSourceTupleOver_map]
    change idealOf k (Fin.snoc
        (compositionParameterTuple (ι ∘ a) (ι ∘ b) (ι ∘ c)) x) =
      idealOf k (Fin.snoc
        (compositionParameterTuple (ι ∘ w.aReps) (ι ∘ w.bReps)
          (ι ∘ w.cReps)) (ι w.X.rep))
    have hmapParameters :
        compositionParameterTuple (ι ∘ a) (ι ∘ b) (ι ∘ c) =
          ι ∘ compositionParameterTuple a b c := by
      funext i
      fin_cases i <;> rfl
    have hmapSelected :
        compositionParameterTuple (ι ∘ w.aReps) (ι ∘ w.bReps)
            (ι ∘ w.cReps) =
          ι ∘ w.abcReps := by
      funext i
      fin_cases i <;> rfl
    rw [hmapParameters, hmapSelected]
    exact idealOf_snoc_eq_of_idealOf_eq_of_generic
      hparameter hx hsource
  have hselectedAlgebraic (j : Fin 9) :
      (ι ∘ w.psiSelectedCurveCompositionTuple) j ∈ racl k
        (Set.range (ι ∘ psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep)) := by
    rw [Set.range_comp]
    exact (algHom_mem_racl_image_iff ι).2
      (w.psiSelectedCurveCompositionTuple_mem_parameterSource_racl hψ j)
  obtain ⟨v, hv, hfix⟩ := exists_tuple_relocation_fixing_locus
    hfixed
    (u := ι ∘ w.psiSelectedCurveCompositionTuple)
    (e := psiCurveParameterSourceIndex)
    (fun i ↦ by
      change ι (w.psiSelectedCurveCompositionTuple
          (psiCurveParameterSourceIndex i)) =
        ι (psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep i)
      congr 1
      exact congrFun
        (w.psiCurveCompositionTuple_comp_parameterSourceIndex
          w.aReps w.bReps w.cReps w.X.rep w.Y.rep w.Z.rep) i)
    hselectedAlgebraic
  let y : Ω := v 7
  let z : Ω := v 8
  have htotal :
      w.psiCurveCompositionTupleOver
          (ι ∘ a) (ι ∘ b) (ι ∘ c) x y z = v := by
    funext i
    fin_cases i
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 0).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 1).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 2).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 3).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 4).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 5).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 6).symm
    · rfl
    · rfl
  let R : w.PsiCurveCompositionBaseChangeRealization ι
      (ι ∘ a) (ι ∘ b) (ι ∘ c) :=
    { source := x
      middle := y
      target := z
      locus := by rw [htotal]; exact hv }
  exact ⟨R, rfl⟩

namespace PsiCurveCompositionBaseChangeRealization

variable {w : QWitness k K} {ι : K →ₐ[k] Ω}
  {a b c : Fin 2 → Ω}
  (R : w.PsiCurveCompositionBaseChangeRealization ι a b c)

/-- The complete tuple of an ambient-base-changed realization. -/
abbrev totalTuple : Fin 9 → Ω :=
  w.psiCurveCompositionTupleOver a b c R.source R.middle R.target

/-- Its `A` branch is the corresponding restriction of the complete
tuple. -/
@[simp] theorem totalTuple_comp_aFamilyIndex :
    R.totalTuple ∘ PsiCurveCompositionRealization.aFamilyIndex =
      Fin.snoc (Fin.snoc a R.source) R.middle := by
  funext i
  fin_cases i <;> rfl

/-- Its `B` branch is the corresponding restriction of the complete
tuple. -/
@[simp] theorem totalTuple_comp_bFamilyIndex :
    R.totalTuple ∘ PsiCurveCompositionRealization.bFamilyIndex =
      Fin.snoc (Fin.snoc b R.middle) R.target := by
  funext i
  fin_cases i <;> rfl

/-- Its direct `C` branch is the corresponding restriction of the complete
tuple. -/
@[simp] theorem totalTuple_comp_cFamilyIndex :
    R.totalTuple ∘ PsiCurveCompositionRealization.cFamilyIndex =
      Fin.snoc (Fin.snoc c R.source) R.target := by
  funext i
  fin_cases i <;> rfl

/-- The embedded selected tuple restricts to the embedded selected `A`
family member. -/
@[simp] theorem selectedTuple_comp_aFamilyIndex (hψ : w.Psi) :
    (ι ∘ w.psiSelectedCurveCompositionTuple) ∘
        PsiCurveCompositionRealization.aFamilyIndex =
      ((w.xyCorrespondenceFamilyMember hψ).map ι).tuple := by
  funext i
  fin_cases i <;> rfl

/-- The embedded selected tuple restricts to the embedded selected `B`
family member. -/
@[simp] theorem selectedTuple_comp_bFamilyIndex (hψ : w.Psi) :
    (ι ∘ w.psiSelectedCurveCompositionTuple) ∘
        PsiCurveCompositionRealization.bFamilyIndex =
      ((w.yzCorrespondenceFamilyMember hψ).map ι).tuple := by
  funext i
  fin_cases i <;> rfl

/-- The embedded selected tuple restricts to the embedded selected `C`
family member. -/
@[simp] theorem selectedTuple_comp_cFamilyIndex (hψ : w.Psi) :
    (ι ∘ w.psiSelectedCurveCompositionTuple) ∘
        PsiCurveCompositionRealization.cFamilyIndex =
      ((w.xzCorrespondenceFamilyMember hψ).map ι).tuple := by
  funext i
  fin_cases i <;> rfl

/-- The relocated `A` branch has exactly the embedded selected `A` family
locus. -/
theorem aFamilyLocus (hψ : w.Psi) :
    idealOf k (Fin.snoc (Fin.snoc a R.source) R.middle) =
      ((w.xyCorrespondenceFamilyMember hψ).map ι).ideal := by
  have h := idealOf_comp_eq_of_idealOf_eq R.locus
    PsiCurveCompositionRealization.aFamilyIndex
  change idealOf k (Fin.snoc (Fin.snoc a R.source) R.middle) =
    idealOf k ((w.xyCorrespondenceFamilyMember hψ).map ι).tuple
  rw [← R.totalTuple_comp_aFamilyIndex,
    ← selectedTuple_comp_aFamilyIndex (w := w) (ι := ι) hψ]
  exact h

/-- The relocated `B` branch has exactly the embedded selected `B` family
locus. -/
theorem bFamilyLocus (hψ : w.Psi) :
    idealOf k (Fin.snoc (Fin.snoc b R.middle) R.target) =
      ((w.yzCorrespondenceFamilyMember hψ).map ι).ideal := by
  have h := idealOf_comp_eq_of_idealOf_eq R.locus
    PsiCurveCompositionRealization.bFamilyIndex
  change idealOf k (Fin.snoc (Fin.snoc b R.middle) R.target) =
    idealOf k ((w.yzCorrespondenceFamilyMember hψ).map ι).tuple
  rw [← R.totalTuple_comp_bFamilyIndex,
    ← selectedTuple_comp_bFamilyIndex (w := w) (ι := ι) hψ]
  exact h

/-- The relocated direct `C` branch has exactly the embedded selected `C`
family locus. -/
theorem cFamilyLocus (hψ : w.Psi) :
    idealOf k (Fin.snoc (Fin.snoc c R.source) R.target) =
      ((w.xzCorrespondenceFamilyMember hψ).map ι).ideal := by
  have h := idealOf_comp_eq_of_idealOf_eq R.locus
    PsiCurveCompositionRealization.cFamilyIndex
  change idealOf k (Fin.snoc (Fin.snoc c R.source) R.target) =
    idealOf k ((w.xzCorrespondenceFamilyMember hψ).map ι).tuple
  rw [← R.totalTuple_comp_cFamilyIndex,
    ← selectedTuple_comp_cFamilyIndex (w := w) (ι := ι) hψ]
  exact h

/-- The relocated embedded `A` restriction is a genuine generic member of
the mapped selected family. -/
def aCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) 2 :=
  ((w.xyCorrespondenceFamilyMember hψ).map ι).ofTupleIdealEqOnly
    (R.aFamilyLocus hψ)

/-- The relocated embedded `B` restriction is a genuine generic member of
the mapped selected family. -/
def bCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) 2 :=
  ((w.yzCorrespondenceFamilyMember hψ).map ι).ofTupleIdealEqOnly
    (R.bFamilyLocus hψ)

/-- The relocated embedded `C` restriction is a genuine generic member of
the mapped selected family. -/
def cCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) 2 :=
  ((w.xzCorrespondenceFamilyMember hψ).map ι).ofTupleIdealEqOnly
    (R.cFamilyLocus hψ)

/-- Data witnessing that an embedded curve triangle can be regarded over a
larger common coefficient field.  Its three displayed parameter blocks may
be algebraic, rather than rational, over that field. -/
structure CommonBaseData {n : ℕ} (base : Fin n → Ω) where
  /-- The source coordinate used literally in all common-base pairs. -/
  source : Ω
  /-- The relocated source equals the displayed common source. -/
  source_eq : R.source = source
  /-- The common source is generic over the larger coefficient tuple. -/
  source_generic : source ∉ racl k (Set.range base)
  /-- Every `A` parameter coordinate is algebraic over the common base. -/
  a_mem : ∀ i, a i ∈ racl k (Set.range base)
  /-- Every `B` parameter coordinate is algebraic over the common base. -/
  b_mem : ∀ i, b i ∈ racl k (Set.range base)
  /-- Every `C` parameter coordinate is algebraic over the common base. -/
  c_mem : ∀ i, c i ∈ racl k (Set.range base)

namespace CommonBaseData

variable {n : ℕ} {base : Fin n → Ω}
  (H : R.CommonBaseData base)

/-- The common coefficient field generated by the larger base tuple. -/
def coefficientField (_H : R.CommonBaseData base) :
    IntermediateField k Ω :=
  adjoin k (Set.range base)

private theorem lift_insert_dependency
    (_H : R.CommonBaseData base) {p : Fin 2 → Ω} {x y : Ω}
    (hy : y ∈ racl k (insert x (Set.range p)))
    (hp : ∀ i, p i ∈ racl k (Set.range base)) :
    y ∈ racl k (insert x (Set.range base)) := by
  refine racl_le_of_subset_racl ?_ hy
  intro z hz
  rw [Set.mem_insert_iff] at hz
  rcases hz with rfl | ⟨i, rfl⟩
  · exact subset_racl k _ (Set.mem_insert _ _)
  · exact racl_mono (Set.subset_insert x _) (hp i)

private theorem descend_generic
    (_H : R.CommonBaseData base) {p : Fin 2 → Ω} {x y : Ω}
    (hx : x ∉ racl k (Set.range base))
    (hxy : x ∈ racl k (insert y (Set.range p)))
    (hp : ∀ i, p i ∈ racl k (Set.range base)) :
    y ∉ racl k (Set.range base) := by
  intro hy
  apply hx
  refine racl_le_of_subset_racl ?_ hxy
  intro z hz
  rw [Set.mem_insert_iff] at hz
  rcases hz with rfl | ⟨i, rfl⟩
  · exact hy
  · exact hp i

/-- The embedded `A` branch as a finite correspondence over the larger
common coefficient field. -/
def aCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥H.coefficientField) Ω where
  source := H.source
  target := R.middle
  source_generic := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact H.source_generic
  target_mem_source := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.aCorrespondenceFamilyMember hψ)
      |>.target_mem_parameter_source
    change R.middle ∈ racl k (insert R.source (Set.range a)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.a_mem
  source_mem_target := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.aCorrespondenceFamilyMember hψ)
      |>.source_mem_parameter_target
    change R.source ∈ racl k (insert R.middle (Set.range a)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.a_mem

/-- The middle coordinate is generic over the larger common coefficient
field because it is interalgebraic there with the common formal source. -/
theorem middle_generic (H : R.CommonBaseData base) (hψ : w.Psi) :
    R.middle ∉ racl k (Set.range base) := by
  have h := (R.aCorrespondenceFamilyMember hψ)
    |>.source_mem_parameter_target
  change R.source ∈ racl k (insert R.middle (Set.range a)) at h
  rw [H.source_eq] at h
  exact descend_generic (R := R) H H.source_generic h H.a_mem

/-- The embedded `B` branch as a finite correspondence over the same
larger common coefficient field. -/
def bCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥H.coefficientField) Ω where
  source := R.middle
  target := R.target
  source_generic := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact middle_generic (R := R) H hψ
  target_mem_source := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.bCorrespondenceFamilyMember hψ)
      |>.target_mem_parameter_source
    change R.target ∈ racl k (insert R.middle (Set.range b)) at h
    exact lift_insert_dependency (R := R) H h H.b_mem
  source_mem_target := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.bCorrespondenceFamilyMember hψ)
      |>.source_mem_parameter_target
    change R.middle ∈ racl k (insert R.target (Set.range b)) at h
    exact lift_insert_dependency (R := R) H h H.b_mem

/-- The embedded direct `C` branch as a finite correspondence over the
same larger common coefficient field. -/
def cCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥H.coefficientField) Ω where
  source := H.source
  target := R.target
  source_generic := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact H.source_generic
  target_mem_source := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.cCorrespondenceFamilyMember hψ)
      |>.target_mem_parameter_source
    change R.target ∈ racl k (insert R.source (Set.range c)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.c_mem
  source_mem_target := by
    rw [coefficientField, mem_racl_adjoin_base_iff, Set.union_singleton]
    have h := (R.cCorrespondenceFamilyMember hψ)
      |>.source_mem_parameter_target
    change R.source ∈ racl k (insert R.target (Set.range c)) at h
    rw [H.source_eq] at h
    exact lift_insert_dependency (R := R) H h H.c_mem

/-- The two successive common-base pairs share their middle coordinate
definitionally. -/
@[simp] theorem aPair_target_eq_bPair_source (hψ : w.Psi) :
    (aCorrespondencePair (R := R) H hψ).target =
      (bCorrespondencePair (R := R) H hψ).source := rfl

/-- The common finite normal source cover of the larger-base triangle. -/
noncomputable def finiteSourceCover (hψ : w.Psi) :=
  FiniteCorrespondencePair.FiniteCoverTriangle.sourceCover
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)

/-- The common finite normal middle cover of the larger-base triangle. -/
noncomputable def finiteMiddleCover (hψ : w.Psi) :=
  FiniteCorrespondencePair.FiniteCoverTriangle.middleCover
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)

/-- The common finite normal target cover of the larger-base triangle. -/
noncomputable def finiteTargetCover (hψ : w.Psi) :=
  FiniteCorrespondencePair.FiniteCoverTriangle.targetCover
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)

/-- The deck-corrected finite-cover action of the common-base triangle. -/
noncomputable def finiteCoverCompositionTriangle (hψ : w.Psi) :
    FieldEquiv.CompositionTriangle
      (↥(finiteSourceCover (R := R) H hψ).field)
      (↥(finiteMiddleCover (R := R) H hψ).field)
      (↥(finiteTargetCover (R := R) H hψ).field) where
  left := FiniteCorrespondencePair.FiniteCoverTriangle.leftEquiv
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)
  right := FiniteCorrespondencePair.FiniteCoverTriangle.rightEquiv
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)
  direct := FiniteCorrespondencePair.FiniteCoverTriangle.strictDirectEquiv
    (aCorrespondencePair (R := R) H hψ)
    (bCorrespondencePair (R := R) H hψ)
    (aPair_target_eq_bPair_source (R := R) H hψ)
  composition :=
    FiniteCorrespondencePair.FiniteCoverTriangle.strictComposition
      (aCorrespondencePair (R := R) H hψ)
      (bCorrespondencePair (R := R) H hψ)
      (aPair_target_eq_bPair_source (R := R) H hψ)

end CommonBaseData

end PsiCurveCompositionBaseChangeRealization

/-- Four embedded Ψ curve triangles with one literal common formal source. -/
structure PsiCurveFourArrowCommonSourceRealizations
    (hψ : w.Psi) {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) where
  /-- Curve triangle above `s·e=u`. -/
  se : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ s)
    (commonCurveEmbedding (k := k) (K := K) ∘ e)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
  /-- Its source is the common formal coordinate. -/
  se_source : se.source = commonCurveSource (K := K)
  /-- Curve triangle above `sA·a=u`. -/
  sAa : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
    (commonCurveEmbedding (k := k) (K := K) ∘ a)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
  /-- Its source is the same common formal coordinate. -/
  sAa_source : sAa.source = commonCurveSource (K := K)
  /-- Curve triangle above `s·b=uB`. -/
  sb : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ s)
    (commonCurveEmbedding (k := k) (K := K) ∘ b)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
  /-- Its source is the same common formal coordinate. -/
  sb_source : sb.source = commonCurveSource (K := K)
  /-- Curve triangle above `sA·c=uB`. -/
  sAc : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.c)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
  /-- Its source is the same common formal coordinate. -/
  sAc_source : sAc.source = commonCurveSource (K := K)

/-- The formal rational-function coordinate supplies a single common source
for all four edges of every Ψ parameter difference diagram. -/
theorem exists_psiCurveFourArrowCommonSourceRealizations
    (hψ : w.Psi) {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) :
    Nonempty (w.PsiCurveFourArrowCommonSourceRealizations hψ D) := by
  let ι : K →ₐ[k] CommonCurveAmbient K :=
    commonCurveEmbedding (k := k) (K := K)
  have hse : w.psiFamilyCompositionRelation s e D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s e D.u).2 D.se_u
  have hsAa : w.psiFamilyCompositionRelation D.sA a D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA a D.u).2 D.sA_a_u
  have hsb : w.psiFamilyCompositionRelation s b D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s b D.uB).2
      D.s_b_uB
  have hsAc : w.psiFamilyCompositionRelation D.sA D.c D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA D.c D.uB).2 D.sA_c_uB
  obtain ⟨Rse, hRse⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hse
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple s e D.u))
  obtain ⟨RsAa, hRsAa⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsAa
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple D.sA a D.u))
  obtain ⟨Rsb, hRsb⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsb
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple s b D.uB))
  obtain ⟨RsAc, hRsAc⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsAc
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple D.sA D.c D.uB))
  exact ⟨⟨Rse, hRse, RsAa, hRsAa, Rsb, hRsb, RsAc, hRsAc⟩⟩

namespace PsiCurveFourArrowCommonSourceRealizations

variable {w : QWitness k K} {hψ : w.Psi}
  {s a b e : Fin 2 → K}
  {D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e}
  (R : w.PsiCurveFourArrowCommonSourceRealizations hψ D)

/-- The mapped eight-input tuple used as the one coefficient base for all
four embedded curve triangles. -/
def commonInputTuple (_R : w.PsiCurveFourArrowCommonSourceRealizations hψ D) :
    Fin 8 → CommonCurveAmbient K :=
  commonCurveEmbedding (k := k) (K := K) ∘
    rankTwoFourTuple s e a b

/-- The six independent ambient coordinates complementary to the repeated
`s` parameter block. -/
def repeatedSAuxiliaryInput
    (_R : w.PsiCurveFourArrowCommonSourceRealizations hψ D) :
    Fin 6 → CommonCurveAmbient K :=
  commonCurveEmbedding (k := k) (K := K) ∘
    ![e 0, e 1, a 0, a 1, b 0, b 1]

/-- The six independent ambient coordinates complementary to the repeated
`sA` parameter block in the independent presentation `(s,sA,a,b)`. -/
def repeatedSAAuxiliaryInput
    (_R : w.PsiCurveFourArrowCommonSourceRealizations hψ D) :
    Fin 6 → CommonCurveAmbient K :=
  commonCurveEmbedding (k := k) (K := K) ∘
    ![s 0, s 1, a 0, a 1, b 0, b 1]

/-- The six independent ambient coordinates complementary to the repeated
`u` parameter block in the independent presentation `(s,u,a,b)`. -/
def repeatedUAuxiliaryInput
    (_R : w.PsiCurveFourArrowCommonSourceRealizations hψ D) :
    Fin 6 → CommonCurveAmbient K :=
  commonCurveEmbedding (k := k) (K := K) ∘
    ![s 0, s 1, a 0, a 1, b 0, b 1]

/-- The six independent ambient coordinates complementary to the repeated
`uB` parameter block in the independent presentation `(s,sA,a,uB)`. -/
def repeatedUBAuxiliaryInput
    (_R : w.PsiCurveFourArrowCommonSourceRealizations hψ D) :
    Fin 6 → CommonCurveAmbient K :=
  commonCurveEmbedding (k := k) (K := K) ∘
    ![s 0, s 1, D.sA 0, D.sA 1, a 0, a 1]

/-- The six algebraic coefficient coordinates needed to compare the three
alternative full input fields with the original common input field. -/
def algebraicCoefficientTuple
    (_R : w.PsiCurveFourArrowCommonSourceRealizations hψ D) :
    Fin 6 → CommonCurveAmbient K :=
  commonCurveEmbedding (k := k) (K := K) ∘
    ![D.sA 0, D.sA 1, D.u 0, D.u 1, D.uB 0, D.uB 1]

/-- The common input field enlarged by the actual algebraic parameter
blocks `sA`, `u`, and `uB`. -/
def commonCoefficientExtendedField :
    IntermediateField k (CommonCurveAmbient K) :=
  adjoin k
    (Set.range R.commonInputTuple ∪ Set.range R.algebraicCoefficientTuple)

/-- The alternative independent coefficient field used by the repeated
`sA` relation. -/
def repeatedSAAlternativeInputField :
    IntermediateField k (CommonCurveAmbient K) :=
  adjoin k
    (Set.range (commonCurveEmbedding (k := k) (K := K) ∘ D.sA) ∪
      Set.range R.repeatedSAAuxiliaryInput)

/-- The alternative independent coefficient field used by the repeated
direct `u` relation. -/
def repeatedUAlternativeInputField :
    IntermediateField k (CommonCurveAmbient K) :=
  adjoin k
    (Set.range (commonCurveEmbedding (k := k) (K := K) ∘ D.u) ∪
      Set.range R.repeatedUAuxiliaryInput)

/-- The alternative independent coefficient field used by the repeated
direct `uB` relation. -/
def repeatedUBAlternativeInputField :
    IntermediateField k (CommonCurveAmbient K) :=
  adjoin k
    (Set.range (commonCurveEmbedding (k := k) (K := K) ∘ D.uB) ∪
      Set.range R.repeatedUBAuxiliaryInput)

private theorem commonInput_mem_extended (i : Fin 8) :
    R.commonInputTuple i ∈ R.commonCoefficientExtendedField :=
  subset_adjoin k _ (Or.inl (Set.mem_range_self i))

private theorem algebraicCoefficient_mem_extended (i : Fin 6) :
    R.algebraicCoefficientTuple i ∈ R.commonCoefficientExtendedField :=
  subset_adjoin k _ (Or.inr (Set.mem_range_self i))

/-- The full alternative `sA` input field lies in the common finite
coefficient enlargement. -/
theorem repeatedSAAlternativeInputField_le_extended :
    R.repeatedSAAlternativeInputField ≤
      R.commonCoefficientExtendedField := by
  apply adjoin_le_iff.2
  rintro _ (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact R.algebraicCoefficient_mem_extended 0
    · exact R.algebraicCoefficient_mem_extended 1
  · fin_cases i
    · exact R.commonInput_mem_extended 0
    · exact R.commonInput_mem_extended 1
    · exact R.commonInput_mem_extended 4
    · exact R.commonInput_mem_extended 5
    · exact R.commonInput_mem_extended 6
    · exact R.commonInput_mem_extended 7

/-- The full alternative `u` input field lies in the common finite
coefficient enlargement. -/
theorem repeatedUAlternativeInputField_le_extended :
    R.repeatedUAlternativeInputField ≤
      R.commonCoefficientExtendedField := by
  apply adjoin_le_iff.2
  rintro _ (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact R.algebraicCoefficient_mem_extended 2
    · exact R.algebraicCoefficient_mem_extended 3
  · fin_cases i
    · exact R.commonInput_mem_extended 0
    · exact R.commonInput_mem_extended 1
    · exact R.commonInput_mem_extended 4
    · exact R.commonInput_mem_extended 5
    · exact R.commonInput_mem_extended 6
    · exact R.commonInput_mem_extended 7

/-- The full alternative `uB` input field lies in the common finite
coefficient enlargement. -/
theorem repeatedUBAlternativeInputField_le_extended :
    R.repeatedUBAlternativeInputField ≤
      R.commonCoefficientExtendedField := by
  apply adjoin_le_iff.2
  rintro _ (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact R.algebraicCoefficient_mem_extended 4
    · exact R.algebraicCoefficient_mem_extended 5
  · fin_cases i
    · exact R.commonInput_mem_extended 0
    · exact R.commonInput_mem_extended 1
    · exact R.algebraicCoefficient_mem_extended 0
    · exact R.algebraicCoefficient_mem_extended 1
    · exact R.commonInput_mem_extended 4
    · exact R.commonInput_mem_extended 5

/-- The repeated `s` parameter, its six complementary inputs, and the
formal source are jointly independent. -/
theorem repeatedS_auxiliary_parameter_source_independent
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    AlgebraicIndependent k
      (Sum.elim R.repeatedSAuxiliaryInput
        (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ s)
          (commonCurveSource (K := K)))) := by
  let f : Fin 6 ⊕ Fin 3 → Fin 9 :=
    Sum.elim ![2, 3, 4, 5, 6, 7] ![0, 1, 8]
  have hf : Function.Injective f := by decide
  have h := AlgebraicIndependent.comp
    (mappedTuple_snoc_commonCurveSource_independent
      (k := k) (K := K) hind) f hf
  convert h using 1
  funext i
  rcases i with i | i <;> fin_cases i <;> rfl

/-- The repeated `sA` parameter, its six complementary inputs, and the
formal source are jointly independent. -/
theorem repeatedSA_auxiliary_parameter_source_independent
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    AlgebraicIndependent k
      (Sum.elim R.repeatedSAAuxiliaryInput
        (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
          (commonCurveSource (K := K)))) := by
  let q : Fin 8 → K := rankTwoFourTuple s D.sA a b
  let f : Fin 6 ⊕ Fin 3 → Fin 9 :=
    Sum.elim ![0, 1, 4, 5, 6, 7] ![2, 3, 8]
  have hf : Function.Injective f := by decide
  have h := AlgebraicIndependent.comp
    (mappedTuple_snoc_commonCurveSource_independent
      (k := k) (K := K) (D.s_sA_a_b_independent hind)) f hf
  convert h using 1
  funext i
  rcases i with i | i <;> fin_cases i <;> rfl

/-- The repeated `u` parameter, its six complementary inputs, and the
formal source are jointly independent. -/
theorem repeatedU_auxiliary_parameter_source_independent
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    AlgebraicIndependent k
      (Sum.elim R.repeatedUAuxiliaryInput
        (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
          (commonCurveSource (K := K)))) := by
  let q : Fin 8 → K := rankTwoFourTuple s D.u a b
  let f : Fin 6 ⊕ Fin 3 → Fin 9 :=
    Sum.elim ![0, 1, 4, 5, 6, 7] ![2, 3, 8]
  have hf : Function.Injective f := by decide
  have h := AlgebraicIndependent.comp
    (mappedTuple_snoc_commonCurveSource_independent
      (k := k) (K := K) (D.s_u_a_b_independent hind)) f hf
  convert h using 1
  funext i
  rcases i with i | i <;> fin_cases i <;> rfl

/-- The repeated `uB` parameter, its six complementary inputs, and the
formal source are jointly independent. -/
theorem repeatedUB_auxiliary_parameter_source_independent
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    AlgebraicIndependent k
      (Sum.elim R.repeatedUBAuxiliaryInput
        (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
          (commonCurveSource (K := K)))) := by
  let q : Fin 8 → K := rankTwoFourTuple s D.sA a D.uB
  let f : Fin 6 ⊕ Fin 3 → Fin 9 :=
    Sum.elim ![0, 1, 2, 3, 4, 5] ![6, 7, 8]
  have hf : Function.Injective f := by decide
  have h := AlgebraicIndependent.comp
    (mappedTuple_snoc_commonCurveSource_independent
      (k := k) (K := K) (D.s_sA_a_uB_independent hind)) f hf
  convert h using 1
  funext i
  rcases i with i | i <;> fin_cases i <;> rfl

private theorem map_mem_input_racl {x : K}
    (hx : x ∈ racl k (Set.range (rankTwoFourTuple s e a b))) :
    commonCurveEmbedding (k := k) (K := K) x ∈ racl k
      (Set.range R.commonInputTuple) := by
  rw [commonInputTuple, Set.range_comp]
  exact (algHom_mem_racl_image_iff
    (commonCurveEmbedding (k := k) (K := K))).2 hx

/-- The mapped `s` coordinates belong to the closure of the common input
tuple. -/
theorem s_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (s i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨0, rfl⟩
  · exact subset_racl k _ ⟨1, rfl⟩

/-- The mapped `e` coordinates belong to the closure of the common input
tuple. -/
theorem e_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (e i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨2, rfl⟩
  · exact subset_racl k _ ⟨3, rfl⟩

/-- The mapped `a` coordinates belong to the closure of the common input
tuple. -/
theorem a_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (a i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨4, rfl⟩
  · exact subset_racl k _ ⟨5, rfl⟩

/-- The mapped `b` coordinates belong to the closure of the common input
tuple. -/
theorem b_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (b i) ∈ racl k
      (Set.range R.commonInputTuple) := by
  apply R.map_mem_input_racl
  fin_cases i
  · exact subset_racl k _ ⟨6, rfl⟩
  · exact subset_racl k _ ⟨7, rfl⟩

/-- The mapped selected output `u` is algebraic over the common input
tuple. -/
theorem u_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.u i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.u_mem_input_racl i)

/-- The mapped selected quotient `sA` is algebraic over the common input
tuple. -/
theorem sA_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.sA i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.sA_mem_input_racl i)

/-- The mapped selected output `uB` is algebraic over the common input
tuple. -/
theorem uB_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.uB i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.uB_mem_input_racl i)

/-- The mapped difference output `c` is algebraic over the common input
tuple. -/
theorem c_mem_commonInput_racl (i : Fin 2) :
    commonCurveEmbedding (k := k) (K := K) (D.c i) ∈ racl k
      (Set.range R.commonInputTuple) :=
  R.map_mem_input_racl (D.c_mem_input_racl i)

/-- Common-base data for the face `s·e=u`. -/
def seCommonBaseData : R.se.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.se_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.s_mem_commonInput_racl
  b_mem := R.e_mem_commonInput_racl
  c_mem := R.u_mem_commonInput_racl

/-- Common-base data for the face `sA·a=u`. -/
def sAaCommonBaseData : R.sAa.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.sAa_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.sA_mem_commonInput_racl
  b_mem := R.a_mem_commonInput_racl
  c_mem := R.u_mem_commonInput_racl

/-- Common-base data for the face `s·b=uB`. -/
def sbCommonBaseData : R.sb.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.sb_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.s_mem_commonInput_racl
  b_mem := R.b_mem_commonInput_racl
  c_mem := R.uB_mem_commonInput_racl

/-- Common-base data for the face `sA·c=uB`. -/
def sAcCommonBaseData : R.sAc.CommonBaseData R.commonInputTuple where
  source := commonCurveSource (K := K)
  source_eq := R.sAc_source
  source_generic := commonCurveSource_notMem_racl
    (k := k) (K := K) (rankTwoFourTuple s e a b)
  a_mem := R.sA_mem_commonInput_racl
  b_mem := R.c_mem_commonInput_racl
  c_mem := R.uB_mem_commonInput_racl

/-- The original common eight-input coefficient field embeds in the finite
algebraic coefficient enlargement. -/
theorem commonCoefficientField_le_extended :
    R.seCommonBaseData.coefficientField ≤
      R.commonCoefficientExtendedField := by
  change adjoin k (Set.range R.commonInputTuple) ≤
    adjoin k
      (Set.range R.commonInputTuple ∪ Set.range R.algebraicCoefficientTuple)
  exact adjoin.mono k _ _ Set.subset_union_left

/-- The algebraic coefficient enlargement regarded as an extension of the
literal common eight-input field. -/
def commonCoefficientOverInput :
    IntermediateField (↥R.seCommonBaseData.coefficientField)
      (CommonCurveAmbient K) :=
  extendScalars R.commonCoefficientField_le_extended

/-- Every newly adjoined coefficient coordinate is algebraic over the
common eight-input tuple. -/
theorem algebraicCoefficientTuple_mem_commonInput_racl (i : Fin 6) :
    R.algebraicCoefficientTuple i ∈
      racl k (Set.range R.commonInputTuple) := by
  fin_cases i
  · exact R.sA_mem_commonInput_racl 0
  · exact R.sA_mem_commonInput_racl 1
  · exact R.u_mem_commonInput_racl 0
  · exact R.u_mem_commonInput_racl 1
  · exact R.uB_mem_commonInput_racl 0
  · exact R.uB_mem_commonInput_racl 1

/-- The common coefficient enlargement is finite over the original
eight-input field. -/
theorem commonCoefficientOverInput_finiteDimensional :
    FiniteDimensional (↥R.seCommonBaseData.coefficientField)
      (↥R.commonCoefficientOverInput) := by
  have key : R.commonCoefficientOverInput =
      adjoin (↥R.seCommonBaseData.coefficientField)
        (Set.range R.algebraicCoefficientTuple) := by
    refine restrictScalars_injective k ?_
    unfold commonCoefficientOverInput commonCoefficientExtendedField
      PsiCurveCompositionBaseChangeRealization.CommonBaseData.coefficientField
    rw [adjoin_adjoin_left, extendScalars_restrictScalars, adjoin_union]
  rw [key]
  letI : Fintype (Set.range R.algebraicCoefficientTuple) :=
    Set.Finite.fintype (Set.finite_range R.algebraicCoefficientTuple)
  exact finiteDimensional_adjoin fun z hz ↦ by
    obtain ⟨i, rfl⟩ := hz
    have hmem : R.algebraicCoefficientTuple i ∈
        racl (↥R.seCommonBaseData.coefficientField)
          (∅ : Set (CommonCurveAmbient K)) := by
      rw [PsiCurveCompositionBaseChangeRealization.CommonBaseData.coefficientField,
        mem_racl_adjoin_base_iff, Set.union_empty]
      exact R.algebraicCoefficientTuple_mem_commonInput_racl i
    exact (isAlgebraic_of_mem_racl_empty hmem).isIntegral

/-- One normal coefficient field containing the original common inputs and
all three algebraic replacement blocks. -/
def commonCoefficientNormalField :
    IntermediateField (↥R.seCommonBaseData.coefficientField)
      (CommonCurveAmbient K) :=
  FiniteCover.normalClosureOver R.commonCoefficientField_le_extended

/-- The finite coefficient enlargement lies in its normal closure. -/
theorem commonCoefficientOverInput_le_normalField :
    R.commonCoefficientOverInput ≤ R.commonCoefficientNormalField :=
  FiniteCover.extendScalars_le_normalClosureOver
    R.commonCoefficientField_le_extended

/-- The common coefficient normal field remains finite over the original
eight-input field. -/
theorem commonCoefficientNormalField_finiteDimensional :
    FiniteDimensional (↥R.seCommonBaseData.coefficientField)
      (↥R.commonCoefficientNormalField) :=
  FiniteCover.normalClosureOver_finiteDimensional
    R.commonCoefficientField_le_extended
    R.commonCoefficientOverInput_finiteDimensional

/-- The common coefficient normal field is normal over the original
eight-input field. -/
theorem commonCoefficientNormalField_normal :
    Normal (↥R.seCommonBaseData.coefficientField)
      (↥R.commonCoefficientNormalField) := by
  letI : FiniteDimensional (↥R.seCommonBaseData.coefficientField)
      (↥(extendScalars R.commonCoefficientField_le_extended)) :=
    R.commonCoefficientOverInput_finiteDimensional
  exact FiniteCover.normalClosureOver_normal
    R.commonCoefficientField_le_extended
    (Algebra.IsAlgebraic.of_finite _ _)

/-- The full finite coefficient enlargement embeds in the underlying
`k`-field of its normal closure. -/
theorem commonCoefficientExtendedField_le_normalField :
    R.commonCoefficientExtendedField ≤
      R.commonCoefficientNormalField.restrictScalars k := by
  have h : R.commonCoefficientOverInput.restrictScalars k ≤
      R.commonCoefficientNormalField.restrictScalars k :=
    R.commonCoefficientOverInput_le_normalField
  simpa [commonCoefficientOverInput] using h

/-- The alternative `sA` coefficient field is contained in the common
finite normal coefficient field. -/
theorem repeatedSAAlternativeInputField_le_normalField :
    R.repeatedSAAlternativeInputField ≤
      R.commonCoefficientNormalField.restrictScalars k :=
  R.repeatedSAAlternativeInputField_le_extended.trans
    R.commonCoefficientExtendedField_le_normalField

/-- The alternative `u` coefficient field is contained in the common
finite normal coefficient field. -/
theorem repeatedUAlternativeInputField_le_normalField :
    R.repeatedUAlternativeInputField ≤
      R.commonCoefficientNormalField.restrictScalars k :=
  R.repeatedUAlternativeInputField_le_extended.trans
    R.commonCoefficientExtendedField_le_normalField

/-- The alternative `uB` coefficient field is contained in the common
finite normal coefficient field. -/
theorem repeatedUBAlternativeInputField_le_normalField :
    R.repeatedUBAlternativeInputField ≤
      R.commonCoefficientNormalField.restrictScalars k :=
  R.repeatedUBAlternativeInputField_le_extended.trans
    R.commonCoefficientExtendedField_le_normalField

/-- The two independently relocated occurrences of the `s`-family branch
have the same complete parameter/source/target locus. -/
theorem seAFamily_ideal_eq_sbAFamily :
    (R.se.aCorrespondenceFamilyMember hψ).ideal =
      (R.sb.aCorrespondenceFamilyMember hψ).ideal := by
  change idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ s)
        R.se.source) R.se.middle) =
    idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ s)
        R.sb.source) R.sb.middle)
  exact (R.se.aFamilyLocus hψ).trans (R.sb.aFamilyLocus hψ).symm

/-- The two independently relocated occurrences of the `sA`-family branch
have the same complete parameter/source/target locus. -/
theorem sAaAFamily_ideal_eq_sAcAFamily :
    (R.sAa.aCorrespondenceFamilyMember hψ).ideal =
      (R.sAc.aCorrespondenceFamilyMember hψ).ideal := by
  change idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
        R.sAa.source) R.sAa.middle) =
    idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
        R.sAc.source) R.sAc.middle)
  exact (R.sAa.aFamilyLocus hψ).trans (R.sAc.aFamilyLocus hψ).symm

/-- The two independently relocated direct branches labelled by `u` have
the same complete family locus. -/
theorem seCFamily_ideal_eq_sAaCFamily :
    (R.se.cCorrespondenceFamilyMember hψ).ideal =
      (R.sAa.cCorrespondenceFamilyMember hψ).ideal := by
  change idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
        R.se.source) R.se.target) =
    idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
        R.sAa.source) R.sAa.target)
  exact (R.se.cFamilyLocus hψ).trans (R.sAa.cFamilyLocus hψ).symm

/-- The two independently relocated direct branches labelled by `uB` have
the same complete family locus. -/
theorem sbCFamily_ideal_eq_sAcCFamily :
    (R.sb.cCorrespondenceFamilyMember hψ).ideal =
      (R.sAc.cCorrespondenceFamilyMember hψ).ideal := by
  change idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
        R.sb.source) R.sb.target) =
    idealOf k
      (Fin.snoc (Fin.snoc
        (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
        R.sAc.source) R.sAc.target)
  exact (R.sb.cFamilyLocus hψ).trans (R.sAc.cFamilyLocus hψ).symm

/-- The two selected `s` branches have the same endpoint-pair ideal over
the literal rank-two `s` parameter field. -/
theorem repeatedSPairIdeal_eq_over_parameterField :
    idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ s))))
        ![R.se.source, R.se.middle] =
      idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ s))))
        ![R.sb.source, R.sb.middle] := by
  apply pairIdeal_eq_over_commonParameter_of_familyIdeal_eq
  exact R.seAFamily_ideal_eq_sbAFamily

/-- The two selected `sA` branches have the same endpoint-pair ideal over
the literal rank-two `sA` parameter field. -/
theorem repeatedSAPairIdeal_eq_over_parameterField :
    idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.sA))))
        ![R.sAa.source, R.sAa.middle] =
      idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.sA))))
        ![R.sAc.source, R.sAc.middle] := by
  apply pairIdeal_eq_over_commonParameter_of_familyIdeal_eq
  exact R.sAaAFamily_ideal_eq_sAcAFamily

/-- The two selected direct `u` branches have the same endpoint-pair ideal
over the literal rank-two `u` parameter field. -/
theorem repeatedUPairIdeal_eq_over_parameterField :
    idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.u))))
        ![R.se.source, R.se.target] =
      idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.u))))
        ![R.sAa.source, R.sAa.target] := by
  apply pairIdeal_eq_over_commonParameter_of_familyIdeal_eq
  exact R.seCFamily_ideal_eq_sAaCFamily

/-- The two selected direct `uB` branches have the same endpoint-pair ideal
over the literal rank-two `uB` parameter field. -/
theorem repeatedUBPairIdeal_eq_over_parameterField :
    idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.uB))))
        ![R.sb.source, R.sb.target] =
      idealOf
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.uB))))
        ![R.sAc.source, R.sAc.target] := by
  apply pairIdeal_eq_over_commonParameter_of_familyIdeal_eq
  exact R.sbCFamily_ideal_eq_sAcCFamily

/-- The repeated `s` curve relation remains equal after adjoining the six
complementary independent inputs. -/
theorem repeatedSPairIdeal_eq_over_independentInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ s))))
          (Set.range R.repeatedSAuxiliaryInput)).restrictScalars k))
        ![R.se.source, R.se.middle] =
      idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ s))))
          (Set.range R.repeatedSAuxiliaryInput)).restrictScalars k))
        ![R.sb.source, R.sb.middle] := by
  apply pairIdeal_eq_over_independentExtension_of_pairIdeal_eq
    R.repeatedSPairIdeal_eq_over_parameterField
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.se_source] using
        R.repeatedS_auxiliary_parameter_source_independent hind
    · exact (R.se.aCorrespondenceFamilyMember hψ).target_mem_parameter_source
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.sb_source] using
        R.repeatedS_auxiliary_parameter_source_independent hind
    · exact (R.sb.aCorrespondenceFamilyMember hψ).target_mem_parameter_source

/-- For the repeated `s` block, adjoining its six complementary inputs is
literally the original common eight-input coefficient field after
restricting scalars back to `k`. -/
theorem repeatedSIndependentInputField_restrictScalars :
    (adjoin
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ s))))
        (Set.range R.repeatedSAuxiliaryInput)).restrictScalars k =
      (R.seCommonBaseData.coefficientField) := by
  unfold PsiCurveCompositionBaseChangeRealization.CommonBaseData.coefficientField
  rw [adjoin_adjoin_left]
  apply congrArg (adjoin k)
  ext z
  simp only [Set.mem_union, Set.mem_range, Function.comp_apply,
    Fin.exists_fin_two, Fin.isValue]
  constructor
  · rintro ((h | h) | ⟨i, h⟩)
    · exact ⟨0, h⟩
    · exact ⟨1, h⟩
    · fin_cases i
      · exact ⟨2, h⟩
      · exact ⟨3, h⟩
      · exact ⟨4, h⟩
      · exact ⟨5, h⟩
      · exact ⟨6, h⟩
      · exact ⟨7, h⟩
  · rintro ⟨i, h⟩
    fin_cases i
    · exact Or.inl (Or.inl h)
    · exact Or.inl (Or.inr h)
    · exact Or.inr ⟨0, h⟩
    · exact Or.inr ⟨1, h⟩
    · exact Or.inr ⟨2, h⟩
    · exact Or.inr ⟨3, h⟩
    · exact Or.inr ⟨4, h⟩
    · exact Or.inr ⟨5, h⟩

/-- The two occurrences of the `s` action therefore have the same selected
curve ideal over the literal common eight-input coefficient field. -/
theorem repeatedSPairIdeal_eq_over_commonInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf (↥(R.seCommonBaseData.coefficientField))
        ![commonCurveSource (K := K), R.se.middle] =
      idealOf (↥(R.seCommonBaseData.coefficientField))
        ![commonCurveSource (K := K), R.sb.middle] := by
  rw [← R.repeatedSIndependentInputField_restrictScalars]
  simpa only [R.se_source, R.sb_source] using
    R.repeatedSPairIdeal_eq_over_independentInputField hind

/-- The exact common-input equality is the equality of the two selected
finite-correspondence ideals used by the common-cover triangles. -/
theorem repeatedSCommonCorrespondencePair_ideal_eq
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
        (R := R.se) R.seCommonBaseData hψ).ideal =
      (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
        (R := R.sb) R.sbCommonBaseData hψ).ideal := by
  change idealOf (↥(R.seCommonBaseData.coefficientField))
      ![commonCurveSource (K := K), R.se.middle] =
    idealOf (↥(R.seCommonBaseData.coefficientField))
      ![commonCurveSource (K := K), R.sb.middle]
  exact R.repeatedSPairIdeal_eq_over_commonInputField hind

/-- The repeated `s` curve ideals therefore identify their concrete normal
covers semilinearly over the induced common-source-field equivalence. -/
noncomputable def repeatedSCommonNormalCoverEquiv
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ).normalCoverEquivOfIdealEq
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ)
    (R.repeatedSCommonCorrespondencePair_ideal_eq hind)

/-- The common-input comparison of the repeated `s` relation is corrected
to preserve the literal selected branch.  This is the first faithful
anchor for the eventual four-triangle reference alignment. -/
noncomputable def repeatedSCommonBasedBranchEquiv
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ).basedBranchEquivOfIdealEq
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ)
    (R.repeatedSCommonCorrespondencePair_ideal_eq hind)

/-- The faithful common-input `s` comparison sends the selected branch to
the selected branch. -/
@[simp] theorem repeatedSCommonBasedBranchEquiv_selected
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (R.repeatedSCommonBasedBranchEquiv hind).branchEquiv
        (finiteCoverSelectedBranch
          (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
            (R := R.se) R.seCommonBaseData hψ).sourceField_le_branchField) =
      finiteCoverSelectedBranch
        (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
          (R := R.sb) R.sbCommonBaseData hψ).sourceField_le_branchField :=
  (R.repeatedSCommonBasedBranchEquiv hind).map_selected

/-- The nested scalar-extension presentation for `sA` is exactly its named
alternative eight-input coefficient field. -/
theorem repeatedSAIndependentInputField_eq_alternative :
    (adjoin
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.sA))))
        (Set.range R.repeatedSAAuxiliaryInput)).restrictScalars k =
      R.repeatedSAAlternativeInputField := by
  unfold repeatedSAAlternativeInputField
  rw [adjoin_adjoin_left]

/-- The nested scalar-extension presentation for `u` is exactly its named
alternative eight-input coefficient field. -/
theorem repeatedUIndependentInputField_eq_alternative :
    (adjoin
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.u))))
        (Set.range R.repeatedUAuxiliaryInput)).restrictScalars k =
      R.repeatedUAlternativeInputField := by
  unfold repeatedUAlternativeInputField
  rw [adjoin_adjoin_left]

/-- The nested scalar-extension presentation for `uB` is exactly its named
alternative eight-input coefficient field. -/
theorem repeatedUBIndependentInputField_eq_alternative :
    (adjoin
        (↥(adjoin k (Set.range
          (commonCurveEmbedding (k := k) (K := K) ∘ D.uB))))
        (Set.range R.repeatedUBAuxiliaryInput)).restrictScalars k =
      R.repeatedUBAlternativeInputField := by
  unfold repeatedUBAlternativeInputField
  rw [adjoin_adjoin_left]

/-- The repeated `sA` curve relation remains equal after adjoining its six
complementary independent inputs. -/
theorem repeatedSAPairIdeal_eq_over_independentInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ D.sA))))
          (Set.range R.repeatedSAAuxiliaryInput)).restrictScalars k))
        ![R.sAa.source, R.sAa.middle] =
      idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ D.sA))))
          (Set.range R.repeatedSAAuxiliaryInput)).restrictScalars k))
        ![R.sAc.source, R.sAc.middle] := by
  apply pairIdeal_eq_over_independentExtension_of_pairIdeal_eq
    R.repeatedSAPairIdeal_eq_over_parameterField
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.sAa_source] using
        R.repeatedSA_auxiliary_parameter_source_independent hind
    · exact (R.sAa.aCorrespondenceFamilyMember hψ).target_mem_parameter_source
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.sAc_source] using
        R.repeatedSA_auxiliary_parameter_source_independent hind
    · exact (R.sAc.aCorrespondenceFamilyMember hψ).target_mem_parameter_source

/-- The repeated `sA` relation over its named alternative full input
field. -/
theorem repeatedSAPairIdeal_eq_over_alternativeInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf (↥R.repeatedSAAlternativeInputField)
        ![R.sAa.source, R.sAa.middle] =
      idealOf (↥R.repeatedSAAlternativeInputField)
        ![R.sAc.source, R.sAc.middle] := by
  rw [← R.repeatedSAIndependentInputField_eq_alternative]
  exact R.repeatedSAPairIdeal_eq_over_independentInputField hind

/-- The repeated direct `u` curve relation remains equal after adjoining
its six complementary independent inputs. -/
theorem repeatedUPairIdeal_eq_over_independentInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ D.u))))
          (Set.range R.repeatedUAuxiliaryInput)).restrictScalars k))
        ![R.se.source, R.se.target] =
      idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ D.u))))
          (Set.range R.repeatedUAuxiliaryInput)).restrictScalars k))
        ![R.sAa.source, R.sAa.target] := by
  apply pairIdeal_eq_over_independentExtension_of_pairIdeal_eq
    R.repeatedUPairIdeal_eq_over_parameterField
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.se_source] using
        R.repeatedU_auxiliary_parameter_source_independent hind
    · exact (R.se.cCorrespondenceFamilyMember hψ).target_mem_parameter_source
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.sAa_source] using
        R.repeatedU_auxiliary_parameter_source_independent hind
    · exact (R.sAa.cCorrespondenceFamilyMember hψ).target_mem_parameter_source

/-- The repeated direct `u` relation over its named alternative full input
field. -/
theorem repeatedUPairIdeal_eq_over_alternativeInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf (↥R.repeatedUAlternativeInputField)
        ![R.se.source, R.se.target] =
      idealOf (↥R.repeatedUAlternativeInputField)
        ![R.sAa.source, R.sAa.target] := by
  rw [← R.repeatedUIndependentInputField_eq_alternative]
  exact R.repeatedUPairIdeal_eq_over_independentInputField hind

/-- The repeated direct `uB` curve relation remains equal after adjoining
its six complementary independent inputs. -/
theorem repeatedUBPairIdeal_eq_over_independentInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ D.uB))))
          (Set.range R.repeatedUBAuxiliaryInput)).restrictScalars k))
        ![R.sb.source, R.sb.target] =
      idealOf
        (↥((adjoin
          (↥(adjoin k (Set.range
            (commonCurveEmbedding (k := k) (K := K) ∘ D.uB))))
          (Set.range R.repeatedUBAuxiliaryInput)).restrictScalars k))
        ![R.sAc.source, R.sAc.target] := by
  apply pairIdeal_eq_over_independentExtension_of_pairIdeal_eq
    R.repeatedUBPairIdeal_eq_over_parameterField
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.sb_source] using
        R.repeatedUB_auxiliary_parameter_source_independent hind
    · exact (R.sb.cCorrespondenceFamilyMember hψ).target_mem_parameter_source
  · apply auxiliary_independent_over_parameterPairField
    · simpa only [R.sAc_source] using
        R.repeatedUB_auxiliary_parameter_source_independent hind
    · exact (R.sAc.cCorrespondenceFamilyMember hψ).target_mem_parameter_source

/-- The repeated direct `uB` relation over its named alternative full input
field. -/
theorem repeatedUBPairIdeal_eq_over_alternativeInputField
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    idealOf (↥R.repeatedUBAlternativeInputField)
        ![R.sb.source, R.sb.target] =
      idealOf (↥R.repeatedUBAlternativeInputField)
        ![R.sAc.source, R.sAc.target] := by
  rw [← R.repeatedUBIndependentInputField_eq_alternative]
  exact R.repeatedUBPairIdeal_eq_over_independentInputField hind

/-- The first occurrence of the repeated `sA` relation as an actual finite
correspondence over its alternative full input field. -/
def repeatedSAFirstAlternativePair
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    FiniteCorrespondencePair (↥R.repeatedSAAlternativeInputField)
      (CommonCurveAmbient K) := by
  apply (R.sAa.aCorrespondenceFamilyMember hψ).pairOverIndependentExtension
    R.repeatedSAAuxiliaryInput
  change AlgebraicIndependent k
    (Sum.elim R.repeatedSAAuxiliaryInput
      (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
        R.sAa.source))
  simpa only [R.sAa_source] using
    R.repeatedSA_auxiliary_parameter_source_independent hind

/-- The second occurrence of the repeated `sA` relation over the same
alternative full input field. -/
def repeatedSASecondAlternativePair
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    FiniteCorrespondencePair (↥R.repeatedSAAlternativeInputField)
      (CommonCurveAmbient K) := by
  apply (R.sAc.aCorrespondenceFamilyMember hψ).pairOverIndependentExtension
    R.repeatedSAAuxiliaryInput
  change AlgebraicIndependent k
    (Sum.elim R.repeatedSAAuxiliaryInput
      (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
        R.sAc.source))
  simpa only [R.sAc_source] using
    R.repeatedSA_auxiliary_parameter_source_independent hind

/-- The first occurrence of the repeated direct `u` relation over its
alternative full input field. -/
def repeatedUFirstAlternativePair
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    FiniteCorrespondencePair (↥R.repeatedUAlternativeInputField)
      (CommonCurveAmbient K) := by
  apply (R.se.cCorrespondenceFamilyMember hψ).pairOverIndependentExtension
    R.repeatedUAuxiliaryInput
  change AlgebraicIndependent k
    (Sum.elim R.repeatedUAuxiliaryInput
      (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
        R.se.source))
  simpa only [R.se_source] using
    R.repeatedU_auxiliary_parameter_source_independent hind

/-- The second occurrence of the repeated direct `u` relation over the
same alternative full input field. -/
def repeatedUSecondAlternativePair
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    FiniteCorrespondencePair (↥R.repeatedUAlternativeInputField)
      (CommonCurveAmbient K) := by
  apply (R.sAa.cCorrespondenceFamilyMember hψ).pairOverIndependentExtension
    R.repeatedUAuxiliaryInput
  change AlgebraicIndependent k
    (Sum.elim R.repeatedUAuxiliaryInput
      (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
        R.sAa.source))
  simpa only [R.sAa_source] using
    R.repeatedU_auxiliary_parameter_source_independent hind

/-- The first occurrence of the repeated direct `uB` relation over its
alternative full input field. -/
def repeatedUBFirstAlternativePair
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    FiniteCorrespondencePair (↥R.repeatedUBAlternativeInputField)
      (CommonCurveAmbient K) := by
  apply (R.sb.cCorrespondenceFamilyMember hψ).pairOverIndependentExtension
    R.repeatedUBAuxiliaryInput
  change AlgebraicIndependent k
    (Sum.elim R.repeatedUBAuxiliaryInput
      (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
        R.sb.source))
  simpa only [R.sb_source] using
    R.repeatedUB_auxiliary_parameter_source_independent hind

/-- The second occurrence of the repeated direct `uB` relation over the
same alternative full input field. -/
def repeatedUBSecondAlternativePair
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    FiniteCorrespondencePair (↥R.repeatedUBAlternativeInputField)
      (CommonCurveAmbient K) := by
  apply (R.sAc.cCorrespondenceFamilyMember hψ).pairOverIndependentExtension
    R.repeatedUBAuxiliaryInput
  change AlgebraicIndependent k
    (Sum.elim R.repeatedUBAuxiliaryInput
      (Fin.snoc (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
        R.sAc.source))
  simpa only [R.sAc_source] using
    R.repeatedUB_auxiliary_parameter_source_independent hind

/-- The two alternative-field `sA` pairs have the same selected curve
ideal. -/
theorem repeatedSAAlternativePair_ideal_eq
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (R.repeatedSAFirstAlternativePair hind).ideal =
      (R.repeatedSASecondAlternativePair hind).ideal := by
  change idealOf (↥R.repeatedSAAlternativeInputField)
      ![R.sAa.source, R.sAa.middle] =
    idealOf (↥R.repeatedSAAlternativeInputField)
      ![R.sAc.source, R.sAc.middle]
  exact R.repeatedSAPairIdeal_eq_over_alternativeInputField hind

/-- The two alternative-field direct `u` pairs have the same selected
curve ideal. -/
theorem repeatedUAlternativePair_ideal_eq
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (R.repeatedUFirstAlternativePair hind).ideal =
      (R.repeatedUSecondAlternativePair hind).ideal := by
  change idealOf (↥R.repeatedUAlternativeInputField)
      ![R.se.source, R.se.target] =
    idealOf (↥R.repeatedUAlternativeInputField)
      ![R.sAa.source, R.sAa.target]
  exact R.repeatedUPairIdeal_eq_over_alternativeInputField hind

/-- The two alternative-field direct `uB` pairs have the same selected
curve ideal. -/
theorem repeatedUBAlternativePair_ideal_eq
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (R.repeatedUBFirstAlternativePair hind).ideal =
      (R.repeatedUBSecondAlternativePair hind).ideal := by
  change idealOf (↥R.repeatedUBAlternativeInputField)
      ![R.sb.source, R.sb.target] =
    idealOf (↥R.repeatedUBAlternativeInputField)
      ![R.sAc.source, R.sAc.target]
  exact R.repeatedUBPairIdeal_eq_over_alternativeInputField hind

/-- The repeated `sA` relation has a selected-branch-preserving comparison
over its full alternative input field. -/
noncomputable def repeatedSAAlternativeBasedBranchEquiv
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.repeatedSAFirstAlternativePair hind).basedBranchEquivOfIdealEq
    (R.repeatedSASecondAlternativePair hind)
    (R.repeatedSAAlternativePair_ideal_eq hind)

/-- The repeated direct `u` relation has a selected-branch-preserving
comparison over its full alternative input field. -/
noncomputable def repeatedUAlternativeBasedBranchEquiv
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.repeatedUFirstAlternativePair hind).basedBranchEquivOfIdealEq
    (R.repeatedUSecondAlternativePair hind)
    (R.repeatedUAlternativePair_ideal_eq hind)

/-- The repeated direct `uB` relation has a selected-branch-preserving
comparison over its full alternative input field. -/
noncomputable def repeatedUBAlternativeBasedBranchEquiv
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :=
  (R.repeatedUBFirstAlternativePair hind).basedBranchEquivOfIdealEq
    (R.repeatedUBSecondAlternativePair hind)
    (R.repeatedUBAlternativePair_ideal_eq hind)

/-- All three alternative-field comparisons preserve their literal
selected branches. -/
theorem repeatedAlternativeBasedBranchEquiv_selected
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (R.repeatedSAAlternativeBasedBranchEquiv hind).branchEquiv
        (finiteCoverSelectedBranch
          (R.repeatedSAFirstAlternativePair hind).sourceField_le_branchField) =
        finiteCoverSelectedBranch
          (R.repeatedSASecondAlternativePair hind).sourceField_le_branchField ∧
      (R.repeatedUAlternativeBasedBranchEquiv hind).branchEquiv
        (finiteCoverSelectedBranch
          (R.repeatedUFirstAlternativePair hind).sourceField_le_branchField) =
        finiteCoverSelectedBranch
          (R.repeatedUSecondAlternativePair hind).sourceField_le_branchField ∧
      (R.repeatedUBAlternativeBasedBranchEquiv hind).branchEquiv
        (finiteCoverSelectedBranch
          (R.repeatedUBFirstAlternativePair hind).sourceField_le_branchField) =
        finiteCoverSelectedBranch
          (R.repeatedUBSecondAlternativePair hind).sourceField_le_branchField :=
  ⟨(R.repeatedSAAlternativeBasedBranchEquiv hind).map_selected,
    (R.repeatedUAlternativeBasedBranchEquiv hind).map_selected,
    (R.repeatedUBAlternativeBasedBranchEquiv hind).map_selected⟩

/-- The coefficient-aware normal-cover comparison for the repeated
`s` branch.  It retains the displayed `s` parameter and source coordinates;
the based comparison below additionally corrects it to the selected
branch. -/
noncomputable def repeatedSNormalExtensionEquiv :=
  (R.se.aCorrespondenceFamilyMember hψ).normalExtensionEquivOfIdealEq
    (R.sb.aCorrespondenceFamilyMember hψ)
    R.seAFamily_ideal_eq_sbAFamily

/-- The coefficient-aware normal-cover comparison for the repeated
`sA` branch. -/
noncomputable def repeatedSANormalExtensionEquiv :=
  (R.sAa.aCorrespondenceFamilyMember hψ).normalExtensionEquivOfIdealEq
    (R.sAc.aCorrespondenceFamilyMember hψ)
    R.sAaAFamily_ideal_eq_sAcAFamily

/-- The coefficient-aware normal-cover comparison for the repeated direct
branch labelled by `u`. -/
noncomputable def repeatedUNormalExtensionEquiv :=
  (R.se.cCorrespondenceFamilyMember hψ).normalExtensionEquivOfIdealEq
    (R.sAa.cCorrespondenceFamilyMember hψ)
    R.seCFamily_ideal_eq_sAaCFamily

/-- The coefficient-aware normal-cover comparison for the repeated direct
branch labelled by `uB`. -/
noncomputable def repeatedUBNormalExtensionEquiv :=
  (R.sb.cCorrespondenceFamilyMember hψ).normalExtensionEquivOfIdealEq
    (R.sAc.cCorrespondenceFamilyMember hψ)
    R.sbCFamily_ideal_eq_sAcCFamily

/-- The repeated `s` comparison corrected equivariantly so that the
literal selected middle branch is preserved. -/
noncomputable def repeatedSBasedBranchEquiv :=
  (R.se.aCorrespondenceFamilyMember hψ).basedBranchEquivOfIdealEq
    (R.sb.aCorrespondenceFamilyMember hψ)
    R.seAFamily_ideal_eq_sbAFamily

/-- The repeated `sA` comparison corrected equivariantly so that the
literal selected middle branch is preserved. -/
noncomputable def repeatedSABasedBranchEquiv :=
  (R.sAa.aCorrespondenceFamilyMember hψ).basedBranchEquivOfIdealEq
    (R.sAc.aCorrespondenceFamilyMember hψ)
    R.sAaAFamily_ideal_eq_sAcAFamily

/-- The repeated `u` comparison corrected equivariantly so that the
literal selected target branch is preserved. -/
noncomputable def repeatedUBasedBranchEquiv :=
  (R.se.cCorrespondenceFamilyMember hψ).basedBranchEquivOfIdealEq
    (R.sAa.cCorrespondenceFamilyMember hψ)
    R.seCFamily_ideal_eq_sAaCFamily

/-- The repeated `uB` comparison corrected equivariantly so that the
literal selected target branch is preserved. -/
noncomputable def repeatedUBBasedBranchEquiv :=
  (R.sb.cCorrespondenceFamilyMember hψ).basedBranchEquivOfIdealEq
    (R.sAc.cCorrespondenceFamilyMember hψ)
    R.sbCFamily_ideal_eq_sAcCFamily

/-- The strict finite-cover composition triangle for `s·e=u`, now over the
common eight-input coefficient field. -/
noncomputable def seFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.se) R.seCommonBaseData hψ

/-- The strict finite-cover composition triangle for `sA·a=u`, over the
same common coefficient field. -/
noncomputable def sAaFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.sAa) R.sAaCommonBaseData hψ

/-- The strict finite-cover composition triangle for `s·b=uB`, over the
same common coefficient field. -/
noncomputable def sbFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.sb) R.sbCommonBaseData hψ

/-- The strict finite-cover composition triangle for `sA·c=uB`, over the
same common coefficient field. -/
noncomputable def sAcFiniteCoverCompositionTriangle :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteCoverCompositionTriangle
    (R := R.sAc) R.sAcCommonBaseData hψ

/-- The source cover selected by the `s·e=u` face before simultaneous
enlargement. -/
noncomputable def seFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.se) R.seCommonBaseData hψ

/-- The source cover selected by the `sA·a=u` face before simultaneous
enlargement. -/
noncomputable def sAaFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.sAa) R.sAaCommonBaseData hψ

/-- The source cover selected by the `s·b=uB` face before simultaneous
enlargement. -/
noncomputable def sbFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.sb) R.sbCommonBaseData hψ

/-- The source cover selected by the `sA·c=uB` face before simultaneous
enlargement. -/
noncomputable def sAcFiniteSourceCover :=
  PsiCurveCompositionBaseChangeRealization.CommonBaseData.finiteSourceCover
    (R := R.sAc) R.sAcCommonBaseData hψ

/-- One finite normal source compositum containing the branch
normalizations required by all four common-base faces.  The four source
coordinate fields are definitionally the same because their coefficient
field and formal source coordinate are literally shared. -/
noncomputable def commonFiniteSourceCover :=
  (((R.seFiniteSourceCover.sup R.sAaFiniteSourceCover).sup
      R.sbFiniteSourceCover).sup R.sAcFiniteSourceCover)

/-- The `s·e=u` source normalization lies in the simultaneous source
compositum. -/
theorem seFiniteSourceCover_le_common :
    R.seFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.seFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact (le_sup_left.trans le_sup_left).trans le_sup_left

/-- The `sA·a=u` source normalization lies in the simultaneous source
compositum. -/
theorem sAaFiniteSourceCover_le_common :
    R.sAaFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.sAaFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact (le_sup_right.trans le_sup_left).trans le_sup_left

/-- The `s·b=uB` source normalization lies in the simultaneous source
compositum. -/
theorem sbFiniteSourceCover_le_common :
    R.sbFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.sbFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact le_sup_right.trans le_sup_left

/-- The `sA·c=uB` source normalization lies in the simultaneous source
compositum. -/
theorem sAcFiniteSourceCover_le_common :
    R.sAcFiniteSourceCover.field ≤ R.commonFiniteSourceCover.field := by
  change R.sAcFiniteSourceCover.field ≤
    ((R.seFiniteSourceCover.field ⊔ R.sAaFiniteSourceCover.field) ⊔
      R.sbFiniteSourceCover.field) ⊔ R.sAcFiniteSourceCover.field
  exact le_sup_right

/-- The strict `s·e=u` action after enlarging its source to the
simultaneous four-face compositum. -/
noncomputable def seCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.se) R.seCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.se) R.seCommonBaseData hψ)
    R.commonFiniteSourceCover

/-- The strict `sA·a=u` action on the same simultaneous source
compositum. -/
noncomputable def sAaCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAa) R.sAaCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.sAa) R.sAaCommonBaseData hψ)
    R.commonFiniteSourceCover

/-- The strict `s·b=uB` action on the same simultaneous source
compositum. -/
noncomputable def sbCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sb) R.sbCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.sb) R.sbCommonBaseData hψ)
    R.commonFiniteSourceCover

/-- The strict `sA·c=uB` action on the same simultaneous source
compositum. -/
noncomputable def sAcCommonCoverCompositionTriangle :=
  FiniteCorrespondencePair.FiniteCoverTriangle.OnSourceCover.compositionTriangle
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.bCorrespondencePair
      (R := R.sAc) R.sAcCommonBaseData hψ)
    (PsiCurveCompositionBaseChangeRealization.CommonBaseData.aPair_target_eq_bPair_source
      (R := R.sAc) R.sAcCommonBaseData hψ)
    R.commonFiniteSourceCover

end PsiCurveFourArrowCommonSourceRealizations

end QWitness

end

end AclGeom
