/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.ChunkNormalizedChart
import AclGeom.Correspondence.AlgebraicClosureTransport

/-!
# The selected Ψ chunk on algebraic closures of curve fields

The finite deck bundle of the joint parameter relation resolves conjugate
parameter branches, but it is not itself the positive-dimensional action.
The actual `A`, `B`, and `C` correspondence families act on the curve
coordinate.  Over the field generated by two independent rank-two
parameters, their selected branches give semilinear equivalences between
the algebraic closures of `k(A,B)(X)`, `k(A,B)(Y)`, and `k(A,B)(Z)`.

This module constructs transports over the joint `A,B` coefficient field.
Its `psiCClosureTransport` is a separately chosen lift between the endpoints
of the composed `A,B` branches.  The composition defect is defined by
comparing these two lifts, so correcting by that defect gives equality by
construction.  This does not identify the result with the intrinsic
`C`-parametrized family or prove blueprint equation (8.6).

**Status:** reusable field-transport bookkeeping; the group-chunk route is
frozen pending the audit re-plan (issues #19, #12, #22).
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

namespace QWitness

variable (w : QWitness k K)

/-- The selected `A`-family branch as a transport from the `X` curve field
to the `Y` curve field over the joint `A,B` coefficient field. -/
noncomputable def psiAClosureTransport (hψ : w.Psi) :=
  (w.xyCorrespondencePair hψ).coordinateClosureTransport

/-- The selected `B`-family branch as a transport from the `Y` curve field
to the `Z` curve field over the joint `A,B` coefficient field. -/
noncomputable def psiBClosureTransport (hψ : w.Psi) :=
  (w.yzCorrespondencePair hψ).coordinateClosureTransport

/-- The strictly composed `A`-then-`B` transport. -/
noncomputable def psiABClosureTransport (hψ : w.Psi) :=
  (w.xyCorrespondencePair hψ).chainCoordinateClosureTransport
    (w.yzCorrespondencePair hψ) rfl

/-- A separately selected lift between the composed endpoint fields over
the joint `A,B` coefficient field; its name does not assert an identification
with the intrinsic `C`-family. -/
noncomputable def psiCClosureTransport (hψ : w.Psi) :=
  (w.xyCorrespondencePair hψ).directCompositeClosureTransport
    (w.yzCorrespondencePair hψ) rfl

/-- The deck discrepancy between strict `A`-then-`B` composition and the
independently selected algebraic-closure lift of the `C` branch. -/
noncomputable def psiClosureCompositionDefect (hψ : w.Psi) :=
  (w.xyCorrespondencePair hψ).compositionDefect
    (w.yzCorrespondencePair hψ) rfl

/-- The `A` transport carries the displayed source coordinate `X` to the
selected middle coordinate `Y`. -/
@[simp] theorem psiAClosureTransport_X (hψ : w.Psi) :
    (w.psiAClosureTransport hψ).closureEquiv
        (algebraMap
          (↥(w.xyCorrespondencePair hψ).sourceField)
          (AlgebraicClosure
            (↥(w.xyCorrespondencePair hψ).sourceField))
          ⟨(w.xyCorrespondencePair hψ).source,
            subset_adjoin (↥w.abField) _ (by simp)⟩) =
      algebraMap
        (↥(w.xyCorrespondencePair hψ).targetField)
        (AlgebraicClosure
          (↥(w.xyCorrespondencePair hψ).targetField))
        ⟨(w.xyCorrespondencePair hψ).target,
          subset_adjoin (↥w.abField) _ (by simp)⟩ :=
  (w.xyCorrespondencePair hψ).coordinateClosureTransport_source

/-- The `B` transport carries the shared coordinate `Y` to `Z`. -/
@[simp] theorem psiBClosureTransport_Y (hψ : w.Psi) :
    (w.psiBClosureTransport hψ).closureEquiv
        (algebraMap
          (↥(w.yzCorrespondencePair hψ).sourceField)
          (AlgebraicClosure
            (↥(w.yzCorrespondencePair hψ).sourceField))
          ⟨(w.yzCorrespondencePair hψ).source,
            subset_adjoin (↥w.abField) _ (by simp)⟩) =
      algebraMap
        (↥(w.yzCorrespondencePair hψ).targetField)
        (AlgebraicClosure
          (↥(w.yzCorrespondencePair hψ).targetField))
        ⟨(w.yzCorrespondencePair hψ).target,
          subset_adjoin (↥w.abField) _ (by simp)⟩ :=
  (w.yzCorrespondencePair hψ).coordinateClosureTransport_source

/-- The strictly composed field action sends `X` to `Z`. -/
@[simp] theorem psiABClosureTransport_X (hψ : w.Psi) :
    (w.psiABClosureTransport hψ).closureEquiv
        (algebraMap
          (↥(w.xyCorrespondencePair hψ).sourceField)
          (AlgebraicClosure
            (↥(w.xyCorrespondencePair hψ).sourceField))
          ⟨(w.xyCorrespondencePair hψ).source,
            subset_adjoin (↥w.abField) _ (by simp)⟩) =
      algebraMap
        (↥(w.yzCorrespondencePair hψ).targetField)
        (AlgebraicClosure
          (↥(w.yzCorrespondencePair hψ).targetField))
        ⟨(w.yzCorrespondencePair hψ).target,
          subset_adjoin (↥w.abField) _ (by simp)⟩ :=
  (w.xyCorrespondencePair hψ).chainCoordinateClosureTransport_source
    (w.yzCorrespondencePair hψ) rfl

/-- Composing the two branch transports and then their defined discrepancy
recovers the separately selected endpoint lift.  This transport identity
holds by construction; it does not prove blueprint equation (8.6). -/
theorem psiClosureComposition (hψ : w.Psi) :
    (w.psiABClosureTransport hψ).closureEquiv.trans
        (w.psiClosureCompositionDefect hψ).toRingEquiv =
      (w.psiCClosureTransport hψ).closureEquiv :=
  (w.xyCorrespondencePair hψ)
    |>.chainCoordinateClosureTransport_trans_compositionDefect
      (w.yzCorrespondencePair hψ) rfl

/-- The composition defect is vertical: it fixes the target curve
coordinate `Z` and the entire field `k(A,B)(Z)`. -/
@[simp] theorem psiClosureCompositionDefect_Z (hψ : w.Psi) :
    w.psiClosureCompositionDefect hψ
        (algebraMap
          (↥(w.yzCorrespondencePair hψ).targetField)
          (AlgebraicClosure
            (↥(w.yzCorrespondencePair hψ).targetField))
          ⟨(w.yzCorrespondencePair hψ).target,
            subset_adjoin (↥w.abField) _ (by simp)⟩) =
      algebraMap
        (↥(w.yzCorrespondencePair hψ).targetField)
        (AlgebraicClosure
          (↥(w.yzCorrespondencePair hψ).targetField))
        ⟨(w.yzCorrespondencePair hψ).target,
          subset_adjoin (↥w.abField) _ (by simp)⟩ :=
  (w.xyCorrespondencePair hψ).compositionDefect_target
    (w.yzCorrespondencePair hψ) rfl

/-- The field-action coefficient chart really contains two independent
rank-two parameters; it has not been replaced by a finite deck group. -/
theorem psiClosureParameters_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.abReps :=
  w.abReps_independent hψ

end QWitness

end

end AclGeom
