/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Closure.Ambient
import AclGeom.Config.ChunkCurveFourArrow
import Mathlib.FieldTheory.RatFunc.AsPolynomial

/-!
# A common formal curve source for the four Ψ edges

The edgewise curve triangles constructed previously use different unused
coordinates of the eight-parameter input tuple.  They therefore cannot be
rebased directly to the field generated by all eight inputs: each chosen
source already belongs to that field.

This file adjoins one formal rational-function variable to the original
ambient field and passes to its algebraic closure.  The image of `X` is
transcendental over the whole original ambient field, hence generic over
every parameter tuple coming from it.  Ambient invariance transports the
selected Ψ locus and all algebraicity data along the canonical embedding.
The complete nine-coordinate locus can consequently be relocated over each
of the four parameter edges while fixing the same formal source literally.
-/

namespace AclGeom

open IntermediateField

noncomputable section

universe u

variable {k K Ω : Type u} [Field k] [Field K] [Algebra k K]
  [Field Ω] [Algebra k Ω]

/-- The algebraically closed ambient field obtained by adjoining one formal
curve coordinate to `K`. -/
abbrev CommonCurveAmbient (K : Type u) [Field K] :=
  AlgebraicClosure (RatFunc K)

/-- The canonical ground-field embedding of the original ambient field into
the common curve ambient field. -/
def commonCurveEmbedding : K →ₐ[k] CommonCurveAmbient K :=
  IsScalarTower.toAlgHom k K (CommonCurveAmbient K)

/-- The common formal curve source, namely the image of the rational-function
variable in the algebraic closure of `K(X)`. -/
def commonCurveSource : CommonCurveAmbient K :=
  algebraMap (RatFunc K) (CommonCurveAmbient K) RatFunc.X

/-- The common formal curve source is transcendental even over the entire
original ambient field. -/
theorem commonCurveSource_transcendental :
    Transcendental K (commonCurveSource (K := K)) := by
  rw [commonCurveSource, transcendental_algebraMap_iff
    (algebraMap (RatFunc K) (CommonCurveAmbient K)).injective]
  exact RatFunc.transcendental_X

/-- Consequently the formal source is generic over the image of every finite
tuple from the original ambient field. -/
theorem commonCurveSource_notMem_racl {n : ℕ} (q : Fin n → K) :
    commonCurveSource (K := K) ∉ racl k
      (Set.range (commonCurveEmbedding (k := k) (K := K) ∘ q)) := by
  intro hmem
  let ι : K →ₐ[k] CommonCurveAmbient K :=
    commonCurveEmbedding (k := k) (K := K)
  let E : IntermediateField k (CommonCurveAmbient K) :=
    adjoin k (Set.range (ι ∘ q))
  let F : IntermediateField k (CommonCurveAmbient K) :=
    (⊤ : IntermediateField k K).map ι
  have hEF : E ≤ F := by
    apply adjoin_le_iff.2
    rintro _ ⟨j, rfl⟩
    exact (IntermediateField.map_mem_map
      (S := (⊤ : IntermediateField k K)) ι).2 trivial
  have hE : IsAlgebraic E (commonCurveSource (K := K)) :=
    (mem_racl_iff k).1 hmem
  letI : Algebra E F := (IntermediateField.inclusion hEF).toAlgebra
  haveI : IsScalarTower E F (CommonCurveAmbient K) :=
    .of_algebraMap_eq fun _ ↦ rfl
  have hF : IsAlgebraic F (commonCurveSource (K := K)) :=
    hE.tower_top F
  let eK0 : K ≃ₐ[k] ((⊤ : IntermediateField k K).map ι) :=
    IntermediateField.topEquiv.symm.trans
      ((⊤ : IntermediateField k K).equivMap ι)
  let eK : K ≃ₐ[k] F := eK0
  have hcomm :
      RingHom.comp (algebraMap F (CommonCurveAmbient K))
          eK.toRingEquiv.toRingHom =
        RingHom.comp (RingHom.id (CommonCurveAmbient K))
          (algebraMap K (CommonCurveAmbient K)) := by
    ext x
    change (ι x : CommonCurveAmbient K) =
      algebraMap K (CommonCurveAmbient K) x
    rfl
  have halgK : IsAlgebraic K (commonCurveSource (K := K)) :=
    (isAlgebraic_ringHom_iff_of_comp_eq eK.toRingEquiv
      (RingHom.id (CommonCurveAmbient K)) Function.injective_id hcomm).1 hF
  exact commonCurveSource_transcendental halgK

namespace QWitness

variable (w : QWitness k K)

/-- The parameter-and-curve tuple, with its ambient field independent of the
ambient field containing the original Ψ witness. -/
def psiCurveCompositionTupleOver (_w : QWitness k K) (a b c : Fin 2 → Ω)
    (x y z : Ω) : Fin 9 → Ω :=
  ![a 0, a 1, b 0, b 1, c 0, c 1, x, y, z]

/-- The six displayed parameters followed by a curve source, in an arbitrary
ambient field. -/
def psiCurveParameterSourceTupleOver (_w : QWitness k K) (a b c : Fin 2 → Ω)
    (x : Ω) : Fin 7 → Ω :=
  Fin.snoc (compositionParameterTuple a b c) x

/-- Mapping a parameter-and-curve tuple is the same as constructing the tuple
from the mapped coordinates. -/
@[simp] theorem psiCurveCompositionTupleOver_map
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → K) (x y z : K) :
    w.psiCurveCompositionTupleOver (ι ∘ a) (ι ∘ b) (ι ∘ c)
        (ι x) (ι y) (ι z) =
      ι ∘ w.psiCurveCompositionTuple a b c x y z := by
  funext i
  fin_cases i <;> rfl

/-- Mapping the parameter/source prefix is the same as constructing it from
the mapped coordinates. -/
@[simp] theorem psiCurveParameterSourceTupleOver_map
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → K) (x : K) :
    w.psiCurveParameterSourceTupleOver (ι ∘ a) (ι ∘ b) (ι ∘ c) (ι x) =
      ι ∘ psiCurveParameterSourceTuple a b c x := by
  funext i
  fin_cases i <;> rfl

/-- A realization of the selected Ψ curve-composition locus after embedding
the original witness ambient field into a new algebraically closed field. -/
structure PsiCurveCompositionBaseChangeRealization
    (ι : K →ₐ[k] Ω) (a b c : Fin 2 → Ω) where
  /-- Shared source coordinate of the first and direct branches. -/
  source : Ω
  /-- Shared middle coordinate of the first two branches. -/
  middle : Ω
  /-- Shared target coordinate of the second and direct branches. -/
  target : Ω
  /-- The complete relocated locus equals the embedded selected Ψ locus. -/
  locus :
    idealOf k (w.psiCurveCompositionTupleOver a b c source middle target) =
      idealOf k (ι ∘ w.psiSelectedCurveCompositionTuple)

/-- The selected Ψ curve locus relocates along any ambient embedding while
fixing mapped parameters and any source generic over those parameters. -/
theorem exists_psiCurveCompositionBaseChangeRealization [IsAlgClosed Ω]
    (ι : K →ₐ[k] Ω) (hψ : w.Psi) {a b c : Fin 2 → K}
    (hrel : w.psiFamilyCompositionRelation a b c) {x : Ω}
    (hx : x ∉ racl k
      (Set.range (ι ∘ compositionParameterTuple a b c))) :
    ∃ R : w.PsiCurveCompositionBaseChangeRealization ι
        (ι ∘ a) (ι ∘ b) (ι ∘ c),
      R.source = x := by
  have hparameter :
      idealOf k (ι ∘ compositionParameterTuple a b c) =
        idealOf k (ι ∘ w.abcReps) := by
    calc
      idealOf k (ι ∘ compositionParameterTuple a b c) =
          idealOf k (compositionParameterTuple a b c) :=
        idealOf_comp_algHom k ι _
      _ = idealOf k w.abcReps := by
        simpa [psiFamilyCompositionRelation] using hrel
      _ = idealOf k (ι ∘ w.abcReps) :=
        (idealOf_comp_algHom k ι _).symm
  have hsource :
      ι w.X.rep ∉ racl k (Set.range (ι ∘ w.abcReps)) := by
    intro hmem
    rw [Set.range_comp] at hmem
    exact w.X_rep_notMem_racl_abcReps hψ
      ((algHom_mem_racl_image_iff ι).1 hmem)
  have hfixed :
      idealOf k (w.psiCurveParameterSourceTupleOver
          (ι ∘ a) (ι ∘ b) (ι ∘ c) x) =
        idealOf k (ι ∘ psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep) := by
    rw [← w.psiCurveParameterSourceTupleOver_map]
    change idealOf k (Fin.snoc
        (compositionParameterTuple (ι ∘ a) (ι ∘ b) (ι ∘ c)) x) =
      idealOf k (Fin.snoc
        (compositionParameterTuple (ι ∘ w.aReps) (ι ∘ w.bReps)
          (ι ∘ w.cReps)) (ι w.X.rep))
    have hmapParameters :
        compositionParameterTuple (ι ∘ a) (ι ∘ b) (ι ∘ c) =
          ι ∘ compositionParameterTuple a b c := by
      funext i
      fin_cases i <;> rfl
    have hmapSelected :
        compositionParameterTuple (ι ∘ w.aReps) (ι ∘ w.bReps)
            (ι ∘ w.cReps) =
          ι ∘ w.abcReps := by
      funext i
      fin_cases i <;> rfl
    rw [hmapParameters, hmapSelected]
    exact idealOf_snoc_eq_of_idealOf_eq_of_generic
      hparameter hx hsource
  have hselectedAlgebraic (j : Fin 9) :
      (ι ∘ w.psiSelectedCurveCompositionTuple) j ∈ racl k
        (Set.range (ι ∘ psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep)) := by
    rw [Set.range_comp]
    exact (algHom_mem_racl_image_iff ι).2
      (w.psiSelectedCurveCompositionTuple_mem_parameterSource_racl hψ j)
  obtain ⟨v, hv, hfix⟩ := exists_tuple_relocation_fixing_locus
    hfixed
    (u := ι ∘ w.psiSelectedCurveCompositionTuple)
    (e := psiCurveParameterSourceIndex)
    (fun i ↦ by
      change ι (w.psiSelectedCurveCompositionTuple
          (psiCurveParameterSourceIndex i)) =
        ι (psiCurveParameterSourceTuple
          w.aReps w.bReps w.cReps w.X.rep i)
      congr 1
      exact congrFun
        (w.psiCurveCompositionTuple_comp_parameterSourceIndex
          w.aReps w.bReps w.cReps w.X.rep w.Y.rep w.Z.rep) i)
    hselectedAlgebraic
  let y : Ω := v 7
  let z : Ω := v 8
  have htotal :
      w.psiCurveCompositionTupleOver
          (ι ∘ a) (ι ∘ b) (ι ∘ c) x y z = v := by
    funext i
    fin_cases i
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 0).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 1).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 2).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 3).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 4).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 5).symm
    · simpa [psiCurveParameterSourceIndex,
        psiCurveParameterSourceTupleOver, compositionParameterTuple,
        psiCurveCompositionTupleOver] using (hfix 6).symm
    · rfl
    · rfl
  let R : w.PsiCurveCompositionBaseChangeRealization ι
      (ι ∘ a) (ι ∘ b) (ι ∘ c) :=
    { source := x
      middle := y
      target := z
      locus := by rw [htotal]; exact hv }
  exact ⟨R, rfl⟩

/-- Four embedded Ψ curve triangles with one literal common formal source. -/
structure PsiCurveFourArrowCommonSourceRealizations
    (hψ : w.Psi) {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) where
  /-- Curve triangle above `s·e=u`. -/
  se : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ s)
    (commonCurveEmbedding (k := k) (K := K) ∘ e)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
  /-- Its source is the common formal coordinate. -/
  se_source : se.source = commonCurveSource (K := K)
  /-- Curve triangle above `sA·a=u`. -/
  sAa : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
    (commonCurveEmbedding (k := k) (K := K) ∘ a)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.u)
  /-- Its source is the same common formal coordinate. -/
  sAa_source : sAa.source = commonCurveSource (K := K)
  /-- Curve triangle above `s·b=uB`. -/
  sb : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ s)
    (commonCurveEmbedding (k := k) (K := K) ∘ b)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
  /-- Its source is the same common formal coordinate. -/
  sb_source : sb.source = commonCurveSource (K := K)
  /-- Curve triangle above `sA·c=uB`. -/
  sAc : w.PsiCurveCompositionBaseChangeRealization
    (commonCurveEmbedding (k := k) (K := K))
    (commonCurveEmbedding (k := k) (K := K) ∘ D.sA)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.c)
    (commonCurveEmbedding (k := k) (K := K) ∘ D.uB)
  /-- Its source is the same common formal coordinate. -/
  sAc_source : sAc.source = commonCurveSource (K := K)

/-- The formal rational-function coordinate supplies a single common source
for all four edges of every Ψ parameter difference diagram. -/
theorem exists_psiCurveFourArrowCommonSourceRealizations
    (hψ : w.Psi) {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) :
    Nonempty (w.PsiCurveFourArrowCommonSourceRealizations hψ D) := by
  let ι : K →ₐ[k] CommonCurveAmbient K :=
    commonCurveEmbedding (k := k) (K := K)
  have hse : w.psiFamilyCompositionRelation s e D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s e D.u).2 D.se_u
  have hsAa : w.psiFamilyCompositionRelation D.sA a D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA a D.u).2 D.sA_a_u
  have hsb : w.psiFamilyCompositionRelation s b D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s b D.uB).2
      D.s_b_uB
  have hsAc : w.psiFamilyCompositionRelation D.sA D.c D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA D.c D.uB).2 D.sA_c_uB
  obtain ⟨Rse, hRse⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hse
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple s e D.u))
  obtain ⟨RsAa, hRsAa⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsAa
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple D.sA a D.u))
  obtain ⟨Rsb, hRsb⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsb
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple s b D.uB))
  obtain ⟨RsAc, hRsAc⟩ :=
    w.exists_psiCurveCompositionBaseChangeRealization ι hψ hsAc
      (commonCurveSource_notMem_racl
        (k := k) (K := K) (compositionParameterTuple D.sA D.c D.uB))
  exact ⟨⟨Rse, hRse, RsAa, hRsAa, Rsb, hRsb, RsAc, hRsAc⟩⟩

end QWitness

end

end AclGeom
