/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.ChunkBranchCover

/-!
# Normal covers of the full joint chunk relation

An edge of the joint chunk relation carries three algebraic scalar branches
over its six ambient rank-two coordinates.  This module normalizes that
whole edge at once.  Equal-locus edges have canonically equivalent base and
total function fields, compatible normal-cover transports, and coherent
reference-based branch transitions.

Keeping the whole edge together is essential: it makes the transports at
the four repeated blocks of a difference diagram restrictions of one
coherent local system rather than four unrelated scalar choices.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

namespace QWitness

variable (w : QWitness k K)

/-- One complete realization of the joint rank-two/scalar multiplication
locus. -/
structure PsiChunkRelationRealization where
  /-- Ambient left rank-two parameter. -/
  a : Fin 2 → K
  /-- Ambient right rank-two parameter. -/
  b : Fin 2 → K
  /-- Ambient output rank-two parameter. -/
  c : Fin 2 → K
  /-- Scalar branch above `a`. -/
  s : K
  /-- Scalar branch above `b`. -/
  t : K
  /-- Scalar branch above `c`. -/
  u : K
  /-- The complete nine-coordinate joint locus is the selected one. -/
  relation : w.psiChunkProjectionRelation a b c s t u

namespace PsiChunkRelationRealization

variable {w : QWitness k K}
  (R : w.PsiChunkRelationRealization)

/-- The six ambient rank-two coordinates of a joint realization. -/
def ambientTuple : Fin 6 → K := compositionParameterTuple R.a R.b R.c

/-- All nine coordinates of a joint realization. -/
def jointTuple : Fin 9 → K :=
  chunkProjectionTuple R.a R.b R.c R.s R.t R.u

/-- The field generated by the six ambient rank-two coordinates. -/
def ambientField : IntermediateField k K := adjoin k (Set.range R.ambientTuple)

/-- The field generated by all nine joint coordinates. -/
def jointField : IntermediateField k K := adjoin k (Set.range R.jointTuple)

/-- The coordinate inclusion of the ambient tuple in the joint tuple. -/
def ambientIndex : Fin 6 → Fin 9 := ![0, 1, 2, 3, 4, 5]

@[simp] theorem jointTuple_ambientIndex (i : Fin 6) :
    R.jointTuple (ambientIndex i) = R.ambientTuple i := by
  fin_cases i <;> rfl

/-- The ambient field embeds in the full joint field. -/
theorem ambientField_le_jointField : R.ambientField ≤ R.jointField := by
  apply adjoin.mono
  rintro _ ⟨i, rfl⟩
  have hmem : R.ambientTuple i ∈ Set.range R.jointTuple :=
    ⟨ambientIndex i, R.jointTuple_ambientIndex i⟩
  exact hmem

/-- The full joint field regarded as an extension of its ambient
rank-two field. -/
def jointExtension : IntermediateField (↥R.ambientField) K :=
  extendScalars R.ambientField_le_jointField

/-- The `A` coordinates occur in the ambient six-tuple. -/
theorem a_range_subset_ambientTuple : Set.range R.a ⊆ Set.range R.ambientTuple := by
  rintro _ ⟨i, rfl⟩
  fin_cases i
  · exact ⟨0, rfl⟩
  · exact ⟨1, rfl⟩

/-- The `B` coordinates occur in the ambient six-tuple. -/
theorem b_range_subset_ambientTuple : Set.range R.b ⊆ Set.range R.ambientTuple := by
  rintro _ ⟨i, rfl⟩
  fin_cases i
  · exact ⟨2, rfl⟩
  · exact ⟨3, rfl⟩

/-- The `C` coordinates occur in the ambient six-tuple. -/
theorem c_range_subset_ambientTuple : Set.range R.c ⊆ Set.range R.ambientTuple := by
  rintro _ ⟨i, rfl⟩
  fin_cases i
  · exact ⟨4, rfl⟩
  · exact ⟨5, rfl⟩

/-- Every coordinate of a joint realization is algebraic over its six
ambient coordinates. -/
theorem jointTuple_mem_racl_ambientTuple (hψ : w.Psi) (i : Fin 9) :
    R.jointTuple i ∈ racl k (Set.range R.ambientTuple) := by
  fin_cases i
  · exact subset_racl k _ (Set.mem_range_self 0)
  · exact subset_racl k _ (Set.mem_range_self 1)
  · exact subset_racl k _ (Set.mem_range_self 2)
  · exact subset_racl k _ (Set.mem_range_self 3)
  · exact subset_racl k _ (Set.mem_range_self 4)
  · exact subset_racl k _ (Set.mem_range_self 5)
  · exact racl_mono R.a_range_subset_ambientTuple
      (PsiAProjectionRelation.scalar_mem_racl w hψ
        (PsiChunkProjectionRelation.aProjection w R.relation))
  · exact racl_mono R.b_range_subset_ambientTuple
      (PsiBProjectionRelation.scalar_mem_racl w hψ
        (PsiChunkProjectionRelation.bProjection w R.relation))
  · exact racl_mono R.c_range_subset_ambientTuple
      (PsiCProjectionRelation.scalar_mem_racl w hψ
        (PsiChunkProjectionRelation.cProjection w R.relation))

/-- The full joint edge is a finite extension of its six-coordinate
ambient edge. -/
theorem jointExtension_finiteDimensional (hψ : w.Psi) :
    FiniteDimensional (↥R.ambientField) (↥R.jointExtension) := by
  have key : R.jointExtension = adjoin (↥R.ambientField)
      (Set.range R.jointTuple) := by
    refine restrictScalars_injective k ?_
    unfold jointExtension ambientField jointField
    rw [adjoin_adjoin_left, extendScalars_restrictScalars, adjoin_union]
    exact (sup_eq_right.2 R.ambientField_le_jointField).symm
  rw [key]
  letI : Fintype (Set.range R.jointTuple) :=
    Set.Finite.fintype (Set.finite_range R.jointTuple)
  exact finiteDimensional_adjoin fun x hx ↦ by
    obtain ⟨i, rfl⟩ := hx
    exact ((mem_racl_iff k).1
      (R.jointTuple_mem_racl_ambientTuple hψ i)).isIntegral

/-- The normalized branch arrows above a full joint edge act faithfully on
its concrete normal-cover field over the six-coordinate ambient field.
This packages the finite deck action used to remove branch ambiguity; it
does not identify that finite group with the positive-dimensional chunk
parameter reconstructed from the quadrangle. -/
def translationChunk [IsAlgClosed K] (hψ : w.Psi)
    (b : finiteCoverBranchGroupoid R.ambientField_le_jointField) :
    TranslationGroupChunk (↥R.ambientField)
      (↥(FiniteCover.normalClosureOver R.ambientField_le_jointField))
      (finiteCoverSelectedObject R.ambientField_le_jointField ⟶ b) :=
  finiteCoverTranslationChunk R.ambientField_le_jointField
    (R.jointExtension_finiteDimensional hψ) b

/-- Equal joint loci identify their six-coordinate ambient fields. -/
def ambientEquiv (R V : w.PsiChunkRelationRealization) :
    (↥R.ambientField) ≃ₐ[k] (↥V.ambientField) :=
  locusFunctionFieldEquivOfIdealEq
    ((PsiChunkProjectionRelation.psiFamilyComposition w R.relation).trans
      (PsiChunkProjectionRelation.psiFamilyComposition w V.relation).symm)

/-- Ambient-field transport sends each displayed coordinate to the
corresponding coordinate of the target edge. -/
@[simp] theorem ambientEquiv_apply (R V : w.PsiChunkRelationRealization)
    (i : Fin 6) :
    ambientEquiv R V
        ⟨R.ambientTuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨V.ambientTuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply
    ((PsiChunkProjectionRelation.psiFamilyComposition w R.relation).trans
      (PsiChunkProjectionRelation.psiFamilyComposition w V.relation).symm) i

/-- Equal joint loci identify their full nine-coordinate fields. -/
def jointEquiv (R V : w.PsiChunkRelationRealization) :
    (↥R.jointField) ≃ₐ[k] (↥V.jointField) :=
  locusFunctionFieldEquivOfIdealEq (R.relation.trans V.relation.symm)

/-- Joint-field transport sends all nine coordinates positionwise. -/
@[simp] theorem jointEquiv_apply (R V : w.PsiChunkRelationRealization)
    (i : Fin 9) :
    jointEquiv R V
        ⟨R.jointTuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨V.jointTuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply
    (R.relation.trans V.relation.symm) i

/-- Joint-field transport sends embedded ambient coordinates to the
corresponding embedded ambient coordinates. -/
@[simp] theorem jointEquiv_apply_ambient
    (R V : w.PsiChunkRelationRealization) (i : Fin 6) :
    jointEquiv R V
        ⟨R.ambientTuple i,
          R.ambientField_le_jointField
            (subset_adjoin k _ (Set.mem_range_self i))⟩ =
      ⟨V.ambientTuple i,
        V.ambientField_le_jointField
          (subset_adjoin k _ (Set.mem_range_self i))⟩ := by
  simpa only [jointTuple_ambientIndex] using
    jointEquiv_apply R V (ambientIndex i)

set_option maxHeartbeats 800000 in
-- Unfolding the two locus-generated extension squares is elaboration-heavy.
/-- The ambient and joint field equivalences form a commuting equivalence
of finite extensions. -/
def extensionEquiv (R V : w.PsiChunkRelationRealization) :
    FiniteCover.ExtensionEquiv R.ambientField_le_jointField
      V.ambientField_le_jointField where
  baseEquiv := ambientEquiv R V
  totalEquiv := jointEquiv R V
  commutes := by
    apply adjoin_algHom_ext k
    rintro _ ⟨i, rfl⟩
    change jointEquiv R V
        ⟨R.ambientTuple i, _⟩ =
      IntermediateField.inclusion V.ambientField_le_jointField
        (ambientEquiv R V
          ⟨R.ambientTuple i, _⟩)
    rw [jointEquiv_apply_ambient, ambientEquiv_apply]
    rfl

/-- The concrete normal covers of two joint edges are equivalent over the
corresponding ambient-field equivalence. -/
noncomputable def normalCoverEquiv [IsAlgClosed K]
    (hψ : w.Psi) (R V : w.PsiChunkRelationRealization) :
    (↥(FiniteCover.normalClosureOver R.ambientField_le_jointField)) ≃+*
      (↥(FiniteCover.normalClosureOver V.ambientField_le_jointField)) := by
  have hfinR := R.jointExtension_finiteDimensional hψ
  have hfinV := V.jointExtension_finiteDimensional hψ
  letI : FiniteDimensional (↥R.ambientField)
      (↥(extendScalars R.ambientField_le_jointField)) := hfinR
  letI : FiniteDimensional (↥V.ambientField)
      (↥(extendScalars V.ambientField_le_jointField)) := hfinV
  let cR := FiniteCover.normalClosureOverEquivCanonical
    R.ambientField_le_jointField (Algebra.IsAlgebraic.of_finite _ _)
  let cV := FiniteCover.normalClosureOverEquivCanonical
    V.ambientField_le_jointField (Algebra.IsAlgebraic.of_finite _ _)
  exact cR.toRingEquiv |>.trans
    (extensionEquiv R V).normalLift.normalEquiv |>.trans
      cV.symm.toRingEquiv

/-- Normal-cover transport is semilinear over the ambient edge-field
transport. -/
@[simp] theorem normalCoverEquiv_algebraMap [IsAlgClosed K]
    (hψ : w.Psi) (R V : w.PsiChunkRelationRealization)
    (x : R.ambientField) :
    normalCoverEquiv hψ R V
        (algebraMap (↥R.ambientField)
          (↥(FiniteCover.normalClosureOver
            R.ambientField_le_jointField)) x) =
      algebraMap (↥V.ambientField)
        (↥(FiniteCover.normalClosureOver
          V.ambientField_le_jointField))
        (ambientEquiv R V x) := by
  simp [normalCoverEquiv, extensionEquiv]

/-- Equal-locus joint edges have equivariantly equivalent conjugate-branch
groupoids, based at their literal selected edges. -/
noncomputable def basedBranchEquiv [IsAlgClosed K]
    (hψ : w.Psi) (R V : w.PsiChunkRelationRealization) :
    FiniteCoverBasedBranchEquiv R.ambientField_le_jointField
      V.ambientField_le_jointField := by
  apply finiteCoverBasedBranchEquivOfExtensionEquiv
    R.ambientField_le_jointField V.ambientField_le_jointField
    (V.jointExtension_finiteDimensional hψ)
    (extensionEquiv R V) (normalCoverEquiv hψ R V)
  apply RingHom.ext
  intro x
  exact normalCoverEquiv_algebraMap hψ R V x

/-- Trivialize one joint-edge branch fiber against a fixed reference
edge. -/
noncomputable def branchTrivialization [IsAlgClosed K]
    (hψ : w.Psi) (reference R : w.PsiChunkRelationRealization) :
    FiniteCoverBasedBranchEquiv reference.ambientField_le_jointField
      R.ambientField_le_jointField :=
  basedBranchEquiv hψ reference R

/-- The coherent branch transition from one joint edge to another,
defined through a single reference edge. -/
noncomputable def branchTransition [IsAlgClosed K]
    (hψ : w.Psi) (reference R V : w.PsiChunkRelationRealization) :
    FiniteCoverBasedBranchEquiv R.ambientField_le_jointField
      V.ambientField_le_jointField :=
  (branchTrivialization hψ reference R).symm.trans
    (branchTrivialization hψ reference V)

/-- A reference-based joint-edge branch transition is the identity on
each fiber. -/
theorem branchTransition_self [IsAlgClosed K]
    (hψ : w.Psi) (reference R : w.PsiChunkRelationRealization) :
    branchTransition hψ reference R R =
      FiniteCoverBasedBranchEquiv.refl R.ambientField_le_jointField := by
  unfold branchTransition
  exact FiniteCoverBasedBranchEquiv.symm_trans_self
    (branchTrivialization hψ reference R)

/-- Reversing a reference-based joint-edge transition reverses its
endpoints. -/
theorem branchTransition_symm [IsAlgClosed K]
    (hψ : w.Psi) (reference R V : w.PsiChunkRelationRealization) :
    (branchTransition hψ reference R V).symm =
      branchTransition hψ reference V R := by
  unfold branchTransition
  exact FiniteCoverBasedBranchEquiv.symm_trans_symm
    (branchTrivialization hψ reference R)
    (branchTrivialization hψ reference V)

/-- Reference-based joint-edge transports satisfy the strict cocycle
identity.  Consequently every cycle of transports through the same
reference has trivial holonomy. -/
theorem branchTransition_trans [IsAlgClosed K]
    (hψ : w.Psi)
    (reference R V U : w.PsiChunkRelationRealization) :
    (branchTransition hψ reference R V).trans
        (branchTransition hψ reference V U) =
      branchTransition hψ reference R U := by
  unfold branchTransition
  exact FiniteCoverBasedBranchEquiv.symm_trans_trans_symm_trans
    (branchTrivialization hψ reference R)
    (branchTrivialization hψ reference V)
    (branchTrivialization hψ reference U)

end PsiChunkRelationRealization

namespace PsiChunkFourArrowEdgeLifts

variable {w : QWitness k K} {hψ : w.Psi}
  {s a b e : Fin 2 → K}
  {D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e}
  (L : w.PsiChunkFourArrowEdgeLifts hψ D)

/-- The `s·e=u` edge as a complete joint relation realization. -/
def seRealization : w.PsiChunkRelationRealization where
  a := s
  b := e
  c := D.u
  s := L.se_s
  t := L.se_e
  u := L.se_u
  relation := L.se_lift

/-- The `sA·a=u` edge as a complete joint relation realization. -/
def sA_aRealization : w.PsiChunkRelationRealization where
  a := D.sA
  b := a
  c := D.u
  s := L.sA_a_sA
  t := L.sA_a_a
  u := L.sA_a_u
  relation := L.sA_a_lift

/-- The `s·b=uB` edge as a complete joint relation realization. -/
def s_bRealization : w.PsiChunkRelationRealization where
  a := s
  b := b
  c := D.uB
  s := L.s_b_s
  t := L.s_b_b
  u := L.s_b_uB
  relation := L.s_b_lift

/-- The `sA·c=uB` edge as a complete joint relation realization. -/
def sA_cRealization : w.PsiChunkRelationRealization where
  a := D.sA
  b := D.c
  c := D.uB
  s := L.sA_c_sA
  t := L.sA_c_c
  u := L.sA_c_uB
  relation := L.sA_c_lift

/-- The four edge covers of an ambient difference diagram form one
coherent reference-trivialized branch system. -/
theorem edge_branchTransition_cocycle [IsAlgClosed K]
    (R V U : w.PsiChunkRelationRealization) :
    (PsiChunkRelationRealization.branchTransition hψ L.seRealization R V).trans
        (PsiChunkRelationRealization.branchTransition
          hψ L.seRealization V U) =
      PsiChunkRelationRealization.branchTransition
        hψ L.seRealization R U :=
  PsiChunkRelationRealization.branchTransition_trans
    hψ L.seRealization R V U

/-- The reference-based transport around the four lifted edges has
trivial holonomy.  This is the exact finite-cover cycle statement needed
before descending the local system to one normalized chunk chart. -/
theorem fourEdge_branchCycle [IsAlgClosed K] :
    (((PsiChunkRelationRealization.branchTransition hψ
          L.seRealization L.seRealization L.sA_aRealization).trans
        (PsiChunkRelationRealization.branchTransition hψ
          L.seRealization L.sA_aRealization L.sA_cRealization)).trans
      (PsiChunkRelationRealization.branchTransition hψ
        L.seRealization L.sA_cRealization L.s_bRealization)).trans
    (PsiChunkRelationRealization.branchTransition hψ
      L.seRealization L.s_bRealization L.seRealization) =
      FiniteCoverBasedBranchEquiv.refl
        L.seRealization.ambientField_le_jointField := by
  rw [PsiChunkRelationRealization.branchTransition_trans]
  rw [PsiChunkRelationRealization.branchTransition_trans]
  rw [PsiChunkRelationRealization.branchTransition_trans]
  exact PsiChunkRelationRealization.branchTransition_self
    hψ L.seRealization L.seRealization

end PsiChunkFourArrowEdgeLifts

end QWitness

end
end AclGeom
