/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.ChunkProjection
import AclGeom.Correspondence.BranchGroupoid

/-!
# Finite branch covers for the chunk projection

The scalar coordinate over a rank-two chunk parameter is algebraic, but it
need not be uniquely determined.  This module packages that ambiguity as a
finite extension of function fields.  Equal realizations of one projection
graph induce compatible equivalences of the extensions, their normal
closures, and their based conjugate-branch groupoids.

This is the finite-cover gluing interface used before choosing a
single-valued chart for the rank-one normal kernel.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

namespace QWitness

variable (w : QWitness k K)

/-- The function field generated by a rank-two parameter. -/
def rankTwoParameterField (p : Fin 2 → K) : IntermediateField k K :=
  adjoin k (Set.range p)

/-- The function field generated by a rank-two parameter and one scalar
branch above it. -/
def rankTwoScalarField (p : Fin 2 → K) (x : K) : IntermediateField k K :=
  adjoin k (Set.range (rankTwoScalarTuple p x))

/-- The rank-two parameter field is contained in every scalar branch
field above it. -/
theorem rankTwoParameterField_le_rankTwoScalarField
    (p : Fin 2 → K) (x : K) :
    rankTwoParameterField (k := k) p ≤ rankTwoScalarField (k := k) p x := by
  apply adjoin.mono
  rintro _ ⟨i, rfl⟩
  fin_cases i
  · exact ⟨0, rfl⟩
  · exact ⟨1, rfl⟩

/-- The scalar branch field, regarded as an extension of its rank-two
parameter field. -/
def rankTwoScalarExtension (p : Fin 2 → K) (x : K) :
    IntermediateField (↥(rankTwoParameterField (k := k) p)) K :=
  extendScalars (rankTwoParameterField_le_rankTwoScalarField
    (k := k) p x)

omit [Field K] in
/-- The coordinates of a rank-two/scalar tuple generate the union of the
rank-two coordinates and the scalar singleton. -/
theorem rankTwoScalarTuple_range (p : Fin 2 → K) (x : K) :
    Set.range (rankTwoScalarTuple p x) = Set.range p ∪ {x} := by
  ext z
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i
    · exact Set.mem_union_left _ (Set.mem_range_self 0)
    · exact Set.mem_union_left _ (Set.mem_range_self 1)
    · exact Set.mem_union_right _ (Set.mem_singleton x)
  · rintro (⟨i, rfl⟩ | rfl)
    · fin_cases i
      · exact ⟨0, rfl⟩
      · exact ⟨1, rfl⟩
    · exact ⟨2, rfl⟩

/-- Over the rank-two parameter field, the scalar branch extension is
generated by the scalar coordinate alone. -/
theorem rankTwoScalarExtension_eq_adjoin (p : Fin 2 → K) (x : K) :
    rankTwoScalarExtension (k := k) p x =
      adjoin (↥(rankTwoParameterField (k := k) p)) {x} := by
  refine restrictScalars_injective k ?_
  unfold rankTwoScalarExtension rankTwoParameterField rankTwoScalarField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars,
    rankTwoScalarTuple_range]

/-- Algebraicity of the scalar coordinate makes its branch field finite
over the rank-two parameter field. -/
theorem rankTwoScalarExtension_finiteDimensional
    {p : Fin 2 → K} {x : K} (hx : x ∈ racl k (Set.range p)) :
    FiniteDimensional (↥(rankTwoParameterField (k := k) p))
      (↥(rankTwoScalarExtension (k := k) p x)) := by
  rw [rankTwoScalarExtension_eq_adjoin]
  exact finiteDimensional_adjoin fun z hz ↦ by
    rw [Set.mem_singleton_iff] at hz
    subst z
    exact ((mem_racl_iff k).1 hx).isIntegral

/-- Algebraicity of a distinguished scalar transfers to every realization
of the same rank-two/scalar graph locus. -/
theorem scalar_mem_racl_of_rankTwoScalar_locus
    {p q : Fin 2 → K} {x y : K}
    (hxy : idealOf k (rankTwoScalarTuple p x) =
      idealOf k (rankTwoScalarTuple q y))
    (hy : y ∈ racl k (Set.range q)) :
    x ∈ racl k (Set.range p) := by
  let J : Set (Fin 3) := {0, 1}
  have hq : (rankTwoScalarTuple q y) '' J = Set.range q := by
    ext z
    simp [J, rankTwoScalarTuple]
  have hp : (rankTwoScalarTuple p x) '' J = Set.range p := by
    ext z
    simp [J, rankTwoScalarTuple]
  have hy' : rankTwoScalarTuple q y 2 ∈
      racl k ((rankTwoScalarTuple q y) '' J) := by
    rw [hq]
    exact hy
  have ht := mem_racl_image_of_idealOf_eq k hxy.symm hy'
  rw [hp] at ht
  exact ht

/-- Every realization of the `A/S` projection graph is a finite scalar
branch over its displayed rank-two parameter. -/
theorem PsiAProjectionRelation.scalar_mem_racl
    (hψ : w.Psi) {p : Fin 2 → K} {s : K}
    (h : w.psiAProjectionRelation p s) :
    s ∈ racl k (Set.range p) :=
  scalar_mem_racl_of_rankTwoScalar_locus h
    (w.S_rep_mem_racl_aReps hψ)

/-- Every realization of the `B/T` projection graph is a finite scalar
branch over its displayed rank-two parameter. -/
theorem PsiBProjectionRelation.scalar_mem_racl
    (hψ : w.Psi) {p : Fin 2 → K} {t : K}
    (h : w.psiBProjectionRelation p t) :
    t ∈ racl k (Set.range p) :=
  scalar_mem_racl_of_rankTwoScalar_locus h
    (w.T_rep_mem_racl_bReps hψ)

/-- Every realization of the `C/U` projection graph is a finite scalar
branch over its displayed rank-two parameter. -/
theorem PsiCProjectionRelation.scalar_mem_racl
    (hψ : w.Psi) {p : Fin 2 → K} {u : K}
    (h : w.psiCProjectionRelation p u) :
    u ∈ racl k (Set.range p) :=
  scalar_mem_racl_of_rankTwoScalar_locus h
    (w.U_rep_mem_racl_cReps hψ)

/-- Equal scalar graph loci over the same rank-two parameter canonically
identify their finite extensions. -/
def rankTwoScalarExtensionEquiv {p : Fin 2 → K} {x y : K}
    (hxy : idealOf k (rankTwoScalarTuple p x) =
      idealOf k (rankTwoScalarTuple p y)) :
    FiniteCover.ExtensionEquiv
      (rankTwoParameterField_le_rankTwoScalarField (k := k) p x)
      (rankTwoParameterField_le_rankTwoScalarField (k := k) p y) where
  baseEquiv := AlgEquiv.refl
  totalEquiv := locusFunctionFieldEquivOfIdealEq hxy
  commutes := by
    apply adjoin_algHom_ext k
    rintro _ ⟨i, rfl⟩
    fin_cases i
    · change locusFunctionFieldEquivOfIdealEq hxy
          ⟨rankTwoScalarTuple p x 0, _⟩ =
        ⟨rankTwoScalarTuple p y 0, _⟩
      exact locusFunctionFieldEquivOfIdealEq_apply hxy 0
    · change locusFunctionFieldEquivOfIdealEq hxy
          ⟨rankTwoScalarTuple p x 1, _⟩ =
        ⟨rankTwoScalarTuple p y 1, _⟩
      exact locusFunctionFieldEquivOfIdealEq_apply hxy 1

/-- The concrete normal covers of two scalar branches on the same graph
locus are equivalent over the common rank-two parameter field. -/
noncomputable def rankTwoScalarNormalCoverEquiv [IsAlgClosed K]
    {p : Fin 2 → K} {x y : K}
    (hx : x ∈ racl k (Set.range p))
    (hy : y ∈ racl k (Set.range p))
    (hxy : idealOf k (rankTwoScalarTuple p x) =
      idealOf k (rankTwoScalarTuple p y)) :
    (↥(FiniteCover.normalClosureOver
      (rankTwoParameterField_le_rankTwoScalarField (k := k) p x))) ≃+*
      (↥(FiniteCover.normalClosureOver
        (rankTwoParameterField_le_rankTwoScalarField (k := k) p y))) := by
  have hfinx := rankTwoScalarExtension_finiteDimensional
    (k := k) (K := K) hx
  have hfiny := rankTwoScalarExtension_finiteDimensional
    (k := k) (K := K) hy
  letI : FiniteDimensional (↥(rankTwoParameterField (k := k) p))
      (↥(extendScalars
        (rankTwoParameterField_le_rankTwoScalarField (k := k) p x))) :=
    hfinx
  letI : FiniteDimensional (↥(rankTwoParameterField (k := k) p))
      (↥(extendScalars
        (rankTwoParameterField_le_rankTwoScalarField (k := k) p y))) :=
    hfiny
  let cx := FiniteCover.normalClosureOverEquivCanonical
    (rankTwoParameterField_le_rankTwoScalarField (k := k) p x)
    (Algebra.IsAlgebraic.of_finite _ _)
  let cy := FiniteCover.normalClosureOverEquivCanonical
    (rankTwoParameterField_le_rankTwoScalarField (k := k) p y)
    (Algebra.IsAlgebraic.of_finite _ _)
  exact cx.toRingEquiv |>.trans
    (rankTwoScalarExtensionEquiv (k := k) hxy).normalLift.normalEquiv |>.trans
      cy.symm.toRingEquiv

/-- The concrete normal-cover equivalence fixes the common rank-two
parameter field. -/
@[simp] theorem rankTwoScalarNormalCoverEquiv_algebraMap [IsAlgClosed K]
    {p : Fin 2 → K} {x y : K}
    (hx : x ∈ racl k (Set.range p))
    (hy : y ∈ racl k (Set.range p))
    (hxy : idealOf k (rankTwoScalarTuple p x) =
      idealOf k (rankTwoScalarTuple p y))
    (z : rankTwoParameterField (k := k) p) :
    rankTwoScalarNormalCoverEquiv hx hy hxy
        (algebraMap (↥(rankTwoParameterField (k := k) p))
          (↥(FiniteCover.normalClosureOver
            (rankTwoParameterField_le_rankTwoScalarField (k := k) p x))) z) =
      algebraMap (↥(rankTwoParameterField (k := k) p))
        (↥(FiniteCover.normalClosureOver
          (rankTwoParameterField_le_rankTwoScalarField (k := k) p y))) z := by
  simp [rankTwoScalarNormalCoverEquiv, rankTwoScalarExtensionEquiv]

/-- Equal graph realizations over the same rank-two parameter have
equivariantly equivalent conjugate-branch groupoids, with their literal
selected branches matched. -/
noncomputable def rankTwoScalarBasedBranchEquiv [IsAlgClosed K]
    {p : Fin 2 → K} {x y : K}
    (hx : x ∈ racl k (Set.range p))
    (hy : y ∈ racl k (Set.range p))
    (hxy : idealOf k (rankTwoScalarTuple p x) =
      idealOf k (rankTwoScalarTuple p y)) :
    FiniteCoverBasedBranchEquiv
      (rankTwoParameterField_le_rankTwoScalarField (k := k) p x)
      (rankTwoParameterField_le_rankTwoScalarField (k := k) p y) := by
  apply finiteCoverBasedBranchEquivOfExtensionEquiv
    (rankTwoParameterField_le_rankTwoScalarField (k := k) p x)
    (rankTwoParameterField_le_rankTwoScalarField (k := k) p y)
    (rankTwoScalarExtension_finiteDimensional (k := k) (K := K) hy)
    (rankTwoScalarExtensionEquiv (k := k) hxy)
    (rankTwoScalarNormalCoverEquiv hx hy hxy)
  apply RingHom.ext
  intro z
  exact rankTwoScalarNormalCoverEquiv_algebraMap hx hy hxy z

/-- Independent edgewise lifts of an ambient rank-two four-arrow diagram.
Each edge lies on the full joint locus.  Scalar coordinates at a repeated
rank-two block are retained separately so that their finite branch
transports, rather than a false literal equality, record the gluing data. -/
structure PsiChunkFourArrowEdgeLifts (hψ : w.Psi)
    {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) where
  /-- Scalar `S` branch on the `s·e` edge. -/
  se_s : K
  /-- Scalar `T` branch on the `s·e` edge. -/
  se_e : K
  /-- Scalar `U` branch on the `s·e` edge. -/
  se_u : K
  /-- Joint lift of the `s·e=u` edge. -/
  se_lift : w.psiChunkProjectionRelation s e D.u se_s se_e se_u
  /-- Scalar `S` branch on the `sA·a` edge. -/
  sA_a_sA : K
  /-- Scalar `T` branch on the `sA·a` edge. -/
  sA_a_a : K
  /-- Scalar `U` branch on the `sA·a` edge. -/
  sA_a_u : K
  /-- Joint lift of the `sA·a=u` edge. -/
  sA_a_lift :
    w.psiChunkProjectionRelation D.sA a D.u sA_a_sA sA_a_a sA_a_u
  /-- Scalar `S` branch on the `s·b` edge. -/
  s_b_s : K
  /-- Scalar `T` branch on the `s·b` edge. -/
  s_b_b : K
  /-- Scalar `U` branch on the `s·b` edge. -/
  s_b_uB : K
  /-- Joint lift of the `s·b=uB` edge. -/
  s_b_lift : w.psiChunkProjectionRelation s b D.uB s_b_s s_b_b s_b_uB
  /-- Scalar `S` branch on the `sA·c` edge. -/
  sA_c_sA : K
  /-- Scalar `T` branch on the `sA·c` edge. -/
  sA_c_c : K
  /-- Scalar `U` branch on the `sA·c` edge. -/
  sA_c_uB : K
  /-- Joint lift of the `sA·c=uB` edge. -/
  sA_c_lift :
    w.psiChunkProjectionRelation D.sA D.c D.uB
      sA_c_sA sA_c_c sA_c_uB

/-- Every ambient rank-two four-arrow diagram admits joint lifts of all
four edges.  No compatibility of independently selected scalar branches is
silently assumed. -/
theorem exists_psiChunkFourArrowEdgeLifts [IsAlgClosed K]
    (hψ : w.Psi) {s a b e : Fin 2 → K}
    (D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e) :
    Nonempty (w.PsiChunkFourArrowEdgeLifts hψ D) := by
  have hse : w.psiFamilyCompositionRelation s e D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s e D.u).2 D.se_u
  have hsAa : w.psiFamilyCompositionRelation D.sA a D.u :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA a D.u).2 D.sA_a_u
  have hsb : w.psiFamilyCompositionRelation s b D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization hψ s b D.uB).2 D.s_b_uB
  have hsAc : w.psiFamilyCompositionRelation D.sA D.c D.uB :=
    (w.psiFamilyCompositionRelation_iff_isRealization
      hψ D.sA D.c D.uB).2 D.sA_c_uB
  obtain ⟨se_s, se_e, se_u, hse'⟩ :=
    w.exists_psiChunkProjection_of_relation hψ hse
  obtain ⟨sA_a_sA, sA_a_a, sA_a_u, hsAa'⟩ :=
    w.exists_psiChunkProjection_of_relation hψ hsAa
  obtain ⟨s_b_s, s_b_b, s_b_uB, hsb'⟩ :=
    w.exists_psiChunkProjection_of_relation hψ hsb
  obtain ⟨sA_c_sA, sA_c_c, sA_c_uB, hsAc'⟩ :=
    w.exists_psiChunkProjection_of_relation hψ hsAc
  exact ⟨⟨se_s, se_e, se_u, hse',
    sA_a_sA, sA_a_a, sA_a_u, hsAa',
    s_b_s, s_b_b, s_b_uB, hsb',
    sA_c_sA, sA_c_c, sA_c_uB, hsAc'⟩⟩

namespace PsiChunkFourArrowEdgeLifts

variable {w : QWitness k K} {hψ : w.Psi}
  {s a b e : Fin 2 → K}
  {D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e}
  (L : w.PsiChunkFourArrowEdgeLifts hψ D)

/-- The two scalar branches above the repeated ambient `s` block realize
the same `A/S` graph locus. -/
theorem s_graph_eq :
    idealOf k (rankTwoScalarTuple s L.se_s) =
      idealOf k (rankTwoScalarTuple s L.s_b_s) :=
  (PsiChunkProjectionRelation.aProjection w L.se_lift).trans
    (PsiChunkProjectionRelation.aProjection w L.s_b_lift).symm

/-- The two scalar branches above the repeated ambient `u` block realize
the same `C/U` graph locus. -/
theorem u_graph_eq :
    idealOf k (rankTwoScalarTuple D.u L.se_u) =
      idealOf k (rankTwoScalarTuple D.u L.sA_a_u) :=
  (PsiChunkProjectionRelation.cProjection w L.se_lift).trans
    (PsiChunkProjectionRelation.cProjection w L.sA_a_lift).symm

/-- The two scalar branches above the repeated ambient `sA` block realize
the same `A/S` graph locus. -/
theorem sA_graph_eq :
    idealOf k (rankTwoScalarTuple D.sA L.sA_a_sA) =
      idealOf k (rankTwoScalarTuple D.sA L.sA_c_sA) :=
  (PsiChunkProjectionRelation.aProjection w L.sA_a_lift).trans
    (PsiChunkProjectionRelation.aProjection w L.sA_c_lift).symm

/-- The two scalar branches above the repeated ambient `uB` block realize
the same `C/U` graph locus. -/
theorem uB_graph_eq :
    idealOf k (rankTwoScalarTuple D.uB L.s_b_uB) =
      idealOf k (rankTwoScalarTuple D.uB L.sA_c_uB) :=
  (PsiChunkProjectionRelation.cProjection w L.s_b_lift).trans
    (PsiChunkProjectionRelation.cProjection w L.sA_c_lift).symm

/-- Normal-cover transport reconciles the two scalar branches over the
repeated ambient `s` block. -/
noncomputable def s_branchEquiv [IsAlgClosed K] :
    FiniteCoverBasedBranchEquiv
      (rankTwoParameterField_le_rankTwoScalarField (k := k) s L.se_s)
      (rankTwoParameterField_le_rankTwoScalarField (k := k) s L.s_b_s) :=
  rankTwoScalarBasedBranchEquiv
    (PsiAProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.aProjection w L.se_lift))
    (PsiAProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.aProjection w L.s_b_lift))
    L.s_graph_eq

/-- Normal-cover transport reconciles the two scalar branches over the
repeated ambient output `u`. -/
noncomputable def u_branchEquiv [IsAlgClosed K] :
    FiniteCoverBasedBranchEquiv
      (rankTwoParameterField_le_rankTwoScalarField (k := k) D.u L.se_u)
      (rankTwoParameterField_le_rankTwoScalarField (k := k) D.u L.sA_a_u) :=
  rankTwoScalarBasedBranchEquiv
    (PsiCProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.cProjection w L.se_lift))
    (PsiCProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.cProjection w L.sA_a_lift))
    L.u_graph_eq

/-- Normal-cover transport reconciles the two scalar branches over the
repeated ambient left quotient `sA`. -/
noncomputable def sA_branchEquiv [IsAlgClosed K] :
    FiniteCoverBasedBranchEquiv
      (rankTwoParameterField_le_rankTwoScalarField
        (k := k) D.sA L.sA_a_sA)
      (rankTwoParameterField_le_rankTwoScalarField
        (k := k) D.sA L.sA_c_sA) :=
  rankTwoScalarBasedBranchEquiv
    (PsiAProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.aProjection w L.sA_a_lift))
    (PsiAProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.aProjection w L.sA_c_lift))
    L.sA_graph_eq

/-- Normal-cover transport reconciles the two scalar branches over the
repeated ambient output `uB`. -/
noncomputable def uB_branchEquiv [IsAlgClosed K] :
    FiniteCoverBasedBranchEquiv
      (rankTwoParameterField_le_rankTwoScalarField
        (k := k) D.uB L.s_b_uB)
      (rankTwoParameterField_le_rankTwoScalarField
        (k := k) D.uB L.sA_c_uB) :=
  rankTwoScalarBasedBranchEquiv
    (PsiCProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.cProjection w L.s_b_lift))
    (PsiCProjectionRelation.scalar_mem_racl w hψ
      (PsiChunkProjectionRelation.cProjection w L.sA_c_lift))
    L.uB_graph_eq

/-- Each edgewise joint lift restricts to the corresponding scalar
partial-quadrangle multiplication relation. -/
theorem scalar_edge_relations
    {S' T' U' : Point k K}
    (hquad : IsPartialQuadrangle ![w.S, w.T, w.U, S', T', U']) :
    (IsPartialQuadrangle.parameterMultiplication hquad).IsRealization
        L.se_s L.se_e L.se_u ∧
      (IsPartialQuadrangle.parameterMultiplication hquad).IsRealization
        L.sA_a_sA L.sA_a_a L.sA_a_u ∧
      (IsPartialQuadrangle.parameterMultiplication hquad).IsRealization
        L.s_b_s L.s_b_b L.s_b_uB ∧
      (IsPartialQuadrangle.parameterMultiplication hquad).IsRealization
        L.sA_c_sA L.sA_c_c L.sA_c_uB :=
  ⟨PsiChunkProjectionRelation.parameterMultiplication w L.se_lift hquad,
    PsiChunkProjectionRelation.parameterMultiplication w L.sA_a_lift hquad,
    PsiChunkProjectionRelation.parameterMultiplication w L.s_b_lift hquad,
    PsiChunkProjectionRelation.parameterMultiplication w L.sA_c_lift hquad⟩

end PsiChunkFourArrowEdgeLifts

end QWitness

end
end AclGeom
