/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.CompositionIdentity
import AclGeom.Correspondence.CurveEquation

/-!
# Intrinsic coordinates of the Ψ correspondence germ

The rank-two `B` parameter of the selected `Y → Z` correspondence is not
itself an intrinsic coordinate: the same germ may be displayed using many
generic parameter tuples.  The coefficients of its canonical monic curve
equation are intrinsic.  This file proves that their relative algebraic
closure is exactly the rank-two flat `B`.

The proof uses clause `Z_freeB` at the precise point where minimality is
needed.  The canonical equation makes `Z` algebraic over its coefficient
field and `Y`.  If the closed coefficient field were contained in a point
below `B`, that point and `Y` would already define the incidence, contrary
to the clause.  A rank-two flat has no other proper nonzero closed subflat.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

/-- A finite-correspondence germ with a minimal rank-two parameter is
recovered by the relative closure of its intrinsic coefficients. -/
theorem curveCoefficientClosure_eq_rankTwo_of_minimal
    (E : IntermediateField k K) (P : FiniteCorrespondencePair E K)
    (V : ClosedIF k K) (hEV : E ≤ V.1) (hV : RankEq 2 V)
    (hminimal : ∀ Q : Point k K, Q.1 ≤ V →
      P.target ∉ racl k ({Q.rep, P.source} : Set K)) :
    ClosedIF.close k (P.curveCoefficientField k E) = V := by
  have hcloseV : ClosedIF.close k (P.curveCoefficientField k E) ≤ V := by
    rw [ClosedIF.le_iff]
    change racl k
      (((P.curveCoefficientField k E : IntermediateField k K)) : Set K) ≤ V.1
    calc
      racl k (((P.curveCoefficientField k E : IntermediateField k K)) : Set K) ≤
          racl k ((V.1 : IntermediateField k K) : Set K) :=
        racl_mono ((P.curveCoefficientField_le k E).trans hEV)
      _ = V.1 := isRAC_iff_racl_eq.1 V.2
  apply RankEq.eq_of_le_of_not_le_point hcloseV hV
  intro Q hQV hcloseQ
  apply hminimal Q hQV
  have htarget := P.target_mem_racl_curveCoefficientField_source k E
  rw [FiniteCorrespondencePair.curveCoefficientField,
    mem_racl_adjoin_base_iff] at htarget
  refine racl_le_of_subset_racl ?_ htarget
  intro z hz
  rcases hz with hz | hz
  · have hzCoeff : z ∈ P.curveCoefficientField k E :=
      subset_adjoin k _ hz
    have hzClose : z ∈ ClosedIF.close k (P.curveCoefficientField k E) := by
      change z ∈ racl k
        (((P.curveCoefficientField k E : IntermediateField k K)) : Set K)
      exact subset_racl k _ hzCoeff
    have hzQ : z ∈ Q.1 := (ClosedIF.le_iff.1 hcloseQ) hzClose
    have hzPoint : z ∈ ClosedIF.point k Q.rep := by
      rwa [Q.point_rep]
    exact racl_mono (by simp) hzPoint
  · exact subset_racl k _ (Set.mem_insert_of_mem _ hz)

namespace QWitness

variable (w : QWitness k K)

/-- The intrinsic coefficient field of the selected `B`-family
correspondence germ `Y → Z`. -/
def bGermCoefficientField (hψ : w.Psi) : IntermediateField k K :=
  (w.yzCorrespondencePairOverB hψ).curveCoefficientField k w.bField

/-- The relatively closed geometric element generated by the intrinsic
coefficients of the selected `B`-family germ. -/
def bGermCoefficientClosure (hψ : w.Psi) : ClosedIF k K :=
  ClosedIF.close k (w.bGermCoefficientField hψ)

/-- The intrinsic coefficient field lies in the displayed `B` parameter
field. -/
theorem bGermCoefficientField_le_bField (hψ : w.Psi) :
    w.bGermCoefficientField hψ ≤ w.bField :=
  (w.yzCorrespondencePairOverB hψ).curveCoefficientField_le k w.bField

/-- The selected output is algebraic over the intrinsic germ coefficients
and the selected source. -/
theorem Z_rep_mem_racl_bGermCoefficientField_Y (hψ : w.Psi) :
    w.Z.rep ∈ racl (w.bGermCoefficientField hψ) {w.Y.rep} :=
  (w.yzCorrespondencePairOverB hψ).target_mem_racl_curveCoefficientField_source
    k w.bField

/-- The displayed rational function field `k(B₁,B₂)` lies in the closed
rank-two flat `B`. -/
theorem bField_le_B : w.bField ≤ w.B.1 := by
  rw [bField]
  refine adjoin_le_iff.mpr ?_
  rintro x ⟨i, rfl⟩
  have hi : ClosedIF.point k (w.bReps i) ≤ w.B := by
    rw [w.b_eq_iSup_point]
    exact le_iSup (fun j ↦ ClosedIF.point k (w.bReps j)) i
  exact (ClosedIF.point_le_iff.1 hi)

/-- Closing the intrinsic coefficient field stays inside `B`. -/
theorem bGermCoefficientClosure_le_B (hψ : w.Psi) :
    w.bGermCoefficientClosure hψ ≤ w.B := by
  rw [bGermCoefficientClosure, ClosedIF.le_iff]
  change racl k ((w.bGermCoefficientField hψ : IntermediateField k K) : Set K) ≤ w.B.1
  calc
    racl k ((w.bGermCoefficientField hψ : IntermediateField k K) : Set K) ≤
        racl k ((w.B.1 : IntermediateField k K) : Set K) :=
      racl_mono ((w.bGermCoefficientField_le_bField hψ).trans w.bField_le_B)
    _ = w.B.1 := isRAC_iff_racl_eq.1 w.B.2

/-- No point below `B` contains the closed intrinsic coefficient field. -/
theorem bGermCoefficientClosure_not_le_point (hψ : w.Psi)
    (B' : Point k K) (hB' : B'.1 ≤ w.B) :
    ¬ w.bGermCoefficientClosure hψ ≤ B'.1 := by
  intro hclose
  apply w.Z_rep_notMem_racl_atom_Y hψ B' hB'
  have hZ := w.Z_rep_mem_racl_bGermCoefficientField_Y hψ
  rw [bGermCoefficientField,
    FiniteCorrespondencePair.curveCoefficientField,
    mem_racl_adjoin_base_iff] at hZ
  refine racl_le_of_subset_racl ?_ hZ
  intro z hz
  rcases hz with hz | hz
  · have hzCoeff : z ∈ w.bGermCoefficientField hψ := by
      exact subset_adjoin k _ hz
    have hzClose : z ∈ w.bGermCoefficientClosure hψ := by
      change z ∈ racl k
        ((w.bGermCoefficientField hψ : IntermediateField k K) : Set K)
      exact subset_racl k _ hzCoeff
    have hzB' : z ∈ B'.1 := (ClosedIF.le_iff.1 hclose) hzClose
    have hzPoint : z ∈ ClosedIF.point k B'.rep := by
      rwa [B'.point_rep]
    exact racl_mono (by simp) hzPoint
  · exact subset_racl k _ (Set.mem_insert_of_mem _ hz)

/-- The intrinsic coefficients recover the entire rank-two `B` parameter
flat, up to relative algebraic closure.  This is the faithful-coordinate
input for turning the relational four-arrow product into a rational map. -/
theorem bGermCoefficientClosure_eq_B (hψ : w.Psi) :
    w.bGermCoefficientClosure hψ = w.B := by
  have hBrank : RankEq 2 w.B :=
    (rankEq_iSup_point (w.bReps_independent hψ)).congr
      w.b_eq_iSup_point.symm
  exact RankEq.eq_of_le_of_not_le_point
    (w.bGermCoefficientClosure_le_B hψ) hBrank
    (w.bGermCoefficientClosure_not_le_point hψ)

/-- The intrinsic coefficients of the inverse-oriented `A` germ.  The
orientation `Y → X` matches the minimality clause `X_free`. -/
def aInverseGermCoefficientField (hψ : w.Psi) : IntermediateField k K :=
  ((w.xyCorrespondencePairOverA hψ).swap).curveCoefficientField k w.aField

/-- The closed geometric element generated by the inverse-oriented `A`
germ coefficients. -/
def aInverseGermCoefficientClosure (hψ : w.Psi) : ClosedIF k K :=
  ClosedIF.close k (w.aInverseGermCoefficientField hψ)

/-- The displayed field `k(A₁,A₂)` lies in the rank-two flat `A`. -/
theorem aField_le_A : w.aField ≤ w.A.1 := by
  rw [aField]
  refine adjoin_le_iff.mpr ?_
  rintro x ⟨i, rfl⟩
  have hi : ClosedIF.point k (w.aReps i) ≤ w.A := by
    rw [w.a_eq_iSup_point]
    exact le_iSup (fun j ↦ ClosedIF.point k (w.aReps j)) i
  exact ClosedIF.point_le_iff.1 hi

/-- The inverse-germ coefficients recover the entire rank-two `A` flat. -/
theorem aInverseGermCoefficientClosure_eq_A (hψ : w.Psi) :
    w.aInverseGermCoefficientClosure hψ = w.A := by
  have hArank : RankEq 2 w.A :=
    (rankEq_iSup_point (w.aReps_independent hψ)).congr
      w.a_eq_iSup_point.symm
  exact curveCoefficientClosure_eq_rankTwo_of_minimal w.aField
    (w.xyCorrespondencePairOverA hψ).swap w.A w.aField_le_A hArank
    (by
      intro A' hA'
      change w.X.rep ∉ racl k ({A'.rep, w.Y.rep} : Set K)
      exact w.X_rep_notMem_racl_atom_Y hψ A' hA')

/-- The intrinsic coefficient field of the output `C` germ `X → Z`. -/
def cGermCoefficientField (hψ : w.Psi) : IntermediateField k K :=
  (w.xzCorrespondencePairOverC hψ).curveCoefficientField k w.cField

/-- The closed geometric element generated by the output-germ
coefficients. -/
def cGermCoefficientClosure (hψ : w.Psi) : ClosedIF k K :=
  ClosedIF.close k (w.cGermCoefficientField hψ)

/-- The displayed field `k(C₁,C₂)` lies in the rank-two flat `C`. -/
theorem cField_le_C : w.cField ≤ w.C.1 := by
  rw [cField]
  refine adjoin_le_iff.mpr ?_
  rintro x ⟨i, rfl⟩
  have hi : ClosedIF.point k (w.cReps i) ≤ w.C := by
    rw [w.c_eq_iSup_point]
    exact le_iSup (fun j ↦ ClosedIF.point k (w.cReps j)) i
  exact ClosedIF.point_le_iff.1 hi

/-- The output-germ coefficients recover the entire rank-two `C` flat. -/
theorem cGermCoefficientClosure_eq_C (hψ : w.Psi) :
    w.cGermCoefficientClosure hψ = w.C := by
  have hCrank : RankEq 2 w.C :=
    (rankEq_iSup_point (w.cReps_independent hψ)).congr
      w.c_eq_iSup_point.symm
  exact curveCoefficientClosure_eq_rankTwo_of_minimal w.cField
    (w.xzCorrespondencePairOverC hψ) w.C w.cField_le_C hCrank
    (by
      intro C' hC'
      change w.Z.rep ∉ racl k ({C'.rep, w.X.rep} : Set K)
      exact w.Z_rep_notMem_racl_atom_X hψ C' hC')

end QWitness

end

end AclGeom
