/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.ChunkCurveReferenceBridge

/-!
# Coherent finite fields for the four selected curve faces

The left and direct branches of one composition face share more data than
their two separate normalizations remember: over the common source they are
generated by the same middle and target coordinates.  This file packages
that whole-face field for each of the four semantic triangles.

All four fields are finite subextensions of
`selectedSemanticBranchExtension`.  Their maps to `selectedGraphSourceCover`
therefore factor through the one coherent ten-coordinate embedding.  Later
alignment on one of these domains consequently controls its selected left
and direct branches simultaneously.
-/

namespace AclGeom

open IntermediateField

noncomputable section

universe u

namespace FiniteCorrespondencePair.FiniteCoverTriangle

variable {E Ω : Type u} [Field E] [Field Ω] [Algebra E Ω]
  (P Q : FiniteCorrespondencePair E Ω) (h : P.target = Q.source)

/-- The finite field of a complete selected composition face, generated over
the literal source by its middle and target coordinates. -/
def selectedWholeFaceField
    (_h : P.target = Q.source) : IntermediateField (↥P.sourceField) Ω :=
  adjoin (↥P.sourceField) {P.target, Q.target}

/-- The selected left branch is a literal subextension of the whole-face
field. -/
theorem leftBranchOverSource_le_selectedWholeFaceField :
    P.branchOverSource ≤ selectedWholeFaceField P Q h := by
  rw [P.branchOverSource_eq_adjoin_target]
  apply adjoin.mono
  intro z hz
  rw [Set.mem_singleton_iff] at hz
  subst z
  simp

/-- The selected direct branch is a literal subextension of the same
whole-face field. -/
theorem directBranchOverSource_le_selectedWholeFaceField :
    (P.comp Q h).branchOverSource ≤ selectedWholeFaceField P Q h := by
  rw [(P.comp Q h).branchOverSource_eq_adjoin_target]
  apply adjoin.mono
  intro z hz
  rw [Set.mem_singleton_iff] at hz
  subst z
  simp

/-- Literal inclusion of the whole selected left branch in the complete
face field. -/
noncomputable def selectedLeftBranchToWholeFace :
    (↥P.branchOverSource) →ₐ[↥P.sourceField]
      (↥(selectedWholeFaceField P Q h)) :=
  IntermediateField.inclusion
    (leftBranchOverSource_le_selectedWholeFaceField P Q h)

/-- Literal inclusion of the whole selected direct branch in the same
complete face field. -/
noncomputable def selectedDirectBranchToWholeFace :
    (↥(P.comp Q h).branchOverSource) →ₐ[↥P.sourceField]
      (↥(selectedWholeFaceField P Q h)) := by
  let f : (↥(P.comp Q h).branchOverSource) →+*
      (↥(selectedWholeFaceField P Q h)) :=
    { toFun := fun x ↦
        ⟨x, directBranchOverSource_le_selectedWholeFaceField P Q h x.2⟩
      map_one' := by ext; rfl
      map_mul' := by intro x y; ext; rfl
      map_zero' := by ext; rfl
      map_add' := by intro x y; ext; rfl }
  exact { f with
    commutes' := fun x ↦ by
      apply Subtype.ext
      rfl }

end FiniteCorrespondencePair.FiniteCoverTriangle

namespace QWitness.PsiCurveFourArrowCommonSourceRealizations

variable {k K : Type u} [Field k] [Field K] [Algebra k K]
  {w : QWitness k K} {hψ : w.Psi}
  {s a b e : Fin 2 → K}
  {D : w.PsiParameterFourArrowDifferenceDiagram hψ s a b e}
  (R : w.PsiCurveFourArrowCommonSourceRealizations hψ D)
  (L : w.PsiChunkFourArrowEdgeLifts hψ D)

private abbrev selectedWholeFaceBaseType :=
  ↥(PsiCurveCompositionBaseChangeRealization.CommonBaseData.aCorrespondencePair
    (R := R.se) R.seCommonBaseData hψ).sourceField

/-! ### The four finite whole-face fields -/

/-- The common source together with the middle and target of the `e` face. -/
def seSelectedWholeFaceExtension
    (_L : w.PsiChunkFourArrowEdgeLifts hψ D) :
    IntermediateField (selectedWholeFaceBaseType R) (CommonCurveAmbient K) :=
  adjoin (selectedWholeFaceBaseType R) {R.se.middle, R.se.target}

/-- The common source together with the middle and target of the `a` face. -/
def sAaSelectedWholeFaceExtension
    (_L : w.PsiChunkFourArrowEdgeLifts hψ D) :
    IntermediateField (selectedWholeFaceBaseType R) (CommonCurveAmbient K) :=
  adjoin (selectedWholeFaceBaseType R) {R.sAa.middle, R.sAa.target}

/-- The common source together with the middle and target of the `b` face. -/
def sbSelectedWholeFaceExtension
    (_L : w.PsiChunkFourArrowEdgeLifts hψ D) :
    IntermediateField (selectedWholeFaceBaseType R) (CommonCurveAmbient K) :=
  adjoin (selectedWholeFaceBaseType R) {R.sb.middle, R.sb.target}

/-- The `c` face field also retains the two genuinely algebraic output
parameters.  They are needed for its whole intrinsic coefficient
restriction and are not silently placed in the original common source. -/
def sAcSelectedWholeFaceExtension
    (_L : w.PsiChunkFourArrowEdgeLifts hψ D) :
    IntermediateField (selectedWholeFaceBaseType R) (CommonCurveAmbient K) :=
  adjoin (selectedWholeFaceBaseType R)
    {commonCurveEmbedding (k := k) (K := K) (D.c 0),
      commonCurveEmbedding (k := k) (K := K) (D.c 1),
      R.sAc.middle, R.sAc.target}

/-! ### Literal containment in the coherent ten-coordinate extension -/

/-- The whole `e` face lies in the common selected semantic extension. -/
theorem seSelectedWholeFaceExtension_le_selectedSemanticBranchExtension :
    R.seSelectedWholeFaceExtension L ≤ R.selectedSemanticBranchExtension L := by
  apply adjoin_le_iff.2
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl
  · exact subset_adjoin _ _ ⟨2, rfl⟩
  · exact subset_adjoin _ _ ⟨3, rfl⟩

/-- The whole `a` face lies in the same selected semantic extension. -/
theorem sAaSelectedWholeFaceExtension_le_selectedSemanticBranchExtension :
    R.sAaSelectedWholeFaceExtension L ≤
      R.selectedSemanticBranchExtension L := by
  apply adjoin_le_iff.2
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl
  · exact subset_adjoin _ _ ⟨4, rfl⟩
  · exact subset_adjoin _ _ ⟨5, rfl⟩

/-- The whole `b` face lies in the same selected semantic extension. -/
theorem sbSelectedWholeFaceExtension_le_selectedSemanticBranchExtension :
    R.sbSelectedWholeFaceExtension L ≤ R.selectedSemanticBranchExtension L := by
  apply adjoin_le_iff.2
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl
  · exact subset_adjoin _ _ ⟨6, rfl⟩
  · exact subset_adjoin _ _ ⟨7, rfl⟩

/-- The whole algebraic-output `c` face, including both parameter
coordinates, lies in the same selected semantic extension. -/
theorem sAcSelectedWholeFaceExtension_le_selectedSemanticBranchExtension :
    R.sAcSelectedWholeFaceExtension L ≤
      R.selectedSemanticBranchExtension L := by
  apply adjoin_le_iff.2
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl | rfl | rfl
  · exact subset_adjoin _ _ ⟨0, rfl⟩
  · exact subset_adjoin _ _ ⟨1, rfl⟩
  · exact subset_adjoin _ _ ⟨8, rfl⟩
  · exact subset_adjoin _ _ ⟨9, rfl⟩

/-! ### Finiteness -/

private theorem finiteDimensional_of_le_selectedSemanticBranchExtension
    (F : IntermediateField (selectedWholeFaceBaseType R)
      (CommonCurveAmbient K))
    (hF : F ≤ R.selectedSemanticBranchExtension L) :
    FiniteDimensional (selectedWholeFaceBaseType R) (↥F) := by
  letI : FiniteDimensional (selectedWholeFaceBaseType R)
      (↥(R.selectedSemanticBranchExtension L)) :=
    R.selectedSemanticBranchExtension_finiteDimensional L
  exact FiniteDimensional.of_injective
    (IntermediateField.inclusion hF).toLinearMap
    (IntermediateField.inclusion hF).injective

/-- The selected `e` whole-face field is finite over the common source. -/
theorem seSelectedWholeFaceExtension_finiteDimensional :
    FiniteDimensional (selectedWholeFaceBaseType R)
      (↥(R.seSelectedWholeFaceExtension L)) :=
  finiteDimensional_of_le_selectedSemanticBranchExtension R L
    (R.seSelectedWholeFaceExtension L)
    (R.seSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L)

/-- The selected `a` whole-face field is finite over the common source. -/
theorem sAaSelectedWholeFaceExtension_finiteDimensional :
    FiniteDimensional (selectedWholeFaceBaseType R)
      (↥(R.sAaSelectedWholeFaceExtension L)) :=
  finiteDimensional_of_le_selectedSemanticBranchExtension R L
    (R.sAaSelectedWholeFaceExtension L)
    (R.sAaSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L)

/-- The selected `b` whole-face field is finite over the common source. -/
theorem sbSelectedWholeFaceExtension_finiteDimensional :
    FiniteDimensional (selectedWholeFaceBaseType R)
      (↥(R.sbSelectedWholeFaceExtension L)) :=
  finiteDimensional_of_le_selectedSemanticBranchExtension R L
    (R.sbSelectedWholeFaceExtension L)
    (R.sbSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L)

/-- The selected algebraic-output `c` whole-face field is finite over the
common source. -/
theorem sAcSelectedWholeFaceExtension_finiteDimensional :
    FiniteDimensional (selectedWholeFaceBaseType R)
      (↥(R.sAcSelectedWholeFaceExtension L)) :=
  finiteDimensional_of_le_selectedSemanticBranchExtension R L
    (R.sAcSelectedWholeFaceExtension L)
    (R.sAcSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L)

/-! ### Coherent embeddings in the selected graph source -/

/-- The selected `e` whole face uses the restriction of the single coherent
semantic-extension embedding. -/
noncomputable def seSelectedWholeFaceToSelectedGraphSource
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (↥(R.seSelectedWholeFaceExtension L)) →ₐ[selectedWholeFaceBaseType R]
      (↥(R.selectedGraphSourceCover L hind).field) :=
  (R.selectedSemanticBranchExtensionToSelectedGraphSource L hind).comp
    (IntermediateField.inclusion
      (R.seSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L))

/-- The selected `a` whole face is a restriction of the same coherent map. -/
noncomputable def sAaSelectedWholeFaceToSelectedGraphSource
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (↥(R.sAaSelectedWholeFaceExtension L)) →ₐ[selectedWholeFaceBaseType R]
      (↥(R.selectedGraphSourceCover L hind).field) :=
  (R.selectedSemanticBranchExtensionToSelectedGraphSource L hind).comp
    (IntermediateField.inclusion
      (R.sAaSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L))

/-- The selected `b` whole face is a restriction of the same coherent map. -/
noncomputable def sbSelectedWholeFaceToSelectedGraphSource
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (↥(R.sbSelectedWholeFaceExtension L)) →ₐ[selectedWholeFaceBaseType R]
      (↥(R.selectedGraphSourceCover L hind).field) :=
  (R.selectedSemanticBranchExtensionToSelectedGraphSource L hind).comp
    (IntermediateField.inclusion
      (R.sbSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L))

/-- The selected `c` whole face, including its algebraic parameter field, is
a restriction of the same coherent map. -/
noncomputable def sAcSelectedWholeFaceToSelectedGraphSource
    (hind : AlgebraicIndependent k (rankTwoFourTuple s e a b)) :
    (↥(R.sAcSelectedWholeFaceExtension L)) →ₐ[selectedWholeFaceBaseType R]
      (↥(R.selectedGraphSourceCover L hind).field) :=
  (R.selectedSemanticBranchExtensionToSelectedGraphSource L hind).comp
    (IntermediateField.inclusion
      (R.sAcSelectedWholeFaceExtension_le_selectedSemanticBranchExtension L))

end QWitness.PsiCurveFourArrowCommonSourceRealizations

end

end AclGeom
