/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.Psi
import AclGeom.Correspondence.Composition

/-!
# The selected-component core of the Ψ composition identity

Blueprint equation (8.6) composes the finite correspondence from `Y` to
`X`, parametrized by `A`, with the correspondence from `Y` to `Z`,
parametrized by `B`.  Its first indispensable input is that
`(A₁,A₂,B₁,B₂,Y,X,Z)` is the selected generic point of a rank-five fiber
product.

This module derives that statement directly from the clauses of `Psi`:

* the reverse finite-rank bridge turns `rank_AB` into algebraic
  independence of the four chosen representatives of `A` and `B`;
* `Y_notLe` makes `Y` generic over those four parameters;
* `X_le` and the first projection of `Z_le` make `X` and `Z` algebraic over
  the five generators;
* the second projection of `Z_le` presents `(X,Z)` as the family member
  parametrized by `C`;
* after adjoining all six parameters, the literal pair `(X,Z)` selects a
  common prime component over both the composite `A,B` branch and the
  `C`-parametrized branch.

Together, the rank-five calculation and common-cover prime-ideal theorem are
the selected-component assertion in blueprint (8.6).  Finite base change is
handled honestly: extended ideals are only contained in the selected prime,
since other branches may split off.

**Status:** complete selected-component input for M4a / blueprint (8.6);
global parameter-family and group-chunk assembly remains in progress.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

namespace QWitness

variable (w : QWitness k K)

/-- The four representatives of the two rank-two parameter fields `A` and
`B`, in the order used by the fiber-product count. -/
def abReps : Fin 4 → K :=
  ![w.A₁.rep, w.A₂.rep, w.B₁.rep, w.B₂.rep]

/-- The join `A ∨ B` is generated by the four chosen representatives. -/
theorem ab_join_eq_iSup_point :
    w.A ⊔ w.B = ⨆ i, ClosedIF.point k (w.abReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le ?_ ?_) (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [abReps])
    · exact le_iSup_of_le 1 (by simp [abReps])
    · exact le_iSup_of_le 2 (by simp [abReps])
    · exact le_iSup_of_le 3 (by simp [abReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [abReps, A, B] using
        (le_sup_left.trans le_sup_left :
          w.A₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_right.trans le_sup_left :
          w.A₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_left.trans le_sup_right :
          w.B₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_right.trans le_sup_right :
          w.B₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))

/-- Clause `rank_AB` forces the displayed representatives of `A` and `B`
to be algebraically independent. -/
theorem abReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.abReps := by
  apply algebraicIndependent_of_rankEq_iSup_point
  rw [← w.ab_join_eq_iSup_point]
  exact hψ.rank_AB

/-- The four representatives of `A` and `C`. -/
def acReps : Fin 4 → K :=
  ![w.A₁.rep, w.A₂.rep, w.C₁.rep, w.C₂.rep]

/-- The join `A ∨ C` is generated by `acReps`. -/
theorem ac_join_eq_iSup_point :
    w.A ⊔ w.C = ⨆ i, ClosedIF.point k (w.acReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le ?_ ?_) (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [acReps])
    · exact le_iSup_of_le 1 (by simp [acReps])
    · exact le_iSup_of_le 2 (by simp [acReps])
    · exact le_iSup_of_le 3 (by simp [acReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [acReps, A, C] using
        (le_sup_left.trans le_sup_left :
          w.A₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [acReps, A, C] using
        (le_sup_right.trans le_sup_left :
          w.A₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [acReps, A, C] using
        (le_sup_left.trans le_sup_right :
          w.C₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [acReps, A, C] using
        (le_sup_right.trans le_sup_right :
          w.C₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))

/-- Clause `rank_AC` makes the displayed `A,C` representatives
independent. -/
theorem acReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.acReps := by
  apply algebraicIndependent_of_rankEq_iSup_point
  rw [← w.ac_join_eq_iSup_point]
  exact hψ.rank_AC

/-- The two representatives of the output parameter `C`. -/
def cReps : Fin 2 → K := ![w.C₁.rep, w.C₂.rep]

/-- The join `C` is generated by `cReps`. -/
theorem c_eq_iSup_point :
    w.C = ⨆ i, ClosedIF.point k (w.cReps i) := by
  apply le_antisymm
  · refine sup_le ?_ ?_
    · exact le_iSup_of_le 0 (by simp [cReps])
    · exact le_iSup_of_le 1 (by simp [cReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i <;> simp [cReps, C]

/-- The `C` parameter has rank two. -/
theorem cReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.cReps := by
  have h := AlgebraicIndependent.comp_pair
    (w.acReps_independent hψ) (i := (2 : Fin 4)) (j := (3 : Fin 4))
    (by decide)
  simpa [acReps, cReps] using h

/-- The six displayed representatives of `A,B,C`. -/
def abcReps : Fin 6 → K :=
  ![w.A₁.rep, w.A₂.rep, w.B₁.rep, w.B₂.rep,
    w.C₁.rep, w.C₂.rep]

/-- The total parameter join is generated by `abcReps`. -/
theorem abc_join_eq_iSup_point :
    w.A ⊔ w.B ⊔ w.C = ⨆ i, ClosedIF.point k (w.abcReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le (sup_le ?_ ?_) (sup_le ?_ ?_))
      (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [abcReps])
    · exact le_iSup_of_le 1 (by simp [abcReps])
    · exact le_iSup_of_le 2 (by simp [abcReps])
    · exact le_iSup_of_le 3 (by simp [abcReps])
    · exact le_iSup_of_le 4 (by simp [abcReps])
    · exact le_iSup_of_le 5 (by simp [abcReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [abcReps, A, B, C] using
        (le_sup_left.trans le_sup_left |>.trans le_sup_left :
          w.A₁.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_right.trans le_sup_left |>.trans le_sup_left :
          w.A₂.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_left.trans le_sup_right |>.trans le_sup_left :
          w.B₁.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_right.trans le_sup_right |>.trans le_sup_left :
          w.B₂.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_left.trans le_sup_right :
          w.C₁.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_right.trans le_sup_right :
          w.C₂.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))

/-- The rank-four `A,B` flat already contains `C`. -/
theorem ab_eq_abc (hψ : w.Psi) :
    w.A ⊔ w.B = w.A ⊔ w.B ⊔ w.C :=
  RankEq.eq_of_le le_sup_left hψ.rank_AB hψ.rank_ABC

/-- The `A,B` representatives occur among `abcReps`. -/
theorem abReps_range_subset_abcReps :
    Set.range w.abReps ⊆ Set.range w.abcReps := by
  rintro _ ⟨i, rfl⟩
  fin_cases i <;> simp [abReps, abcReps]

/-- The `C` representatives occur among `abcReps`. -/
theorem cReps_range_subset_abcReps :
    Set.range w.cReps ⊆ Set.range w.abcReps := by
  rintro _ ⟨i, rfl⟩
  fin_cases i <;> simp [cReps, abcReps]

/-- Clause `Y_notLe` says that `Y` is generic over the four `A,B`
parameters. -/
theorem Y_rep_notMem_racl_abReps (hψ : w.Psi) :
    w.Y.rep ∉ racl k (Set.range w.abReps) := by
  intro hY
  apply hψ.Y_notLe
  have hpoint : w.Y.1 ≤ ⨆ i, ClosedIF.point k (w.abReps i) := by
    rw [← w.Y.point_rep]
    exact ClosedIF.point_le_iff.2
      (mem_iSup_point_iff.2 hY)
  rw [← w.ab_join_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_left

/-- `X_notLe` also makes `X` generic over the combined `A,B` parameter
field. -/
theorem X_rep_notMem_racl_abReps (hψ : w.Psi) :
    w.X.rep ∉ racl k (Set.range w.abReps) := by
  intro hX
  apply hψ.X_notLe
  have hpoint : w.X.1 ≤ ⨆ i, ClosedIF.point k (w.abReps i) := by
    rw [← w.X.point_rep]
    exact ClosedIF.point_le_iff.2
      (mem_iSup_point_iff.2 hX)
  rw [← w.ab_join_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_left

/-- `Z_notLe` makes `Z` generic over the combined `A,B` parameter
field. -/
theorem Z_rep_notMem_racl_abReps (hψ : w.Psi) :
    w.Z.rep ∉ racl k (Set.range w.abReps) := by
  intro hZ
  apply hψ.Z_notLe
  have hpoint : w.Z.1 ≤ ⨆ i, ClosedIF.point k (w.abReps i) := by
    rw [← w.Z.point_rep]
    exact ClosedIF.point_le_iff.2
      (mem_iSup_point_iff.2 hZ)
  rw [← w.ab_join_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_left

/-- The incidence `X ≤ A ∨ Y` makes `X` algebraic over
`(A₁,A₂,B₁,B₂,Y)` (the unused `B` parameters are harmless). -/
theorem X_rep_mem_racl_abReps_snoc_Y (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 5, ClosedIF.point k
      ((Fin.snoc (w.abReps : Fin 4 → K) w.Y.rep : Fin 5 → K) i)
  have hA₁ : w.A₁.1 ≤ E :=
    le_iSup_of_le 0 (by simp [abReps])
  have hA₂ : w.A₂.1 ≤ E :=
    le_iSup_of_le 1 (by simp [abReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 4) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hX : w.X.1 ≤ E :=
    hψ.X_le.trans (sup_le (sup_le hA₁ hA₂) hY)
  exact mem_iSup_point_iff.1 (hX w.X.mem_rep)

/-- The first projection of `Z_le` makes `Z` algebraic over
`(A₁,A₂,B₁,B₂,Y)`. -/
theorem Z_rep_mem_racl_abReps_snoc_Y (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 5, ClosedIF.point k
      ((Fin.snoc (w.abReps : Fin 4 → K) w.Y.rep : Fin 5 → K) i)
  have hB₁ : w.B₁.1 ≤ E :=
    le_iSup_of_le 2 (by simp [abReps])
  have hB₂ : w.B₂.1 ≤ E :=
    le_iSup_of_le 3 (by simp [abReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 4) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hZ : w.Z.1 ≤ E :=
    hψ.Z_le.trans inf_le_left |>.trans
      (sup_le (sup_le hB₁ hB₂) hY)
  exact mem_iSup_point_iff.1 (hZ w.Z.mem_rep)

/-- Exchange reverses the `A`-incidence: over the combined parameter
field, `Y` is algebraic over `X`. -/
theorem Y_rep_mem_racl_abReps_snoc_X (hψ : w.Psi) :
    w.Y.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.X.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_abReps_snoc_Y hψ
  · exact w.X_rep_notMem_racl_abReps hψ

/-- Exchange reverses the `B`-incidence: over the combined parameter
field, `Y` is algebraic over `Z`. -/
theorem Y_rep_mem_racl_abReps_snoc_Z (hψ : w.Psi) :
    w.Y.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Z.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_abReps_snoc_Y hψ
  · exact w.Z_rep_notMem_racl_abReps hψ

/-- `X` is generic over the output parameter `C`. -/
theorem X_rep_notMem_racl_cReps (hψ : w.Psi) :
    w.X.rep ∉ racl k (Set.range w.cReps) := by
  intro hX
  apply hψ.X_notLe
  have hpoint : w.X.1 ≤ ⨆ i, ClosedIF.point k (w.cReps i) := by
    rw [← w.X.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hX)
  rw [← w.c_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_right

/-- `Z` is generic over the output parameter `C`. -/
theorem Z_rep_notMem_racl_cReps (hψ : w.Psi) :
    w.Z.rep ∉ racl k (Set.range w.cReps) := by
  intro hZ
  apply hψ.Z_notLe
  have hpoint : w.Z.1 ≤ ⨆ i, ClosedIF.point k (w.cReps i) := by
    rw [← w.Z.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hZ)
  rw [← w.c_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_right

/-- The second projection of `Z_le` makes `Z` algebraic over the output
parameter `C` and `X`. -/
theorem Z_rep_mem_racl_cReps_snoc_X (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.cReps w.X.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 3, ClosedIF.point k
      ((Fin.snoc (w.cReps : Fin 2 → K) w.X.rep : Fin 3 → K) i)
  have hC₁ : w.C₁.1 ≤ E :=
    le_iSup_of_le 0 (by simp [cReps])
  have hC₂ : w.C₂.1 ≤ E :=
    le_iSup_of_le 1 (by simp [cReps])
  have hX : w.X.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 2) ?_
    rw [Fin.snoc_last, w.X.point_rep]
  have hZ : w.Z.1 ≤ E :=
    hψ.Z_le.trans inf_le_right |>.trans
      (sup_le (sup_le hC₁ hC₂) hX)
  exact mem_iSup_point_iff.1 (hZ w.Z.mem_rep)

/-- Exchange reverses the `C`-incidence. -/
theorem X_rep_mem_racl_cReps_snoc_Z (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.cReps w.Z.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_cReps_snoc_X hψ
  · exact w.Z_rep_notMem_racl_cReps hψ

/-- `X` is generic over all six displayed parameters. -/
theorem X_rep_notMem_racl_abcReps (hψ : w.Psi) :
    w.X.rep ∉ racl k (Set.range w.abcReps) := by
  intro hX
  apply hψ.X_notLe
  have hpoint : w.X.1 ≤ ⨆ i, ClosedIF.point k (w.abcReps i) := by
    rw [← w.X.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hX)
  rwa [← w.abc_join_eq_iSup_point] at hpoint

/-- `Z` is generic over all six displayed parameters. -/
theorem Z_rep_notMem_racl_abcReps (hψ : w.Psi) :
    w.Z.rep ∉ racl k (Set.range w.abcReps) := by
  intro hZ
  apply hψ.Z_notLe
  have hpoint : w.Z.1 ≤ ⨆ i, ClosedIF.point k (w.abcReps i) := by
    rw [← w.Z.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hZ)
  rwa [← w.abc_join_eq_iSup_point] at hpoint

/-- The `C`-incidence remains algebraic after adjoining the unused
`A,B` parameters. -/
theorem Z_rep_mem_racl_abcReps_snoc_X (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.abcReps w.X.rep)) := by
  refine racl_mono ?_ (w.Z_rep_mem_racl_cReps_snoc_X hψ)
  rw [Fin.range_snoc, Fin.range_snoc]
  exact Set.union_subset_union Set.Subset.rfl w.cReps_range_subset_abcReps

/-- The reverse `C`-incidence remains algebraic after adjoining `A,B`. -/
theorem X_rep_mem_racl_abcReps_snoc_Z (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.abcReps w.Z.rep)) := by
  refine racl_mono ?_ (w.X_rep_mem_racl_cReps_snoc_Z hψ)
  rw [Fin.range_snoc, Fin.range_snoc]
  exact Set.union_subset_union Set.Subset.rfl w.cReps_range_subset_abcReps

/-- The combined field of the independent `A,B` parameters. -/
def abField : IntermediateField k K :=
  adjoin k (Set.range w.abReps)

/-- The coefficient field generated by the output parameter `C`. -/
def cField : IntermediateField k K :=
  adjoin k (Set.range w.cReps)

/-- A common finite-cover coefficient field containing all displayed
parameters. -/
def abcField : IntermediateField k K :=
  adjoin k (Set.range w.abcReps)

/-- The `A,B` coefficient field embeds in the common coefficient field. -/
theorem abField_le_abcField : w.abField ≤ w.abcField :=
  adjoin.mono k _ _ w.abReps_range_subset_abcReps

/-- The `C` coefficient field embeds in the common coefficient field. -/
theorem cField_le_abcField : w.cField ≤ w.abcField :=
  adjoin.mono k _ _ w.cReps_range_subset_abcReps

/-- The selected `X → Y` correspondence branch over the combined
parameter field.  Both directions of interalgebraicity are consequences of
`X_le`, genericity, and exchange. -/
def xyCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abField) K where
  source := w.X.rep
  target := w.Y.rep
  source_generic := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.X_rep_notMem_racl_abReps hψ
  target_mem_source := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_abReps_snoc_X hψ
  source_mem_target := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_abReps_snoc_Y hψ

/-- The selected `Y → Z` correspondence branch over the combined
parameter field. -/
def yzCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abField) K where
  source := w.Y.rep
  target := w.Z.rep
  source_generic := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.Y_rep_notMem_racl_abReps hψ
  target_mem_source := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_abReps_snoc_Y hψ
  source_mem_target := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_abReps_snoc_Z hψ

/-- The endpoint branch selected by composing the actual `X → Y` and
`Y → Z` generic pairs from a `Psi` witness. -/
def xzCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abField) K :=
  (w.xyCorrespondencePair hψ).comp (w.yzCorrespondencePair hψ) rfl

/-- The output family member parametrized by `C`, presented by its actual
generic pair `(X,Z)`. -/
def xzCorrespondencePairOverC (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.cField) K where
  source := w.X.rep
  target := w.Z.rep
  source_generic := by
    rw [cField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.X_rep_notMem_racl_cReps hψ
  target_mem_source := by
    rw [cField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_cReps_snoc_X hψ
  source_mem_target := by
    rw [cField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_cReps_snoc_Z hψ

/-- The common-cover presentation of the endpoint pair `(X,Z)`.  This is
the prime component selected by the given generic tuple after adjoining
all parameters. -/
def xzCorrespondencePairOverABC (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abcField) K where
  source := w.X.rep
  target := w.Z.rep
  source_generic := by
    rw [abcField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.X_rep_notMem_racl_abcReps hψ
  target_mem_source := by
    rw [abcField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_abcReps_snoc_X hψ
  source_mem_target := by
    rw [abcField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_abcReps_snoc_Z hψ

/-- The selected endpoint prime on the common parameter cover. -/
def psiSelectedComponentIdeal (hψ : w.Psi) :
    Ideal (MvPolynomial (Fin 2) (↥w.abcField)) :=
  (w.xzCorrespondencePairOverABC hψ).ideal

/-- The common-cover endpoint is a prime component. -/
theorem psiSelectedComponentIdeal_isPrime (hψ : w.Psi) :
    (w.psiSelectedComponentIdeal hψ).IsPrime := by
  apply idealOf_isPrime

/-- The selected endpoint component lies over the base change of the
composite `A,B` branch. -/
theorem abComposite_map_le_selectedComponent (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.abField_le_abcField))
        (w.xzCorrespondencePair hψ).ideal ≤
      w.psiSelectedComponentIdeal hψ := by
  change Ideal.map
      (MvPolynomial.map
        (IntermediateField.inclusion w.abField_le_abcField))
      (idealOf (↥w.abField) ![w.X.rep, w.Z.rep]) ≤
    idealOf (↥w.abcField) ![w.X.rep, w.Z.rep]
  exact idealOf_map_le_of_intermediateField_le
    w.abField_le_abcField ![w.X.rep, w.Z.rep]

/-- The same selected endpoint component lies over the base change of the
`C`-parametrized family member. -/
theorem cFamily_map_le_selectedComponent (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.cField_le_abcField))
        (w.xzCorrespondencePairOverC hψ).ideal ≤
      w.psiSelectedComponentIdeal hψ := by
  change Ideal.map
      (MvPolynomial.map
        (IntermediateField.inclusion w.cField_le_abcField))
      (idealOf (↥w.cField) ![w.X.rep, w.Z.rep]) ≤
    idealOf (↥w.abcField) ![w.X.rep, w.Z.rep]
  exact idealOf_map_le_of_intermediateField_le
    w.cField_le_abcField ![w.X.rep, w.Z.rep]

/-- **Prime-ideal form of blueprint (8.6).**  On the common finite cover,
the endpoint selected by composing the `A` and `B` incidence branches and
the family member parametrized by `C` have the same selected prime
component: the vanishing ideal of the literal generic pair `(X,Z)`.

The two inclusions deliberately retain the selected-component semantics of
finite base change; the extended ideals may have other prime branches. -/
theorem psi_composition_selected_component (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.abField_le_abcField))
        (w.xzCorrespondencePair hψ).ideal ≤
        w.psiSelectedComponentIdeal hψ ∧
      Ideal.map
          (MvPolynomial.map
            (IntermediateField.inclusion w.cField_le_abcField))
          (w.xzCorrespondencePairOverC hψ).ideal ≤
        w.psiSelectedComponentIdeal hψ :=
  ⟨w.abComposite_map_le_selectedComponent hψ,
    w.cFamily_map_le_selectedComponent hψ⟩

@[simp] theorem xzCorrespondencePair_source (hψ : w.Psi) :
    (w.xzCorrespondencePair hψ).source = w.X.rep := rfl

@[simp] theorem xzCorrespondencePair_target (hψ : w.Psi) :
    (w.xzCorrespondencePair hψ).target = w.Z.rep := rfl

/-- **Selected-component interface for blueprint (8.6).**  The two
finite-correspondence germs obtained from the actual `Psi` incidences
compose at their literal shared representative `Y`; the selected component
is the endpoint germ presented by `(X,Z)`. -/
theorem psi_selected_correspondence_composes (hψ : w.Psi) :
    FiniteCorrespondenceGerm.Composes
      (FiniteCorrespondenceGerm.ofPair (w.xyCorrespondencePair hψ))
      (FiniteCorrespondenceGerm.ofPair (w.yzCorrespondencePair hψ))
      (FiniteCorrespondenceGerm.ofPair (w.xzCorrespondencePair hψ)) :=
  FiniteCorrespondenceGerm.composes_of_shared_middle
    (w.xyCorrespondencePair hψ) (w.yzCorrespondencePair hψ) rfl

/-- **The rank-five fiber-product calculation for a `Psi` witness.**
The five-tuple `(A₁,A₂,B₁,B₂,Y)` is algebraically independent, and
adjoining the selected outputs `X,Z` does not enlarge its relative
algebraic closure.  This is the dimension assertion in blueprint (8.6),
now obtained from the actual configuration clauses. -/
theorem psi_fiber_product_rank_count (hψ : w.Psi) :
    AlgebraicIndependent k (Fin.snoc w.abReps w.Y.rep) ∧
      racl k (Set.range
        (Fin.snoc
          (Fin.snoc (Fin.snoc w.abReps w.Y.rep) w.X.rep)
          w.Z.rep)) =
        racl k (Set.range (Fin.snoc w.abReps w.Y.rep)) :=
  fiber_product_rank_count
    (w.abReps_independent hψ)
    (w.Y_rep_notMem_racl_abReps hψ)
    (w.X_rep_mem_racl_abReps_snoc_Y hψ)
    (w.Z_rep_mem_racl_abReps_snoc_Y hψ)

end QWitness

end

end AclGeom
