/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.Psi
import AclGeom.Correspondence.RankTwoMultiplication
import AclGeom.Correspondence.FamilyGroupoid
import AclGeom.Correspondence.PartialQuadrangle

/-!
# The selected-component core of the Ψ composition identity

Blueprint equation (8.6) composes the finite correspondence from `Y` to
`X`, parametrized by `A`, with the correspondence from `Y` to `Z`,
parametrized by `B`.  Its first indispensable input is that
`(A₁,A₂,B₁,B₂,Y,X,Z)` is the selected generic point of a rank-five fiber
product.

This module derives that statement directly from the clauses of `Psi`:

* the reverse finite-rank bridge turns `rank_AB` into algebraic
  independence of the four chosen representatives of `A` and `B`;
* `Y_notLe` makes `Y` generic over those four parameters;
* `X_le` and the first projection of `Z_le` make `X` and `Z` algebraic over
  the five generators;
* the second projection of `Z_le` presents `(X,Z)` as the family member
  parametrized by `C`;
* after adjoining all six parameters, the literal pair `(X,Z)` selects a
  common prime component over both the composite `A,B` branch and the
  `C`-parametrized branch.

Together, the rank-five calculation and common-cover prime-ideal theorem are
the selected-component assertion in blueprint (8.6).  Finite base change is
handled honestly: extended ideals are only contained in the selected prime,
since other branches may split off.

**Status:** complete selected-component input for M4a / blueprint (8.6);
global parameter-family and group-chunk assembly remains in progress.
-/

namespace AclGeom

open IntermediateField
open CategoryTheory

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

namespace QWitness

variable (w : QWitness k K)

/-- Elementwise algebraicity of one point representative over two others
is the corresponding lattice incidence. -/
theorem point_le_sup_of_rep_mem_racl_pair
    (P Q R : Point k K)
    (h : P.rep ∈ racl k ({Q.rep, R.rep} : Set K)) :
    P.1 ≤ Q.1 ⊔ R.1 := by
  rw [← P.point_rep]
  apply ClosedIF.point_le_iff.2
  rw [← Q.point_rep, ← R.point_rep]
  change P.rep ∈
    ((ClosedIF.point k Q.rep ⊔ ClosedIF.point k R.rep).1 :
      IntermediateField k K)
  rw [coe_sup_point₂]
  exact h

/-- The four representatives of the two rank-two parameter fields `A` and
`B`, in the order used by the fiber-product count. -/
def abReps : Fin 4 → K :=
  ![w.A₁.rep, w.A₂.rep, w.B₁.rep, w.B₂.rep]

/-- The two representatives of the `A` parameter. -/
def aReps : Fin 2 → K := ![w.A₁.rep, w.A₂.rep]

/-- The two representatives of the `B` parameter. -/
def bReps : Fin 2 → K := ![w.B₁.rep, w.B₂.rep]

/-- The join `A` is generated by `aReps`. -/
theorem a_eq_iSup_point :
    w.A = ⨆ i, ClosedIF.point k (w.aReps i) := by
  rw [A, ← w.A₁.point_rep, ← w.A₂.point_rep,
    sup_eq_iSup_two]
  congr
  funext i
  fin_cases i <;> rfl

/-- The join `B` is generated by `bReps`. -/
theorem b_eq_iSup_point :
    w.B = ⨆ i, ClosedIF.point k (w.bReps i) := by
  rw [B, ← w.B₁.point_rep, ← w.B₂.point_rep,
    sup_eq_iSup_two]
  congr
  funext i
  fin_cases i <;> rfl

/-- The join `A ∨ B` is generated by the four chosen representatives. -/
theorem ab_join_eq_iSup_point :
    w.A ⊔ w.B = ⨆ i, ClosedIF.point k (w.abReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le ?_ ?_) (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [abReps])
    · exact le_iSup_of_le 1 (by simp [abReps])
    · exact le_iSup_of_le 2 (by simp [abReps])
    · exact le_iSup_of_le 3 (by simp [abReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [abReps, A, B] using
        (le_sup_left.trans le_sup_left :
          w.A₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_right.trans le_sup_left :
          w.A₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_left.trans le_sup_right :
          w.B₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_right.trans le_sup_right :
          w.B₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))

/-- Clause `rank_AB` forces the displayed representatives of `A` and `B`
to be algebraically independent. -/
theorem abReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.abReps := by
  apply algebraicIndependent_of_rankEq_iSup_point
  rw [← w.ab_join_eq_iSup_point]
  exact hψ.rank_AB

/-- The `A` parameter has rank two. -/
theorem aReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.aReps := by
  have h := AlgebraicIndependent.comp_pair
    (w.abReps_independent hψ) (i := (0 : Fin 4)) (j := (1 : Fin 4))
    (by decide)
  simpa [abReps, aReps] using h

/-- The `B` parameter has rank two. -/
theorem bReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.bReps := by
  have h := AlgebraicIndependent.comp_pair
    (w.abReps_independent hψ) (i := (2 : Fin 4)) (j := (3 : Fin 4))
    (by decide)
  simpa [abReps, bReps] using h

/-- The four representatives of `A` and `C`. -/
def acReps : Fin 4 → K :=
  ![w.A₁.rep, w.A₂.rep, w.C₁.rep, w.C₂.rep]

/-- The four representatives of `B` and `C`. -/
def bcReps : Fin 4 → K :=
  ![w.B₁.rep, w.B₂.rep, w.C₁.rep, w.C₂.rep]

/-- The join `A ∨ C` is generated by `acReps`. -/
theorem ac_join_eq_iSup_point :
    w.A ⊔ w.C = ⨆ i, ClosedIF.point k (w.acReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le ?_ ?_) (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [acReps])
    · exact le_iSup_of_le 1 (by simp [acReps])
    · exact le_iSup_of_le 2 (by simp [acReps])
    · exact le_iSup_of_le 3 (by simp [acReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [acReps, A, C] using
        (le_sup_left.trans le_sup_left :
          w.A₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [acReps, A, C] using
        (le_sup_right.trans le_sup_left :
          w.A₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [acReps, A, C] using
        (le_sup_left.trans le_sup_right :
          w.C₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [acReps, A, C] using
        (le_sup_right.trans le_sup_right :
          w.C₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))

/-- Clause `rank_AC` makes the displayed `A,C` representatives
independent. -/
theorem acReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.acReps := by
  apply algebraicIndependent_of_rankEq_iSup_point
  rw [← w.ac_join_eq_iSup_point]
  exact hψ.rank_AC

/-- The join `B ∨ C` is generated by `bcReps`. -/
theorem bc_join_eq_iSup_point :
    w.B ⊔ w.C = ⨆ i, ClosedIF.point k (w.bcReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le ?_ ?_) (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [bcReps])
    · exact le_iSup_of_le 1 (by simp [bcReps])
    · exact le_iSup_of_le 2 (by simp [bcReps])
    · exact le_iSup_of_le 3 (by simp [bcReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [bcReps, B, C] using
        (le_sup_left.trans le_sup_left :
          w.B₁.1 ≤ (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [bcReps, B, C] using
        (le_sup_right.trans le_sup_left :
          w.B₂.1 ≤ (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [bcReps, B, C] using
        (le_sup_left.trans le_sup_right :
          w.C₁.1 ≤ (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [bcReps, B, C] using
        (le_sup_right.trans le_sup_right :
          w.C₂.1 ≤ (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))

/-- Clause `rank_BC` makes the displayed `B,C` representatives
independent. -/
theorem bcReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.bcReps := by
  apply algebraicIndependent_of_rankEq_iSup_point
  rw [← w.bc_join_eq_iSup_point]
  exact hψ.rank_BC

/-- The two representatives of the output parameter `C`. -/
def cReps : Fin 2 → K := ![w.C₁.rep, w.C₂.rep]

/-- The join `C` is generated by `cReps`. -/
theorem c_eq_iSup_point :
    w.C = ⨆ i, ClosedIF.point k (w.cReps i) := by
  apply le_antisymm
  · refine sup_le ?_ ?_
    · exact le_iSup_of_le 0 (by simp [cReps])
    · exact le_iSup_of_le 1 (by simp [cReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i <;> simp [cReps, C]

/-- The `C` parameter has rank two. -/
theorem cReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.cReps := by
  have h := AlgebraicIndependent.comp_pair
    (w.acReps_independent hψ) (i := (2 : Fin 4)) (j := (3 : Fin 4))
    (by decide)
  simpa [acReps, cReps] using h

/-- The six displayed representatives of `A,B,C`. -/
def abcReps : Fin 6 → K :=
  ![w.A₁.rep, w.A₂.rep, w.B₁.rep, w.B₂.rep,
    w.C₁.rep, w.C₂.rep]

/-- Concatenate rank-two parameters in the `A,B,C` order used by equation
(8.6). -/
def compositionParameterTuple
    (a b c : Fin 2 → K) : Fin 6 → K :=
  ![a 0, a 1, b 0, b 1, c 0, c 1]

/-- The rank-two parameter composition locus selected by the actual
`(A,B,C)` tuple of a `Psi` witness.  Its orientation is `A ≫ B = C`,
matching the literal `X → Y → Z` correspondence chain. -/
def psiFamilyCompositionRelation
    (a b c : Fin 2 → K) : Prop :=
  idealOf k (compositionParameterTuple a b c) = idealOf k w.abcReps

/-- The displayed `(A,B,C)` parameters lie on their selected composition
locus. -/
theorem psiFamilyCompositionRelation_selected :
    w.psiFamilyCompositionRelation w.aReps w.bReps w.cReps := by
  change idealOf k w.abcReps = idealOf k w.abcReps
  rfl

/-- The genuine three-object groupoid presented by the rank-two
`A/B/C` family composition locus. -/
abbrev psiParameterFamilyGroupoid :=
  PresentedFamilyGroupoidOf w.psiFamilyCompositionRelation

/-- The rank-two `A`-family arrow, oriented `X → Y`. -/
def psiAArrow (a : Fin 2 → K) :
    PresentedFamilyGroupoidOf.x0 w.psiFamilyCompositionRelation ⟶
      PresentedFamilyGroupoidOf.x1 w.psiFamilyCompositionRelation :=
  PresentedFamilyGroupoidOf.t w.psiFamilyCompositionRelation a

/-- The rank-two `B`-family arrow, oriented `Y → Z`. -/
def psiBArrow (b : Fin 2 → K) :
    PresentedFamilyGroupoidOf.x1 w.psiFamilyCompositionRelation ⟶
      PresentedFamilyGroupoidOf.x2 w.psiFamilyCompositionRelation :=
  PresentedFamilyGroupoidOf.s w.psiFamilyCompositionRelation b

/-- The rank-two output `C`-family arrow, oriented `X → Z`. -/
def psiCArrow (c : Fin 2 → K) :
    PresentedFamilyGroupoidOf.x0 w.psiFamilyCompositionRelation ⟶
      PresentedFamilyGroupoidOf.x2 w.psiFamilyCompositionRelation :=
  PresentedFamilyGroupoidOf.u w.psiFamilyCompositionRelation c

/-- Every selected rank-two parameter triple gives the literal
`A`-then-`B` composition in the presented family groupoid. -/
theorem psiA_comp_psiB_eq_psiC {a b c : Fin 2 → K}
    (h : w.psiFamilyCompositionRelation a b c) :
    w.psiAArrow a ≫ w.psiBArrow b = w.psiCArrow c :=
  PresentedFamilyGroupoidOf.t_comp_s_eq_u
    w.psiFamilyCompositionRelation h

/-- The total parameter join is generated by `abcReps`. -/
theorem abc_join_eq_iSup_point :
    w.A ⊔ w.B ⊔ w.C = ⨆ i, ClosedIF.point k (w.abcReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le (sup_le ?_ ?_) (sup_le ?_ ?_))
      (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [abcReps])
    · exact le_iSup_of_le 1 (by simp [abcReps])
    · exact le_iSup_of_le 2 (by simp [abcReps])
    · exact le_iSup_of_le 3 (by simp [abcReps])
    · exact le_iSup_of_le 4 (by simp [abcReps])
    · exact le_iSup_of_le 5 (by simp [abcReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [abcReps, A, B, C] using
        (le_sup_left.trans le_sup_left |>.trans le_sup_left :
          w.A₁.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_right.trans le_sup_left |>.trans le_sup_left :
          w.A₂.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_left.trans le_sup_right |>.trans le_sup_left :
          w.B₁.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_right.trans le_sup_right |>.trans le_sup_left :
          w.B₂.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_left.trans le_sup_right :
          w.C₁.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))
    · simpa [abcReps, A, B, C] using
        (le_sup_right.trans le_sup_right :
          w.C₂.1 ≤ w.A₁.1 ⊔ w.A₂.1 ⊔
            (w.B₁.1 ⊔ w.B₂.1) ⊔ (w.C₁.1 ⊔ w.C₂.1))

/-- The rank-four `A,B` flat already contains `C`. -/
theorem ab_eq_abc (hψ : w.Psi) :
    w.A ⊔ w.B = w.A ⊔ w.B ⊔ w.C :=
  RankEq.eq_of_le le_sup_left hψ.rank_AB hψ.rank_ABC

/-- The rank-four `A,C` flat already contains `B`. -/
theorem ac_eq_abc (hψ : w.Psi) :
    w.A ⊔ w.C = w.A ⊔ w.B ⊔ w.C :=
  RankEq.eq_of_le
    (sup_le (le_sup_left.trans le_sup_left) le_sup_right)
    hψ.rank_AC hψ.rank_ABC

/-- The rank-four `B,C` flat already contains `A`. -/
theorem bc_eq_abc (hψ : w.Psi) :
    w.B ⊔ w.C = w.A ⊔ w.B ⊔ w.C :=
  RankEq.eq_of_le
    (sup_le (le_sup_right.trans le_sup_left) le_sup_right)
    hψ.rank_BC hψ.rank_ABC

/-- Every output-parameter coordinate is algebraic over the two input
parameter tuples. -/
theorem cReps_mem_racl_abReps (hψ : w.Psi) (i : Fin 2) :
    w.cReps i ∈ racl k (Set.range w.abReps) := by
  have hp : ClosedIF.point k (w.cReps i) ≤ w.C := by
    rw [w.c_eq_iSup_point]
    exact le_iSup (fun j ↦ ClosedIF.point k (w.cReps j)) i
  have hC : w.C ≤ w.A ⊔ w.B := by
    rw [w.ab_eq_abc hψ]
    exact le_sup_right
  rw [w.ab_join_eq_iSup_point] at hC
  exact mem_iSup_point_iff.1
    ((hp.trans hC) (ClosedIF.mem_point_self (w.cReps i)))

/-- Every right-input coordinate is algebraic over the left input and
output parameter tuples. -/
theorem bReps_mem_racl_acReps (hψ : w.Psi) (i : Fin 2) :
    w.bReps i ∈ racl k (Set.range w.acReps) := by
  have hp : ClosedIF.point k (w.bReps i) ≤ w.B := by
    rw [w.b_eq_iSup_point]
    exact le_iSup (fun j ↦ ClosedIF.point k (w.bReps j)) i
  have hB : w.B ≤ w.A ⊔ w.C := by
    rw [w.ac_eq_abc hψ]
    exact le_sup_right.trans le_sup_left
  rw [w.ac_join_eq_iSup_point] at hB
  exact mem_iSup_point_iff.1
    ((hp.trans hB) (ClosedIF.mem_point_self (w.bReps i)))

/-- Every left-input coordinate is algebraic over the right input and
output parameter tuples. -/
theorem aReps_mem_racl_bcReps (hψ : w.Psi) (i : Fin 2) :
    w.aReps i ∈ racl k (Set.range w.bcReps) := by
  have hp : ClosedIF.point k (w.aReps i) ≤ w.A := by
    rw [w.a_eq_iSup_point]
    exact le_iSup (fun j ↦ ClosedIF.point k (w.aReps j)) i
  have hA : w.A ≤ w.B ⊔ w.C := by
    rw [w.bc_eq_abc hψ]
    exact le_sup_left.trans le_sup_left
  rw [w.bc_join_eq_iSup_point] at hA
  exact mem_iSup_point_iff.1
    ((hp.trans hA) (ClosedIF.mem_point_self (w.aReps i)))

/-- The `Psi` parameter locus, packaged as a generically finite
rank-two multiplication correspondence. -/
def psiParameterMultiplication (hψ : w.Psi) :
    RankTwoFiniteCorrespondenceMultiplication (k := k) (Ω := K) where
  left := w.aReps
  right := w.bReps
  output := w.cReps
  leftRight_independent := by
    simpa [rankTwoPairTuple, aReps, bReps, abReps] using
      w.abReps_independent hψ
  leftOutput_independent := by
    simpa [rankTwoPairTuple, aReps, cReps, acReps] using
      w.acReps_independent hψ
  rightOutput_independent := by
    simpa [rankTwoPairTuple, bReps, cReps, bcReps] using
      w.bcReps_independent hψ
  output_mem_left_right := by
    intro i
    simpa [rankTwoPairTuple, aReps, bReps, abReps] using
      w.cReps_mem_racl_abReps hψ i
  right_mem_left_output := by
    intro i
    simpa [rankTwoPairTuple, aReps, cReps, acReps] using
      w.bReps_mem_racl_acReps hψ i
  left_mem_right_output := by
    intro i
    simpa [rankTwoPairTuple, bReps, cReps, bcReps] using
      w.aReps_mem_racl_bcReps hψ i

/-- The generic ideal of the packaged multiplication correspondence is
the selected six-parameter `Psi` ideal. -/
@[simp] theorem psiParameterMultiplication_ideal (hψ : w.Psi) :
    (w.psiParameterMultiplication hψ).ideal = idealOf k w.abcReps := by
  rfl

/-- The configuration-specific composition relation is exactly
realization of the packaged rank-two multiplication locus. -/
theorem psiFamilyCompositionRelation_iff_isRealization
    (hψ : w.Psi) (a b c : Fin 2 → K) :
    w.psiFamilyCompositionRelation a b c ↔
      (w.psiParameterMultiplication hψ).IsRealization a b c := by
  rw [psiFamilyCompositionRelation,
    RankTwoFiniteCorrespondenceMultiplication.IsRealization,
    w.psiParameterMultiplication_ideal hψ]
  rfl

/-- Every independent generic pair of rank-two input parameters has an
output on the selected `Psi` composition locus. -/
theorem exists_psiParameter_output [IsAlgClosed K] (hψ : w.Psi)
    {a b : Fin 2 → K}
    (hab : AlgebraicIndependent k (rankTwoPairTuple a b)) :
    ∃ c : Fin 2 → K, w.psiFamilyCompositionRelation a b c := by
  obtain ⟨c, hc⟩ := (w.psiParameterMultiplication hψ).exists_output hab
  exact ⟨c, (w.psiFamilyCompositionRelation_iff_isRealization hψ a b c).2 hc⟩

/-- Every independent generic left-input/output pair admits a right
division solution on the selected `Psi` locus. -/
theorem exists_psiParameter_right [IsAlgClosed K] (hψ : w.Psi)
    {a c : Fin 2 → K}
    (hac : AlgebraicIndependent k (rankTwoPairTuple a c)) :
    ∃ b : Fin 2 → K, w.psiFamilyCompositionRelation a b c := by
  obtain ⟨b, hb⟩ := (w.psiParameterMultiplication hψ).exists_right hac
  exact ⟨b, (w.psiFamilyCompositionRelation_iff_isRealization hψ a b c).2 hb⟩

/-- Every independent generic right-input/output pair admits a left
division solution on the selected `Psi` locus. -/
theorem exists_psiParameter_left [IsAlgClosed K] (hψ : w.Psi)
    {b c : Fin 2 → K}
    (hbc : AlgebraicIndependent k (rankTwoPairTuple b c)) :
    ∃ a : Fin 2 → K, w.psiFamilyCompositionRelation a b c := by
  obtain ⟨a, ha⟩ := (w.psiParameterMultiplication hψ).exists_left hbc
  exact ⟨a, (w.psiFamilyCompositionRelation_iff_isRealization hψ a b c).2 ha⟩

/-- The `A` representatives occur among `abReps`. -/
theorem aReps_range_subset_abReps :
    Set.range w.aReps ⊆ Set.range w.abReps := by
  rintro _ ⟨i, rfl⟩
  fin_cases i <;> simp [aReps, abReps]

/-- The `B` representatives occur among `abReps`. -/
theorem bReps_range_subset_abReps :
    Set.range w.bReps ⊆ Set.range w.abReps := by
  rintro _ ⟨i, rfl⟩
  fin_cases i <;> simp [bReps, abReps]

/-- The `A,B` representatives occur among `abcReps`. -/
theorem abReps_range_subset_abcReps :
    Set.range w.abReps ⊆ Set.range w.abcReps := by
  rintro _ ⟨i, rfl⟩
  fin_cases i <;> simp [abReps, abcReps]

/-- The `C` representatives occur among `abcReps`. -/
theorem cReps_range_subset_abcReps :
    Set.range w.cReps ⊆ Set.range w.abcReps := by
  rintro _ ⟨i, rfl⟩
  fin_cases i <;> simp [cReps, abcReps]

/-- Clause `Y_notLe` says that `Y` is generic over the four `A,B`
parameters. -/
theorem Y_rep_notMem_racl_abReps (hψ : w.Psi) :
    w.Y.rep ∉ racl k (Set.range w.abReps) := by
  intro hY
  apply hψ.Y_notLe
  have hpoint : w.Y.1 ≤ ⨆ i, ClosedIF.point k (w.abReps i) := by
    rw [← w.Y.point_rep]
    exact ClosedIF.point_le_iff.2
      (mem_iSup_point_iff.2 hY)
  rw [← w.ab_join_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_left

/-- `X_notLe` also makes `X` generic over the combined `A,B` parameter
field. -/
theorem X_rep_notMem_racl_abReps (hψ : w.Psi) :
    w.X.rep ∉ racl k (Set.range w.abReps) := by
  intro hX
  apply hψ.X_notLe
  have hpoint : w.X.1 ≤ ⨆ i, ClosedIF.point k (w.abReps i) := by
    rw [← w.X.point_rep]
    exact ClosedIF.point_le_iff.2
      (mem_iSup_point_iff.2 hX)
  rw [← w.ab_join_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_left

/-- `Z_notLe` makes `Z` generic over the combined `A,B` parameter
field. -/
theorem Z_rep_notMem_racl_abReps (hψ : w.Psi) :
    w.Z.rep ∉ racl k (Set.range w.abReps) := by
  intro hZ
  apply hψ.Z_notLe
  have hpoint : w.Z.1 ≤ ⨆ i, ClosedIF.point k (w.abReps i) := by
    rw [← w.Z.point_rep]
    exact ClosedIF.point_le_iff.2
      (mem_iSup_point_iff.2 hZ)
  rw [← w.ab_join_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_left

/-- The incidence `X ≤ A ∨ Y` makes `X` algebraic over
`(A₁,A₂,B₁,B₂,Y)` (the unused `B` parameters are harmless). -/
theorem X_rep_mem_racl_abReps_snoc_Y (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 5, ClosedIF.point k
      ((Fin.snoc (w.abReps : Fin 4 → K) w.Y.rep : Fin 5 → K) i)
  have hA₁ : w.A₁.1 ≤ E :=
    le_iSup_of_le 0 (by simp [abReps])
  have hA₂ : w.A₂.1 ≤ E :=
    le_iSup_of_le 1 (by simp [abReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 4) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hX : w.X.1 ≤ E :=
    hψ.X_le.trans (sup_le (sup_le hA₁ hA₂) hY)
  exact mem_iSup_point_iff.1 (hX w.X.mem_rep)

/-- The first projection of `Z_le` makes `Z` algebraic over
`(A₁,A₂,B₁,B₂,Y)`. -/
theorem Z_rep_mem_racl_abReps_snoc_Y (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 5, ClosedIF.point k
      ((Fin.snoc (w.abReps : Fin 4 → K) w.Y.rep : Fin 5 → K) i)
  have hB₁ : w.B₁.1 ≤ E :=
    le_iSup_of_le 2 (by simp [abReps])
  have hB₂ : w.B₂.1 ≤ E :=
    le_iSup_of_le 3 (by simp [abReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 4) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hZ : w.Z.1 ≤ E :=
    hψ.Z_le.trans inf_le_left |>.trans
      (sup_le (sup_le hB₁ hB₂) hY)
  exact mem_iSup_point_iff.1 (hZ w.Z.mem_rep)

/-- Exchange reverses the `A`-incidence: over the combined parameter
field, `Y` is algebraic over `X`. -/
theorem Y_rep_mem_racl_abReps_snoc_X (hψ : w.Psi) :
    w.Y.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.X.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_abReps_snoc_Y hψ
  · exact w.X_rep_notMem_racl_abReps hψ

/-- Exchange reverses the `B`-incidence: over the combined parameter
field, `Y` is algebraic over `Z`. -/
theorem Y_rep_mem_racl_abReps_snoc_Z (hψ : w.Psi) :
    w.Y.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Z.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_abReps_snoc_Y hψ
  · exact w.Z_rep_notMem_racl_abReps hψ

/-- `X` is generic over `A`. -/
theorem X_rep_notMem_racl_aReps (hψ : w.Psi) :
    w.X.rep ∉ racl k (Set.range w.aReps) := by
  intro hX
  apply hψ.X_notLe
  have hpoint : w.X.1 ≤ ⨆ i, ClosedIF.point k (w.aReps i) := by
    rw [← w.X.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hX)
  rw [← w.a_eq_iSup_point] at hpoint
  exact hpoint.trans (le_sup_left.trans le_sup_left)

/-- `Y` is generic over `A`. -/
theorem Y_rep_notMem_racl_aReps (hψ : w.Psi) :
    w.Y.rep ∉ racl k (Set.range w.aReps) := by
  intro hY
  apply hψ.Y_notLe
  have hpoint : w.Y.1 ≤ ⨆ i, ClosedIF.point k (w.aReps i) := by
    rw [← w.Y.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hY)
  rw [← w.a_eq_iSup_point] at hpoint
  exact hpoint.trans (le_sup_left.trans le_sup_left)

/-- The `A` incidence makes `X` algebraic over `(A₁,A₂,Y)`. -/
theorem X_rep_mem_racl_aReps_snoc_Y (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.aReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 3, ClosedIF.point k
      ((Fin.snoc (w.aReps : Fin 2 → K) w.Y.rep : Fin 3 → K) i)
  have hA₁ : w.A₁.1 ≤ E :=
    le_iSup_of_le 0 (by simp [aReps])
  have hA₂ : w.A₂.1 ≤ E :=
    le_iSup_of_le 1 (by simp [aReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 2) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hX : w.X.1 ≤ E :=
    hψ.X_le.trans (sup_le (sup_le hA₁ hA₂) hY)
  exact mem_iSup_point_iff.1 (hX w.X.mem_rep)

/-- Exchange reverses the `A` incidence. -/
theorem Y_rep_mem_racl_aReps_snoc_X (hψ : w.Psi) :
    w.Y.rep ∈ racl k
      (Set.range (Fin.snoc w.aReps w.X.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_aReps_snoc_Y hψ
  · exact w.X_rep_notMem_racl_aReps hψ

/-- `Y` is generic over `B`. -/
theorem Y_rep_notMem_racl_bReps (hψ : w.Psi) :
    w.Y.rep ∉ racl k (Set.range w.bReps) := by
  intro hY
  apply hψ.Y_notLe
  have hpoint : w.Y.1 ≤ ⨆ i, ClosedIF.point k (w.bReps i) := by
    rw [← w.Y.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hY)
  rw [← w.b_eq_iSup_point] at hpoint
  exact hpoint.trans (le_sup_right.trans le_sup_left)

/-- `Z` is generic over `B`. -/
theorem Z_rep_notMem_racl_bReps (hψ : w.Psi) :
    w.Z.rep ∉ racl k (Set.range w.bReps) := by
  intro hZ
  apply hψ.Z_notLe
  have hpoint : w.Z.1 ≤ ⨆ i, ClosedIF.point k (w.bReps i) := by
    rw [← w.Z.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hZ)
  rw [← w.b_eq_iSup_point] at hpoint
  exact hpoint.trans (le_sup_right.trans le_sup_left)

/-- The `B` incidence makes `Z` algebraic over `(B₁,B₂,Y)`. -/
theorem Z_rep_mem_racl_bReps_snoc_Y (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.bReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 3, ClosedIF.point k
      ((Fin.snoc (w.bReps : Fin 2 → K) w.Y.rep : Fin 3 → K) i)
  have hB₁ : w.B₁.1 ≤ E :=
    le_iSup_of_le 0 (by simp [bReps])
  have hB₂ : w.B₂.1 ≤ E :=
    le_iSup_of_le 1 (by simp [bReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 2) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hZ : w.Z.1 ≤ E :=
    hψ.Z_le.trans inf_le_left |>.trans
      (sup_le (sup_le hB₁ hB₂) hY)
  exact mem_iSup_point_iff.1 (hZ w.Z.mem_rep)

/-- Exchange reverses the `B` incidence. -/
theorem Y_rep_mem_racl_bReps_snoc_Z (hψ : w.Psi) :
    w.Y.rep ∈ racl k
      (Set.range (Fin.snoc w.bReps w.Z.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_bReps_snoc_Y hψ
  · exact w.Z_rep_notMem_racl_bReps hψ

/-- Clause `X_free` is the exact rank-two minimal-parameter statement for
the `A`-family: no atom below `A` makes the generic incidence algebraic. -/
theorem X_rep_notMem_racl_atom_Y (hψ : w.Psi)
    (A' : Point k K) (hA' : A'.1 ≤ w.A) :
    w.X.rep ∉ racl k ({A'.rep, w.Y.rep} : Set K) := by
  intro hX
  exact hψ.X_free A' hA'
    (point_le_sup_of_rep_mem_racl_pair w.X A' w.Y hX)

/-- Clause `Z_freeB` gives minimal parameter rank two for the `B`-family. -/
theorem Z_rep_notMem_racl_atom_Y (hψ : w.Psi)
    (B' : Point k K) (hB' : B'.1 ≤ w.B) :
    w.Z.rep ∉ racl k ({B'.rep, w.Y.rep} : Set K) := by
  intro hZ
  exact hψ.Z_freeB B' hB'
    (point_le_sup_of_rep_mem_racl_pair w.Z B' w.Y hZ)

/-- Clause `Z_freeC` gives minimal parameter rank two for the `C`-family. -/
theorem Z_rep_notMem_racl_atom_X (hψ : w.Psi)
    (C' : Point k K) (hC' : C'.1 ≤ w.C) :
    w.Z.rep ∉ racl k ({C'.rep, w.X.rep} : Set K) := by
  intro hZ
  exact hψ.Z_freeC C' hC'
    (point_le_sup_of_rep_mem_racl_pair w.Z C' w.X hZ)

/-- **Exact parameter-rank input for the three correspondence families.**
The displayed `A,B,C` parameter pairs are independent, while the atom
clauses say that no rank-one subparameter already defines the corresponding
generic incidence. -/
theorem psi_family_parameters_rank_two_minimal (hψ : w.Psi) :
    AlgebraicIndependent k w.aReps ∧
      AlgebraicIndependent k w.bReps ∧
      AlgebraicIndependent k w.cReps ∧
      (∀ A' : Point k K, A'.1 ≤ w.A →
        w.X.rep ∉ racl k ({A'.rep, w.Y.rep} : Set K)) ∧
      (∀ B' : Point k K, B'.1 ≤ w.B →
        w.Z.rep ∉ racl k ({B'.rep, w.Y.rep} : Set K)) ∧
      (∀ C' : Point k K, C'.1 ≤ w.C →
        w.Z.rep ∉ racl k ({C'.rep, w.X.rep} : Set K)) :=
  ⟨w.aReps_independent hψ, w.bReps_independent hψ,
    w.cReps_independent hψ, w.X_rep_notMem_racl_atom_Y hψ,
    w.Z_rep_notMem_racl_atom_Y hψ,
    w.Z_rep_notMem_racl_atom_X hψ⟩

/-- `X` is generic over the output parameter `C`. -/
theorem X_rep_notMem_racl_cReps (hψ : w.Psi) :
    w.X.rep ∉ racl k (Set.range w.cReps) := by
  intro hX
  apply hψ.X_notLe
  have hpoint : w.X.1 ≤ ⨆ i, ClosedIF.point k (w.cReps i) := by
    rw [← w.X.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hX)
  rw [← w.c_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_right

/-- `Z` is generic over the output parameter `C`. -/
theorem Z_rep_notMem_racl_cReps (hψ : w.Psi) :
    w.Z.rep ∉ racl k (Set.range w.cReps) := by
  intro hZ
  apply hψ.Z_notLe
  have hpoint : w.Z.1 ≤ ⨆ i, ClosedIF.point k (w.cReps i) := by
    rw [← w.Z.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hZ)
  rw [← w.c_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_right

/-- The second projection of `Z_le` makes `Z` algebraic over the output
parameter `C` and `X`. -/
theorem Z_rep_mem_racl_cReps_snoc_X (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.cReps w.X.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 3, ClosedIF.point k
      ((Fin.snoc (w.cReps : Fin 2 → K) w.X.rep : Fin 3 → K) i)
  have hC₁ : w.C₁.1 ≤ E :=
    le_iSup_of_le 0 (by simp [cReps])
  have hC₂ : w.C₂.1 ≤ E :=
    le_iSup_of_le 1 (by simp [cReps])
  have hX : w.X.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 2) ?_
    rw [Fin.snoc_last, w.X.point_rep]
  have hZ : w.Z.1 ≤ E :=
    hψ.Z_le.trans inf_le_right |>.trans
      (sup_le (sup_le hC₁ hC₂) hX)
  exact mem_iSup_point_iff.1 (hZ w.Z.mem_rep)

/-- Exchange reverses the `C`-incidence. -/
theorem X_rep_mem_racl_cReps_snoc_Z (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.cReps w.Z.rep)) := by
  rw [Fin.range_snoc]
  apply racl_exchange
  · simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_cReps_snoc_X hψ
  · exact w.Z_rep_notMem_racl_cReps hψ

/-- `X` is generic over all six displayed parameters. -/
theorem X_rep_notMem_racl_abcReps (hψ : w.Psi) :
    w.X.rep ∉ racl k (Set.range w.abcReps) := by
  intro hX
  apply hψ.X_notLe
  have hpoint : w.X.1 ≤ ⨆ i, ClosedIF.point k (w.abcReps i) := by
    rw [← w.X.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hX)
  rwa [← w.abc_join_eq_iSup_point] at hpoint

/-- `Z` is generic over all six displayed parameters. -/
theorem Z_rep_notMem_racl_abcReps (hψ : w.Psi) :
    w.Z.rep ∉ racl k (Set.range w.abcReps) := by
  intro hZ
  apply hψ.Z_notLe
  have hpoint : w.Z.1 ≤ ⨆ i, ClosedIF.point k (w.abcReps i) := by
    rw [← w.Z.point_rep]
    exact ClosedIF.point_le_iff.2 (mem_iSup_point_iff.2 hZ)
  rwa [← w.abc_join_eq_iSup_point] at hpoint

/-- The `C`-incidence remains algebraic after adjoining the unused
`A,B` parameters. -/
theorem Z_rep_mem_racl_abcReps_snoc_X (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.abcReps w.X.rep)) := by
  refine racl_mono ?_ (w.Z_rep_mem_racl_cReps_snoc_X hψ)
  rw [Fin.range_snoc, Fin.range_snoc]
  exact Set.union_subset_union Set.Subset.rfl w.cReps_range_subset_abcReps

/-- The reverse `C`-incidence remains algebraic after adjoining `A,B`. -/
theorem X_rep_mem_racl_abcReps_snoc_Z (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.abcReps w.Z.rep)) := by
  refine racl_mono ?_ (w.X_rep_mem_racl_cReps_snoc_Z hψ)
  rw [Fin.range_snoc, Fin.range_snoc]
  exact Set.union_subset_union Set.Subset.rfl w.cReps_range_subset_abcReps

/-- The combined field of the independent `A,B` parameters. -/
def abField : IntermediateField k K :=
  adjoin k (Set.range w.abReps)

/-- The coefficient field generated by the `A` parameter. -/
def aField : IntermediateField k K :=
  adjoin k (Set.range w.aReps)

/-- The coefficient field generated by the `B` parameter. -/
def bField : IntermediateField k K :=
  adjoin k (Set.range w.bReps)

/-- The coefficient field generated by the output parameter `C`. -/
def cField : IntermediateField k K :=
  adjoin k (Set.range w.cReps)

/-- A common finite-cover coefficient field containing all displayed
parameters. -/
def abcField : IntermediateField k K :=
  adjoin k (Set.range w.abcReps)

/-- The `A,B` coefficient field embeds in the common coefficient field. -/
theorem abField_le_abcField : w.abField ≤ w.abcField :=
  adjoin.mono k _ _ w.abReps_range_subset_abcReps

/-- Every displayed `A,B,C` coordinate is algebraic over the independent
`A,B` coefficient field.  For the `C` coordinates this is the content of
`rank_AB = rank_ABC = 4`. -/
theorem abcReps_isAlgebraic_abField (hψ : w.Psi) (i : Fin 6) :
    IsAlgebraic (↥w.abField) (w.abcReps i) := by
  have hp : ClosedIF.point k (w.abcReps i) ≤
      ⨆ j, ClosedIF.point k (w.abcReps j) :=
    le_iSup (fun j ↦ ClosedIF.point k (w.abcReps j)) i
  rw [← w.abc_join_eq_iSup_point, ← w.ab_eq_abc hψ,
    w.ab_join_eq_iSup_point] at hp
  have hmem := mem_iSup_point_iff.1
    (hp (ClosedIF.mem_point_self (w.abcReps i)))
  rw [abField]
  exact (mem_racl_iff k).1 hmem

/-- The common coefficient field, regarded as an extension of the
composable `A,B` field. -/
def abcOverAb : IntermediateField (↥w.abField) K :=
  extendScalars w.abField_le_abcField

/-- The common coefficient cover is algebraic over the `A,B` field. -/
theorem abcOverAb_isAlgebraic (hψ : w.Psi) :
    Algebra.IsAlgebraic (↥w.abField) (↥w.abcOverAb) := by
  apply isAlgebraic_extendScalars_adjoin w.abField_le_abcField
  rintro _ ⟨i, rfl⟩
  exact w.abcReps_isAlgebraic_abField hψ i

/-- **The common parameter cover is finite.**  It is generated over the
`A,B` field by the finite six-tuple `abcReps`, all of whose members are
algebraic there. -/
theorem abcOverAb_finiteDimensional (hψ : w.Psi) :
    FiniteDimensional (↥w.abField) (↥w.abcOverAb) := by
  have key : w.abcOverAb =
      adjoin (↥w.abField) (Set.range w.abcReps) := by
    refine restrictScalars_injective k ?_
    unfold abcOverAb abField abcField
    rw [adjoin_adjoin_left,
      extendScalars_restrictScalars, adjoin_union]
    exact (sup_eq_right.2 w.abField_le_abcField).symm
  rw [key]
  letI : Fintype (Set.range w.abcReps) :=
    Set.Finite.fintype (Set.finite_range w.abcReps)
  exact finiteDimensional_adjoin fun x hx ↦ by
    obtain ⟨i, rfl⟩ := hx
    exact (w.abcReps_isAlgebraic_abField hψ i).isIntegral

/-- The normal closure of the common `A,B,C` coefficient field over the
independent `A,B` coefficient field. -/
def abcNormalOverAb : IntermediateField (↥w.abField) K :=
  FiniteCover.normalClosureOver w.abField_le_abcField

/-- The common coefficient field embeds in its normal closure. -/
theorem abcOverAb_le_abcNormalOverAb :
    w.abcOverAb ≤ w.abcNormalOverAb :=
  FiniteCover.extendScalars_le_normalClosureOver
    w.abField_le_abcField

/-- The common coefficient normal closure is finite over the `A,B`
field. -/
theorem abcNormalOverAb_finiteDimensional (hψ : w.Psi) :
    FiniteDimensional (↥w.abField) (↥w.abcNormalOverAb) :=
  FiniteCover.normalClosureOver_finiteDimensional
    w.abField_le_abcField (w.abcOverAb_finiteDimensional hψ)

/-- In an algebraically closed ambient field, the common coefficient
normal closure is normal over `A,B`. -/
theorem abcNormalOverAb_normal [IsAlgClosed K] (hψ : w.Psi) :
    Normal (↥w.abField) (↥w.abcNormalOverAb) := by
  letI := w.abcOverAb_finiteDimensional hψ
  exact FiniteCover.normalClosureOver_normal w.abField_le_abcField
    (Algebra.IsAlgebraic.of_finite (↥w.abField) (↥w.abcOverAb))

/-- The `A` coefficient field embeds in the composable `A,B` field. -/
theorem aField_le_abField : w.aField ≤ w.abField :=
  adjoin.mono k _ _ w.aReps_range_subset_abReps

/-- The `B` coefficient field embeds in the composable `A,B` field. -/
theorem bField_le_abField : w.bField ≤ w.abField :=
  adjoin.mono k _ _ w.bReps_range_subset_abReps

/-- The `C` coefficient field embeds in the common coefficient field. -/
theorem cField_le_abcField : w.cField ≤ w.abcField :=
  adjoin.mono k _ _ w.cReps_range_subset_abcReps

/-- The actual rank-two `A`-family member, oriented `X → Y`.  This retains
the parameter tuple in the ground field `k`, rather than replacing it by a
fixed coefficient field. -/
def xyCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := K) 2 where
  parameter := w.aReps
  source := w.X.rep
  target := w.Y.rep
  parameter_independent := w.aReps_independent hψ
  source_generic := w.X_rep_notMem_racl_aReps hψ
  target_mem_parameter_source := by
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_aReps_snoc_X hψ
  source_mem_parameter_target := by
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_aReps_snoc_Y hψ

/-- The actual rank-two `B`-family member, oriented `Y → Z`. -/
def yzCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := K) 2 where
  parameter := w.bReps
  source := w.Y.rep
  target := w.Z.rep
  parameter_independent := w.bReps_independent hψ
  source_generic := w.Y_rep_notMem_racl_bReps hψ
  target_mem_parameter_source := by
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_bReps_snoc_Y hψ
  source_mem_parameter_target := by
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_bReps_snoc_Z hψ

/-- The actual rank-two output `C`-family member, oriented `X → Z`. -/
def xzCorrespondenceFamilyMember (hψ : w.Psi) :
    FiniteCorrespondenceFamilyMember (k := k) (Ω := K) 2 where
  parameter := w.cReps
  source := w.X.rep
  target := w.Z.rep
  parameter_independent := w.cReps_independent hψ
  source_generic := w.X_rep_notMem_racl_cReps hψ
  target_mem_parameter_source := by
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_cReps_snoc_X hψ
  source_mem_parameter_target := by
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_cReps_snoc_Z hψ

/-- Every independent parameter/source triple carries a member of the
same `A`-family locus as the selected `(A,X,Y)` tuple. -/
theorem xyFamily_exists_relocation [IsAlgClosed K] (hψ : w.Psi)
    {q : Fin 2 → K} {x : K}
    (hqx : AlgebraicIndependent k (Fin.snoc q x)) :
    ∃ y : K,
      idealOf k (Fin.snoc (Fin.snoc q x) y) =
        (w.xyCorrespondenceFamilyMember hψ).ideal :=
  (w.xyCorrespondenceFamilyMember hψ).exists_relocation hqx

/-- Every independent parameter/source triple carries a member of the
same `B`-family locus as the selected `(B,Y,Z)` tuple. -/
theorem yzFamily_exists_relocation [IsAlgClosed K] (hψ : w.Psi)
    {q : Fin 2 → K} {y : K}
    (hqy : AlgebraicIndependent k (Fin.snoc q y)) :
    ∃ z : K,
      idealOf k (Fin.snoc (Fin.snoc q y) z) =
        (w.yzCorrespondenceFamilyMember hψ).ideal :=
  (w.yzCorrespondenceFamilyMember hψ).exists_relocation hqy

/-- Every independent parameter/source triple carries a member of the
same output `C`-family locus as the selected `(C,X,Z)` tuple. -/
theorem xzFamily_exists_relocation [IsAlgClosed K] (hψ : w.Psi)
    {q : Fin 2 → K} {x : K}
    (hqx : AlgebraicIndependent k (Fin.snoc q x)) :
    ∃ z : K,
      idealOf k (Fin.snoc (Fin.snoc q x) z) =
        (w.xzCorrespondenceFamilyMember hψ).ideal :=
  (w.xzCorrespondenceFamilyMember hψ).exists_relocation hqx

/-- The actual family member parametrized by `A`, oriented `X → Y` so
that it composes with the `B` member below. -/
def xyCorrespondencePairOverA (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.aField) K where
  source := w.X.rep
  target := w.Y.rep
  source_generic := by
    rw [aField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.X_rep_notMem_racl_aReps hψ
  target_mem_source := by
    rw [aField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_aReps_snoc_X hψ
  source_mem_target := by
    rw [aField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_aReps_snoc_Y hψ

/-- Forgetting the varying parameter from the `A`-family member recovers
the previously selected finite-correspondence pair over `k(A)`. -/
theorem xyCorrespondenceFamilyMember_toPair (hψ : w.Psi) :
    (w.xyCorrespondenceFamilyMember hψ).toPair =
      w.xyCorrespondencePairOverA hψ :=
  rfl

/-- The actual family member parametrized by `B`, oriented `Y → Z`. -/
def yzCorrespondencePairOverB (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.bField) K where
  source := w.Y.rep
  target := w.Z.rep
  source_generic := by
    rw [bField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.Y_rep_notMem_racl_bReps hψ
  target_mem_source := by
    rw [bField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_bReps_snoc_Y hψ
  source_mem_target := by
    rw [bField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_bReps_snoc_Z hψ

/-- Forgetting the varying parameter from the `B`-family member recovers
the selected finite-correspondence pair over `k(B)`. -/
theorem yzCorrespondenceFamilyMember_toPair (hψ : w.Psi) :
    (w.yzCorrespondenceFamilyMember hψ).toPair =
      w.yzCorrespondencePairOverB hψ :=
  rfl

/-- The selected `X → Y` correspondence branch over the combined
parameter field.  Both directions of interalgebraicity are consequences of
`X_le`, genericity, and exchange. -/
def xyCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abField) K where
  source := w.X.rep
  target := w.Y.rep
  source_generic := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.X_rep_notMem_racl_abReps hψ
  target_mem_source := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_abReps_snoc_X hψ
  source_mem_target := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_abReps_snoc_Y hψ

/-- The selected `Y → Z` correspondence branch over the combined
parameter field. -/
def yzCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abField) K where
  source := w.Y.rep
  target := w.Z.rep
  source_generic := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.Y_rep_notMem_racl_abReps hψ
  target_mem_source := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_abReps_snoc_Y hψ
  source_mem_target := by
    rw [abField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Y_rep_mem_racl_abReps_snoc_Z hψ

/-- After adjoining the independent `B` parameters, the `A` family member
has the selected `(X,Y)` prime branch used in composition. -/
theorem aFamily_map_le_abBranch (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.aField_le_abField))
        (w.xyCorrespondencePairOverA hψ).ideal ≤
      (w.xyCorrespondencePair hψ).ideal := by
  change Ideal.map
      (MvPolynomial.map
        (IntermediateField.inclusion w.aField_le_abField))
      (idealOf (↥w.aField) ![w.X.rep, w.Y.rep]) ≤
    idealOf (↥w.abField) ![w.X.rep, w.Y.rep]
  exact idealOf_map_le_of_intermediateField_le
    w.aField_le_abField ![w.X.rep, w.Y.rep]

/-- After adjoining the independent `A` parameters, the `B` family member
has the selected `(Y,Z)` prime branch used in composition. -/
theorem bFamily_map_le_abBranch (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.bField_le_abField))
        (w.yzCorrespondencePairOverB hψ).ideal ≤
      (w.yzCorrespondencePair hψ).ideal := by
  change Ideal.map
      (MvPolynomial.map
        (IntermediateField.inclusion w.bField_le_abField))
      (idealOf (↥w.bField) ![w.Y.rep, w.Z.rep]) ≤
    idealOf (↥w.abField) ![w.Y.rep, w.Z.rep]
  exact idealOf_map_le_of_intermediateField_le
    w.bField_le_abField ![w.Y.rep, w.Z.rep]

/-- The endpoint branch selected by composing the actual `X → Y` and
`Y → Z` generic pairs from a `Psi` witness. -/
def xzCorrespondencePair (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abField) K :=
  (w.xyCorrespondencePair hψ).comp (w.yzCorrespondencePair hψ) rfl

/-- The output family member parametrized by `C`, presented by its actual
generic pair `(X,Z)`. -/
def xzCorrespondencePairOverC (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.cField) K where
  source := w.X.rep
  target := w.Z.rep
  source_generic := by
    rw [cField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.X_rep_notMem_racl_cReps hψ
  target_mem_source := by
    rw [cField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_cReps_snoc_X hψ
  source_mem_target := by
    rw [cField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_cReps_snoc_Z hψ

/-- Forgetting the varying output parameter from the `C`-family member
recovers the selected endpoint pair over `k(C)`. -/
theorem xzCorrespondenceFamilyMember_toPair (hψ : w.Psi) :
    (w.xzCorrespondenceFamilyMember hψ).toPair =
      w.xzCorrespondencePairOverC hψ :=
  rfl

/-- The common-cover presentation of the endpoint pair `(X,Z)`.  This is
the prime component selected by the given generic tuple after adjoining
all parameters. -/
def xzCorrespondencePairOverABC (hψ : w.Psi) :
    FiniteCorrespondencePair (↥w.abcField) K where
  source := w.X.rep
  target := w.Z.rep
  source_generic := by
    rw [abcField, mem_racl_adjoin_base_iff, Set.union_empty]
    exact w.X_rep_notMem_racl_abcReps hψ
  target_mem_source := by
    rw [abcField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.Z_rep_mem_racl_abcReps_snoc_X hψ
  source_mem_target := by
    rw [abcField, mem_racl_adjoin_base_iff, Set.union_singleton]
    simpa only [Fin.range_snoc] using
      w.X_rep_mem_racl_abcReps_snoc_Z hψ

/-- The selected endpoint prime on the common parameter cover. -/
def psiSelectedComponentIdeal (hψ : w.Psi) :
    Ideal (MvPolynomial (Fin 2) (↥w.abcField)) :=
  (w.xzCorrespondencePairOverABC hψ).ideal

/-- The common-cover endpoint is a prime component. -/
theorem psiSelectedComponentIdeal_isPrime (hψ : w.Psi) :
    (w.psiSelectedComponentIdeal hψ).IsPrime := by
  apply idealOf_isPrime

/-- The selected endpoint component lies over the base change of the
composite `A,B` branch. -/
theorem abComposite_map_le_selectedComponent (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.abField_le_abcField))
        (w.xzCorrespondencePair hψ).ideal ≤
      w.psiSelectedComponentIdeal hψ := by
  change Ideal.map
      (MvPolynomial.map
        (IntermediateField.inclusion w.abField_le_abcField))
      (idealOf (↥w.abField) ![w.X.rep, w.Z.rep]) ≤
    idealOf (↥w.abcField) ![w.X.rep, w.Z.rep]
  exact idealOf_map_le_of_intermediateField_le
    w.abField_le_abcField ![w.X.rep, w.Z.rep]

/-- The same selected endpoint component lies over the base change of the
`C`-parametrized family member. -/
theorem cFamily_map_le_selectedComponent (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.cField_le_abcField))
        (w.xzCorrespondencePairOverC hψ).ideal ≤
      w.psiSelectedComponentIdeal hψ := by
  change Ideal.map
      (MvPolynomial.map
        (IntermediateField.inclusion w.cField_le_abcField))
      (idealOf (↥w.cField) ![w.X.rep, w.Z.rep]) ≤
    idealOf (↥w.abcField) ![w.X.rep, w.Z.rep]
  exact idealOf_map_le_of_intermediateField_le
    w.cField_le_abcField ![w.X.rep, w.Z.rep]

/-- **Prime-ideal form of blueprint (8.6).**  On the common finite cover,
the endpoint selected by composing the `A` and `B` incidence branches and
the family member parametrized by `C` have the same selected prime
component: the vanishing ideal of the literal generic pair `(X,Z)`.

The two inclusions deliberately retain the selected-component semantics of
finite base change; the extended ideals may have other prime branches. -/
theorem psi_composition_selected_component (hψ : w.Psi) :
    Ideal.map
        (MvPolynomial.map
          (IntermediateField.inclusion w.abField_le_abcField))
        (w.xzCorrespondencePair hψ).ideal ≤
        w.psiSelectedComponentIdeal hψ ∧
      Ideal.map
          (MvPolynomial.map
            (IntermediateField.inclusion w.cField_le_abcField))
          (w.xzCorrespondencePairOverC hψ).ideal ≤
        w.psiSelectedComponentIdeal hψ :=
  ⟨w.abComposite_map_le_selectedComponent hψ,
    w.cFamily_map_le_selectedComponent hψ⟩

@[simp] theorem xzCorrespondencePair_source (hψ : w.Psi) :
    (w.xzCorrespondencePair hψ).source = w.X.rep := rfl

@[simp] theorem xzCorrespondencePair_target (hψ : w.Psi) :
    (w.xzCorrespondencePair hψ).target = w.Z.rep := rfl

/-- Clause `Psi.quad` supplies a second concrete three-object
correspondence groupoid.  Its arrows are the `T`, `S`, and `U` members of
the partial quadrangle and satisfy `S ∘ T = U` at the literal shared
representative `U'`. -/
theorem psi_exists_partialQuadrangle_correspondence_groupoid (hψ : w.Psi) :
    ∃ (S' T' U' : Point k K)
      (hquad : IsPartialQuadrangle ![w.S, w.T, w.U, S', T', U']),
      FiniteCorrespondenceGerm.Composes
        (FiniteCorrespondenceGerm.ofPair
          (IsPartialQuadrangle.tPair hquad))
        (FiniteCorrespondenceGerm.ofPair
          (IsPartialQuadrangle.sPair hquad))
        (FiniteCorrespondenceGerm.ofPair
          (IsPartialQuadrangle.uPair hquad)) := by
  obtain ⟨S', T', U', hquad⟩ := hψ.quad
  exact ⟨S', T', U', hquad,
    IsPartialQuadrangle.selected_correspondence_composes hquad⟩

/-- **Selected-component interface for blueprint (8.6).**  The two
finite-correspondence germs obtained from the actual `Psi` incidences
compose at their literal shared representative `Y`; the selected component
is the endpoint germ presented by `(X,Z)`. -/
theorem psi_selected_correspondence_composes (hψ : w.Psi) :
    FiniteCorrespondenceGerm.Composes
      (FiniteCorrespondenceGerm.ofPair (w.xyCorrespondencePair hψ))
      (FiniteCorrespondenceGerm.ofPair (w.yzCorrespondencePair hψ))
      (FiniteCorrespondenceGerm.ofPair (w.xzCorrespondencePair hψ)) :=
  FiniteCorrespondenceGerm.composes_of_shared_middle
    (w.xyCorrespondencePair hψ) (w.yzCorrespondencePair hψ) rfl

/-- Equation (8.6) simultaneously as a rank-two parameter-family arrow
identity and as composition of the actual selected finite-correspondence
germs.  The first conjunct supplies genuine categorical associativity; the
second records the geometric selected component at `(X,Y,Z)`. -/
theorem psi_selected_family_groupoid_composition (hψ : w.Psi) :
    w.psiAArrow w.aReps ≫ w.psiBArrow w.bReps =
        w.psiCArrow w.cReps ∧
      FiniteCorrespondenceGerm.Composes
        (FiniteCorrespondenceGerm.ofPair (w.xyCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.ofPair (w.yzCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.ofPair (w.xzCorrespondencePair hψ)) :=
  ⟨w.psiA_comp_psiB_eq_psiC
      w.psiFamilyCompositionRelation_selected,
    w.psi_selected_correspondence_composes hψ⟩

/-- The actual `Psi` branches satisfy the selected groupoid inverse laws
alongside (8.6).  Thus the `X → Y → Z` path, its endpoint, and their
reverse branches form the concrete input expected by the difference-chart
bookkeeping. -/
theorem psi_selected_correspondence_groupoid_laws (hψ : w.Psi) :
    FiniteCorrespondenceGerm.Composes
        (FiniteCorrespondenceGerm.ofPair (w.xyCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.ofPair (w.yzCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.ofPair (w.xzCorrespondencePair hψ)) ∧
      FiniteCorrespondenceGerm.Composes
        (FiniteCorrespondenceGerm.ofPair (w.xyCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.inverseOfPair
          (w.xyCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.identity w.X.rep
          (w.xyCorrespondencePair hψ).source_generic) ∧
      FiniteCorrespondenceGerm.Composes
        (FiniteCorrespondenceGerm.inverseOfPair
          (w.xyCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.ofPair (w.xyCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.identity w.Y.rep
          (w.xyCorrespondencePair hψ).target_generic) ∧
      FiniteCorrespondenceGerm.Composes
        (FiniteCorrespondenceGerm.ofPair (w.yzCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.inverseOfPair
          (w.yzCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.identity w.Y.rep
          (w.yzCorrespondencePair hψ).source_generic) ∧
      FiniteCorrespondenceGerm.Composes
        (FiniteCorrespondenceGerm.inverseOfPair
          (w.yzCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.ofPair (w.yzCorrespondencePair hψ))
        (FiniteCorrespondenceGerm.identity w.Z.rep
          (w.yzCorrespondencePair hψ).target_generic) :=
  ⟨w.psi_selected_correspondence_composes hψ,
    FiniteCorrespondenceGerm.composes_inverse_right
      (w.xyCorrespondencePair hψ),
    FiniteCorrespondenceGerm.composes_inverse_left
      (w.xyCorrespondencePair hψ),
    FiniteCorrespondenceGerm.composes_inverse_right
      (w.yzCorrespondencePair hψ),
    FiniteCorrespondenceGerm.composes_inverse_left
      (w.yzCorrespondencePair hψ)⟩

/-- The literal `X → Y → Z` chain selected by `Psi` has a common joint
function field finite over the left branch, the right branch, and the
composite endpoint branch.  These are the three finite covers on which
the selected correspondence groupoid can be compared before normalizing. -/
theorem psi_selected_chain_field_finite_covers (hψ : w.Psi) :
    let P := w.xyCorrespondencePair hψ
    let Q := w.yzCorrespondencePair hψ
    FiniteDimensional (↥P.branchField) (↥(P.chainOverLeft Q)) ∧
      FiniteDimensional (↥Q.branchField) (↥(P.chainOverRight Q rfl)) ∧
      FiniteDimensional (↥(P.comp Q rfl).branchField)
        (↥(P.chainOverComposite Q rfl)) := by
  dsimp only
  exact
    ⟨(w.xyCorrespondencePair hψ).chainOverLeft_finiteDimensional
        (w.yzCorrespondencePair hψ) rfl,
      (w.xyCorrespondencePair hψ).chainOverRight_finiteDimensional
        (w.yzCorrespondencePair hψ) rfl,
      (w.xyCorrespondencePair hψ).chainOverComposite_finiteDimensional
        (w.yzCorrespondencePair hψ) rfl⟩

/-- Over an algebraically closed ambient field, the actual `Psi` chain
embeds into a finite normal closure over its selected `(X,Z)` endpoint
branch.  This is the function field of the normalization on which every
ambient conjugate of the shared middle branch is available. -/
theorem psi_selected_chain_normal_cover [IsAlgClosed K] (hψ : w.Psi) :
    let P := w.xyCorrespondencePair hψ
    let Q := w.yzCorrespondencePair hψ
    FiniteDimensional (↥(P.comp Q rfl).branchField)
        (↥(P.chainNormalOverComposite Q rfl)) ∧
      Normal (↥(P.comp Q rfl).branchField)
        (↥(P.chainNormalOverComposite Q rfl)) ∧
      P.chainOverComposite Q rfl ≤
        P.chainNormalOverComposite Q rfl := by
  dsimp only
  exact
    ⟨(w.xyCorrespondencePair hψ).chainNormalOverComposite_finiteDimensional
        (w.yzCorrespondencePair hψ) rfl,
      (w.xyCorrespondencePair hψ).chainNormalOverComposite_normal
        (w.yzCorrespondencePair hψ) rfl,
      (w.xyCorrespondencePair hψ).chainOverComposite_le_normal
        (w.yzCorrespondencePair hψ) rfl⟩

/-- The literal `Psi` component becomes a single selected embedding on
the normal cover, while all ambient conjugate branches and all normal-cover
automorphisms form finite types. -/
theorem psi_selected_chain_component_on_normal_cover (hψ : w.Psi) :
    let P := w.xyCorrespondencePair hψ
    let Q := w.yzCorrespondencePair hψ
    let hle := P.compositeBranchField_le_chainField Q rfl
    (P.chainNormalOverComposite Q rfl).val.comp
          (FiniteCover.selectedEmbedding hle) =
        (P.chainOverComposite Q rfl).val ∧
      Finite ((↥(P.chainOverComposite Q rfl)) →ₐ[
        ↥(P.comp Q rfl).branchField] K) ∧
      Finite ((↥(P.chainNormalOverComposite Q rfl)) ≃ₐ[
        ↥(P.comp Q rfl).branchField]
          (↥(P.chainNormalOverComposite Q rfl))) := by
  dsimp only
  exact
    ⟨FiniteCover.normalClosure_val_comp_selectedEmbedding _,
      FiniteCover.finite_ambientEmbeddings _
        ((w.xyCorrespondencePair hψ).chainOverComposite_finiteDimensional
          (w.yzCorrespondencePair hψ) rfl),
      FiniteCover.finite_normalAutomorphisms _
        ((w.xyCorrespondencePair hψ).chainOverComposite_finiteDimensional
          (w.yzCorrespondencePair hψ) rfl)⟩

/-- In the algebraically closed setting, ambient embeddings of the actual
`Psi` normal cover are exactly its automorphisms over the selected endpoint
branch. -/
noncomputable def psiSelectedChainEmbeddingEquivAut [IsAlgClosed K]
    (hψ : w.Psi) :
    let P := w.xyCorrespondencePair hψ
    let Q := w.yzCorrespondencePair hψ
    ((↥(P.chainNormalOverComposite Q rfl)) →ₐ[
        ↥(P.comp Q rfl).branchField] K) ≃
      ((↥(P.chainNormalOverComposite Q rfl)) ≃ₐ[
        ↥(P.comp Q rfl).branchField]
          (↥(P.chainNormalOverComposite Q rfl))) := by
  dsimp only
  let P := w.xyCorrespondencePair hψ
  let Q := w.yzCorrespondencePair hψ
  let hle := P.compositeBranchField_le_chainField Q rfl
  change ((↥(FiniteCover.normalClosureOver hle)) →ₐ[
      ↥(P.comp Q rfl).branchField] K) ≃
    ((↥(FiniteCover.normalClosureOver hle)) ≃ₐ[
      ↥(P.comp Q rfl).branchField]
        (↥(FiniteCover.normalClosureOver hle)))
  letI : FiniteDimensional (↥(P.comp Q rfl).branchField)
      (↥(extendScalars hle)) :=
    P.chainOverComposite_finiteDimensional Q rfl
  letI : Normal (↥(P.comp Q rfl).branchField)
      (↥(FiniteCover.normalClosureOver hle)) :=
    FiniteCover.normalClosureOver_normal hle
      (Algebra.IsAlgebraic.of_finite
        (↥(P.comp Q rfl).branchField) (↥(extendScalars hle)))
  exact FiniteCover.normalEmbeddingEquivAut hle

/-- The genuine action groupoid of conjugate embeddings of the actual
`Psi` chain into its normal cover. -/
abbrev psiSelectedChainBranchGroupoid (hψ : w.Psi) :=
  finiteCoverBranchGroupoid
    ((w.xyCorrespondencePair hψ).compositeBranchField_le_chainField
      (w.yzCorrespondencePair hψ) rfl)

/-- The literal `(X,Y,Z)` component as the selected object of the `Psi`
normal-cover branch groupoid. -/
def psiSelectedChainBranchObject (hψ : w.Psi) :
    w.psiSelectedChainBranchGroupoid hψ :=
  finiteCoverSelectedObject
    ((w.xyCorrespondencePair hψ).compositeBranchField_le_chainField
      (w.yzCorrespondencePair hψ) rfl)

/-- The normal cover of the selected `Psi` chain has only finitely many
conjugate branch objects. -/
theorem finite_psiSelectedChainBranches (hψ : w.Psi) :
    Finite
      (FiniteCoverBranch
        ((w.xyCorrespondencePair hψ).compositeBranchField_le_chainField
          (w.yzCorrespondencePair hψ) rfl)) :=
  finite_coverBranches _
    ((w.xyCorrespondencePair hψ).chainOverComposite_finiteDimensional
      (w.yzCorrespondencePair hψ) rfl)

/-- Over an algebraically closed ambient field, the conjugate components
of the selected `Psi` chain form a connected genuine groupoid. -/
theorem psiSelectedChainBranchGroupoid_isConnected [IsAlgClosed K]
    (hψ : w.Psi) :
    CategoryTheory.IsConnected (w.psiSelectedChainBranchGroupoid hψ) :=
  finiteCoverBranchGroupoid_isConnected _
    ((w.xyCorrespondencePair hψ).chainOverComposite_finiteDimensional
      (w.yzCorrespondencePair hψ) rfl)

/-- **The rank-five fiber-product calculation for a `Psi` witness.**
The five-tuple `(A₁,A₂,B₁,B₂,Y)` is algebraically independent, and
adjoining the selected outputs `X,Z` does not enlarge its relative
algebraic closure.  This is the dimension assertion in blueprint (8.6),
now obtained from the actual configuration clauses. -/
theorem psi_fiber_product_rank_count (hψ : w.Psi) :
    AlgebraicIndependent k (Fin.snoc w.abReps w.Y.rep) ∧
      racl k (Set.range
        (Fin.snoc
          (Fin.snoc (Fin.snoc w.abReps w.Y.rep) w.X.rep)
          w.Z.rep)) =
        racl k (Set.range (Fin.snoc w.abReps w.Y.rep)) :=
  fiber_product_rank_count
    (w.abReps_independent hψ)
    (w.Y_rep_notMem_racl_abReps hψ)
    (w.X_rep_mem_racl_abReps_snoc_Y hψ)
    (w.Z_rep_mem_racl_abReps_snoc_Y hψ)

end QWitness

end

end AclGeom
