/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Config.Psi
import AclGeom.Correspondence.Composition

/-!
# The rank-five core of the Ψ composition identity

Blueprint equation (8.6) composes the finite correspondence from `Y` to
`X`, parametrized by `A`, with the correspondence from `Y` to `Z`,
parametrized by `B`.  Its first indispensable input is that
`(A₁,A₂,B₁,B₂,Y,X,Z)` is the selected generic point of a rank-five fiber
product.

This module derives that statement directly from the clauses of `Psi`:

* the reverse finite-rank bridge turns `rank_AB` into algebraic
  independence of the four chosen representatives of `A` and `B`;
* `Y_notLe` makes `Y` generic over those four parameters;
* `X_le` and the first projection of `Z_le` make `X` and `Z` algebraic over
  the five generators.

The resulting theorem is the elementwise rank calculation in blueprint
(8.6).  The remaining component-identification step must package the two
parameterized loci as finite-correspondence germs and compare their selected
prime ideals.

**Status:** complete rank-five input for M4a / blueprint (8.6); selected
component identification remains in progress.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

namespace QWitness

variable (w : QWitness k K)

/-- The four representatives of the two rank-two parameter fields `A` and
`B`, in the order used by the fiber-product count. -/
def abReps : Fin 4 → K :=
  ![w.A₁.rep, w.A₂.rep, w.B₁.rep, w.B₂.rep]

/-- The join `A ∨ B` is generated by the four chosen representatives. -/
theorem ab_join_eq_iSup_point :
    w.A ⊔ w.B = ⨆ i, ClosedIF.point k (w.abReps i) := by
  apply le_antisymm
  · refine sup_le (sup_le ?_ ?_) (sup_le ?_ ?_)
    · exact le_iSup_of_le 0 (by simp [abReps])
    · exact le_iSup_of_le 1 (by simp [abReps])
    · exact le_iSup_of_le 2 (by simp [abReps])
    · exact le_iSup_of_le 3 (by simp [abReps])
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · simpa [abReps, A, B] using
        (le_sup_left.trans le_sup_left :
          w.A₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_right.trans le_sup_left :
          w.A₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_left.trans le_sup_right :
          w.B₁.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))
    · simpa [abReps, A, B] using
        (le_sup_right.trans le_sup_right :
          w.B₂.1 ≤ (w.A₁.1 ⊔ w.A₂.1) ⊔ (w.B₁.1 ⊔ w.B₂.1))

/-- Clause `rank_AB` forces the displayed representatives of `A` and `B`
to be algebraically independent. -/
theorem abReps_independent (hψ : w.Psi) :
    AlgebraicIndependent k w.abReps := by
  apply algebraicIndependent_of_rankEq_iSup_point
  rw [← w.ab_join_eq_iSup_point]
  exact hψ.rank_AB

/-- Clause `Y_notLe` says that `Y` is generic over the four `A,B`
parameters. -/
theorem Y_rep_notMem_racl_abReps (hψ : w.Psi) :
    w.Y.rep ∉ racl k (Set.range w.abReps) := by
  intro hY
  apply hψ.Y_notLe
  have hpoint : w.Y.1 ≤ ⨆ i, ClosedIF.point k (w.abReps i) := by
    rw [← w.Y.point_rep]
    exact ClosedIF.point_le_iff.2
      (mem_iSup_point_iff.2 hY)
  rw [← w.ab_join_eq_iSup_point] at hpoint
  exact hpoint.trans le_sup_left

/-- The incidence `X ≤ A ∨ Y` makes `X` algebraic over
`(A₁,A₂,B₁,B₂,Y)` (the unused `B` parameters are harmless). -/
theorem X_rep_mem_racl_abReps_snoc_Y (hψ : w.Psi) :
    w.X.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 5, ClosedIF.point k
      ((Fin.snoc (w.abReps : Fin 4 → K) w.Y.rep : Fin 5 → K) i)
  have hA₁ : w.A₁.1 ≤ E :=
    le_iSup_of_le 0 (by simp [abReps])
  have hA₂ : w.A₂.1 ≤ E :=
    le_iSup_of_le 1 (by simp [abReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 4) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hX : w.X.1 ≤ E :=
    hψ.X_le.trans (sup_le (sup_le hA₁ hA₂) hY)
  exact mem_iSup_point_iff.1 (hX w.X.mem_rep)

/-- The first projection of `Z_le` makes `Z` algebraic over
`(A₁,A₂,B₁,B₂,Y)`. -/
theorem Z_rep_mem_racl_abReps_snoc_Y (hψ : w.Psi) :
    w.Z.rep ∈ racl k
      (Set.range (Fin.snoc w.abReps w.Y.rep)) := by
  let E : ClosedIF k K :=
    ⨆ i : Fin 5, ClosedIF.point k
      ((Fin.snoc (w.abReps : Fin 4 → K) w.Y.rep : Fin 5 → K) i)
  have hB₁ : w.B₁.1 ≤ E :=
    le_iSup_of_le 2 (by simp [abReps])
  have hB₂ : w.B₂.1 ≤ E :=
    le_iSup_of_le 3 (by simp [abReps])
  have hY : w.Y.1 ≤ E := by
    refine le_iSup_of_le (Fin.last 4) ?_
    rw [Fin.snoc_last, w.Y.point_rep]
  have hZ : w.Z.1 ≤ E :=
    hψ.Z_le.trans inf_le_left |>.trans
      (sup_le (sup_le hB₁ hB₂) hY)
  exact mem_iSup_point_iff.1 (hZ w.Z.mem_rep)

/-- **The rank-five fiber-product calculation for a `Psi` witness.**
The five-tuple `(A₁,A₂,B₁,B₂,Y)` is algebraically independent, and
adjoining the selected outputs `X,Z` does not enlarge its relative
algebraic closure.  This is the dimension assertion in blueprint (8.6),
now obtained from the actual configuration clauses. -/
theorem psi_fiber_product_rank_count (hψ : w.Psi) :
    AlgebraicIndependent k (Fin.snoc w.abReps w.Y.rep) ∧
      racl k (Set.range
        (Fin.snoc
          (Fin.snoc (Fin.snoc w.abReps w.Y.rep) w.X.rep)
          w.Z.rep)) =
        racl k (Set.range (Fin.snoc w.abReps w.Y.rep)) :=
  fiber_product_rank_count
    (w.abReps_independent hψ)
    (w.Y_rep_notMem_racl_abReps hψ)
    (w.X_rep_mem_racl_abReps_snoc_Y hψ)
    (w.Z_rep_mem_racl_abReps_snoc_Y hψ)

end QWitness

end

end AclGeom
