/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Config.Quadrangle

/-!
# The seven meet equations of the soundness witness

Clause (vii) of Ψ at the table-7.1 witness. Each meet is a literal
independent-variable intersection (blueprint eq. 8.9a):

`racl k(U,V) ∩ racl k(U,W) = racl k(U)` for independent `U, V, W` —

which in this formalization is exactly the exchange brick
`mem_racl_of_mem_racl_insert` proved for the multiplicative endgame of
the hard kernel; no linear-disjointness machinery is needed. The
workhorse `sup_point_inf_sup_point_eq` packages it: after the birational
coordinate changes of the blueprint's table, every meet has the form
`(point p₁ ∨ point p₂) ∧ (point q₁ ∨ point q₂) = point m` with the two
sides generated by `{m, s}` and `{m, t}` and `t` not algebraic over
`{s, m}`.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M4, checklist G3 soundness, clause (vii)).
-/

namespace AclGeom

noncomputable section

variable {k : Type*} {K : Type*} [Field k] [Field K] [Algebra k K]

/-- Membership in a join of two principal closures. -/
theorem ClosedIF.mem_sup_point_iff {u v z : K} :
    z ∈ ClosedIF.point k u ⊔ ClosedIF.point k v ↔
      z ∈ racl k ({u, v} : Set K) := by
  rw [ClosedIF.mem_sup_iff, ClosedIF.coe_set_point, ClosedIF.coe_set_point,
    racl_union_left, racl_union_right, Set.singleton_union]

/-- **The meet workhorse** (blueprint eq. 8.9a in lattice form): if two
plane joins are generated by `{m, s}` and `{m, t}` with `t` not algebraic
over `{s, m}`, their meet is the point of `m`. The proof is the exchange
argument of `mem_racl_of_mem_racl_insert`. -/
theorem sup_point_inf_sup_point_eq {p₁ p₂ q₁ q₂ m s t : K}
    (hE : racl k ({p₁, p₂} : Set K) = racl k ({m, s} : Set K))
    (hF : racl k ({q₁, q₂} : Set K) = racl k ({m, t} : Set K))
    (ht : t ∉ racl k ({s, m} : Set K)) :
    (ClosedIF.point k p₁ ⊔ ClosedIF.point k p₂) ⊓
      (ClosedIF.point k q₁ ⊔ ClosedIF.point k q₂) =
      ClosedIF.point k m := by
  refine le_antisymm ?_ ?_
  · rw [ClosedIF.le_iff]
    intro z hz
    have hz' : z ∈ (ClosedIF.point k p₁ ⊔ ClosedIF.point k p₂) ⊓
        (ClosedIF.point k q₁ ⊔ ClosedIF.point k q₂) := hz
    rw [ClosedIF.mem_inf_iff] at hz'
    obtain ⟨hzE, hzF⟩ := hz'
    rw [ClosedIF.mem_sup_point_iff, hE] at hzE
    rw [ClosedIF.mem_sup_point_iff, hF] at hzF
    have hzE' : z ∈ racl k (insert s ({m} : Set K)) := by
      rwa [Set.pair_comm m s] at hzE
    have hzF' : z ∈ racl k (insert t ({m} : Set K)) := by
      rwa [Set.pair_comm m t] at hzF
    exact mem_racl_of_mem_racl_insert hzE' hzF' ht
  · refine le_inf ?_ ?_
    · refine ClosedIF.point_le_iff.2 ?_
      rw [ClosedIF.mem_sup_point_iff, hE]
      exact subset_racl k _ (by simp)
    · refine ClosedIF.point_le_iff.2 ?_
      rw [ClosedIF.mem_sup_point_iff, hF]
      exact subset_racl k _ (by simp)

section QTable

variable {a b c d x : K} (hind : AlgebraicIndependent k ![a, b, c, d, x])

include hind

/-- The exchange side condition for meet `D`: `a` is not algebraic over
`{b, ax}` — otherwise exchange would put `ax` in `racl{a, b}` and hence
`x` there too. -/
theorem qtable_a_notMem_b_ax : a ∉ racl k ({b, a * x} : Set K) := by
  intro hmem
  have hab : a ∉ racl k ({b} : Set K) := qtable_a_notMem_b hind
  have hmem' : a ∈ racl k (insert (a * x) ({b} : Set K)) := by
    rwa [Set.pair_comm b (a * x)] at hmem
  have hax : a * x ∈ racl k (insert a ({b} : Set K)) :=
    racl_exchange hmem' hab
  have hax' : a * x ∈ racl k ({a, b} : Set K) := hax
  have ha : a ∈ racl k ({a, b} : Set K) := subset_racl k _ (by simp)
  have hx : x ∈ racl k ({a, b} : Set K) := by
    have h := MulMemClass.mul_mem (inv_mem ha) hax'
    rwa [inv_mul_cancel_left₀ (qtable_a_ne_zero hind)] at h
  exact qtable_x_notMem_ab hind hx

/-- Meet `D` of clause (vii): `(P ∨ Y) ∧ (S ∨ X) = D`, i.e.
`([b] ∨ [ax+b]) ∧ ([a] ∨ [x]) = [ax]`. -/
theorem qWitness_meet_D :
    ((qWitness hind).P.1 ⊔ (qWitness hind).Y.1) ⊓
      ((qWitness hind).S.1 ⊔ (qWitness hind).X.1) =
      (qWitness hind).D.1 := by
  show (ClosedIF.point k b ⊔ ClosedIF.point k (a * x + b)) ⊓
    (ClosedIF.point k a ⊔ ClosedIF.point k x) =
    ClosedIF.point k (a * x)
  refine sup_point_inf_sup_point_eq (s := b) (t := a) ?_ ?_ ?_
  · -- racl {b, ax+b} = racl {ax, b}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hax : a * x ∈ racl k ({a * x, b} : Set K) :=
        subset_racl k _ (by simp)
      have hb : b ∈ racl k ({a * x, b} : Set K) :=
        subset_racl k _ (by simp)
      exact add_mem hax hb
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hY : a * x + b ∈ racl k ({b, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      have hb : b ∈ racl k ({b, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      have h := sub_mem hY hb
      rwa [add_sub_cancel_right] at h
  · -- racl {a, x} = racl {ax, a}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have ha : a ∈ racl k ({a * x, a} : Set K) :=
        subset_racl k _ (by simp)
      have hax : a * x ∈ racl k ({a * x, a} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem ha) hax
      rwa [inv_mul_cancel_left₀ (qtable_a_ne_zero hind)] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have ha : a ∈ racl k ({a, x} : Set K) := subset_racl k _ (by simp)
      have hx : x ∈ racl k ({a, x} : Set K) := subset_racl k _ (by simp)
      exact MulMemClass.mul_mem ha hx
  · exact qtable_a_notMem_b_ax hind

/-- The exchange side condition for meet `G`: `d` is not algebraic over
`{b, bc}`. -/
theorem qtable_d_notMem_b_bc : d ∉ racl k ({b, b * c} : Set K) := by
  intro hmem
  have hsub : racl k ({b, b * c} : Set K) ≤ racl k ({b, c} : Set K) := by
    refine racl_le_of_subset_racl ?_
    rintro z (rfl | rfl)
    · exact subset_racl k _ (by simp)
    · have hb : b ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      have hc : c ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      exact MulMemClass.mul_mem hb hc
  exact qtable_d_notMem_bc hind (hsub hmem)

/-- Meet `G` of clause (vii): `(P ∨ T) ∧ (Q ∨ R) = G`, i.e.
`([b] ∨ [c]) ∧ ([d] ∨ [bc+d]) = [bc]`. -/
theorem qWitness_meet_G :
    ((qWitness hind).P.1 ⊔ (qWitness hind).T.1) ⊓
      ((qWitness hind).Q.1 ⊔ (qWitness hind).R.1) =
      (qWitness hind).G.1 := by
  show (ClosedIF.point k b ⊔ ClosedIF.point k c) ⊓
    (ClosedIF.point k d ⊔ ClosedIF.point k (b * c + d)) =
    ClosedIF.point k (b * c)
  refine sup_point_inf_sup_point_eq (s := b) (t := d) ?_ ?_ ?_
  · -- racl {b, c} = racl {bc, b}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hbc : b * c ∈ racl k ({b * c, b} : Set K) :=
        subset_racl k _ (by simp)
      have hb : b ∈ racl k ({b * c, b} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem hb) hbc
      rwa [inv_mul_cancel_left₀ (qtable_b_ne_zero hind)] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hb : b ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      have hc : c ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      exact MulMemClass.mul_mem hb hc
  · -- racl {d, bc+d} = racl {bc, d}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hbc : b * c ∈ racl k ({b * c, d} : Set K) :=
        subset_racl k _ (by simp)
      have hd : d ∈ racl k ({b * c, d} : Set K) :=
        subset_racl k _ (by simp)
      exact add_mem hbc hd
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hR : b * c + d ∈ racl k ({d, b * c + d} : Set K) :=
        subset_racl k _ (by simp)
      have hd : d ∈ racl k ({d, b * c + d} : Set K) :=
        subset_racl k _ (by simp)
      have h := sub_mem hR hd
      rwa [add_sub_cancel_right] at h
  · exact qtable_d_notMem_b_bc hind


/-- `b` is not algebraic over `a` (pair projection). -/
theorem qtable_b_notMem_a : b ∉ racl k ({a} : Set K) := by
  have h : AlgebraicIndependent k ![a, b] := by
    simpa using AlgebraicIndependent.comp_pair hind
      (i := 0) (j := 1) (by decide)
  exact AlgebraicIndependent.notMem_racl_pair h

theorem qtable_d_notMem_abc : d ∉ racl k ({a, b, c} : Set K) := by
  have h := AlgebraicIndependent.notMem_racl_image hind
    (S := {0, 1, 2}) (i := 3) (by decide)
  simpa [Set.image_insert_eq] using h

/-- The exchange side condition for meet `E`: `d ∉ racl{c, cY}`. -/
theorem qtable_d_notMem_c_cY :
    d ∉ racl k ({c, c * (a * x + b)} : Set K) := by
  intro hmem
  have hsub : racl k ({c, c * (a * x + b)} : Set K) ≤
      racl k ({a, b, c, x} : Set K) := by
    refine racl_le_of_subset_racl ?_
    rw [Set.insert_subset_iff, Set.singleton_subset_iff]
    have ha : a ∈ racl k ({a, b, c, x} : Set K) := subset_racl k _ (by simp)
    have hb : b ∈ racl k ({a, b, c, x} : Set K) := subset_racl k _ (by simp)
    have hc : c ∈ racl k ({a, b, c, x} : Set K) := subset_racl k _ (by simp)
    have hx : x ∈ racl k ({a, b, c, x} : Set K) := subset_racl k _ (by simp)
    exact ⟨hc, MulMemClass.mul_mem hc
      (add_mem (MulMemClass.mul_mem ha hx) hb)⟩
  exact qtable_d_notMem_abcx hind (hsub hmem)

/-- Meet `E` of clause (vii): `(T ∨ Y) ∧ (Q ∨ Z) = E`, i.e.
`([c] ∨ [ax+b]) ∧ ([d] ∨ [c(ax+b)+d]) = [c(ax+b)]`. -/
theorem qWitness_meet_E :
    ((qWitness hind).T.1 ⊔ (qWitness hind).Y.1) ⊓
      ((qWitness hind).Q.1 ⊔ (qWitness hind).Z.1) =
      (qWitness hind).E.1 := by
  show (ClosedIF.point k c ⊔ ClosedIF.point k (a * x + b)) ⊓
    (ClosedIF.point k d ⊔ ClosedIF.point k (c * (a * x + b) + d)) =
    ClosedIF.point k (c * (a * x + b))
  refine sup_point_inf_sup_point_eq (s := c) (t := d) ?_ ?_ ?_
  · -- racl {c, ax+b} = racl {c(ax+b), c}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hc : c ∈ racl k ({c * (a * x + b), c} : Set K) :=
        subset_racl k _ (by simp)
      have hcY : c * (a * x + b) ∈ racl k ({c * (a * x + b), c} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem hc) hcY
      rwa [inv_mul_cancel_left₀ (qtable_c_ne_zero hind)] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      have hc : c ∈ racl k ({c, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      have hY : a * x + b ∈ racl k ({c, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      exact ⟨MulMemClass.mul_mem hc hY, hc⟩
  · -- racl {d, c(ax+b)+d} = racl {c(ax+b), d}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hcY : c * (a * x + b) ∈
          racl k ({c * (a * x + b), d} : Set K) :=
        subset_racl k _ (by simp)
      have hd : d ∈ racl k ({c * (a * x + b), d} : Set K) :=
        subset_racl k _ (by simp)
      exact add_mem hcY hd
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      have hZ : c * (a * x + b) + d ∈
          racl k ({d, c * (a * x + b) + d} : Set K) :=
        subset_racl k _ (by simp)
      have hd : d ∈ racl k ({d, c * (a * x + b) + d} : Set K) :=
        subset_racl k _ (by simp)
      have h := sub_mem hZ hd
      rw [add_sub_cancel_right] at h
      exact ⟨h, hd⟩
  · exact qtable_d_notMem_c_cY hind

/-- `c` is not algebraic over `ac` alone. -/
theorem qtable_c_notMem_acm : c ∉ racl k ({a * c} : Set K) := by
  intro hmem
  have hc0 : c ∉ racl k (∅ : Set K) := fun h ↦
    qtable_c_notMem_a hind (racl_mono (Set.empty_subset _) h)
  have hmem' : c ∈ racl k (insert (a * c) (∅ : Set K)) := by
    simpa using hmem
  have h := racl_exchange hmem' hc0
  have h' : a * c ∈ racl k ({c} : Set K) := by
    simpa using h
  exact qtable_ac_notMem_c hind h'

/-- The exchange side condition for meet `F`: `c ∉ racl{ac, acx}`. -/
theorem qtable_c_notMem_ac_acx :
    c ∉ racl k ({a * c, a * c * x} : Set K) := by
  intro hmem
  have heq : racl k ({a * c, a * c * x} : Set K) =
      racl k ({a * c, x} : Set K) := by
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hac : a * c ∈ racl k ({a * c, x} : Set K) :=
        subset_racl k _ (by simp)
      have hx : x ∈ racl k ({a * c, x} : Set K) :=
        subset_racl k _ (by simp)
      exact MulMemClass.mul_mem hac hx
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hac : a * c ∈ racl k ({a * c, a * c * x} : Set K) :=
        subset_racl k _ (by simp)
      have hacx : a * c * x ∈ racl k ({a * c, a * c * x} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem hac) hacx
      rwa [inv_mul_cancel_left₀ (mul_ne_zero (qtable_a_ne_zero hind)
        (qtable_c_ne_zero hind))] at h
  rw [heq] at hmem
  have hmem' : c ∈ racl k (insert x ({a * c} : Set K)) := by
    rwa [Set.pair_comm (a * c) x] at hmem
  have hx := racl_exchange hmem' (qtable_c_notMem_acm hind)
  have hx' : x ∈ racl k ({c, a * c} : Set K) := hx
  have hsub : racl k ({c, a * c} : Set K) ≤ racl k ({a, c} : Set K) := by
    refine racl_le_of_subset_racl ?_
    rw [Set.insert_subset_iff, Set.singleton_subset_iff]
    have ha : a ∈ racl k ({a, c} : Set K) := subset_racl k _ (by simp)
    have hc : c ∈ racl k ({a, c} : Set K) := subset_racl k _ (by simp)
    exact ⟨hc, MulMemClass.mul_mem ha hc⟩
  exact qtable_x_notMem_ac hind (hsub hx')

/-- Meet `F` of clause (vii): `(U ∨ X) ∧ (T ∨ D) = F`, i.e.
`([ac] ∨ [x]) ∧ ([c] ∨ [ax]) = [acx]`. -/
theorem qWitness_meet_F :
    ((qWitness hind).U.1 ⊔ (qWitness hind).X.1) ⊓
      ((qWitness hind).T.1 ⊔ (qWitness hind).D.1) =
      (qWitness hind).F.1 := by
  show (ClosedIF.point k (a * c) ⊔ ClosedIF.point k x) ⊓
    (ClosedIF.point k c ⊔ ClosedIF.point k (a * x)) =
    ClosedIF.point k (a * c * x)
  refine sup_point_inf_sup_point_eq (s := a * c) (t := c) ?_ ?_ ?_
  · -- racl {ac, x} = racl {acx, ac}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hac : a * c ∈ racl k ({a * c * x, a * c} : Set K) :=
        subset_racl k _ (by simp)
      have hacx : a * c * x ∈ racl k ({a * c * x, a * c} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem hac) hacx
      rwa [inv_mul_cancel_left₀ (mul_ne_zero (qtable_a_ne_zero hind)
        (qtable_c_ne_zero hind))] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      have hac : a * c ∈ racl k ({a * c, x} : Set K) :=
        subset_racl k _ (by simp)
      have hx : x ∈ racl k ({a * c, x} : Set K) :=
        subset_racl k _ (by simp)
      exact ⟨MulMemClass.mul_mem hac hx, hac⟩
  · -- racl {c, ax} = racl {acx, c}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hc : c ∈ racl k ({a * c * x, c} : Set K) :=
        subset_racl k _ (by simp)
      have hacx : a * c * x ∈ racl k ({a * c * x, c} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem hc) hacx
      have harith : c⁻¹ * (a * c * x) = a * x := by
        have hr : a * c * x = c * (a * x) := by ring
        rw [hr, inv_mul_cancel_left₀ (qtable_c_ne_zero hind)]
      rwa [harith] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      have hc : c ∈ racl k ({c, a * x} : Set K) :=
        subset_racl k _ (by simp)
      have hax : a * x ∈ racl k ({c, a * x} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem hc hax
      have harith : c * (a * x) = a * c * x := by ring
      rw [harith] at h
      exact ⟨h, hc⟩
  · exact qtable_c_notMem_ac_acx hind

/-- `b` is not algebraic over `a/b` alone. -/
theorem qtable_b_notMem_hdiv : b ∉ racl k ({a / b} : Set K) := by
  intro hmem
  have ha : a ∈ racl k ({a / b} : Set K) := by
    have hq : a / b ∈ racl k ({a / b} : Set K) := subset_racl k _ rfl
    have h := MulMemClass.mul_mem hq hmem
    rwa [div_mul_cancel₀ a (qtable_b_ne_zero hind)] at h
  have ha0 : a ∉ racl k (∅ : Set K) := fun h ↦
    qtable_a_notMem_b hind (racl_mono (Set.empty_subset _) h)
  have ha' : a ∈ racl k (insert (a / b) (∅ : Set K)) := by
    simpa using ha
  have h := racl_exchange ha' ha0
  have h' : a / b ∈ racl k ({a} : Set K) := by
    simpa using h
  have hb : b ∈ racl k ({a} : Set K) := by
    have haa : a ∈ racl k ({a} : Set K) := subset_racl k _ rfl
    have hq0 : a / b ≠ 0 :=
      div_ne_zero (qtable_a_ne_zero hind) (qtable_b_ne_zero hind)
    have h2 := MulMemClass.mul_mem haa (inv_mem h')
    have ha0 : a ≠ 0 := qtable_a_ne_zero hind
    have hb0 : b ≠ 0 := qtable_b_ne_zero hind
    have harith : a * (a / b)⁻¹ = b := by
      field_simp
    rwa [harith] at h2
  exact qtable_b_notMem_a hind hb

/-- The exchange side condition for meet `I`: `b ∉ racl{a/b, ax/b}`. -/
theorem qtable_b_notMem_hdiv_axb :
    b ∉ racl k ({a / b, a * x / b} : Set K) := by
  intro hmem
  have heq : racl k ({a / b, a * x / b} : Set K) =
      racl k ({a / b, x} : Set K) := by
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hq : a / b ∈ racl k ({a / b, x} : Set K) :=
        subset_racl k _ (by simp)
      have hx : x ∈ racl k ({a / b, x} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem hq hx
      have harith : a / b * x = a * x / b := by ring
      rwa [harith] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hq : a / b ∈ racl k ({a / b, a * x / b} : Set K) :=
        subset_racl k _ (by simp)
      have haxb : a * x / b ∈ racl k ({a / b, a * x / b} : Set K) :=
        subset_racl k _ (by simp)
      have hq0 : a / b ≠ 0 :=
        div_ne_zero (qtable_a_ne_zero hind) (qtable_b_ne_zero hind)
      have h := MulMemClass.mul_mem (inv_mem hq) haxb
      have ha0 : a ≠ 0 := qtable_a_ne_zero hind
      have hb0 : b ≠ 0 := qtable_b_ne_zero hind
      have harith : (a / b)⁻¹ * (a * x / b) = x := by
        field_simp
      rwa [harith] at h
  rw [heq] at hmem
  have hmem' : b ∈ racl k (insert x ({a / b} : Set K)) := by
    rwa [Set.pair_comm (a / b) x] at hmem
  have hx := racl_exchange hmem' (qtable_b_notMem_hdiv hind)
  have hx' : x ∈ racl k ({b, a / b} : Set K) := hx
  have hsub : racl k ({b, a / b} : Set K) ≤ racl k ({a, b} : Set K) := by
    refine racl_le_of_subset_racl ?_
    rw [Set.insert_subset_iff, Set.singleton_subset_iff]
    have ha : a ∈ racl k ({a, b} : Set K) := subset_racl k _ (by simp)
    have hb : b ∈ racl k ({a, b} : Set K) := subset_racl k _ (by simp)
    have h2 := MulMemClass.mul_mem ha (inv_mem hb)
    rw [← div_eq_mul_inv] at h2
    exact ⟨hb, h2⟩
  exact qtable_x_notMem_ab hind (hsub hx')

/-- Meet `I` of clause (vii): `(H ∨ X) ∧ (P ∨ Y) = I`, i.e.
`([a/b] ∨ [x]) ∧ ([b] ∨ [ax+b]) = [ax/b]`. -/
theorem qWitness_meet_I :
    ((qWitness hind).H.1 ⊔ (qWitness hind).X.1) ⊓
      ((qWitness hind).P.1 ⊔ (qWitness hind).Y.1) =
      (qWitness hind).I.1 := by
  show (ClosedIF.point k (a / b) ⊔ ClosedIF.point k x) ⊓
    (ClosedIF.point k b ⊔ ClosedIF.point k (a * x + b)) =
    ClosedIF.point k (a * x / b)
  refine sup_point_inf_sup_point_eq (s := a / b) (t := b) ?_ ?_ ?_
  · -- racl {a/b, x} = racl {ax/b, a/b}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hq : a / b ∈ racl k ({a * x / b, a / b} : Set K) :=
        subset_racl k _ (by simp)
      have haxb : a * x / b ∈ racl k ({a * x / b, a / b} : Set K) :=
        subset_racl k _ (by simp)
      have hq0 : a / b ≠ 0 :=
        div_ne_zero (qtable_a_ne_zero hind) (qtable_b_ne_zero hind)
      have h := MulMemClass.mul_mem (inv_mem hq) haxb
      have ha0 : a ≠ 0 := qtable_a_ne_zero hind
      have hb0 : b ≠ 0 := qtable_b_ne_zero hind
      have harith : (a / b)⁻¹ * (a * x / b) = x := by
        field_simp
      rwa [harith] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      have hq : a / b ∈ racl k ({a / b, x} : Set K) :=
        subset_racl k _ (by simp)
      have hx : x ∈ racl k ({a / b, x} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem hq hx
      have harith : a / b * x = a * x / b := by ring
      rw [harith] at h
      exact ⟨h, hq⟩
  · -- racl {b, ax+b} = racl {ax/b, b}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hb : b ∈ racl k ({a * x / b, b} : Set K) :=
        subset_racl k _ (by simp)
      have haxb : a * x / b ∈ racl k ({a * x / b, b} : Set K) :=
        subset_racl k _ (by simp)
      have h := add_mem (MulMemClass.mul_mem haxb hb) hb
      have harith : a * x / b * b + b = a * x + b := by
        rw [div_mul_cancel₀ _ (qtable_b_ne_zero hind)]
      rwa [harith] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      have hb : b ∈ racl k ({b, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      have hY : a * x + b ∈ racl k ({b, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (sub_mem hY hb) (inv_mem hb)
      have harith : (a * x + b - b) * b⁻¹ = a * x / b := by
        rw [add_sub_cancel_right, div_eq_mul_inv]
      rw [harith] at h
      exact ⟨h, hb⟩
  · exact qtable_b_notMem_hdiv_axb hind

/-- `c ∉ racl{ac, b}` — exchange against the pair `{c, b}`. -/
theorem qtable_c_notMem_ac_b : c ∉ racl k ({a * c, b} : Set K) := by
  intro hmem
  have hmem' : c ∈ racl k (insert (a * c) ({b} : Set K)) := hmem
  have hcb : c ∉ racl k ({b} : Set K) := qtable_c_notMem_b hind
  have h := racl_exchange hmem' hcb
  have h' : a * c ∈ racl k ({c, b} : Set K) := h
  have hc : c ∈ racl k ({c, b} : Set K) := subset_racl k _ (by simp)
  have ha : a ∈ racl k ({c, b} : Set K) := by
    have h2 := MulMemClass.mul_mem h' (inv_mem hc)
    rwa [mul_inv_cancel_right₀ (qtable_c_ne_zero hind)] at h2
  exact qtable_a_notMem_cb hind ha

/-- The exchange side condition for meet `H`: `b ∉ racl{ac, a/b}`. -/
theorem qtable_b_notMem_ac_hdiv :
    b ∉ racl k ({a * c, a / b} : Set K) := by
  intro hmem
  have hmem' : b ∈ racl k (insert (a / b) ({a * c} : Set K)) := by
    rwa [Set.pair_comm (a * c) (a / b)] at hmem
  have hbac : b ∉ racl k ({a * c} : Set K) := by
    intro h
    have hsub : racl k ({a * c} : Set K) ≤ racl k ({a, c} : Set K) := by
      refine racl_le_of_subset_racl (Set.singleton_subset_iff.2 ?_)
      have ha : a ∈ racl k ({a, c} : Set K) := subset_racl k _ (by simp)
      have hc : c ∈ racl k ({a, c} : Set K) := subset_racl k _ (by simp)
      exact MulMemClass.mul_mem ha hc
    exact qtable_b_notMem_ac hind (hsub h)
  have h := racl_exchange hmem' hbac
  have h' : a / b ∈ racl k ({b, a * c} : Set K) := h
  have hb : b ∈ racl k ({b, a * c} : Set K) := subset_racl k _ (by simp)
  have ha : a ∈ racl k ({b, a * c} : Set K) := by
    have h2 := MulMemClass.mul_mem h' hb
    rwa [div_mul_cancel₀ a (qtable_b_ne_zero hind)] at h2
  have hc : c ∈ racl k ({b, a * c} : Set K) := by
    have hac : a * c ∈ racl k ({b, a * c} : Set K) :=
      subset_racl k _ (by simp)
    have h2 := MulMemClass.mul_mem (inv_mem ha) hac
    rwa [inv_mul_cancel_left₀ (qtable_a_ne_zero hind)] at h2
  exact qtable_c_notMem_ac_b hind (by
    have hsub : racl k ({b, a * c} : Set K) ≤
        racl k ({a * c, b} : Set K) := by
      refine racl_le_of_subset_racl ?_
      rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      exact ⟨subset_racl k _ (by simp), subset_racl k _ (by simp)⟩
    exact hsub hc)

/-- Meet `H` of clause (vii): `(U ∨ G) ∧ A = H`, i.e.
`([ac] ∨ [bc]) ∧ ([a] ∨ [b]) = [a/b]`. -/
theorem qWitness_meet_H :
    ((qWitness hind).U.1 ⊔ (qWitness hind).G.1) ⊓ (qWitness hind).A =
      (qWitness hind).H.1 := by
  show (ClosedIF.point k (a * c) ⊔ ClosedIF.point k (b * c)) ⊓
    (ClosedIF.point k a ⊔ ClosedIF.point k b) =
    ClosedIF.point k (a / b)
  refine sup_point_inf_sup_point_eq (s := a * c) (t := b) ?_ ?_ ?_
  · -- racl {ac, bc} = racl {a/b, ac}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hq : a / b ∈ racl k ({a / b, a * c} : Set K) :=
        subset_racl k _ (by simp)
      have hac : a * c ∈ racl k ({a / b, a * c} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem hq) hac
      have harith : (a / b)⁻¹ * (a * c) = b * c := by
        rw [inv_div, div_mul_eq_mul_div]
        have hr : b * (a * c) = a * (b * c) := by ring
        rw [hr, mul_div_cancel_left₀ _ (qtable_a_ne_zero hind)]
      rwa [harith] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hac : a * c ∈ racl k ({a * c, b * c} : Set K) :=
        subset_racl k _ (by simp)
      have hbc : b * c ∈ racl k ({a * c, b * c} : Set K) :=
        subset_racl k _ (by simp)
      have hbc0 : b * c ≠ 0 :=
        mul_ne_zero (qtable_b_ne_zero hind) (qtable_c_ne_zero hind)
      have h := MulMemClass.mul_mem hac (inv_mem hbc)
      have ha0 : a ≠ 0 := qtable_a_ne_zero hind
      have hb0 : b ≠ 0 := qtable_b_ne_zero hind
      have hc0 : c ≠ 0 := qtable_c_ne_zero hind
      have harith : a * c * (b * c)⁻¹ = a / b := by
        field_simp
      rwa [harith] at h
  · -- racl {a, b} = racl {a/b, b}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hq : a / b ∈ racl k ({a / b, b} : Set K) :=
        subset_racl k _ (by simp)
      have hb : b ∈ racl k ({a / b, b} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem hq hb
      rwa [div_mul_cancel₀ a (qtable_b_ne_zero hind)] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have ha : a ∈ racl k ({a, b} : Set K) := subset_racl k _ (by simp)
      have hb : b ∈ racl k ({a, b} : Set K) := subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem ha (inv_mem hb)
      rwa [← div_eq_mul_inv] at h
  · exact qtable_b_notMem_ac_hdiv hind

/-- `ac` is not algebraic over `bc+d` alone. -/
theorem qtable_ac_notMem_bcd : a * c ∉ racl k ({b * c + d} : Set K) := by
  intro hmem
  have hac0 : a * c ∉ racl k (∅ : Set K) := by
    intro h
    have h' : a * c ∈ racl k ({a} : Set K) :=
      racl_mono (Set.empty_subset _) h
    exact qtable_ac_notMem_a hind h'
  have hmem' : a * c ∈ racl k (insert (b * c + d) (∅ : Set K)) := by
    simpa using hmem
  have h := racl_exchange hmem' hac0
  have h' : b * c + d ∈ racl k ({a * c} : Set K) := by
    simpa using h
  have hsub : racl k ({a * c} : Set K) ≤ racl k ({a, b, c} : Set K) := by
    refine racl_le_of_subset_racl (Set.singleton_subset_iff.2 ?_)
    have ha : a ∈ racl k ({a, b, c} : Set K) := subset_racl k _ (by simp)
    have hc : c ∈ racl k ({a, b, c} : Set K) := subset_racl k _ (by simp)
    exact MulMemClass.mul_mem ha hc
  have hbcd : b * c + d ∈ racl k ({a, b, c} : Set K) := hsub h'
  have hb : b ∈ racl k ({a, b, c} : Set K) := subset_racl k _ (by simp)
  have hc : c ∈ racl k ({a, b, c} : Set K) := subset_racl k _ (by simp)
  have hd : d ∈ racl k ({a, b, c} : Set K) := by
    have h2 := sub_mem hbcd (MulMemClass.mul_mem hb hc)
    rwa [add_sub_cancel_left] at h2
  exact qtable_d_notMem_abc hind hd

/-- The exchange side condition for meet `R`: `ac ∉ racl{acx, bc+d}`. -/
theorem qtable_ac_notMem_acx_bcd :
    a * c ∉ racl k ({a * c * x, b * c + d} : Set K) := by
  intro hmem
  have hmem' : a * c ∈
      racl k (insert (a * c * x) ({b * c + d} : Set K)) := hmem
  have h := racl_exchange hmem' (qtable_ac_notMem_bcd hind)
  have h' : a * c * x ∈ racl k ({a * c, b * c + d} : Set K) := h
  have hac : a * c ∈ racl k ({a * c, b * c + d} : Set K) :=
    subset_racl k _ (by simp)
  have hx : x ∈ racl k ({a * c, b * c + d} : Set K) := by
    have h2 := MulMemClass.mul_mem (inv_mem hac) h'
    rwa [inv_mul_cancel_left₀ (mul_ne_zero (qtable_a_ne_zero hind)
      (qtable_c_ne_zero hind))] at h2
  have hsub : racl k ({a * c, b * c + d} : Set K) ≤
      racl k ({a, b, c, d} : Set K) := by
    refine racl_le_of_subset_racl ?_
    rw [Set.insert_subset_iff, Set.singleton_subset_iff]
    have ha : a ∈ racl k ({a, b, c, d} : Set K) := subset_racl k _ (by simp)
    have hb : b ∈ racl k ({a, b, c, d} : Set K) := subset_racl k _ (by simp)
    have hc : c ∈ racl k ({a, b, c, d} : Set K) := subset_racl k _ (by simp)
    have hd : d ∈ racl k ({a, b, c, d} : Set K) := subset_racl k _ (by simp)
    exact ⟨MulMemClass.mul_mem ha hc,
      add_mem (MulMemClass.mul_mem hb hc) hd⟩
  exact qtable_x_notMem_abcd hind (hsub hx)

/-- Meet `R` of clause (vii): `(F ∨ Z) ∧ C = R`, i.e.
`([acx] ∨ [c(ax+b)+d]) ∧ ([ac] ∨ [bc+d]) = [bc+d]`. -/
theorem qWitness_meet_R :
    ((qWitness hind).F.1 ⊔ (qWitness hind).Z.1) ⊓ (qWitness hind).C =
      (qWitness hind).R.1 := by
  show (ClosedIF.point k (a * c * x) ⊔
    ClosedIF.point k (c * (a * x + b) + d)) ⊓
    (ClosedIF.point k (a * c) ⊔ ClosedIF.point k (b * c + d)) =
    ClosedIF.point k (b * c + d)
  refine sup_point_inf_sup_point_eq (s := a * c * x) (t := a * c) ?_ ?_ ?_
  · -- racl {acx, c(ax+b)+d} = racl {bc+d, acx}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hbcd : b * c + d ∈ racl k ({b * c + d, a * c * x} : Set K) :=
        subset_racl k _ (by simp)
      have hacx : a * c * x ∈ racl k ({b * c + d, a * c * x} : Set K) :=
        subset_racl k _ (by simp)
      have h := add_mem hacx hbcd
      have harith : a * c * x + (b * c + d) = c * (a * x + b) + d := by
        ring
      rwa [harith] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hZ : c * (a * x + b) + d ∈
          racl k ({a * c * x, c * (a * x + b) + d} : Set K) :=
        subset_racl k _ (by simp)
      have hacx : a * c * x ∈
          racl k ({a * c * x, c * (a * x + b) + d} : Set K) :=
        subset_racl k _ (by simp)
      have h := sub_mem hZ hacx
      have harith : c * (a * x + b) + d - a * c * x = b * c + d := by
        ring
      rwa [harith] at h
  · -- racl {ac, bc+d} = racl {bc+d, ac}
    rw [Set.pair_comm (a * c) (b * c + d)]
  · exact qtable_ac_notMem_acx_bcd hind

end QTable

end

end AclGeom
