/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Config.WitnessTable

/-!
# The seven meet equations of the soundness witness

Clause (vii) of Ψ at the table-7.1 witness. Each meet is a literal
independent-variable intersection (blueprint eq. 8.9a):

`racl k(U,V) ∩ racl k(U,W) = racl k(U)` for independent `U, V, W` —

which in this formalization is exactly the exchange brick
`mem_racl_of_mem_racl_insert` proved for the multiplicative endgame of
the hard kernel; no linear-disjointness machinery is needed. The
workhorse `sup_point_inf_sup_point_eq` packages it: after the birational
coordinate changes of the blueprint's table, every meet has the form
`(point p₁ ∨ point p₂) ∧ (point q₁ ∨ point q₂) = point m` with the two
sides generated by `{m, s}` and `{m, t}` and `t` not algebraic over
`{s, m}`.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M4, checklist G3 soundness, clause (vii)).
-/

namespace AclGeom

noncomputable section

variable {k : Type*} {K : Type*} [Field k] [Field K] [Algebra k K]

/-- Membership in a join of two principal closures. -/
theorem ClosedIF.mem_sup_point_iff {u v z : K} :
    z ∈ ClosedIF.point k u ⊔ ClosedIF.point k v ↔
      z ∈ racl k ({u, v} : Set K) := by
  rw [ClosedIF.mem_sup_iff, ClosedIF.coe_set_point, ClosedIF.coe_set_point,
    racl_union_left, racl_union_right, Set.singleton_union]

/-- **The meet workhorse** (blueprint eq. 8.9a in lattice form): if two
plane joins are generated by `{m, s}` and `{m, t}` with `t` not algebraic
over `{s, m}`, their meet is the point of `m`. The proof is the exchange
argument of `mem_racl_of_mem_racl_insert`. -/
theorem sup_point_inf_sup_point_eq {p₁ p₂ q₁ q₂ m s t : K}
    (hE : racl k ({p₁, p₂} : Set K) = racl k ({m, s} : Set K))
    (hF : racl k ({q₁, q₂} : Set K) = racl k ({m, t} : Set K))
    (ht : t ∉ racl k ({s, m} : Set K)) :
    (ClosedIF.point k p₁ ⊔ ClosedIF.point k p₂) ⊓
      (ClosedIF.point k q₁ ⊔ ClosedIF.point k q₂) =
      ClosedIF.point k m := by
  refine le_antisymm ?_ ?_
  · rw [ClosedIF.le_iff]
    intro z hz
    have hz' : z ∈ (ClosedIF.point k p₁ ⊔ ClosedIF.point k p₂) ⊓
        (ClosedIF.point k q₁ ⊔ ClosedIF.point k q₂) := hz
    rw [ClosedIF.mem_inf_iff] at hz'
    obtain ⟨hzE, hzF⟩ := hz'
    rw [ClosedIF.mem_sup_point_iff, hE] at hzE
    rw [ClosedIF.mem_sup_point_iff, hF] at hzF
    have hzE' : z ∈ racl k (insert s ({m} : Set K)) := by
      rwa [Set.pair_comm m s] at hzE
    have hzF' : z ∈ racl k (insert t ({m} : Set K)) := by
      rwa [Set.pair_comm m t] at hzF
    exact mem_racl_of_mem_racl_insert hzE' hzF' ht
  · refine le_inf ?_ ?_
    · refine ClosedIF.point_le_iff.2 ?_
      rw [ClosedIF.mem_sup_point_iff, hE]
      exact subset_racl k _ (by simp)
    · refine ClosedIF.point_le_iff.2 ?_
      rw [ClosedIF.mem_sup_point_iff, hF]
      exact subset_racl k _ (by simp)

section QTable

variable {a b c d x : K} (hind : AlgebraicIndependent k ![a, b, c, d, x])

include hind

/-- The exchange side condition for meet `D`: `a` is not algebraic over
`{b, ax}` — otherwise exchange would put `ax` in `racl{a, b}` and hence
`x` there too. -/
theorem qtable_a_notMem_b_ax : a ∉ racl k ({b, a * x} : Set K) := by
  intro hmem
  have hab : a ∉ racl k ({b} : Set K) := qtable_a_notMem_b hind
  have hmem' : a ∈ racl k (insert (a * x) ({b} : Set K)) := by
    rwa [Set.pair_comm b (a * x)] at hmem
  have hax : a * x ∈ racl k (insert a ({b} : Set K)) :=
    racl_exchange hmem' hab
  have hax' : a * x ∈ racl k ({a, b} : Set K) := hax
  have ha : a ∈ racl k ({a, b} : Set K) := subset_racl k _ (by simp)
  have hx : x ∈ racl k ({a, b} : Set K) := by
    have h := MulMemClass.mul_mem (inv_mem ha) hax'
    rwa [inv_mul_cancel_left₀ (qtable_a_ne_zero hind)] at h
  exact qtable_x_notMem_ab hind hx

/-- Meet `D` of clause (vii): `(P ∨ Y) ∧ (S ∨ X) = D`, i.e.
`([b] ∨ [ax+b]) ∧ ([a] ∨ [x]) = [ax]`. -/
theorem qWitness_meet_D :
    ((qWitness hind).P.1 ⊔ (qWitness hind).Y.1) ⊓
      ((qWitness hind).S.1 ⊔ (qWitness hind).X.1) =
      (qWitness hind).D.1 := by
  show (ClosedIF.point k b ⊔ ClosedIF.point k (a * x + b)) ⊓
    (ClosedIF.point k a ⊔ ClosedIF.point k x) =
    ClosedIF.point k (a * x)
  refine sup_point_inf_sup_point_eq (s := b) (t := a) ?_ ?_ ?_
  · -- racl {b, ax+b} = racl {ax, b}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hax : a * x ∈ racl k ({a * x, b} : Set K) :=
        subset_racl k _ (by simp)
      have hb : b ∈ racl k ({a * x, b} : Set K) :=
        subset_racl k _ (by simp)
      exact add_mem hax hb
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hY : a * x + b ∈ racl k ({b, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      have hb : b ∈ racl k ({b, a * x + b} : Set K) :=
        subset_racl k _ (by simp)
      have h := sub_mem hY hb
      rwa [add_sub_cancel_right] at h
  · -- racl {a, x} = racl {ax, a}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have ha : a ∈ racl k ({a * x, a} : Set K) :=
        subset_racl k _ (by simp)
      have hax : a * x ∈ racl k ({a * x, a} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem ha) hax
      rwa [inv_mul_cancel_left₀ (qtable_a_ne_zero hind)] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have ha : a ∈ racl k ({a, x} : Set K) := subset_racl k _ (by simp)
      have hx : x ∈ racl k ({a, x} : Set K) := subset_racl k _ (by simp)
      exact MulMemClass.mul_mem ha hx
  · exact qtable_a_notMem_b_ax hind

/-- The exchange side condition for meet `G`: `d` is not algebraic over
`{b, bc}`. -/
theorem qtable_d_notMem_b_bc : d ∉ racl k ({b, b * c} : Set K) := by
  intro hmem
  have hsub : racl k ({b, b * c} : Set K) ≤ racl k ({b, c} : Set K) := by
    refine racl_le_of_subset_racl ?_
    rintro z (rfl | rfl)
    · exact subset_racl k _ (by simp)
    · have hb : b ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      have hc : c ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      exact MulMemClass.mul_mem hb hc
  exact qtable_d_notMem_bc hind (hsub hmem)

/-- Meet `G` of clause (vii): `(P ∨ T) ∧ (Q ∨ R) = G`, i.e.
`([b] ∨ [c]) ∧ ([d] ∨ [bc+d]) = [bc]`. -/
theorem qWitness_meet_G :
    ((qWitness hind).P.1 ⊔ (qWitness hind).T.1) ⊓
      ((qWitness hind).Q.1 ⊔ (qWitness hind).R.1) =
      (qWitness hind).G.1 := by
  show (ClosedIF.point k b ⊔ ClosedIF.point k c) ⊓
    (ClosedIF.point k d ⊔ ClosedIF.point k (b * c + d)) =
    ClosedIF.point k (b * c)
  refine sup_point_inf_sup_point_eq (s := b) (t := d) ?_ ?_ ?_
  · -- racl {b, c} = racl {bc, b}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hbc : b * c ∈ racl k ({b * c, b} : Set K) :=
        subset_racl k _ (by simp)
      have hb : b ∈ racl k ({b * c, b} : Set K) :=
        subset_racl k _ (by simp)
      have h := MulMemClass.mul_mem (inv_mem hb) hbc
      rwa [inv_mul_cancel_left₀ (qtable_b_ne_zero hind)] at h
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hb : b ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      have hc : c ∈ racl k ({b, c} : Set K) := subset_racl k _ (by simp)
      exact MulMemClass.mul_mem hb hc
  · -- racl {d, bc+d} = racl {bc, d}
    refine racl_congr_of_subset_racl ?_ ?_
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨subset_racl k _ (by simp), ?_⟩
      have hbc : b * c ∈ racl k ({b * c, d} : Set K) :=
        subset_racl k _ (by simp)
      have hd : d ∈ racl k ({b * c, d} : Set K) :=
        subset_racl k _ (by simp)
      exact add_mem hbc hd
    · rw [Set.insert_subset_iff, Set.singleton_subset_iff]
      refine ⟨?_, subset_racl k _ (by simp)⟩
      have hR : b * c + d ∈ racl k ({d, b * c + d} : Set K) :=
        subset_racl k _ (by simp)
      have hd : d ∈ racl k ({d, b * c + d} : Set K) :=
        subset_racl k _ (by simp)
      have h := sub_mem hR hd
      rwa [add_sub_cancel_right] at h
  · exact qtable_d_notMem_b_bc hind

end QTable

end

end AclGeom
