/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.Algebra.Polynomial.Expand
import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
import Mathlib.RingTheory.Ideal.Maps

/-!
# Primality of primitive binomials

Blueprint Lemma `simultaneous-coset` (8.9) compares the additive and
multiplicative coset equations of a correspondence curve through its prime
generator. The multiplicative equation is a *primitive binomial*
`x^m − c·y^n` with coprime exponents; this file proves it is prime, via the
monomial-curve parametrization: the kernel of
`x ↦ α·T^n, y ↦ T^m` (with `α^m = c`) is exactly the ideal generated by the
binomial, and the target `K[T]` is a domain. The kernel computation reduces
a remainder of `y`-degree `< n` along the residues of exponents modulo `n`,
where coprimality makes the classes `m·j mod n` distinct.

Conventions match `eq_monomial_of_eq_smul_binomial`: the outer variable is
`y`, the inner one `x`, so the ambient ring is `(K[x])[y]`.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** stable (M3, checklist C5).
-/

namespace AclGeom

open Polynomial

noncomputable section

variable {K : Type*} [Field K]

/-- Scaling the variable: `p(x) ↦ p(α·x)`, as a ring homomorphism. -/
def compScale (α : K) : Polynomial K →+* Polynomial K :=
  Polynomial.compRingHom (Polynomial.C α * Polynomial.X)

theorem compScale_apply (α : K) (p : Polynomial K) :
    compScale α p = p.comp (Polynomial.C α * Polynomial.X) :=
  Polynomial.coe_compRingHom_apply p _

theorem compScale_injective {α : K} (hα : α ≠ 0) :
    Function.Injective (compScale α) := by
  intro p q h
  have h2 := congrArg (compScale α⁻¹) h
  have hcomp : ∀ r : Polynomial K, compScale α⁻¹ (compScale α r) = r := by
    intro r
    rw [compScale_apply, compScale_apply, Polynomial.comp_assoc]
    have hlin : (Polynomial.C α * Polynomial.X).comp
        (Polynomial.C α⁻¹ * Polynomial.X) = Polynomial.X := by
      rw [Polynomial.mul_comp, Polynomial.C_comp, Polynomial.X_comp,
        ← mul_assoc, ← Polynomial.C_mul, mul_inv_cancel₀ hα,
        Polynomial.C_1, one_mul]
    rw [hlin, Polynomial.comp_X]
  rwa [hcomp, hcomp] at h2

/-- The inner substitution `x ↦ α·T^n`. -/
def innerParam (α : K) (n : ℕ) : Polynomial K →+* Polynomial K :=
  (Polynomial.expand K n).toRingHom.comp (compScale α)

theorem innerParam_apply (α : K) (n : ℕ) (p : Polynomial K) :
    innerParam α n p = Polynomial.expand K n (compScale α p) := rfl

theorem innerParam_injective {α : K} (hα : α ≠ 0) {n : ℕ} (hn : n ≠ 0) :
    Function.Injective (innerParam α n) :=
  (Polynomial.expand_injective (Nat.pos_of_ne_zero hn)).comp
    (compScale_injective hα)

/-- Supports of inner substitutions consist of multiples of `n`. -/
theorem innerParam_coeff_eq_zero {α : K} {n : ℕ} (hn : n ≠ 0)
    (p : Polynomial K) {e : ℕ} (he : ¬ n ∣ e) :
    (innerParam α n p).coeff e = 0 := by
  rw [innerParam_apply, Polynomial.coeff_expand (Nat.pos_of_ne_zero hn),
    if_neg he]

/-- The full parametrization `(K[x])[y] → K[T]`: `y ↦ T^m`, `x ↦ α·T^n`. -/
def binomialParam (α : K) (n m : ℕ) :
    Polynomial (Polynomial K) →+* Polynomial K :=
  Polynomial.eval₂RingHom (innerParam α n) (Polynomial.X ^ m)

theorem binomialParam_C (α : K) (n m : ℕ) (p : Polynomial K) :
    binomialParam α n m (Polynomial.C p) = innerParam α n p := by
  simp [binomialParam]

theorem binomialParam_X (α : K) (n m : ℕ) :
    binomialParam α n m Polynomial.X = Polynomial.X ^ m := by
  simp [binomialParam]

/-- The binomial in the conventions of the coset-comparison lemma. -/
def cosetBinomial (c : K) (m n : ℕ) : Polynomial (Polynomial K) :=
  Polynomial.C ((Polynomial.X : Polynomial K) ^ m) -
    Polynomial.C (Polynomial.C c) * (Polynomial.X : Polynomial (Polynomial K)) ^ n

/-- The parametrization kills the binomial. -/
theorem binomialParam_cosetBinomial {α c : K} (m₀ n₀ : ℕ)
    (hroot : α ^ m₀ = c) :
    binomialParam α n₀ m₀ (cosetBinomial c m₀ n₀) = 0 := by
  have h1 : binomialParam α n₀ m₀
      (Polynomial.C ((Polynomial.X : Polynomial K) ^ m₀)) =
      Polynomial.C (α ^ m₀) * Polynomial.X ^ (n₀ * m₀) := by
    rw [binomialParam_C, map_pow, innerParam_apply, compScale_apply,
      Polynomial.X_comp]
    rw [map_mul, Polynomial.expand_C, Polynomial.expand_X, mul_pow,
      ← Polynomial.C_pow, ← pow_mul]
  have h2 : binomialParam α n₀ m₀
      (Polynomial.C (Polynomial.C c)) = Polynomial.C c := by
    rw [binomialParam_C, innerParam_apply, compScale_apply,
      Polynomial.C_comp, Polynomial.expand_C]
  have h3 : binomialParam α n₀ m₀
      ((Polynomial.X : Polynomial (Polynomial K)) ^ n₀) =
      Polynomial.X ^ (m₀ * n₀) := by
    rw [map_pow, binomialParam_X, ← pow_mul]
  rw [cosetBinomial, map_sub, map_mul, h1, h2, h3, hroot, mul_comm n₀ m₀,
    sub_self]

/-- **The kernel of the parametrization**: a polynomial killed by the
monomial-curve substitution is a multiple of the binomial. -/
theorem cosetBinomial_dvd_of_binomialParam_eq_zero {α c : K} (hα : α ≠ 0)
    (hc : c ≠ 0) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0)
    (hcop : Nat.gcd m n = 1) (hroot : α ^ m = c)
    {f : Polynomial (Polynomial K)} (hf : binomialParam α n m f = 0) :
    cosetBinomial c m n ∣ f := by
  classical
  set bmon : Polynomial (Polynomial K) :=
    Polynomial.X ^ n - Polynomial.C (Polynomial.C c⁻¹ * Polynomial.X ^ m)
    with hbmon
  have hmonic : bmon.Monic := Polynomial.monic_X_pow_sub_C _ hn
  have hbrel : cosetBinomial c m n = -Polynomial.C (Polynomial.C c) * bmon := by
    rw [hbmon, cosetBinomial]
    rw [neg_mul, mul_sub, ← Polynomial.C_mul, ← mul_assoc,
      ← Polynomial.C_mul, mul_inv_cancel₀ hc, Polynomial.C_1, one_mul]
    ring
  -- The monic normalization is also killed.
  have hbmon0 : binomialParam α n m bmon = 0 := by
    have hb0 := binomialParam_cosetBinomial (α := α) m n hroot
    rw [hbrel, map_mul, map_neg] at hb0
    have hCc : binomialParam α n m (Polynomial.C (Polynomial.C c)) =
        Polynomial.C c := by
      rw [binomialParam_C, innerParam_apply, compScale_apply,
        Polynomial.C_comp, Polynomial.expand_C]
    rw [hCc] at hb0
    have hCc0 : (Polynomial.C c : Polynomial K) ≠ 0 := by
      simpa using hc
    rcases mul_eq_zero.1 hb0 with h | h
    · exact absurd (neg_eq_zero.1 h) hCc0
    · exact h
  -- Divide with remainder and kill the remainder.
  have hdiv := Polynomial.modByMonic_add_div f bmon
  have hr0 : f %ₘ bmon = 0 := by
    set r := f %ₘ bmon with hrdef
    have hψr : binomialParam α n m r = 0 := by
      have h := congrArg (binomialParam α n m) hdiv
      rw [map_add, map_mul, hbmon0, zero_mul, add_zero] at h
      rw [h]
      exact hf
    rcases eq_or_ne r 0 with h0 | hrne
    · exact h0
    exfalso
    have hdeg : r.natDegree < n := by
      have h1 := Polynomial.degree_modByMonic_lt f hmonic
      have h2 : bmon.degree = n := by
        rw [hbmon]
        exact Polynomial.degree_X_pow_sub_C (Nat.pos_of_ne_zero hn) _
      rw [← hrdef, h2] at h1
      exact (Polynomial.natDegree_lt_iff_degree_lt hrne).2 h1
    -- Expand the remainder and analyze exponent residues mod `n`.
    have hrsum : r = ∑ j ∈ Finset.range n,
        Polynomial.C (r.coeff j) * Polynomial.X ^ j := by
      conv_lhs => rw [Polynomial.as_sum_range' r n hdeg]
      exact Finset.sum_congr rfl fun j _ ↦
        (Polynomial.C_mul_X_pow_eq_monomial).symm
    have hψsum : ∑ j ∈ Finset.range n,
        innerParam α n (r.coeff j) * Polynomial.X ^ (m * j) = 0 := by
      have h := hψr
      rw [hrsum] at h
      rw [map_sum] at h
      have hterm : ∀ j ∈ Finset.range n,
          binomialParam α n m (Polynomial.C (r.coeff j) * Polynomial.X ^ j) =
          innerParam α n (r.coeff j) * Polynomial.X ^ (m * j) := by
        intro j _
        rw [map_mul, map_pow, binomialParam_C, binomialParam_X, ← pow_mul]
      rwa [Finset.sum_congr rfl hterm] at h
    -- Each residue class carries a single term.
    have hterm0 : ∀ j₀ ∈ Finset.range n,
        innerParam α n (r.coeff j₀) * Polynomial.X ^ (m * j₀) = 0 := by
      intro j₀ hj₀
      ext e
      rw [Polynomial.coeff_zero]
      by_contra hce
      -- The nonvanishing coefficient pins down the residue of `e`.
      have hle : m * j₀ ≤ e := by
        by_contra hlt
        rw [Polynomial.coeff_mul_X_pow', if_neg hlt] at hce
        exact hce rfl
      have hdvd : n ∣ e - m * j₀ := by
        by_contra hnd
        rw [Polynomial.coeff_mul_X_pow', if_pos hle,
          innerParam_coeff_eq_zero hn _ hnd] at hce
        exact hce rfl
      -- Any other term vanishes at `e`.
      have hothers : ∀ j ∈ Finset.range n, j ≠ j₀ →
          (innerParam α n (r.coeff j) * Polynomial.X ^ (m * j)).coeff e
          = 0 := by
        intro j hj hne
        by_contra hcj
        have hlej : m * j ≤ e := by
          by_contra hlt
          rw [Polynomial.coeff_mul_X_pow', if_neg hlt] at hcj
          exact hcj rfl
        have hdvdj : n ∣ e - m * j := by
          by_contra hnd
          rw [Polynomial.coeff_mul_X_pow', if_pos hlej,
            innerParam_coeff_eq_zero hn _ hnd] at hcj
          exact hcj rfl
        have hmod : m * j ≡ m * j₀ [MOD n] := by
          have h1 : m * j₀ ≡ e [MOD n] :=
            (Nat.modEq_iff_dvd' hle).2 hdvd
          have h2 : m * j ≡ e [MOD n] :=
            (Nat.modEq_iff_dvd' hlej).2 hdvdj
          exact h2.trans h1.symm
        have hjj : j ≡ j₀ [MOD n] :=
          hmod.cancel_left_of_coprime ((Nat.gcd_comm n m).trans hcop)
        have : j = j₀ := by
          have h1 := hjj
          unfold Nat.ModEq at h1
          rwa [Nat.mod_eq_of_lt (Finset.mem_range.1 hj),
            Nat.mod_eq_of_lt (Finset.mem_range.1 hj₀)] at h1
        exact hne this
      have hsum := congrArg (fun p ↦ Polynomial.coeff p e) hψsum
      rw [Polynomial.finsetSum_coeff] at hsum
      rw [Finset.sum_eq_single j₀ hothers (fun h ↦ absurd hj₀ h)] at hsum
      exact hce hsum
    -- All low coefficients vanish, contradicting `r ≠ 0`.
    refine hrne ?_
    ext j
    rcases Nat.lt_or_ge j n with hj | hj
    · have h := hterm0 j (Finset.mem_range.2 hj)
      have hX0 : (Polynomial.X : Polynomial K) ^ (m * j) ≠ 0 :=
        pow_ne_zero _ Polynomial.X_ne_zero
      rcases mul_eq_zero.1 h with h1 | h1
      · have h2 : innerParam α n (r.coeff j) = innerParam α n 0 := by
          rw [h1, map_zero]
        have := innerParam_injective hα hn h2
        simp [this]
      · exact absurd h1 hX0
    · simp [Polynomial.coeff_eq_zero_of_natDegree_lt
        (lt_of_lt_of_le hdeg hj)]
  -- Reassemble.
  have hfact : f = bmon * (f /ₘ bmon) := by
    conv_lhs => rw [← hdiv]
    rw [hr0, zero_add]
  have hcc : (-Polynomial.C (Polynomial.C c) : Polynomial (Polynomial K)) *
      (-Polynomial.C (Polynomial.C c⁻¹)) = 1 := by
    rw [neg_mul_neg, ← Polynomial.C_mul, ← Polynomial.C_mul,
      mul_inv_cancel₀ hc, Polynomial.C_1, Polynomial.C_1]
  refine ⟨-Polynomial.C (Polynomial.C c⁻¹) * (f /ₘ bmon), ?_⟩
  rw [hbrel]
  calc f = bmon * (f /ₘ bmon) := hfact
    _ = (-Polynomial.C (Polynomial.C c) * -Polynomial.C (Polynomial.C c⁻¹)) *
        (bmon * (f /ₘ bmon)) := by rw [hcc, one_mul]
    _ = -Polynomial.C (Polynomial.C c) * bmon *
        (-Polynomial.C (Polynomial.C c⁻¹) * (f /ₘ bmon)) := by ring

/-- **Primality of primitive binomials**: `x^m − c·y^n` is prime for
coprime positive exponents and `c ≠ 0`, over an algebraically closed
field. -/
theorem cosetBinomial_prime [IsAlgClosed K] {c : K} (hc : c ≠ 0) {m n : ℕ}
    (hm : m ≠ 0) (hn : n ≠ 0) (hcop : Nat.gcd m n = 1) :
    Prime (cosetBinomial c m n) := by
  classical
  obtain ⟨α, hα⟩ := IsAlgClosed.exists_pow_nat_eq c (Nat.pos_of_ne_zero hm)
  have hα0 : α ≠ 0 := by
    rintro rfl
    rw [zero_pow hm] at hα
    exact hc hα.symm
  have hker_eq : Ideal.span {cosetBinomial c m n} =
      RingHom.ker (binomialParam α n m) := by
    ext f
    rw [Ideal.mem_span_singleton, RingHom.mem_ker]
    constructor
    · rintro ⟨g, rfl⟩
      rw [map_mul, binomialParam_cosetBinomial m n hα, zero_mul]
    · exact cosetBinomial_dvd_of_binomialParam_eq_zero hα0 hc hm hn hcop hα
  have hprime_ideal : (Ideal.span {cosetBinomial c m n}).IsPrime := by
    rw [hker_eq]
    exact RingHom.ker_isPrime _
  have hb0 : cosetBinomial c m n ≠ 0 := by
    intro h0
    have hcoeff := congrArg (fun p ↦ Polynomial.coeff p n) h0
    simp only [cosetBinomial, Polynomial.coeff_sub, Polynomial.coeff_zero,
      Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, if_pos rfl, mul_one,
      Polynomial.coeff_C, if_neg hn] at hcoeff
    rw [zero_sub, neg_eq_zero] at hcoeff
    exact hc (by simpa using hcoeff)
  exact (Ideal.span_singleton_prime hb0).1 hprime_ideal

section MvForm

open MvPolynomial

variable (K) in
/-- The nested-polynomial presentation of the bivariate polynomial ring:
`X 1` becomes the inner variable, `X 0` the outer one. -/
def nestEquiv : MvPolynomial (Fin 2) K ≃ₐ[K] Polynomial (Polynomial K) :=
  (MvPolynomial.finSuccEquiv K 1).trans
    (Polynomial.mapAlgEquiv (MvPolynomial.uniqueAlgEquiv K (Fin 1)))

theorem nestEquiv_X_zero :
    nestEquiv K (MvPolynomial.X 0) =
      (Polynomial.X : Polynomial (Polynomial K)) := by
  rw [nestEquiv, AlgEquiv.trans_apply, MvPolynomial.finSuccEquiv_X_zero,
    Polynomial.coe_mapAlgEquiv, Polynomial.map_X]

theorem nestEquiv_X_one :
    nestEquiv K (MvPolynomial.X 1) = Polynomial.C Polynomial.X := by
  rw [nestEquiv, AlgEquiv.trans_apply]
  have hXone : MvPolynomial.finSuccEquiv K 1 (MvPolynomial.X (1 : Fin 2)) =
      Polynomial.C (MvPolynomial.X 0) := by
    have h := MvPolynomial.finSuccEquiv_X_succ (R := K) (n := 1) (j := 0)
    simpa using h
  rw [hXone, Polynomial.coe_mapAlgEquiv, Polynomial.map_C]
  congr 1
  have h2 : MvPolynomial.uniqueAlgEquiv K (Fin 1) (MvPolynomial.X 0) =
      Polynomial.X := by
    have hX : (MvPolynomial.X (0 : Fin 1) : MvPolynomial (Fin 1) K) =
        MvPolynomial.monomial (Finsupp.single 0 1) 1 := by
      rw [MvPolynomial.monomial_eq]
      simp
    rw [hX, MvPolynomial.uniqueAlgEquiv_monomial]
    simp [Polynomial.monomial_one_one_eq_X]
  exact h2

theorem nestEquiv_C (a : K) :
    nestEquiv K (MvPolynomial.C a) = Polynomial.C (Polynomial.C a) := by
  have h : nestEquiv K (MvPolynomial.C a) = algebraMap K _ a :=
    (nestEquiv K).commutes a
  rw [h]
  rfl

/-- **Primality of primitive binomials, bivariate form**:
`X₀^m − c·X₁^n` is prime for coprime positive exponents over an
algebraically closed field. -/
theorem mvBinomial_prime [IsAlgClosed K] {c : K} (hc : c ≠ 0) {m n : ℕ}
    (hm : m ≠ 0) (hn : n ≠ 0) (hcop : Nat.gcd m n = 1) :
    Prime ((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
      MvPolynomial.C c * MvPolynomial.X 1 ^ n) := by
  have himage : nestEquiv K
      ((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
        MvPolynomial.C c * MvPolynomial.X 1 ^ n) =
      -Polynomial.C (Polynomial.C c) * cosetBinomial c⁻¹ n m := by
    rw [map_sub, map_mul, map_pow, map_pow, nestEquiv_X_zero, nestEquiv_X_one,
      nestEquiv_C, cosetBinomial]
    rw [neg_mul, mul_sub, ← Polynomial.C_pow, ← Polynomial.C_mul,
      ← mul_assoc, ← Polynomial.C_mul, ← Polynomial.C_mul,
      mul_inv_cancel₀ hc, Polynomial.C_1, Polynomial.C_1, one_mul]
    ring
  have hunit : IsUnit (-Polynomial.C (Polynomial.C c) :
      Polynomial (Polynomial K)) := by
    refine IsUnit.neg ?_
    rw [Polynomial.isUnit_C, Polynomial.isUnit_C]
    exact isUnit_iff_ne_zero.2 hc
  have hprime : Prime (nestEquiv K
      ((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
        MvPolynomial.C c * MvPolynomial.X 1 ^ n)) := by
    rw [himage]
    obtain ⟨u, hu⟩ := hunit
    have hassoc : Associated (cosetBinomial c⁻¹ n m)
        (-Polynomial.C (Polynomial.C c) * cosetBinomial c⁻¹ n m) :=
      ⟨u, by rw [hu]; ring⟩
    exact hassoc.prime (cosetBinomial_prime (inv_ne_zero hc) hn hm
      ((Nat.gcd_comm n m).trans hcop))
  exact (MulEquiv.prime_iff (nestEquiv K)).1 hprime

/-- The bivariate parametrization: `X 0 ↦ α·T^n`, `X 1 ↦ T^m`. -/
def mvParam (α : K) (n m : ℕ) : MvPolynomial (Fin 2) K →ₐ[K] Polynomial K :=
  MvPolynomial.aeval ![Polynomial.C α * Polynomial.X ^ n, Polynomial.X ^ m]

theorem mvParam_binomial {α c : K} {m n : ℕ} (hroot : α ^ m = c) :
    mvParam α n m ((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
      MvPolynomial.C c * MvPolynomial.X 1 ^ n) = 0 := by
  rw [mvParam, map_sub, map_mul, map_pow, map_pow, MvPolynomial.aeval_X,
    MvPolynomial.aeval_X, MvPolynomial.aeval_C]
  have h0 : (![Polynomial.C α * Polynomial.X ^ n, Polynomial.X ^ m] :
      Fin 2 → Polynomial K) 0 = Polynomial.C α * Polynomial.X ^ n := rfl
  have h1 : (![Polynomial.C α * Polynomial.X ^ n, Polynomial.X ^ m] :
      Fin 2 → Polynomial K) 1 = Polynomial.X ^ m := rfl
  rw [h0, h1, mul_pow, ← Polynomial.C_pow, hroot, ← pow_mul, ← pow_mul,
    mul_comm n m]
  have halg : (algebraMap K (Polynomial K)) c = Polynomial.C c := rfl
  rw [halg, sub_self]

/-- **The simultaneous-coset core classification**: an axes-supported prime
whose constant shift is divisible by a primitive binomial *is* a scalar
multiple of that binomial — the shift vanishes and the two one-variable
parts are monomials. -/
theorem eq_smul_binomial_of_dvd_shift [IsAlgClosed K]
    {G : MvPolynomial (Fin 2) K} (hGp : Prime G)
    {P Q : Polynomial K} (hP0 : P.coeff 0 = 0) (hQ0 : Q.coeff 0 = 0)
    (hsplit : G = Polynomial.aeval (MvPolynomial.X 0) P +
      Polynomial.aeval (MvPolynomial.X 1) Q)
    {c d : K} (hc : c ≠ 0) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0)
    (hcop : Nat.gcd m n = 1)
    (hdvd : ((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
      MvPolynomial.C c * MvPolynomial.X 1 ^ n) ∣ (G - MvPolynomial.C d)) :
    d = 0 ∧ ∃ l : K, l ≠ 0 ∧
      P = Polynomial.C l * Polynomial.X ^ m ∧
      Q = -(Polynomial.C (l * c)) * Polynomial.X ^ n := by
  classical
  obtain ⟨α, hα⟩ := IsAlgClosed.exists_pow_nat_eq c (Nat.pos_of_ne_zero hm)
  -- Composition computations for the parametrization.
  have hcomp0 : ∀ p : Polynomial K,
      mvParam α n m (Polynomial.aeval (MvPolynomial.X 0) p) =
        Polynomial.aeval (Polynomial.C α * Polynomial.X ^ n) p := by
    intro p
    rw [← Polynomial.aeval_algHom_apply, mvParam, MvPolynomial.aeval_X]
    rfl
  have hcomp1 : ∀ p : Polynomial K,
      mvParam α n m (Polynomial.aeval (MvPolynomial.X 1) p) =
        Polynomial.aeval (Polynomial.X ^ m) p := by
    intro p
    rw [← Polynomial.aeval_algHom_apply, mvParam, MvPolynomial.aeval_X]
    rfl
  -- The image of the shifted generator vanishes.
  have hGval : mvParam α n m G = Polynomial.C d := by
    obtain ⟨R, hR⟩ := hdvd
    have h := congrArg (mvParam α n m) hR
    rw [map_sub, map_mul, mvParam_binomial hα, zero_mul] at h
    rw [sub_eq_zero] at h
    rw [h]
    exact MvPolynomial.aeval_C _ _
  -- The constant coefficient forces the shift to vanish.
  have hd0 : d = 0 := by
    have hc0 := congrArg (fun p ↦ Polynomial.coeff p 0) hGval
    simp only [Polynomial.coeff_C_zero] at hc0
    rw [hsplit, map_add, hcomp0, hcomp1] at hc0
    have he0 : ∀ (s : Polynomial K), s.eval 0 = 0 →
        ∀ p : Polynomial K, p.coeff 0 = 0 →
        (Polynomial.aeval s p).coeff 0 = 0 := by
      intro s hs p hp
      have haev : Polynomial.aeval s p = p.comp s := rfl
      rw [haev, Polynomial.coeff_zero_eq_eval_zero, Polynomial.eval_comp,
        hs, ← Polynomial.coeff_zero_eq_eval_zero, hp]
    rw [Polynomial.coeff_add,
      he0 _ (by simp [Polynomial.eval_pow, zero_pow hn]) _ hP0,
      he0 _ (by simp [zero_pow hm]) _ hQ0, add_zero] at hc0
    exact hc0.symm
  -- The binomial is associated to the prime generator.
  subst hd0
  rw [map_zero, sub_zero] at hdvd
  have hassoc : Associated ((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
      MvPolynomial.C c * MvPolynomial.X 1 ^ n) G :=
    (mvBinomial_prime hc hm hn hcop).associated_of_dvd hGp hdvd
  obtain ⟨u, hu⟩ := hassoc
  -- Units are nonzero constants.
  have hudeg : ((u : MvPolynomial (Fin 2) K)).totalDegree = 0 := by
    have h1 : ((u : MvPolynomial (Fin 2) K) *
        ((u⁻¹ : (MvPolynomial (Fin 2) K)ˣ) :
          MvPolynomial (Fin 2) K)).totalDegree = 0 := by
      rw [Units.mul_inv]
      exact MvPolynomial.totalDegree_one
    rw [MvPolynomial.totalDegree_mul_of_isDomain (Units.ne_zero u)
      (Units.ne_zero u⁻¹)] at h1
    omega
  set l := MvPolynomial.coeff 0 (u : MvPolynomial (Fin 2) K) with hldef
  have hCform : (u : MvPolynomial (Fin 2) K) = MvPolynomial.C l :=
    MvPolynomial.totalDegree_eq_zero_iff_eq_C.1 hudeg
  refine ⟨rfl, l, ?_, ?_, ?_⟩
  · intro h0
    have hne := Units.ne_zero u
    rw [hCform, h0, map_zero] at hne
    exact hne rfl
  · -- Extract `P` by evaluating the second variable at zero.
    have hΦG : MvPolynomial.aeval
        (![Polynomial.X, (0 : Polynomial K)] : Fin 2 → Polynomial K) G =
        P := by
      rw [hsplit, map_add, ← Polynomial.aeval_algHom_apply,
        ← Polynomial.aeval_algHom_apply, MvPolynomial.aeval_X,
        MvPolynomial.aeval_X]
      have h0 : (![Polynomial.X, (0 : Polynomial K)] : Fin 2 → Polynomial K)
          0 = Polynomial.X := rfl
      have h1 : (![Polynomial.X, (0 : Polynomial K)] : Fin 2 → Polynomial K)
          1 = 0 := rfl
      rw [h0, h1, Polynomial.aeval_X_left_apply]
      have hQ0' : Polynomial.aeval (0 : Polynomial K) Q = 0 := by
        rw [Polynomial.aeval_def, Polynomial.eval₂_at_zero, hQ0, map_zero]
      rw [hQ0', add_zero]
    have hΦB : MvPolynomial.aeval
        (![Polynomial.X, (0 : Polynomial K)] : Fin 2 → Polynomial K)
        (((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
          MvPolynomial.C c * MvPolynomial.X 1 ^ n) *
          (u : MvPolynomial (Fin 2) K)) =
        Polynomial.C l * Polynomial.X ^ m := by
      rw [hCform, map_mul, MvPolynomial.aeval_C, map_sub, map_mul, map_pow,
        map_pow, MvPolynomial.aeval_X, MvPolynomial.aeval_X,
        MvPolynomial.aeval_C]
      have h0 : (![Polynomial.X, (0 : Polynomial K)] : Fin 2 → Polynomial K)
          0 = Polynomial.X := rfl
      have h1 : (![Polynomial.X, (0 : Polynomial K)] : Fin 2 → Polynomial K)
          1 = 0 := rfl
      rw [h0, h1, zero_pow hn, mul_zero, sub_zero, Polynomial.algebraMap_eq]
      ring
    rw [← hΦG, ← hu, hΦB]
  · -- Extract `Q` by evaluating the first variable at zero.
    have hΦG : MvPolynomial.aeval
        (![(0 : Polynomial K), Polynomial.X] : Fin 2 → Polynomial K) G =
        Q := by
      rw [hsplit, map_add, ← Polynomial.aeval_algHom_apply,
        ← Polynomial.aeval_algHom_apply, MvPolynomial.aeval_X,
        MvPolynomial.aeval_X]
      have h0 : (![(0 : Polynomial K), Polynomial.X] : Fin 2 → Polynomial K)
          0 = 0 := rfl
      have h1 : (![(0 : Polynomial K), Polynomial.X] : Fin 2 → Polynomial K)
          1 = Polynomial.X := rfl
      rw [h0, h1, Polynomial.aeval_X_left_apply]
      have hP0' : Polynomial.aeval (0 : Polynomial K) P = 0 := by
        rw [Polynomial.aeval_def, Polynomial.eval₂_at_zero, hP0, map_zero]
      rw [hP0', zero_add]
    have hΦB : MvPolynomial.aeval
        (![(0 : Polynomial K), Polynomial.X] : Fin 2 → Polynomial K)
        (((MvPolynomial.X 0 : MvPolynomial (Fin 2) K) ^ m -
          MvPolynomial.C c * MvPolynomial.X 1 ^ n) *
          (u : MvPolynomial (Fin 2) K)) =
        -(Polynomial.C (l * c)) * Polynomial.X ^ n := by
      rw [hCform, map_mul, MvPolynomial.aeval_C, map_sub, map_mul, map_pow,
        map_pow, MvPolynomial.aeval_X, MvPolynomial.aeval_X,
        MvPolynomial.aeval_C]
      have h0 : (![(0 : Polynomial K), Polynomial.X] : Fin 2 → Polynomial K)
          0 = 0 := rfl
      have h1 : (![(0 : Polynomial K), Polynomial.X] : Fin 2 → Polynomial K)
          1 = Polynomial.X := rfl
      rw [h0, h1, zero_pow hm, zero_sub, Polynomial.algebraMap_eq,
        Polynomial.C_mul]
      ring
    rw [← hΦG, ← hu, hΦB]

end MvForm

end

end AclGeom
