/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.Algebra.Polynomial.Expand
import Mathlib.RingTheory.Ideal.Maps

/-!
# Primality of primitive binomials

Blueprint Lemma `simultaneous-coset` (8.9) compares the additive and
multiplicative coset equations of a correspondence curve through its prime
generator. The multiplicative equation is a *primitive binomial*
`x^m − c·y^n` with coprime exponents; this file proves it is prime, via the
monomial-curve parametrization: the kernel of
`x ↦ α·T^n, y ↦ T^m` (with `α^m = c`) is exactly the ideal generated by the
binomial, and the target `K[T]` is a domain. The kernel computation reduces
a remainder of `y`-degree `< n` along the residues of exponents modulo `n`,
where coprimality makes the classes `m·j mod n` distinct.

Conventions match `eq_monomial_of_eq_smul_binomial`: the outer variable is
`y`, the inner one `x`, so the ambient ring is `(K[x])[y]`.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** stable (M3, checklist C5).
-/

namespace AclGeom

open Polynomial

noncomputable section

variable {K : Type*} [Field K]

/-- Scaling the variable: `p(x) ↦ p(α·x)`, as a ring homomorphism. -/
def compScale (α : K) : Polynomial K →+* Polynomial K :=
  Polynomial.compRingHom (Polynomial.C α * Polynomial.X)

theorem compScale_apply (α : K) (p : Polynomial K) :
    compScale α p = p.comp (Polynomial.C α * Polynomial.X) :=
  Polynomial.coe_compRingHom_apply p _

theorem compScale_injective {α : K} (hα : α ≠ 0) :
    Function.Injective (compScale α) := by
  intro p q h
  have h2 := congrArg (compScale α⁻¹) h
  have hcomp : ∀ r : Polynomial K, compScale α⁻¹ (compScale α r) = r := by
    intro r
    rw [compScale_apply, compScale_apply, Polynomial.comp_assoc]
    have hlin : (Polynomial.C α * Polynomial.X).comp
        (Polynomial.C α⁻¹ * Polynomial.X) = Polynomial.X := by
      rw [Polynomial.mul_comp, Polynomial.C_comp, Polynomial.X_comp,
        ← mul_assoc, ← Polynomial.C_mul, mul_inv_cancel₀ hα,
        Polynomial.C_1, one_mul]
    rw [hlin, Polynomial.comp_X]
  rwa [hcomp, hcomp] at h2

/-- The inner substitution `x ↦ α·T^n`. -/
def innerParam (α : K) (n : ℕ) : Polynomial K →+* Polynomial K :=
  (Polynomial.expand K n).toRingHom.comp (compScale α)

theorem innerParam_apply (α : K) (n : ℕ) (p : Polynomial K) :
    innerParam α n p = Polynomial.expand K n (compScale α p) := rfl

theorem innerParam_injective {α : K} (hα : α ≠ 0) {n : ℕ} (hn : n ≠ 0) :
    Function.Injective (innerParam α n) :=
  (Polynomial.expand_injective (Nat.pos_of_ne_zero hn)).comp
    (compScale_injective hα)

/-- Supports of inner substitutions consist of multiples of `n`. -/
theorem innerParam_coeff_eq_zero {α : K} {n : ℕ} (hn : n ≠ 0)
    (p : Polynomial K) {e : ℕ} (he : ¬ n ∣ e) :
    (innerParam α n p).coeff e = 0 := by
  rw [innerParam_apply, Polynomial.coeff_expand (Nat.pos_of_ne_zero hn),
    if_neg he]

/-- The full parametrization `(K[x])[y] → K[T]`: `y ↦ T^m`, `x ↦ α·T^n`. -/
def binomialParam (α : K) (n m : ℕ) :
    Polynomial (Polynomial K) →+* Polynomial K :=
  Polynomial.eval₂RingHom (innerParam α n) (Polynomial.X ^ m)

theorem binomialParam_C (α : K) (n m : ℕ) (p : Polynomial K) :
    binomialParam α n m (Polynomial.C p) = innerParam α n p := by
  simp [binomialParam]

theorem binomialParam_X (α : K) (n m : ℕ) :
    binomialParam α n m Polynomial.X = Polynomial.X ^ m := by
  simp [binomialParam]

/-- The binomial in the conventions of the coset-comparison lemma. -/
def cosetBinomial (c : K) (m n : ℕ) : Polynomial (Polynomial K) :=
  Polynomial.C ((Polynomial.X : Polynomial K) ^ m) -
    Polynomial.C (Polynomial.C c) * (Polynomial.X : Polynomial (Polynomial K)) ^ n

/-- The parametrization kills the binomial. -/
theorem binomialParam_cosetBinomial {α c : K} (m₀ n₀ : ℕ)
    (hroot : α ^ m₀ = c) :
    binomialParam α n₀ m₀ (cosetBinomial c m₀ n₀) = 0 := by
  have h1 : binomialParam α n₀ m₀
      (Polynomial.C ((Polynomial.X : Polynomial K) ^ m₀)) =
      Polynomial.C (α ^ m₀) * Polynomial.X ^ (n₀ * m₀) := by
    rw [binomialParam_C, map_pow, innerParam_apply, compScale_apply,
      Polynomial.X_comp]
    rw [map_mul, Polynomial.expand_C, Polynomial.expand_X, mul_pow,
      ← Polynomial.C_pow, ← pow_mul]
  have h2 : binomialParam α n₀ m₀
      (Polynomial.C (Polynomial.C c)) = Polynomial.C c := by
    rw [binomialParam_C, innerParam_apply, compScale_apply,
      Polynomial.C_comp, Polynomial.expand_C]
  have h3 : binomialParam α n₀ m₀
      ((Polynomial.X : Polynomial (Polynomial K)) ^ n₀) =
      Polynomial.X ^ (m₀ * n₀) := by
    rw [map_pow, binomialParam_X, ← pow_mul]
  rw [cosetBinomial, map_sub, map_mul, h1, h2, h3, hroot, mul_comm n₀ m₀,
    sub_self]

/-- **The kernel of the parametrization**: a polynomial killed by the
monomial-curve substitution is a multiple of the binomial. -/
theorem cosetBinomial_dvd_of_binomialParam_eq_zero {α c : K} (hα : α ≠ 0)
    (hc : c ≠ 0) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0)
    (hcop : Nat.gcd m n = 1) (hroot : α ^ m = c)
    {f : Polynomial (Polynomial K)} (hf : binomialParam α n m f = 0) :
    cosetBinomial c m n ∣ f := by
  classical
  set bmon : Polynomial (Polynomial K) :=
    Polynomial.X ^ n - Polynomial.C (Polynomial.C c⁻¹ * Polynomial.X ^ m)
    with hbmon
  have hmonic : bmon.Monic := Polynomial.monic_X_pow_sub_C _ hn
  have hbrel : cosetBinomial c m n = -Polynomial.C (Polynomial.C c) * bmon := by
    rw [hbmon, cosetBinomial]
    rw [neg_mul, mul_sub, ← Polynomial.C_mul, ← mul_assoc,
      ← Polynomial.C_mul, mul_inv_cancel₀ hc, Polynomial.C_1, one_mul]
    ring
  -- The monic normalization is also killed.
  have hbmon0 : binomialParam α n m bmon = 0 := by
    have hb0 := binomialParam_cosetBinomial (α := α) m n hroot
    rw [hbrel, map_mul, map_neg] at hb0
    have hCc : binomialParam α n m (Polynomial.C (Polynomial.C c)) =
        Polynomial.C c := by
      rw [binomialParam_C, innerParam_apply, compScale_apply,
        Polynomial.C_comp, Polynomial.expand_C]
    rw [hCc] at hb0
    have hCc0 : (Polynomial.C c : Polynomial K) ≠ 0 := by
      simpa using hc
    rcases mul_eq_zero.1 hb0 with h | h
    · exact absurd (neg_eq_zero.1 h) hCc0
    · exact h
  -- Divide with remainder and kill the remainder.
  have hdiv := Polynomial.modByMonic_add_div f bmon
  have hr0 : f %ₘ bmon = 0 := by
    set r := f %ₘ bmon with hrdef
    have hψr : binomialParam α n m r = 0 := by
      have h := congrArg (binomialParam α n m) hdiv
      rw [map_add, map_mul, hbmon0, zero_mul, add_zero] at h
      rw [h]
      exact hf
    rcases eq_or_ne r 0 with h0 | hrne
    · exact h0
    exfalso
    have hdeg : r.natDegree < n := by
      have h1 := Polynomial.degree_modByMonic_lt f hmonic
      have h2 : bmon.degree = n := by
        rw [hbmon]
        exact Polynomial.degree_X_pow_sub_C (Nat.pos_of_ne_zero hn) _
      rw [← hrdef, h2] at h1
      exact (Polynomial.natDegree_lt_iff_degree_lt hrne).2 h1
    -- Expand the remainder and analyze exponent residues mod `n`.
    have hrsum : r = ∑ j ∈ Finset.range n,
        Polynomial.C (r.coeff j) * Polynomial.X ^ j := by
      conv_lhs => rw [Polynomial.as_sum_range' r n hdeg]
      exact Finset.sum_congr rfl fun j _ ↦
        (Polynomial.C_mul_X_pow_eq_monomial).symm
    have hψsum : ∑ j ∈ Finset.range n,
        innerParam α n (r.coeff j) * Polynomial.X ^ (m * j) = 0 := by
      have h := hψr
      rw [hrsum] at h
      rw [map_sum] at h
      have hterm : ∀ j ∈ Finset.range n,
          binomialParam α n m (Polynomial.C (r.coeff j) * Polynomial.X ^ j) =
          innerParam α n (r.coeff j) * Polynomial.X ^ (m * j) := by
        intro j _
        rw [map_mul, map_pow, binomialParam_C, binomialParam_X, ← pow_mul]
      rwa [Finset.sum_congr rfl hterm] at h
    -- Each residue class carries a single term.
    have hterm0 : ∀ j₀ ∈ Finset.range n,
        innerParam α n (r.coeff j₀) * Polynomial.X ^ (m * j₀) = 0 := by
      intro j₀ hj₀
      ext e
      rw [Polynomial.coeff_zero]
      by_contra hce
      -- The nonvanishing coefficient pins down the residue of `e`.
      have hle : m * j₀ ≤ e := by
        by_contra hlt
        rw [Polynomial.coeff_mul_X_pow', if_neg hlt] at hce
        exact hce rfl
      have hdvd : n ∣ e - m * j₀ := by
        by_contra hnd
        rw [Polynomial.coeff_mul_X_pow', if_pos hle,
          innerParam_coeff_eq_zero hn _ hnd] at hce
        exact hce rfl
      -- Any other term vanishes at `e`.
      have hothers : ∀ j ∈ Finset.range n, j ≠ j₀ →
          (innerParam α n (r.coeff j) * Polynomial.X ^ (m * j)).coeff e
          = 0 := by
        intro j hj hne
        by_contra hcj
        have hlej : m * j ≤ e := by
          by_contra hlt
          rw [Polynomial.coeff_mul_X_pow', if_neg hlt] at hcj
          exact hcj rfl
        have hdvdj : n ∣ e - m * j := by
          by_contra hnd
          rw [Polynomial.coeff_mul_X_pow', if_pos hlej,
            innerParam_coeff_eq_zero hn _ hnd] at hcj
          exact hcj rfl
        have hmod : m * j ≡ m * j₀ [MOD n] := by
          have h1 : m * j₀ ≡ e [MOD n] :=
            (Nat.modEq_iff_dvd' hle).2 hdvd
          have h2 : m * j ≡ e [MOD n] :=
            (Nat.modEq_iff_dvd' hlej).2 hdvdj
          exact h2.trans h1.symm
        have hjj : j ≡ j₀ [MOD n] :=
          hmod.cancel_left_of_coprime ((Nat.gcd_comm n m).trans hcop)
        have : j = j₀ := by
          have h1 := hjj
          unfold Nat.ModEq at h1
          rwa [Nat.mod_eq_of_lt (Finset.mem_range.1 hj),
            Nat.mod_eq_of_lt (Finset.mem_range.1 hj₀)] at h1
        exact hne this
      have hsum := congrArg (fun p ↦ Polynomial.coeff p e) hψsum
      rw [Polynomial.finsetSum_coeff] at hsum
      rw [Finset.sum_eq_single j₀ hothers (fun h ↦ absurd hj₀ h)] at hsum
      exact hce hsum
    -- All low coefficients vanish, contradicting `r ≠ 0`.
    refine hrne ?_
    ext j
    rcases Nat.lt_or_ge j n with hj | hj
    · have h := hterm0 j (Finset.mem_range.2 hj)
      have hX0 : (Polynomial.X : Polynomial K) ^ (m * j) ≠ 0 :=
        pow_ne_zero _ Polynomial.X_ne_zero
      rcases mul_eq_zero.1 h with h1 | h1
      · have h2 : innerParam α n (r.coeff j) = innerParam α n 0 := by
          rw [h1, map_zero]
        have := innerParam_injective hα hn h2
        simp [this]
      · exact absurd h1 hX0
    · simp [Polynomial.coeff_eq_zero_of_natDegree_lt
        (lt_of_lt_of_le hdeg hj)]
  -- Reassemble.
  have hfact : f = bmon * (f /ₘ bmon) := by
    conv_lhs => rw [← hdiv]
    rw [hr0, zero_add]
  have hcc : (-Polynomial.C (Polynomial.C c) : Polynomial (Polynomial K)) *
      (-Polynomial.C (Polynomial.C c⁻¹)) = 1 := by
    rw [neg_mul_neg, ← Polynomial.C_mul, ← Polynomial.C_mul,
      mul_inv_cancel₀ hc, Polynomial.C_1, Polynomial.C_1]
  refine ⟨-Polynomial.C (Polynomial.C c⁻¹) * (f /ₘ bmon), ?_⟩
  rw [hbrel]
  calc f = bmon * (f /ₘ bmon) := hfact
    _ = (-Polynomial.C (Polynomial.C c) * -Polynomial.C (Polynomial.C c⁻¹)) *
        (bmon * (f /ₘ bmon)) := by rw [hcc, one_mul]
    _ = -Polynomial.C (Polynomial.C c) * bmon *
        (-Polynomial.C (Polynomial.C c⁻¹) * (f /ₘ bmon)) := by ring

/-- **Primality of primitive binomials**: `x^m − c·y^n` is prime for
coprime positive exponents and `c ≠ 0`, over an algebraically closed
field. -/
theorem cosetBinomial_prime [IsAlgClosed K] {c : K} (hc : c ≠ 0) {m n : ℕ}
    (hm : m ≠ 0) (hn : n ≠ 0) (hcop : Nat.gcd m n = 1) :
    Prime (cosetBinomial c m n) := by
  classical
  obtain ⟨α, hα⟩ := IsAlgClosed.exists_pow_nat_eq c (Nat.pos_of_ne_zero hm)
  have hα0 : α ≠ 0 := by
    rintro rfl
    rw [zero_pow hm] at hα
    exact hc hα.symm
  have hker_eq : Ideal.span {cosetBinomial c m n} =
      RingHom.ker (binomialParam α n m) := by
    ext f
    rw [Ideal.mem_span_singleton, RingHom.mem_ker]
    constructor
    · rintro ⟨g, rfl⟩
      rw [map_mul, binomialParam_cosetBinomial m n hα, zero_mul]
    · exact cosetBinomial_dvd_of_binomialParam_eq_zero hα0 hc hm hn hcop hα
  have hprime_ideal : (Ideal.span {cosetBinomial c m n}).IsPrime := by
    rw [hker_eq]
    exact RingHom.ker_isPrime _
  have hb0 : cosetBinomial c m n ≠ 0 := by
    intro h0
    have hcoeff := congrArg (fun p ↦ Polynomial.coeff p n) h0
    simp only [cosetBinomial, Polynomial.coeff_sub, Polynomial.coeff_zero,
      Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, if_pos rfl, mul_one,
      Polynomial.coeff_C, if_neg hn] at hcoeff
    rw [zero_sub, neg_eq_zero] at hcoeff
    exact hc (by simpa using hcoeff)
  exact (Ideal.span_singleton_prime hb0).1 hprime_ideal

end

end AclGeom
