/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Correspondence.FunctionField
import Mathlib.RingTheory.Ideal.Height
import Mathlib.RingTheory.KrullDimension.Polynomial
import Mathlib.RingTheory.KrullDimension.Field
import Mathlib.RingTheory.Jacobson.Ring
import Mathlib.RingTheory.UniqueFactorizationDomain.Ideal
import Mathlib.RingTheory.Polynomial.UniqueFactorization

/-!
# The curve ideal is principal

The vanishing ideal of a planar curve point — a pair `(u, v)` with `u`
transcendental and `v` algebraic over `k(u)` — is a height-one prime of
`k[X, Y]`, hence generated by a single prime polynomial (blueprint
Lemma `subgroup-classification`, opening step). This is the ring-theoretic
input to the Hopf/minimal-degree argument of the hard kernel: the generator
is the minimal equation of the curve, and every polynomial vanishing at the
generic point is divisible by it.

* `idealOf_ne_bot_of_mem_racl`: the algebraic relation makes the ideal
  nonzero;
* `not_isMaximal_idealOf`: the transcendental coordinate keeps it from being
  maximal (Zariski's lemma);
* `exists_prime_span_idealOf`: the principal-generator theorem.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M3a, checklist C7).
-/

namespace AclGeom

open MvPolynomial

noncomputable section

variable (k : Type*) {Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- The vanishing ideal of a dependent pair is nonzero. -/
theorem idealOf_ne_bot_of_mem_racl {u v : Ω} (hv : v ∈ racl k {u}) :
    idealOf k ![u, v] ≠ ⊥ := fun h ↦
  AlgebraicIndependent.notMem_racl_pair ((idealOf_eq_bot_iff k).1 h) hv

/-- Zariski's lemma, applied to the curve: the vanishing ideal of a pair with
a transcendental coordinate is not maximal — its residue ring embeds into
`Ω` and contains the transcendental coordinate, so it cannot be algebraic
over `k`. -/
theorem not_isMaximal_idealOf {u v : Ω} (hu : Transcendental k u) :
    ¬(idealOf k ![u, v]).IsMaximal := by
  intro hM
  letI : Field (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    Ideal.Quotient.field _
  have hft : Algebra.FiniteType k (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    Algebra.FiniteType.of_surjective (Ideal.Quotient.mkₐ k _)
      (Ideal.Quotient.mkₐ_surjective k _)
  have hfin : Module.Finite k (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    finite_of_finite_type_of_isJacobsonRing k _
  have hint : Algebra.IsIntegral k
      (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    Algebra.IsIntegral.of_finite k _
  -- Push the integrality of `X 0` mod the ideal forward to `u`.
  have h0 : IsIntegral k (Ideal.Quotient.mk (idealOf k ![u, v]) (X 0)) :=
    Algebra.IsIntegral.isIntegral _
  have hlift := h0.map (Ideal.Quotient.liftₐ (idealOf k ![u, v])
    (aeval ![u, v]) fun a ha ↦ (mem_idealOf_iff k).1 ha)
  have heval : Ideal.Quotient.liftₐ (idealOf k ![u, v]) (aeval ![u, v])
      (fun a ha ↦ (mem_idealOf_iff k).1 ha)
      (Ideal.Quotient.mk (idealOf k ![u, v]) (X 0)) = u := by
    rw [Ideal.Quotient.liftₐ_apply, Ideal.Quotient.lift_mk]
    simp
  rw [heval] at hlift
  exact hu hlift.isAlgebraic

/-- **The curve ideal is principal**: the vanishing ideal of a pair `(u, v)`
with `u` transcendental over `k` and `v` algebraic over `k(u)` is generated
by a single prime polynomial. The generator is the minimal equation of the
curve; every relation between `u` and `v` over `k` is divisible by it. -/
theorem exists_prime_span_idealOf {u v : Ω} (hu : Transcendental k u)
    (hv : v ∈ racl k {u}) :
    ∃ f : MvPolynomial (Fin 2) k, Prime f ∧ idealOf k ![u, v] = Ideal.span {f} := by
  have hbot : idealOf k ![u, v] ≠ ⊥ := idealOf_ne_bot_of_mem_racl k hv
  obtain ⟨f, hfP, hf⟩ :=
    (idealOf_isPrime k ![u, v]).exists_mem_prime_of_ne_bot hbot
  refine ⟨f, hf, ?_⟩
  -- The ideal has height one: nonzero, and strictly below a maximal ideal
  -- in a ring of Krull dimension two.
  have hheight : (idealOf k ![u, v]).height = 1 := by
    obtain ⟨M, hMmax, hPM⟩ := Ideal.exists_le_maximal (idealOf k ![u, v])
      (idealOf_isPrime k ![u, v]).ne_top
    have hlt : idealOf k ![u, v] < M :=
      lt_of_le_of_ne hPM fun h ↦ not_isMaximal_idealOf k hu (h ▸ hMmax)
    have hdim : ringKrullDim (MvPolynomial (Fin 2) k) = 2 := by
      rw [MvPolynomial.ringKrullDim_of_isNoetherianRing,
        ringKrullDim_eq_zero_of_field]
      simp
    have hM2 : (M.height : WithBot ℕ∞) ≤ 2 := by
      rw [← hdim]
      exact Ideal.height_le_ringKrullDim_of_ne_top hMmax.ne_top
    have hstep : (idealOf k ![u, v]).height + 1 ≤ M.height :=
      Ideal.height_add_one_le_of_lt_of_isPrime hlt
    have hle : (idealOf k ![u, v]).height + 1 ≤ 2 := by
      exact_mod_cast hstep.trans (WithBot.coe_le_coe.1 hM2)
    have hne : (idealOf k ![u, v]).height ≠ 0 := fun h ↦
      hbot (Ideal.height_eq_zero_iff_eq_bot.1 h)
    -- `ℕ∞` arithmetic: `h + 1 ≤ 2` and `h ≠ 0` force `h = 1`.
    set h := (idealOf k ![u, v]).height with hh
    have htop : h ≠ ⊤ := by
      intro ht
      rw [ht, top_add] at hle
      simp at hle
    lift h to ℕ using htop with n hn
    have h1 : n + 1 ≤ 2 := by exact_mod_cast hle
    have h2 : n ≠ 0 := by exact_mod_cast hne
    have h3 : n = 1 := by omega
    exact_mod_cast congrArg (Nat.cast : ℕ → ℕ∞) h3
  exact Ideal.eq_span_singleton_of_height_eq_one hheight hfP hf

end

end AclGeom
