/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Correspondence.FunctionField
import Mathlib.RingTheory.Ideal.Height
import Mathlib.RingTheory.KrullDimension.Polynomial
import Mathlib.RingTheory.KrullDimension.Field
import Mathlib.RingTheory.Jacobson.Ring
import Mathlib.RingTheory.UniqueFactorizationDomain.Ideal
import Mathlib.RingTheory.Polynomial.UniqueFactorization
import Mathlib.Algebra.MvPolynomial.NoZeroDivisors

/-!
# The curve ideal is principal

The vanishing ideal of a planar curve point — a pair `(u, v)` with `u`
transcendental and `v` algebraic over `k(u)` — is a height-one prime of
`k[X, Y]`, hence generated by a single prime polynomial (blueprint
Lemma `subgroup-classification`, opening step). This is the ring-theoretic
input to the Hopf/minimal-degree argument of the hard kernel: the generator
is the minimal equation of the curve, and every polynomial vanishing at the
generic point is divisible by it.

* `idealOf_ne_bot_of_mem_racl`: the algebraic relation makes the ideal
  nonzero;
* `not_isMaximal_idealOf`: the transcendental coordinate keeps it from being
  maximal (Zariski's lemma);
* `exists_prime_span_idealOf`: the principal-generator theorem.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M3a, checklist C7).
-/

namespace AclGeom

open MvPolynomial

noncomputable section

variable (k : Type*) {Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- The vanishing ideal of a dependent pair is nonzero. -/
theorem idealOf_ne_bot_of_mem_racl {u v : Ω} (hv : v ∈ racl k {u}) :
    idealOf k ![u, v] ≠ ⊥ := fun h ↦
  AlgebraicIndependent.notMem_racl_pair ((idealOf_eq_bot_iff k).1 h) hv

/-- Zariski's lemma, applied to the curve: the vanishing ideal of a pair with
a transcendental coordinate is not maximal — its residue ring embeds into
`Ω` and contains the transcendental coordinate, so it cannot be algebraic
over `k`. -/
theorem not_isMaximal_idealOf {u v : Ω} (hu : Transcendental k u) :
    ¬(idealOf k ![u, v]).IsMaximal := by
  intro hM
  letI : Field (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    Ideal.Quotient.field _
  have hft : Algebra.FiniteType k (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    Algebra.FiniteType.of_surjective (Ideal.Quotient.mkₐ k _)
      (Ideal.Quotient.mkₐ_surjective k _)
  have hfin : Module.Finite k (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    finite_of_finite_type_of_isJacobsonRing k _
  have hint : Algebra.IsIntegral k
      (MvPolynomial (Fin 2) k ⧸ idealOf k ![u, v]) :=
    Algebra.IsIntegral.of_finite k _
  -- Push the integrality of `X 0` mod the ideal forward to `u`.
  have h0 : IsIntegral k (Ideal.Quotient.mk (idealOf k ![u, v]) (X 0)) :=
    Algebra.IsIntegral.isIntegral _
  have hlift := h0.map (Ideal.Quotient.liftₐ (idealOf k ![u, v])
    (aeval ![u, v]) fun a ha ↦ (mem_idealOf_iff k).1 ha)
  have heval : Ideal.Quotient.liftₐ (idealOf k ![u, v]) (aeval ![u, v])
      (fun a ha ↦ (mem_idealOf_iff k).1 ha)
      (Ideal.Quotient.mk (idealOf k ![u, v]) (X 0)) = u := by
    rw [Ideal.Quotient.liftₐ_apply, Ideal.Quotient.lift_mk]
    simp
  rw [heval] at hlift
  exact hu hlift.isAlgebraic

/-- **The curve ideal is principal**: the vanishing ideal of a pair `(u, v)`
with `u` transcendental over `k` and `v` algebraic over `k(u)` is generated
by a single prime polynomial. The generator is the minimal equation of the
curve; every relation between `u` and `v` over `k` is divisible by it. -/
theorem exists_prime_span_idealOf {u v : Ω} (hu : Transcendental k u)
    (hv : v ∈ racl k {u}) :
    ∃ f : MvPolynomial (Fin 2) k, Prime f ∧ idealOf k ![u, v] = Ideal.span {f} := by
  have hbot : idealOf k ![u, v] ≠ ⊥ := idealOf_ne_bot_of_mem_racl k hv
  obtain ⟨f, hfP, hf⟩ :=
    (idealOf_isPrime k ![u, v]).exists_mem_prime_of_ne_bot hbot
  refine ⟨f, hf, ?_⟩
  -- The ideal has height one: nonzero, and strictly below a maximal ideal
  -- in a ring of Krull dimension two.
  have hheight : (idealOf k ![u, v]).height = 1 := by
    obtain ⟨M, hMmax, hPM⟩ := Ideal.exists_le_maximal (idealOf k ![u, v])
      (idealOf_isPrime k ![u, v]).ne_top
    have hlt : idealOf k ![u, v] < M :=
      lt_of_le_of_ne hPM fun h ↦ not_isMaximal_idealOf k hu (h ▸ hMmax)
    have hdim : ringKrullDim (MvPolynomial (Fin 2) k) = 2 := by
      rw [MvPolynomial.ringKrullDim_of_isNoetherianRing,
        ringKrullDim_eq_zero_of_field]
      simp
    have hM2 : (M.height : WithBot ℕ∞) ≤ 2 := by
      rw [← hdim]
      exact Ideal.height_le_ringKrullDim_of_ne_top hMmax.ne_top
    have hstep : (idealOf k ![u, v]).height + 1 ≤ M.height :=
      Ideal.height_add_one_le_of_lt_of_isPrime hlt
    have hle : (idealOf k ![u, v]).height + 1 ≤ 2 := by
      exact_mod_cast hstep.trans (WithBot.coe_le_coe.1 hM2)
    have hne : (idealOf k ![u, v]).height ≠ 0 := fun h ↦
      hbot (Ideal.height_eq_zero_iff_eq_bot.1 h)
    -- `ℕ∞` arithmetic: `h + 1 ≤ 2` and `h ≠ 0` force `h = 1`.
    set h := (idealOf k ![u, v]).height with hh
    have htop : h ≠ ⊤ := by
      intro ht
      rw [ht, top_add] at hle
      simp at hle
    lift h to ℕ using htop with n hn
    have h1 : n + 1 ≤ 2 := by exact_mod_cast hle
    have h2 : n ≠ 0 := by exact_mod_cast hne
    have h3 : n = 1 := by omega
    exact_mod_cast congrArg (Nat.cast : ℕ → ℕ∞) h3
  exact Ideal.eq_span_singleton_of_height_eq_one hheight hfP hf

section Translation

variable {σ : Type*} {K : Type*} [Field K]

/-- The translation substitution `X j ↦ X j + C (c j)`. -/
def translate (c : σ → K) : MvPolynomial σ K →ₐ[K] MvPolynomial σ K :=
  aeval fun j ↦ X j + C (c j)

@[simp]
theorem translate_X (c : σ → K) (j : σ) :
    translate c (X j) = X j + C (c j) := by
  simp [translate]

@[simp]
theorem translate_C (c : σ → K) (a : K) : translate c (C a) = C a := by
  simp [translate, algebraMap_eq]

/-- Degree drop, one-variable core: translating `X j ^ n` changes it only in
total degree `< n`. -/
theorem totalDegree_translate_pow_sub_lt (c : σ → K) (j : σ) {n : ℕ}
    (hn : 0 < n) :
    ((X j + C (c j)) ^ n - X j ^ n : MvPolynomial σ K).totalDegree < n := by
  induction n with
  | zero => exact absurd hn (lt_irrefl 0)
  | succ m ih =>
    rcases Nat.eq_zero_or_pos m with rfl | hm
    · simpa [totalDegree_C] using Nat.zero_lt_one
    · have key : ((X j + C (c j)) ^ (m + 1) - X j ^ (m + 1) : MvPolynomial σ K) =
          ((X j + C (c j)) ^ m - X j ^ m) * (X j + C (c j)) + X j ^ m * C (c j) := by
        ring
      rw [key]
      refine lt_of_le_of_lt (totalDegree_add _ _) (max_lt ?_ ?_)
      · refine lt_of_le_of_lt (totalDegree_mul _ _) ?_
        have h1 := ih hm
        have h2 : (X j + C (c j) : MvPolynomial σ K).totalDegree ≤ 1 := by
          refine le_trans (totalDegree_add _ _) ?_
          simp [totalDegree_X, totalDegree_C]
        omega
      · refine lt_of_le_of_lt (totalDegree_mul _ _) ?_
        rw [totalDegree_C, totalDegree_X_pow]
        omega

/-- A `ℕ`-valued finsupp with zero value sum is zero. -/
theorem finsupp_sum_id_eq_zero_iff {m : σ →₀ ℕ} :
    (m.sum fun _ e ↦ e) = 0 ↔ m = 0 := by
  constructor
  · intro h
    ext a
    rcases eq_or_ne (m a) 0 with h0 | h0
    · simp [h0]
    · exact absurd ((Finset.sum_eq_zero_iff.1 h) a (Finsupp.mem_support_iff.2 h0)) h0
  · intro h
    simp [h]

/-- Degree drop for monomials: translation changes a monomial only in total
degree strictly below its own. -/
theorem totalDegree_translate_monomial_sub_lt (c : σ → K) {m : σ →₀ ℕ}
    (hm : 0 < m.sum fun _ e ↦ e) :
    (translate c (monomial m 1) - monomial m 1).totalDegree <
      m.sum fun _ e ↦ e := by
  induction m using Finsupp.induction with
  | zero => simp at hm
  | single_add j n m' hjm' hn ih =>
    have hsum : ((Finsupp.single j n + m').sum fun _ e ↦ e) =
        n + m'.sum fun _ e ↦ e := by
      rw [Finsupp.sum_add_index' (fun _ ↦ rfl) fun _ _ _ ↦ rfl]
      rw [Finsupp.sum_single_index rfl]
    have hn' : 0 < n := Nat.pos_of_ne_zero hn
    -- Split the monomial and its translation into the two factors.
    have hmono : (monomial (Finsupp.single j n + m') (1 : K)) =
        monomial (Finsupp.single j n) 1 * monomial m' 1 := by
      rw [monomial_mul, mul_one]
    have htrA : translate c (monomial (Finsupp.single j n) (1 : K)) =
        (X j + C (c j)) ^ n := by
      rw [← X_pow_eq_monomial, map_pow, translate_X]
    rcases eq_or_ne m' 0 with rfl | hm'0
    · rw [add_zero, ← X_pow_eq_monomial, map_pow, translate_X,
        Finsupp.sum_single_index rfl]
      exact totalDegree_translate_pow_sub_lt c j hn'
    · have hm'pos : 0 < m'.sum fun _ e ↦ e := by
        rcases Nat.eq_zero_or_pos (m'.sum fun _ e ↦ e) with hz | hp
        · exact absurd (finsupp_sum_id_eq_zero_iff.1 hz) hm'0
        · exact hp
      have ihm := ih hm'pos
      have hB₀deg : (monomial m' (1 : K)).totalDegree = m'.sum fun _ e ↦ e :=
        totalDegree_monomial m' one_ne_zero
      have hBdeg : (translate c (monomial m' 1)).totalDegree ≤
          m'.sum fun _ e ↦ e := by
        have hsplit : translate c (monomial m' (1 : K)) =
            (translate c (monomial m' 1) - monomial m' 1) + monomial m' 1 := by
          ring
        rw [hsplit]
        refine le_trans (totalDegree_add _ _) (max_le (le_of_lt ?_) ?_)
        · exact hB₀deg ▸ ihm
        · exact le_of_eq hB₀deg
      -- Decompose the difference along the two factors.
      have hkey : translate c (monomial (Finsupp.single j n + m') 1) -
          monomial (Finsupp.single j n + m') 1 =
          ((X j + C (c j)) ^ n - X j ^ n) * translate c (monomial m' 1) +
            X j ^ n * (translate c (monomial m' 1) - monomial m' 1) := by
        rw [hmono, map_mul, htrA, X_pow_eq_monomial]
        ring
      rw [hkey, hsum]
      refine lt_of_le_of_lt (totalDegree_add _ _) (max_lt ?_ ?_)
      · refine lt_of_le_of_lt (totalDegree_mul _ _) ?_
        have h1 := totalDegree_translate_pow_sub_lt c j hn' (σ := σ)
        omega
      · refine lt_of_le_of_lt (totalDegree_mul _ _) ?_
        rw [totalDegree_X_pow]
        omega

/-- Degree drop for polynomials: translating a polynomial of positive total
degree changes it only in strictly smaller total degree. -/
theorem totalDegree_translate_sub_lt (c : σ → K) {F : MvPolynomial σ K}
    (hF : 0 < F.totalDegree) :
    (translate c F - F).totalDegree < F.totalDegree := by
  classical
  have hrepr : translate c F - F = ∑ m ∈ F.support,
      C (coeff m F) * (translate c (monomial m 1) - monomial m 1) := by
    conv_lhs => rw [F.as_sum]
    rw [map_sum, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun m _ ↦ ?_
    have hCm : monomial m (coeff m F) = C (coeff m F) * monomial m 1 := by
      rw [C_mul_monomial, mul_one]
    rw [hCm, map_mul, translate_C, mul_sub]
  rw [hrepr]
  refine lt_of_le_of_lt (totalDegree_finsetSum _ _) ?_
  rw [Finset.sup_lt_iff (by simpa using hF)]
  intro m hmF
  refine lt_of_le_of_lt (totalDegree_mul _ _) ?_
  rw [totalDegree_C, zero_add]
  rcases Nat.eq_zero_or_pos (m.sum fun _ e ↦ e) with hz | hp
  · have hm0 : m = 0 := finsupp_sum_id_eq_zero_iff.1 hz
    subst hm0
    have h1 : (monomial (0 : σ →₀ ℕ) (1 : K)) = 1 := by
      rw [monomial_zero']
      exact C_1
    rw [h1, map_one, sub_self]
    simpa using hF
  · exact lt_of_lt_of_le (totalDegree_translate_monomial_sub_lt c hp)
      (le_totalDegree hmF)

/-- **Rigidity of the generator under translation**: a translation that fixes
the ideal generated by `F` fixes `F` itself. The translation perturbs `F`
only below its top degree, so the comparison unit is a constant, and a
top-degree coefficient forces it to be `1` (step 4c of the fused curve-coset
chain). -/
theorem translate_eq_self_of_span_eq {c : σ → K} {F : MvPolynomial σ K}
    (hF : F ≠ 0) (h : Ideal.span {translate c F} = Ideal.span {F}) :
    translate c F = F := by
  classical
  rcases Nat.eq_zero_or_pos F.totalDegree with h0 | hpos
  · have hFC : F = C (F.coeff 0) := totalDegree_eq_zero_iff_eq_C.1 h0
    rw [hFC, translate_C]
  · obtain ⟨u, hu⟩ := Ideal.span_singleton_eq_span_singleton.1 h
    have hτF : translate c F ≠ 0 := by
      intro h0
      rw [h0, zero_mul] at hu
      exact hF hu.symm
    have hdrop := totalDegree_translate_sub_lt c hpos
    -- The translation preserves the total degree.
    have hτdeg : (translate c F).totalDegree = F.totalDegree := by
      have hle : (translate c F).totalDegree ≤ F.totalDegree := by
        have hsplit : translate c F = (translate c F - F) + F := by ring
        rw [hsplit]
        exact le_trans (totalDegree_add _ _) (max_le (le_of_lt hdrop) le_rfl)
      have hge : F.totalDegree ≤ (translate c F).totalDegree := by
        have hsplit : F = translate c F + -(translate c F - F) := by ring
        have hFle : F.totalDegree ≤ max (translate c F).totalDegree
            (translate c F - F).totalDegree := by
          calc F.totalDegree
              = (translate c F + -(translate c F - F)).totalDegree := by
                rw [← hsplit]
            _ ≤ max (translate c F).totalDegree
                (-(translate c F - F)).totalDegree := totalDegree_add _ _
            _ = max (translate c F).totalDegree
                (translate c F - F).totalDegree := by rw [totalDegree_neg]
        rcases max_cases (translate c F).totalDegree
            (translate c F - F).totalDegree with ⟨hmax, -⟩ | ⟨hmax, -⟩ <;>
          rw [hmax] at hFle <;> omega
      omega
    -- The unit is a nonzero constant.
    have hudeg : (u : MvPolynomial σ K).totalDegree = 0 := by
      have hprod := totalDegree_mul_of_isDomain hτF u.ne_zero
      rw [hu, hτdeg] at hprod
      omega
    set a : K := coeff 0 (u : MvPolynomial σ K) with ha_def
    have ha : (u : MvPolynomial σ K) = C a := totalDegree_eq_zero_iff_eq_C.1 hudeg
    -- A top-degree coefficient of `F` is unchanged by the translation,
    -- forcing the unit to be `1`.
    obtain ⟨e, heF, hesum⟩ := F.support.exists_mem_eq_sup
      (support_nonempty.2 hF) fun m : σ →₀ ℕ ↦ Multiset.card (Finsupp.toMultiset m)
    have hesum' : F.totalDegree = ∑ i ∈ e.support, e i := by
      rw [totalDegree_eq, hesum, Finsupp.card_toMultiset]
      rfl
    have hcoeff : coeff e F ≠ 0 := mem_support_iff.1 heF
    have htop : coeff e (translate c F) = coeff e F := by
      have hzero : coeff e (translate c F - F) = 0 :=
        coeff_eq_zero_of_totalDegree_lt (hesum' ▸ hdrop)
      have hsplit : translate c F = (translate c F - F) + F := by ring
      rw [hsplit, coeff_add, hzero, zero_add]
    rw [mul_comm] at hu
    have hcmp : coeff e F = a * coeff e F := by
      nth_rewrite 1 [← hu]
      rw [ha, coeff_C_mul, htop]
    have ha1 : a = 1 :=
      mul_right_cancel₀ hcoeff (by rw [← hcmp, one_mul])
    rw [ha, ha1, C_1, one_mul] at hu
    exact hu

theorem translate_translate (c c' : σ → K) (g : MvPolynomial σ K) :
    translate c (translate c' g) = translate (c + c') g := by
  have hcomp : (translate (σ := σ) c).comp (translate c') = translate (c + c') := by
    refine algHom_ext fun i ↦ ?_
    simp [translate, map_add, add_assoc]
  exact congrArg (fun (f : MvPolynomial σ K →ₐ[K] MvPolynomial σ K) ↦ f g) hcomp

theorem translate_zero (g : MvPolynomial σ K) :
    translate (0 : σ → K) g = g := by
  have hid : translate (σ := σ) (0 : σ → K) = AlgHom.id K _ := by
    refine algHom_ext fun i ↦ ?_
    simp [translate]
  rw [hid]
  rfl

theorem translate_neg_translate (c : σ → K) (g : MvPolynomial σ K) :
    translate (-c) (translate c g) = g := by
  rw [translate_translate, neg_add_cancel, translate_zero]

theorem translate_translate_neg (c : σ → K) (g : MvPolynomial σ K) :
    translate c (translate (-c) g) = g := by
  rw [translate_translate, add_neg_cancel, translate_zero]

/-- Evaluation through a translation shifts the point. -/
theorem aeval_translate {Ω : Type*} [Field Ω] [Algebra K Ω]
    (a : σ → Ω) (c : σ → K) (g : MvPolynomial σ K) :
    aeval a (translate c g) = aeval (fun j ↦ a j + algebraMap K Ω (c j)) g := by
  have hcomp : ((aeval a : MvPolynomial σ K →ₐ[K] Ω).comp (translate c)) =
      aeval fun j ↦ a j + algebraMap K Ω (c j) := by
    refine algHom_ext fun i ↦ ?_
    simp [translate, algebraMap_eq]
  exact congrArg (fun (f : MvPolynomial σ K →ₐ[K] Ω) ↦ f g) hcomp

/-- Vanishing ideals transform by translation: the ideal of the shifted
point is generated by the translated generator. -/
theorem idealOf_translate_span {Ω : Type*} [Field Ω] [Algebra K Ω]
    {a : Fin 2 → Ω} {c : Fin 2 → K} {F : MvPolynomial (Fin 2) K}
    (h : idealOf K a = Ideal.span {F}) :
    idealOf K (fun j ↦ a j - algebraMap K Ω (c j)) =
      Ideal.span {translate c F} := by
  classical
  have hkey : ∀ g : MvPolynomial (Fin 2) K,
      aeval (fun j ↦ a j - algebraMap K Ω (c j)) (translate c g) = aeval a g := by
    intro g
    have hfun : (fun j ↦ (a j - algebraMap K Ω (c j)) + algebraMap K Ω (c j)) = a := by
      funext j
      rw [sub_add_cancel]
    rw [aeval_translate, hfun]
  ext g
  rw [mem_idealOf_iff, Ideal.mem_span_singleton]
  constructor
  · intro hg
    have hg' : translate (-c) g ∈ idealOf K a := by
      rw [mem_idealOf_iff, ← hkey (translate (-c) g), translate_translate_neg]
      exact hg
    rw [h, Ideal.mem_span_singleton] at hg'
    obtain ⟨e, he⟩ := hg'
    refine ⟨translate c e, ?_⟩
    have hT := congrArg (translate c) he
    rw [translate_translate_neg, map_mul] at hT
    exact hT
  · rintro ⟨e, rfl⟩
    rw [map_mul]
    have hF : aeval (fun j ↦ a j - algebraMap K Ω (c j)) (translate c F) = 0 := by
      rw [hkey]
      exact (mem_idealOf_iff K).1 (h ▸ Ideal.subset_span rfl)
    rw [hF, zero_mul]

end Translation

section Scaling

variable {σ : Type*} {K : Type*} [Field K]

/-- The scaling substitution `X j ↦ C (c j) * X j` — the multiplicative
analogue of `translate`. -/
def scale (c : σ → K) : MvPolynomial σ K →ₐ[K] MvPolynomial σ K :=
  aeval fun j ↦ C (c j) * X j

@[simp]
theorem scale_X (c : σ → K) (j : σ) : scale c (X j) = C (c j) * X j := by
  simp [scale]

@[simp]
theorem scale_C (c : σ → K) (a : K) : scale c (C a) = C a := by
  simp [scale, algebraMap_eq]

/-- Scaling acts on a monomial by the corresponding monomial value. -/
theorem scale_monomial (c : σ → K) (m : σ →₀ ℕ) (a : K) :
    scale c (monomial m a) = monomial m ((m.prod fun j e ↦ c j ^ e) * a) := by
  classical
  rw [scale, aeval_monomial]
  have hprod : (m.prod fun j e ↦ (C (c j) * X j : MvPolynomial σ K) ^ e) =
      C (m.prod fun j e ↦ c j ^ e) * m.prod fun j e ↦ (X j : MvPolynomial σ K) ^ e := by
    rw [Finsupp.prod, Finsupp.prod, Finsupp.prod, map_prod,
      ← Finset.prod_mul_distrib]
    refine Finset.prod_congr rfl fun j _ ↦ ?_
    rw [mul_pow, C_pow]
  have hmono : (m.prod fun j e ↦ (X j : MvPolynomial σ K) ^ e) =
      monomial m (1 : K) := by
    rw [monomial_eq, C_1, one_mul]
  rw [hprod, MvPolynomial.algebraMap_eq, hmono, ← mul_assoc, ← C_mul,
    C_mul_monomial, mul_one, mul_comm a (m.prod fun j e ↦ c j ^ e)]

/-- The coefficient formula for scaling: each coefficient is multiplied by
the corresponding monomial value. In particular the support is preserved
when the scaling vector has no zero entries. -/
theorem coeff_scale (c : σ → K) (g : MvPolynomial σ K) (m : σ →₀ ℕ) :
    coeff m (scale c g) = (m.prod fun j e ↦ c j ^ e) * coeff m g := by
  classical
  conv_lhs => rw [g.as_sum, map_sum]
  rw [Finset.sum_congr rfl fun m' _ ↦ scale_monomial c m' (coeff m' g)]
  rw [MvPolynomial.coeff_sum]
  rw [Finset.sum_congr rfl fun m' _ ↦ MvPolynomial.coeff_monomial m m' _]
  by_cases hm : m ∈ g.support
  · rw [Finset.sum_ite_eq' g.support m
      fun m' ↦ (m'.prod fun j e ↦ c j ^ e) * coeff m' g, if_pos hm]
  · rw [Finset.sum_ite_eq' g.support m
      fun m' ↦ (m'.prod fun j e ↦ c j ^ e) * coeff m' g, if_neg hm]
    rw [MvPolynomial.notMem_support_iff.1 hm, mul_zero]

end Scaling

end

end AclGeom
