/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Correspondence.Family
import AclGeom.Correspondence.BranchGroupoid
import Mathlib.RingTheory.AlgebraicIndependent.AlgebraicClosure

/-!
# Finite normal covers of generic correspondence-family members

A generic family member is a tuple `(p,x,y)` in which `y` is algebraic
over the independent prefix `(p,x)`.  Hence its complete function field is
a finite extension of the parameter/source field.  Equality of two complete
family loci canonically identifies both levels of this extension and sends
every displayed coordinate to its counterpart.  The extension equivalence
then lifts to a semilinear equivalence of canonical normal covers.

This is the coefficient-aware comparison needed when two independently
relocated branches represent the same parameterized correspondence.  It
remembers the parameter block and the selected branch, unlike an abstract
equivalence of the endpoint rational function fields.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- Equality of two complete family loci with the same literal parameter
tuple descends to equality of the endpoint-pair ideals over the field
generated by that parameter.  The complete-locus equivalence fixes the
parameter field generator by generator and carries the displayed source
and target coordinates, so it transports every polynomial relation over
that field in both directions. -/
theorem pairIdeal_eq_over_commonParameter_of_familyIdeal_eq
    {d : ℕ} {p : Fin d → Ω} {x y x' y' : Ω}
    (h : idealOf k (Fin.snoc (Fin.snoc p x) y) =
      idealOf k (Fin.snoc (Fin.snoc p x') y')) :
    idealOf (↥(adjoin k (Set.range p))) ![x, y] =
      idealOf (↥(adjoin k (Set.range p))) ![x', y'] := by
  classical
  let E : IntermediateField k Ω := adjoin k (Set.range p)
  change idealOf (↥E) ![x, y] = idealOf (↥E) ![x', y']
  let t : Fin (d + 2) → Ω := Fin.snoc (Fin.snoc p x) y
  let t' : Fin (d + 2) → Ω := Fin.snoc (Fin.snoc p x') y'
  let L : IntermediateField k Ω := adjoin k (Set.range t)
  let L' : IntermediateField k Ω := adjoin k (Set.range t')
  have hEL : E ≤ L := by
    apply adjoin.mono
    rintro _ ⟨i, rfl⟩
    exact ⟨i.castSucc.castSucc, by simp [t]⟩
  have hEL' : E ≤ L' := by
    apply adjoin.mono
    rintro _ ⟨i, rfl⟩
    exact ⟨i.castSucc.castSucc, by simp [t']⟩
  letI : Algebra E L := (IntermediateField.inclusion hEL).toAlgebra
  letI : Algebra E L' := (IntermediateField.inclusion hEL').toAlgebra
  let e₀ : L ≃ₐ[k] L' := locusFunctionFieldEquivOfIdealEq h
  have he₀ : e₀.toAlgHom.comp (IntermediateField.inclusion hEL) =
      IntermediateField.inclusion hEL' := by
    apply adjoin_algHom_ext k
    rintro _ ⟨i, rfl⟩
    change e₀ ⟨p i, _⟩ = ⟨p i, _⟩
    simpa [e₀, t, t'] using
      (locusFunctionFieldEquivOfIdealEq_apply h i.castSucc.castSucc)
  let e : L ≃ₐ[E] L' :=
    { e₀.toRingEquiv with
      commutes' := fun z ↦ DFunLike.congr_fun he₀ z }
  let q : Fin 2 → L :=
    ![⟨x, subset_adjoin k _ ⟨(Fin.last d).castSucc, by simp [t]⟩⟩,
      ⟨y, subset_adjoin k _ ⟨Fin.last (d + 1), by simp [t]⟩⟩]
  let q' : Fin 2 → L' :=
    ![⟨x', subset_adjoin k _ ⟨(Fin.last d).castSucc, by simp [t']⟩⟩,
      ⟨y', subset_adjoin k _ ⟨Fin.last (d + 1), by simp [t']⟩⟩]
  have heq (i : Fin 2) : e (q i) = q' i := by
    fin_cases i
    · simpa [e, e₀, q, q', t, t'] using
        (locusFunctionFieldEquivOfIdealEq_apply h (Fin.last d).castSucc)
    · simpa [e, e₀, q, q', t, t'] using
        (locusFunctionFieldEquivOfIdealEq_apply h (Fin.last (d + 1)))
  let vL : L →ₐ[E] Ω :=
    { L.val.toRingHom with commutes' := fun _ ↦ rfl }
  let vL' : L' →ₐ[E] Ω :=
    { L'.val.toRingHom with commutes' := fun _ ↦ rfl }
  ext f
  rw [mem_idealOf_iff, mem_idealOf_iff]
  have hval : MvPolynomial.aeval ![x, y] f =
      L.val (MvPolynomial.aeval q f) := by
    have hqval : (fun i ↦ vL (q i)) = (![x, y] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x, y] f =
          MvPolynomial.aeval (fun i ↦ vL (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vL (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) vL f).symm
      _ = L.val (MvPolynomial.aeval q f) := rfl
  have hval' : MvPolynomial.aeval ![x', y'] f =
      L'.val (MvPolynomial.aeval q' f) := by
    have hqval : (fun i ↦ vL' (q' i)) = (![x', y'] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x', y'] f =
          MvPolynomial.aeval (fun i ↦ vL' (q' i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vL' (MvPolynomial.aeval q' f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q') vL' f).symm
      _ = L'.val (MvPolynomial.aeval q' f) := rfl
  have heval : MvPolynomial.aeval q' f =
      e (MvPolynomial.aeval q f) := by
    have hqeval : (fun i ↦ e.toAlgHom (q i)) = q' := by
      funext i
      exact heq i
    calc
      MvPolynomial.aeval q' f =
          MvPolynomial.aeval (fun i ↦ e.toAlgHom (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqeval.symm
      _ = e (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) e.toAlgHom f).symm
  rw [hval, hval', heval]
  constructor
  · intro hz
    have hzero : MvPolynomial.aeval q f = 0 := by
      exact L.val.injective hz
    rw [hzero, map_zero]
    rfl
  · intro hz
    have hzero : e (MvPolynomial.aeval q f) = 0 := by
      apply L'.val.injective
      simpa using hz
    have := e.injective (hzero.trans (map_zero e).symm)
    simpa using congrArg L.val this

/-- If an auxiliary tuple is jointly independent from a parameter/source
prefix, it remains independent after adjoining a target algebraic over that
prefix.  The conclusion is stated over the endpoint-pair field above the
parameter field, exactly as required by independent scalar extension. -/
theorem auxiliary_independent_over_parameterPairField
    {d n : ℕ} {p : Fin d → Ω} {r : Fin n → Ω} {x y : Ω}
    (hprx : AlgebraicIndependent k
      (Sum.elim r (Fin.snoc p x) : Fin n ⊕ Fin (d + 1) → Ω))
    (hy : y ∈ racl k (insert x (Set.range p))) :
    AlgebraicIndependent
      (↥(adjoin (↥(adjoin k (Set.range p)))
        (Set.range (![x, y] : Fin 2 → Ω)))) r := by
  classical
  let base : Fin (d + 1) → Ω := Fin.snoc p x
  let B : IntermediateField k Ω := adjoin k (Set.range base)
  let E : IntermediateField k Ω := adjoin k (Set.range p)
  let L : IntermediateField (↥E) Ω :=
    adjoin (↥E) (Set.range (![x, y] : Fin 2 → Ω))
  have hrB : AlgebraicIndependent (↥B) r := by
    change AlgebraicIndependent
      (↥(adjoin k (Set.range (Fin.snoc p x)))) r
    rw [IntermediateField.algebraicIndependent_adjoin_iff]
    exact (AlgebraicIndependent.sumElim_iff.1 hprx).2
  have hEB : E ≤ B := by
    apply adjoin.mono
    rintro _ ⟨i, rfl⟩
    exact ⟨i.castSucc, by simp [base]⟩
  have hBL : B ≤ L.restrictScalars k := by
    apply adjoin_le_iff.2
    rintro _ ⟨i, rfl⟩
    refine Fin.lastCases ?_ (fun j ↦ ?_) i
    · simpa [L, base] using
        (subset_adjoin (↥E)
          (Set.range (![x, y] : Fin 2 → Ω))
          (Set.mem_range_self (0 : Fin 2)))
    · simpa [L, base] using
        (IntermediateField.algebraMap_mem L
          ⟨p j, subset_adjoin k _ (Set.mem_range_self j)⟩)
  letI : Algebra B L := (IntermediateField.inclusion hBL).toAlgebra
  haveI : IsScalarTower B L Ω := IsScalarTower.of_algebraMap_eq' rfl
  have hLB : Algebra.IsAlgebraic (↥B) (↥L) := by
    constructor
    rintro ⟨z, hz⟩
    rw [← isAlgebraic_algHom_iff
      (IsScalarTower.toAlgHom (↥B) (↥L) Ω) Subtype.val_injective]
    change IsAlgebraic (↥B) z
    apply adjoin_induction (F := ↥E) (s := Set.range (![x, y] : Fin 2 → Ω))
        (p := fun z _ ↦ IsAlgebraic (↥B) z)
    · rintro _ ⟨i, rfl⟩
      fin_cases i
      · exact isAlgebraic_algebraMap (R := ↥B) (A := Ω)
          ⟨x, subset_adjoin k _ ⟨Fin.last d, by simp [base]⟩⟩
      · have hy' : IsAlgebraic (↥B) y := by
          change IsAlgebraic
            (↥(adjoin k (Set.range (Fin.snoc p x)))) y
          rw [Fin.range_snoc]
          exact (mem_racl_iff k).1 hy
        exact hy'
    · intro z
      exact isAlgebraic_algebraMap (R := ↥B) (A := Ω)
        ⟨z, hEB z.2⟩
    · exact fun _ _ _ _ hx hy ↦ hx.add hy
    · exact fun _ _ hx ↦ hx.inv
    · exact fun _ _ _ _ hx hy ↦ hx.mul hy
    · exact hz
  exact hrB.extendScalars L

/-- If an auxiliary tuple is jointly independent from a family
parameter/source prefix, then the source remains generic over the field
generated by the parameter and auxiliary coordinates. -/
theorem source_notMem_racl_independentExtension
    {d n : ℕ} {p : Fin d → Ω} {r : Fin n → Ω} {x : Ω}
    (hprx : AlgebraicIndependent k
      (Sum.elim r (Fin.snoc p x) : Fin n ⊕ Fin (d + 1) → Ω)) :
    x ∉ racl (↥(adjoin k (Set.range p ∪ Set.range r)))
      (∅ : Set Ω) := by
  let B : IntermediateField k Ω := adjoin k (Set.range r)
  have hswap : AlgebraicIndependent k
      (Sum.elim (Fin.snoc p x) r : Fin (d + 1) ⊕ Fin n → Ω) := by
    have h := AlgebraicIndependent.comp hprx
      (Equiv.sumComm (Fin (d + 1)) (Fin n))
      (Equiv.sumComm (Fin (d + 1)) (Fin n)).injective
    convert h using 1
    funext i
    rcases i with i | i <;> rfl
  have hpx : AlgebraicIndependent (↥B) (Fin.snoc p x) := by
    change AlgebraicIndependent
      (↥(adjoin k (Set.range r))) (Fin.snoc p x)
    rw [IntermediateField.algebraicIndependent_adjoin_iff]
    exact (AlgebraicIndependent.sumElim_iff.1 hswap).2
  let S : Set (Fin (d + 1)) := Set.range Fin.castSucc
  have hlast : Fin.last d ∉ S := by
    rintro ⟨i, hi⟩
    exact Fin.castSucc_ne_last i hi
  have hx := AlgebraicIndependent.notMem_racl_image hpx hlast
  have himage : Fin.snoc p x '' S = Set.range p := by
    rw [← Set.range_comp]
    congr 1
    funext i
    simp
  rw [himage] at hx
  rw [mem_racl_adjoin_base_iff, Set.union_empty]
  rw [mem_racl_adjoin_base_iff] at hx
  simpa only [B, Fin.snoc_last, Set.union_comm] using hx

set_option maxHeartbeats 800000 in
-- The nested coefficient-field transports elaborate above the default budget.
/-- Equality of endpoint-pair ideals survives adjoining a matching tuple
that is algebraically independent over both complete endpoint fields.  The
extended function-field equivalence fixes the enlarged coefficient field
and still carries both displayed endpoints. -/
theorem pairIdeal_eq_over_independentExtension_of_pairIdeal_eq
    {E : IntermediateField k Ω} {ι : Type*} {r : ι → Ω}
    {x y x' y' : Ω}
    (h : idealOf (↥E) ![x, y] = idealOf (↥E) ![x', y'])
    (hr : AlgebraicIndependent
      (↥(adjoin (↥E) (Set.range (![x, y] : Fin 2 → Ω)))) r)
    (hr' : AlgebraicIndependent
      (↥(adjoin (↥E) (Set.range (![x', y'] : Fin 2 → Ω)))) r) :
    idealOf
        (↥((adjoin (↥E) (Set.range r)).restrictScalars k)) ![x, y] =
      idealOf
        (↥((adjoin (↥E) (Set.range r)).restrictScalars k)) ![x', y'] := by
  classical
  let L : IntermediateField (↥E) Ω :=
    adjoin (↥E) (Set.range (![x, y] : Fin 2 → Ω))
  let L' : IntermediateField (↥E) Ω :=
    adjoin (↥E) (Set.range (![x', y'] : Fin 2 → Ω))
  let C : IntermediateField (↥E) Ω := adjoin (↥E) (Set.range r)
  let Ck : IntermediateField k Ω := C.restrictScalars k
  let M : IntermediateField (↥L) Ω := adjoin (↥L) (Set.range r)
  let M' : IntermediateField (↥L') Ω := adjoin (↥L') (Set.range r)
  let e₀ : L ≃ₐ[E] L' := locusFunctionFieldEquivOfIdealEq h
  let ex : M ≃ₐ[E] M' :=
    adjoinIndependentEquivOfEquiv e₀ hr hr'
  have hCM : C ≤ M.restrictScalars (↥E) := by
    apply adjoin_le_iff.2
    rintro _ ⟨i, rfl⟩
    exact subset_adjoin (↥L) _ (Set.mem_range_self i)
  have hCM' : C ≤ M'.restrictScalars (↥E) := by
    apply adjoin_le_iff.2
    rintro _ ⟨i, rfl⟩
    exact subset_adjoin (↥L') _ (Set.mem_range_self i)
  let iCkM : Ck →+* M :=
    { toFun := fun z ↦ ⟨z, hCM z.2⟩
      map_one' := rfl
      map_mul' := fun _ _ ↦ rfl
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  let iCkM' : Ck →+* M' :=
    { toFun := fun z ↦ ⟨z, hCM' z.2⟩
      map_one' := rfl
      map_mul' := fun _ _ ↦ rfl
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  letI : Algebra Ck M := iCkM.toAlgebra
  letI : Algebra Ck M' := iCkM'.toAlgebra
  have hexC : ex.toAlgHom.comp (IntermediateField.inclusion hCM) =
      IntermediateField.inclusion hCM' := by
    apply adjoin_algHom_ext (↥E)
    rintro _ ⟨i, rfl⟩
    change ex ⟨r i, _⟩ = ⟨r i, _⟩
    simpa [ex, M, M'] using
      (adjoinIndependentEquivOfEquiv_generator e₀ hr hr' i)
  let e : M ≃ₐ[Ck] M' :=
    { ex.toRingEquiv with
      commutes' := fun z ↦ by
        change ex ⟨z, hCM z.2⟩ = ⟨z, hCM' z.2⟩
        exact DFunLike.congr_fun hexC (⟨z, z.2⟩ : C) }
  let q : Fin 2 → M :=
    ![algebraMap L M
        ⟨x, subset_adjoin (↥E) _ (Set.mem_range_self 0)⟩,
      algebraMap L M
        ⟨y, subset_adjoin (↥E) _ (Set.mem_range_self 1)⟩]
  let q' : Fin 2 → M' :=
    ![algebraMap L' M'
        ⟨x', subset_adjoin (↥E) _ (Set.mem_range_self 0)⟩,
      algebraMap L' M'
        ⟨y', subset_adjoin (↥E) _ (Set.mem_range_self 1)⟩]
  have heq (i : Fin 2) : e (q i) = q' i := by
    fin_cases i
    · change ex (algebraMap L M ⟨x, _⟩) = algebraMap L' M' ⟨x', _⟩
      rw [adjoinIndependentEquivOfEquiv_algebraMap]
      exact congrArg (algebraMap L' M')
        (locusFunctionFieldEquivOfIdealEq_apply h 0)
    · change ex (algebraMap L M ⟨y, _⟩) = algebraMap L' M' ⟨y', _⟩
      rw [adjoinIndependentEquivOfEquiv_algebraMap]
      exact congrArg (algebraMap L' M')
        (locusFunctionFieldEquivOfIdealEq_apply h 1)
  let vM : M →ₐ[Ck] Ω :=
    { M.val.toRingHom with commutes' := fun _ ↦ rfl }
  let vM' : M' →ₐ[Ck] Ω :=
    { M'.val.toRingHom with commutes' := fun _ ↦ rfl }
  change idealOf (↥Ck) ![x, y] = idealOf (↥Ck) ![x', y']
  ext f
  rw [mem_idealOf_iff, mem_idealOf_iff]
  have hval : MvPolynomial.aeval ![x, y] f =
      M.val (MvPolynomial.aeval q f) := by
    have hqval : (fun i ↦ vM (q i)) = (![x, y] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x, y] f =
          MvPolynomial.aeval (fun i ↦ vM (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vM (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) vM f).symm
      _ = M.val (MvPolynomial.aeval q f) := rfl
  have hval' : MvPolynomial.aeval ![x', y'] f =
      M'.val (MvPolynomial.aeval q' f) := by
    have hqval : (fun i ↦ vM' (q' i)) = (![x', y'] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x', y'] f =
          MvPolynomial.aeval (fun i ↦ vM' (q' i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vM' (MvPolynomial.aeval q' f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q') vM' f).symm
      _ = M'.val (MvPolynomial.aeval q' f) := rfl
  have heval : MvPolynomial.aeval q' f =
      e (MvPolynomial.aeval q f) := by
    have hqeval : (fun i ↦ e.toAlgHom (q i)) = q' := by
      funext i
      exact heq i
    calc
      MvPolynomial.aeval q' f =
          MvPolynomial.aeval (fun i ↦ e.toAlgHom (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqeval.symm
      _ = e (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) e.toAlgHom f).symm
  rw [hval, hval', heval]
  constructor
  · intro hz
    have hzero : MvPolynomial.aeval q f = 0 := M.val.injective hz
    rw [hzero, map_zero]
    rfl
  · intro hz
    have hzero : e (MvPolynomial.aeval q f) = 0 := by
      apply M'.val.injective
      simpa using hz
    have := e.injective (hzero.trans (map_zero e).symm)
    simpa using congrArg M.val this

namespace FiniteCorrespondencePair

variable (P : FiniteCorrespondencePair k Ω)

@[simp] private theorem coe_equivOfEq
    {E E' : IntermediateField k Ω} (h : E = E') (x : E) :
    (((IntermediateField.equivOfEq h) x : E') : Ω) = x := by
  subst E'
  rfl

/-- Equality of selected curve ideals restricts to equality of the
one-coordinate source loci. -/
theorem sourceIdeal_eq_of_ideal_eq
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    idealOf k (![P.source] : Fin 1 → Ω) =
      idealOf k (![Q.source] : Fin 1 → Ω) := by
  let e : Fin 1 → Fin 2 := Fin.castSucc
  have h' := idealOf_comp_eq_of_idealOf_eq h e
  convert h' using 1 <;> congr 1 <;> funext i <;> fin_cases i <;> rfl

/-- Equal selected curve ideals identify the finite extensions from the
source-coordinate fields to the complete branch fields.  The comparison
sends both displayed endpoints to their counterparts and remembers the
source-field inclusion square. -/
def extensionEquivOfIdealEq
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    FiniteCover.ExtensionEquiv P.sourceField_le_branchField
      Q.sourceField_le_branchField := by
  let hsource := P.sourceIdeal_eq_of_ideal_eq Q h
  let pSourceRange : P.sourceField =
      adjoin k (Set.range (![P.source] : Fin 1 → Ω)) := by
    ext z
    simp [FiniteCorrespondencePair.sourceField,
      Matrix.range_cons, Matrix.range_empty]
  let qSourceRange : Q.sourceField =
      adjoin k (Set.range (![Q.source] : Fin 1 → Ω)) := by
    ext z
    simp [FiniteCorrespondencePair.sourceField,
      Matrix.range_cons, Matrix.range_empty]
  let pBranchRange : P.branchField =
      adjoin k (Set.range (![P.source, P.target] : Fin 2 → Ω)) := by
    change adjoin k {P.source, P.target} = _
    rw [show Set.range (![P.source, P.target] : Fin 2 → Ω) =
      {P.target, P.source} by
        simp [Matrix.range_cons, Matrix.range_empty]]
    exact congrArg (adjoin k) (Set.pair_comm _ _)
  let qBranchRange : Q.branchField =
      adjoin k (Set.range (![Q.source, Q.target] : Fin 2 → Ω)) := by
    change adjoin k {Q.source, Q.target} = _
    rw [show Set.range (![Q.source, Q.target] : Fin 2 → Ω) =
      {Q.target, Q.source} by
        simp [Matrix.range_cons, Matrix.range_empty]]
    exact congrArg (adjoin k) (Set.pair_comm _ _)
  let eBase : (↥P.sourceField) ≃ₐ[k] (↥Q.sourceField) :=
    (IntermediateField.equivOfEq pSourceRange).trans
      ((locusFunctionFieldEquivOfIdealEq hsource).trans
        (IntermediateField.equivOfEq qSourceRange.symm))
  let eTotal : (↥P.branchField) ≃ₐ[k] (↥Q.branchField) :=
    (IntermediateField.equivOfEq pBranchRange).trans
      ((locusFunctionFieldEquivOfIdealEq h).trans
        (IntermediateField.equivOfEq qBranchRange.symm))
  refine
    { baseEquiv := eBase
      totalEquiv := eTotal
      commutes := ?_ }
  apply adjoin_algHom_ext k
  rintro _ hz
  rw [Set.mem_singleton_iff] at hz
  subst hz
  change eTotal ⟨P.source, _⟩ =
    IntermediateField.inclusion Q.sourceField_le_branchField
      (eBase ⟨P.source, _⟩)
  apply Subtype.ext
  change ((eTotal ⟨P.source, _⟩ : Q.branchField) : Ω) =
    ((eBase ⟨P.source, _⟩ : Q.sourceField) : Ω)
  have htotal := congrArg Subtype.val
    (locusFunctionFieldEquivOfIdealEq_apply h 0)
  have hbase := congrArg Subtype.val
    (locusFunctionFieldEquivOfIdealEq_apply hsource 0)
  have hpTotal :
      IntermediateField.equivOfEq pBranchRange
          ⟨P.source, subset_adjoin k _ (by simp)⟩ =
        ⟨(![P.source, P.target] : Fin 2 → Ω) 0,
          subset_adjoin k _ (Set.mem_range_self 0)⟩ := by
    apply Subtype.ext
    rfl
  have hpBase :
      IntermediateField.equivOfEq pSourceRange
          ⟨P.source, subset_adjoin k _ (by simp)⟩ =
        ⟨(![P.source] : Fin 1 → Ω) 0,
          subset_adjoin k _ (Set.mem_range_self 0)⟩ := by
    apply Subtype.ext
    rfl
  dsimp only [eTotal, eBase]
  simp only [AlgEquiv.trans_apply]
  rw [hpTotal, hpBase]
  simpa only [coe_equivOfEq] using
    htotal.trans hbase.symm

/-- On the source-coordinate field, the extension comparison sends the
displayed source to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_base_source
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    (P.extensionEquivOfIdealEq Q h).baseEquiv
        ⟨P.source, subset_adjoin k _ (by simp)⟩ =
      ⟨Q.source, subset_adjoin k _ (by simp)⟩ := by
  let hsource := P.sourceIdeal_eq_of_ideal_eq Q h
  let pSourceRange : P.sourceField =
      adjoin k (Set.range (![P.source] : Fin 1 → Ω)) := by
    ext z
    simp [FiniteCorrespondencePair.sourceField,
      Matrix.range_cons, Matrix.range_empty]
  let qSourceRange : Q.sourceField =
      adjoin k (Set.range (![Q.source] : Fin 1 → Ω)) := by
    ext z
    simp [FiniteCorrespondencePair.sourceField,
      Matrix.range_cons, Matrix.range_empty]
  let eBase : (↥P.sourceField) ≃ₐ[k] (↥Q.sourceField) :=
    (IntermediateField.equivOfEq pSourceRange).trans
      ((locusFunctionFieldEquivOfIdealEq hsource).trans
        (IntermediateField.equivOfEq qSourceRange.symm))
  change eBase ⟨P.source, subset_adjoin k _ (by simp)⟩ =
    ⟨Q.source, subset_adjoin k _ (by simp)⟩
  apply Subtype.ext
  have hpBase :
      IntermediateField.equivOfEq pSourceRange
          ⟨P.source, subset_adjoin k _ (by simp)⟩ =
        ⟨(![P.source] : Fin 1 → Ω) 0,
          subset_adjoin k _ (Set.mem_range_self 0)⟩ := by
    apply Subtype.ext
    rfl
  have hbase := congrArg Subtype.val
    (locusFunctionFieldEquivOfIdealEq_apply hsource 0)
  dsimp only [eBase]
  simp only [AlgEquiv.trans_apply]
  rw [hpBase]
  simpa only [coe_equivOfEq, Matrix.cons_val_zero] using hbase

/-- On the branch field, the extension comparison sends the displayed
target to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_total_target
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    (P.extensionEquivOfIdealEq Q h).totalEquiv
        ⟨P.target, subset_adjoin k _ (by simp)⟩ =
      ⟨Q.target, subset_adjoin k _ (by simp)⟩ := by
  let pBranchRange : P.branchField =
      adjoin k (Set.range (![P.source, P.target] : Fin 2 → Ω)) := by
    change adjoin k {P.source, P.target} = _
    rw [show Set.range (![P.source, P.target] : Fin 2 → Ω) =
      {P.target, P.source} by
        simp [Matrix.range_cons, Matrix.range_empty]]
    exact congrArg (adjoin k) (Set.pair_comm _ _)
  let qBranchRange : Q.branchField =
      adjoin k (Set.range (![Q.source, Q.target] : Fin 2 → Ω)) := by
    change adjoin k {Q.source, Q.target} = _
    rw [show Set.range (![Q.source, Q.target] : Fin 2 → Ω) =
      {Q.target, Q.source} by
        simp [Matrix.range_cons, Matrix.range_empty]]
    exact congrArg (adjoin k) (Set.pair_comm _ _)
  let eTotal : (↥P.branchField) ≃ₐ[k] (↥Q.branchField) :=
    (IntermediateField.equivOfEq pBranchRange).trans
      ((locusFunctionFieldEquivOfIdealEq h).trans
        (IntermediateField.equivOfEq qBranchRange.symm))
  change eTotal ⟨P.target, subset_adjoin k _ (by simp)⟩ =
    ⟨Q.target, subset_adjoin k _ (by simp)⟩
  apply Subtype.ext
  have hpTotal :
      IntermediateField.equivOfEq pBranchRange
          ⟨P.target, subset_adjoin k _ (by simp)⟩ =
        ⟨(![P.source, P.target] : Fin 2 → Ω) 1,
          subset_adjoin k _ (Set.mem_range_self 1)⟩ := by
    apply Subtype.ext
    rfl
  have htotal := congrArg Subtype.val
    (locusFunctionFieldEquivOfIdealEq_apply h 1)
  dsimp only [eTotal]
  simp only [AlgEquiv.trans_apply]
  rw [hpTotal]
  simpa only [coe_equivOfEq, Matrix.cons_val_one,
    Matrix.cons_val_zero] using htotal

/-- Equal selected curve ideals identify the canonical normal extensions
semilinearly over the induced source-coordinate equivalence. -/
noncomputable def normalExtensionEquivOfIdealEq
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    FiniteCover.NormalExtensionEquiv P.sourceField_le_branchField
      Q.sourceField_le_branchField :=
  (P.extensionEquivOfIdealEq Q h).normalLift

/-- Equal selected curve ideals identify the concrete normal closures in
the common algebraically closed ambient field. -/
noncomputable def normalCoverEquivOfIdealEq [IsAlgClosed Ω]
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    (↥(FiniteCover.normalClosureOver P.sourceField_le_branchField)) ≃+*
      (↥(FiniteCover.normalClosureOver
        Q.sourceField_le_branchField)) := by
  letI : FiniteDimensional (↥P.sourceField)
      (↥(extendScalars P.sourceField_le_branchField)) :=
    P.branchOverSource_finiteDimensional
  letI : FiniteDimensional (↥Q.sourceField)
      (↥(extendScalars Q.sourceField_le_branchField)) :=
    Q.branchOverSource_finiteDimensional
  let cP := FiniteCover.normalClosureOverEquivCanonical
    P.sourceField_le_branchField
    (Algebra.IsAlgebraic.of_finite _ _)
  let cQ := FiniteCover.normalClosureOverEquivCanonical
    Q.sourceField_le_branchField
    (Algebra.IsAlgebraic.of_finite _ _)
  exact cP.toRingEquiv |>.trans
    ((P.normalExtensionEquivOfIdealEq Q h).normalEquiv.trans
      cQ.symm.toRingEquiv)

/-- The concrete normal-cover comparison is semilinear over the source
coordinate equivalence induced by the equal curve ideals. -/
@[simp] theorem normalCoverEquivOfIdealEq_algebraMap [IsAlgClosed Ω]
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal)
    (z : P.sourceField) :
    P.normalCoverEquivOfIdealEq Q h
        (algebraMap (↥P.sourceField)
          (↥(FiniteCover.normalClosureOver
            P.sourceField_le_branchField)) z) =
      algebraMap (↥Q.sourceField)
        (↥(FiniteCover.normalClosureOver
          Q.sourceField_le_branchField))
        ((P.extensionEquivOfIdealEq Q h).baseEquiv z) := by
  simp [normalCoverEquivOfIdealEq, normalExtensionEquivOfIdealEq,
    extensionEquivOfIdealEq]

/-- Correct the normal-cover comparison by a target deck transformation
so that equal selected curve ideals identify their literal selected
branches, not merely their abstract normal fields. -/
noncomputable def basedBranchEquivOfIdealEq [IsAlgClosed Ω]
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    FiniteCoverBasedBranchEquiv P.sourceField_le_branchField
      Q.sourceField_le_branchField := by
  apply finiteCoverBasedBranchEquivOfExtensionEquiv
    P.sourceField_le_branchField
    Q.sourceField_le_branchField
    Q.branchOverSource_finiteDimensional
    (P.extensionEquivOfIdealEq Q h)
    (P.normalCoverEquivOfIdealEq Q h)
  apply RingHom.ext
  intro z
  exact P.normalCoverEquivOfIdealEq_algebraMap Q h z

/-- The based comparison of equal selected curve ideals preserves the
literal selected branch. -/
@[simp] theorem basedBranchEquivOfIdealEq_selected [IsAlgClosed Ω]
    (Q : FiniteCorrespondencePair k Ω) (h : P.ideal = Q.ideal) :
    (P.basedBranchEquivOfIdealEq Q h).branchEquiv
        (finiteCoverSelectedBranch P.sourceField_le_branchField) =
      finiteCoverSelectedBranch Q.sourceField_le_branchField :=
  (P.basedBranchEquivOfIdealEq Q h).map_selected

end FiniteCorrespondencePair

namespace FiniteCorrespondenceFamilyMember

variable {d : ℕ}
  (F : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)

/-- Adjoining an auxiliary tuple jointly independent from a generic
family parameter/source prefix turns the selected member into a finite
correspondence over the enlarged coefficient field. -/
def pairOverIndependentExtension {n : ℕ} (r : Fin n → Ω)
    (hprx : AlgebraicIndependent k
      (Sum.elim r F.parameterSource : Fin n ⊕ Fin (d + 1) → Ω)) :
    FiniteCorrespondencePair
      (↥(adjoin k (Set.range F.parameter ∪ Set.range r))) Ω where
  source := F.source
  target := F.target
  source_generic := by
    exact source_notMem_racl_independentExtension hprx
  target_mem_source := by
    rw [mem_racl_adjoin_base_iff, Set.union_singleton]
    refine racl_mono ?_ F.target_mem_parameter_source
    intro z hz
    rw [Set.mem_insert_iff] at hz
    rcases hz with rfl | ⟨i, rfl⟩
    · simp
    · simp
  source_mem_target := by
    rw [mem_racl_adjoin_base_iff, Set.union_singleton]
    refine racl_mono ?_ F.source_mem_parameter_target
    intro z hz
    rw [Set.mem_insert_iff] at hz
    rcases hz with rfl | ⟨i, rfl⟩
    · simp
    · simp

/-- The function field generated by the independent parameter/source
prefix of a generic family member. -/
def parameterSourceField : IntermediateField k Ω :=
  adjoin k (Set.range F.parameterSource)

/-- The function field generated by the complete family tuple. -/
def familyField : IntermediateField k Ω :=
  adjoin k (Set.range F.tuple)

/-- The parameter/source field embeds in the complete family field. -/
theorem parameterSourceField_le_familyField :
    F.parameterSourceField ≤ F.familyField := by
  apply adjoin.mono
  rintro _ ⟨i, rfl⟩
  exact ⟨i.castSucc, by simp [tuple]⟩

/-- The complete family field regarded as an extension of the independent
parameter/source field. -/
def familyOverParameterSource :
    IntermediateField (↥F.parameterSourceField) Ω :=
  extendScalars F.parameterSourceField_le_familyField

/-- Over the parameter/source field, the complete family field is generated
by the selected target coordinate. -/
theorem familyOverParameterSource_eq_adjoin_target :
    F.familyOverParameterSource =
      adjoin (↥F.parameterSourceField) {F.target} := by
  refine restrictScalars_injective k ?_
  unfold familyOverParameterSource parameterSourceField familyField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  simp only [tuple, Fin.range_snoc, Set.union_singleton]

/-- A generic family member determines a finite extension of its
parameter/source function field. -/
theorem familyOverParameterSource_finiteDimensional :
    FiniteDimensional (↥F.parameterSourceField)
      (↥F.familyOverParameterSource) := by
  rw [F.familyOverParameterSource_eq_adjoin_target]
  exact finiteDimensional_adjoin fun z hz ↦ by
    rw [Set.mem_singleton_iff] at hz
    subst z
    exact ((mem_racl_iff k).1 F.target_mem_parameterSource).isIntegral

/-- Equality of complete family loci restricts to equality of their
parameter/source loci. -/
theorem parameterSource_ideal_eq_of_ideal_eq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    idealOf k F.parameterSource = idealOf k G.parameterSource := by
  change idealOf k F.tuple = idealOf k G.tuple at h
  have hprefix := idealOf_comp_eq_of_idealOf_eq h
    (Fin.castSucc : Fin (d + 1) → Fin (d + 2))
  simpa [tuple] using hprefix

/-- Equality of complete family loci restricts to equality of their
parameter loci. -/
theorem parameter_ideal_eq_of_ideal_eq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    idealOf k F.parameter = idealOf k G.parameter := by
  change idealOf k F.tuple = idealOf k G.tuple at h
  have hprefix := idealOf_comp_eq_of_idealOf_eq h
    (fun i : Fin d => i.castSucc.castSucc)
  have hF : F.tuple ∘ (fun i : Fin d => i.castSucc.castSucc) =
      F.parameter := by
    funext i
    simp [tuple, parameterSource]
  have hG : G.tuple ∘ (fun i : Fin d => i.castSucc.castSucc) =
      G.parameter := by
    funext i
    simp [tuple, parameterSource]
  simpa only [hF, hG] using hprefix

/-- Equal complete family loci canonically identify their parameter
function fields. -/
noncomputable def parameterEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (↥F.parameterField) ≃ₐ[k] (↥G.parameterField) :=
  locusFunctionFieldEquivOfIdealEq
    (F.parameter_ideal_eq_of_ideal_eq G h)

/-- The parameter-field comparison sends each displayed parameter to its
counterpart. -/
@[simp] theorem parameterEquivOfIdealEq_apply
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (i : Fin d) :
    F.parameterEquivOfIdealEq G h
        ⟨F.parameter i,
          subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨G.parameter i,
        subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply
    (F.parameter_ideal_eq_of_ideal_eq G h) i

/-- Equal complete family loci canonically identify the finite extensions
from their parameter/source fields to their full family fields.  Both
equivalences send every displayed coordinate to its matching coordinate. -/
def extensionEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCover.ExtensionEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField where
  baseEquiv := locusFunctionFieldEquivOfIdealEq
    (F.parameterSource_ideal_eq_of_ideal_eq G h)
  totalEquiv := locusFunctionFieldEquivOfIdealEq h
  commutes := by
    apply adjoin_algHom_ext k
    rintro _ ⟨i, rfl⟩
    change locusFunctionFieldEquivOfIdealEq h
          ⟨F.parameterSource i, _⟩ =
      IntermediateField.inclusion G.parameterSourceField_le_familyField
        (locusFunctionFieldEquivOfIdealEq
          (F.parameterSource_ideal_eq_of_ideal_eq G h)
          ⟨F.parameterSource i, _⟩)
    rw [locusFunctionFieldEquivOfIdealEq_apply
      (F.parameterSource_ideal_eq_of_ideal_eq G h) i]
    apply Subtype.ext
    have ht := congrArg Subtype.val
      (locusFunctionFieldEquivOfIdealEq_apply h i.castSucc)
    simpa [tuple] using ht

/-- On the parameter/source field, the extension comparison sends every
displayed prefix coordinate to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_base_apply
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (i : Fin (d + 1)) :
    (F.extensionEquivOfIdealEq G h).baseEquiv
        ⟨F.parameterSource i,
          subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨G.parameterSource i,
        subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply
    (F.parameterSource_ideal_eq_of_ideal_eq G h) i

/-- On the full family field, the extension comparison sends every
displayed family coordinate to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_total_apply
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (i : Fin (d + 2)) :
    (F.extensionEquivOfIdealEq G h).totalEquiv
        ⟨F.tuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨G.tuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply h i

/-- The family parameter/source field is literally the restriction to the
ground field of the source field of the associated correspondence pair. -/
theorem parameterSourceField_eq_toPair_sourceField :
    F.parameterSourceField = F.toPair.sourceField.restrictScalars k := by
  unfold parameterSourceField parameterSource
    FiniteCorrespondencePair.sourceField parameterField
  rw [adjoin_adjoin_left]
  simp only [Fin.range_snoc, Set.union_singleton]
  rfl

/-- The complete family field is the ground-field restriction of the full
branch field of the associated correspondence pair. -/
theorem familyField_eq_toPair_branchField :
    F.familyField = F.toPair.branchField.restrictScalars k := by
  unfold familyField tuple parameterSource
    FiniteCorrespondencePair.branchField parameterField
  rw [adjoin_adjoin_left]
  simp only [Fin.range_snoc]
  congr 1
  ext z
  change z ∈ insert F.target (insert F.source (Set.range F.parameter)) ↔
    z ∈ Set.range F.parameter ∪ {F.source, F.target}
  simp
  tauto

/-- Identify the family parameter/source subtype with the source-field
subtype used by its associated correspondence pair. -/
noncomputable def parameterSourceFieldEquivPairSource :
    (↥F.parameterSourceField) ≃+* (↥F.toPair.sourceField) :=
  (IntermediateField.equivOfEq
    F.parameterSourceField_eq_toPair_sourceField).toRingEquiv

/-- Identify the complete family-field subtype with the selected branch
viewed as an extension of its source field. -/
noncomputable def familyFieldEquivPairBranch :
    (↥F.familyField) ≃+* (↥F.toPair.branchOverSource) :=
  (IntermediateField.equivOfEq
    F.familyField_eq_toPair_branchField).toRingEquiv

/-- The family/branch identification does not change ambient values. -/
@[simp] theorem familyFieldEquivPairBranch_val (z : F.familyField) :
    ((F.familyFieldEquivPairBranch z : F.toPair.branchOverSource) : Ω) = z :=
  rfl

/-- The inverse family/branch identification also preserves ambient values. -/
@[simp] theorem familyFieldEquivPairBranch_symm_val
    (z : F.toPair.branchOverSource) :
    ((F.familyFieldEquivPairBranch.symm z : F.familyField) : Ω) = z :=
  rfl

/-- The family parameter field is contained in its parameter/source
field. -/
theorem parameterField_le_parameterSourceField :
    F.parameterField ≤ F.parameterSourceField := by
  apply adjoin.mono
  rintro _ ⟨i, rfl⟩
  exact ⟨i.castSucc, by simp [parameterSource]⟩

/-- The base equivalence attached to equality of complete family loci
restricts to the canonical equivalence of their parameter fields. -/
theorem extensionEquivOfIdealEq_base_parameter
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterField) :
    (F.extensionEquivOfIdealEq G h).baseEquiv
        (IntermediateField.inclusion
          F.parameterField_le_parameterSourceField z) =
      IntermediateField.inclusion G.parameterField_le_parameterSourceField
        (F.parameterEquivOfIdealEq G h z) := by
  let f : F.parameterField →ₐ[k] G.parameterSourceField :=
    (F.extensionEquivOfIdealEq G h).baseEquiv.toAlgHom.comp
      (IntermediateField.inclusion
        F.parameterField_le_parameterSourceField)
  let g : F.parameterField →ₐ[k] G.parameterSourceField :=
    (IntermediateField.inclusion
      G.parameterField_le_parameterSourceField).comp
        (F.parameterEquivOfIdealEq G h).toAlgHom
  change f z = g z
  apply adjoin_induction (F := k) (s := Set.range F.parameter)
      (p := fun x hx ↦ f ⟨x, hx⟩ = g ⟨x, hx⟩)
  · rintro _ ⟨i, rfl⟩
    unfold f g
    simp only [AlgHom.comp_apply]
    have hin : IntermediateField.inclusion
          F.parameterField_le_parameterSourceField
          ⟨F.parameter i, subset_adjoin k _ (Set.mem_range_self i)⟩ =
        ⟨F.parameterSource i.castSucc,
          subset_adjoin k _ (Set.mem_range_self i.castSucc)⟩ := by
      apply Subtype.ext
      simp [parameterSource]
    have hout : IntermediateField.inclusion
          G.parameterField_le_parameterSourceField
          (F.parameterEquivOfIdealEq G h
            ⟨F.parameter i, subset_adjoin k _ (Set.mem_range_self i)⟩) =
        ⟨G.parameterSource i.castSucc,
          subset_adjoin k _ (Set.mem_range_self i.castSucc)⟩ := by
      apply Subtype.ext
      change ↑(F.parameterEquivOfIdealEq G h
        ⟨F.parameter i, subset_adjoin k _ (Set.mem_range_self i)⟩) =
          G.parameterSource i.castSucc
      rw [F.parameterEquivOfIdealEq_apply G h i]
      simp [parameterSource]
    rw [hin]
    exact (F.extensionEquivOfIdealEq_base_apply G h i.castSucc).trans
      hout.symm
  · intro x
    exact (f.commutes x).trans (g.commutes x).symm
  · intro x y hx hy hfx hfy
    change f (⟨x, hx⟩ + ⟨y, hy⟩) = g (⟨x, hx⟩ + ⟨y, hy⟩)
    rw [map_add, map_add, hfx, hfy]
  · intro x hx hfx
    change f (⟨x, hx⟩⁻¹) = g (⟨x, hx⟩⁻¹)
    rw [map_inv₀, map_inv₀, hfx]
  · intro x y hx hy hfx hfy
    change f (⟨x, hx⟩ * ⟨y, hy⟩) = g (⟨x, hx⟩ * ⟨y, hy⟩)
    rw [map_mul, map_mul, hfx, hfy]

/-- Equality of complete family loci identifies the actual complete branch
fields used by their associated finite correspondences.  This is the
branch-level form of the family extension equivalence. -/
noncomputable def completeBranchRingEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (↥F.toPair.branchOverSource) ≃+* (↥G.toPair.branchOverSource) :=
  F.familyFieldEquivPairBranch.symm.trans
    ((F.extensionEquivOfIdealEq G h).totalEquiv.toRingEquiv.trans
      G.familyFieldEquivPairBranch)

/-- On the displayed parameter field, the complete-branch equivalence is
the canonical parameter transport induced by equality of family loci. -/
theorem completeBranchRingEquivOfIdealEq_algebraMap
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterField) :
    F.completeBranchRingEquivOfIdealEq G h
        (algebraMap (↥F.parameterField) (↥F.toPair.branchOverSource) z) =
      algebraMap (↥G.parameterField) (↥G.toPair.branchOverSource)
        (F.parameterEquivOfIdealEq G h z) := by
  have hb := F.extensionEquivOfIdealEq_base_parameter G h z
  have ht := (F.extensionEquivOfIdealEq G h).commutes_apply
    (IntermediateField.inclusion
      F.parameterField_le_parameterSourceField z)
  have htotal := ht.trans (congrArg
    (IntermediateField.inclusion G.parameterSourceField_le_familyField) hb)
  have hin : F.familyFieldEquivPairBranch.symm
        (algebraMap (↥F.parameterField) (↥F.toPair.branchOverSource) z) =
      IntermediateField.inclusion F.parameterSourceField_le_familyField
        (IntermediateField.inclusion
          F.parameterField_le_parameterSourceField z) := by
    apply Subtype.ext
    rfl
  have hout : G.familyFieldEquivPairBranch
        (IntermediateField.inclusion G.parameterSourceField_le_familyField
          (IntermediateField.inclusion
            G.parameterField_le_parameterSourceField
            (F.parameterEquivOfIdealEq G h z))) =
      algebraMap (↥G.parameterField) (↥G.toPair.branchOverSource)
        (F.parameterEquivOfIdealEq G h z) := by
    apply Subtype.ext
    rfl
  unfold completeBranchRingEquivOfIdealEq
  simp only [RingEquiv.trans_apply]
  rw [hin]
  change (F.extensionEquivOfIdealEq G h).totalEquiv.toRingEquiv
      (IntermediateField.inclusion F.parameterSourceField_le_familyField
        (IntermediateField.inclusion
          F.parameterField_le_parameterSourceField z)) = _ at htotal
  rw [htotal]
  exact hout

/-- The canonical normal covers of equal complete family loci are
semilinearly equivalent over the induced parameter/source-field
equivalence. -/
noncomputable def normalExtensionEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCover.NormalExtensionEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField :=
  (F.extensionEquivOfIdealEq G h).normalLift

/-- The normal-cover comparison induced by equal family loci is semilinear
over the canonical parameter/source comparison. -/
theorem normalExtensionEquivOfIdealEq_commutes
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterSourceField) :
    (F.normalExtensionEquivOfIdealEq G h).normalEquiv
        (algebraMap (↥F.parameterSourceField)
          (↥(FiniteCover.canonicalNormalClosure
            F.parameterSourceField_le_familyField)) z) =
      algebraMap (↥G.parameterSourceField)
        (↥(FiniteCover.canonicalNormalClosure
          G.parameterSourceField_le_familyField))
        ((F.extensionEquivOfIdealEq G h).baseEquiv z) :=
  (F.normalExtensionEquivOfIdealEq G h).normal_commutes_apply z

/-- Equal family loci identify the concrete normal closures inside the
common algebraically closed ambient field. -/
noncomputable def normalCoverEquivOfIdealEq [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (↥(FiniteCover.normalClosureOver
      F.parameterSourceField_le_familyField)) ≃+*
      (↥(FiniteCover.normalClosureOver
        G.parameterSourceField_le_familyField)) := by
  letI : FiniteDimensional (↥F.parameterSourceField)
      (↥(extendScalars F.parameterSourceField_le_familyField)) :=
    F.familyOverParameterSource_finiteDimensional
  letI : FiniteDimensional (↥G.parameterSourceField)
      (↥(extendScalars G.parameterSourceField_le_familyField)) :=
    G.familyOverParameterSource_finiteDimensional
  let cF := FiniteCover.normalClosureOverEquivCanonical
    F.parameterSourceField_le_familyField
    (Algebra.IsAlgebraic.of_finite _ _)
  let cG := FiniteCover.normalClosureOverEquivCanonical
    G.parameterSourceField_le_familyField
    (Algebra.IsAlgebraic.of_finite _ _)
  exact cF.toRingEquiv |>.trans
    ((F.normalExtensionEquivOfIdealEq G h).normalEquiv.trans
      cG.symm.toRingEquiv)

/-- The concrete normal-cover comparison is semilinear over the canonical
parameter/source-field comparison. -/
@[simp] theorem normalCoverEquivOfIdealEq_algebraMap [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterSourceField) :
    F.normalCoverEquivOfIdealEq G h
        (algebraMap (↥F.parameterSourceField)
          (↥(FiniteCover.normalClosureOver
            F.parameterSourceField_le_familyField)) z) =
      algebraMap (↥G.parameterSourceField)
        (↥(FiniteCover.normalClosureOver
          G.parameterSourceField_le_familyField))
        ((F.extensionEquivOfIdealEq G h).baseEquiv z) := by
  simp [normalCoverEquivOfIdealEq, normalExtensionEquivOfIdealEq,
    extensionEquivOfIdealEq]

/-- Correct the raw normal-cover comparison by a target deck
transformation so that it preserves the literal selected family branch,
while retaining equivariance for the deck actions. -/
noncomputable def basedBranchEquivOfIdealEq [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCoverBasedBranchEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField := by
  apply finiteCoverBasedBranchEquivOfExtensionEquiv
    F.parameterSourceField_le_familyField
    G.parameterSourceField_le_familyField
    G.familyOverParameterSource_finiteDimensional
    (F.extensionEquivOfIdealEq G h)
    (F.normalCoverEquivOfIdealEq G h)
  apply RingHom.ext
  intro z
  exact F.normalCoverEquivOfIdealEq_algebraMap G h z

/-- The based comparison really sends the literal selected source branch
to the literal selected target branch. -/
@[simp] theorem basedBranchEquivOfIdealEq_selected [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (F.basedBranchEquivOfIdealEq G h).branchEquiv
        (finiteCoverSelectedBranch F.parameterSourceField_le_familyField) =
      finiteCoverSelectedBranch G.parameterSourceField_le_familyField :=
  (F.basedBranchEquivOfIdealEq G h).map_selected

end FiniteCorrespondenceFamilyMember

end


end AclGeom
