/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Correspondence.Family
import AclGeom.Correspondence.BranchGroupoid

/-!
# Finite normal covers of generic correspondence-family members

A generic family member is a tuple `(p,x,y)` in which `y` is algebraic
over the independent prefix `(p,x)`.  Hence its complete function field is
a finite extension of the parameter/source field.  Equality of two complete
family loci canonically identifies both levels of this extension and sends
every displayed coordinate to its counterpart.  The extension equivalence
then lifts to a semilinear equivalence of canonical normal covers.

This is the coefficient-aware comparison needed when two independently
relocated branches represent the same parameterized correspondence.  It
remembers the parameter block and the selected branch, unlike an abstract
equivalence of the endpoint rational function fields.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

namespace FiniteCorrespondenceFamilyMember

variable {d : ℕ}
  (F : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)

/-- The function field generated by the independent parameter/source
prefix of a generic family member. -/
def parameterSourceField : IntermediateField k Ω :=
  adjoin k (Set.range F.parameterSource)

/-- The function field generated by the complete family tuple. -/
def familyField : IntermediateField k Ω :=
  adjoin k (Set.range F.tuple)

/-- The parameter/source field embeds in the complete family field. -/
theorem parameterSourceField_le_familyField :
    F.parameterSourceField ≤ F.familyField := by
  apply adjoin.mono
  rintro _ ⟨i, rfl⟩
  exact ⟨i.castSucc, by simp [tuple]⟩

/-- The complete family field regarded as an extension of the independent
parameter/source field. -/
def familyOverParameterSource :
    IntermediateField (↥F.parameterSourceField) Ω :=
  extendScalars F.parameterSourceField_le_familyField

/-- Over the parameter/source field, the complete family field is generated
by the selected target coordinate. -/
theorem familyOverParameterSource_eq_adjoin_target :
    F.familyOverParameterSource =
      adjoin (↥F.parameterSourceField) {F.target} := by
  refine restrictScalars_injective k ?_
  unfold familyOverParameterSource parameterSourceField familyField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  simp only [tuple, Fin.range_snoc, Set.union_singleton]

/-- A generic family member determines a finite extension of its
parameter/source function field. -/
theorem familyOverParameterSource_finiteDimensional :
    FiniteDimensional (↥F.parameterSourceField)
      (↥F.familyOverParameterSource) := by
  rw [F.familyOverParameterSource_eq_adjoin_target]
  exact finiteDimensional_adjoin fun z hz ↦ by
    rw [Set.mem_singleton_iff] at hz
    subst z
    exact ((mem_racl_iff k).1 F.target_mem_parameterSource).isIntegral

/-- Equality of complete family loci restricts to equality of their
parameter/source loci. -/
theorem parameterSource_ideal_eq_of_ideal_eq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    idealOf k F.parameterSource = idealOf k G.parameterSource := by
  change idealOf k F.tuple = idealOf k G.tuple at h
  have hprefix := idealOf_comp_eq_of_idealOf_eq h
    (Fin.castSucc : Fin (d + 1) → Fin (d + 2))
  simpa [tuple] using hprefix

/-- Equal complete family loci canonically identify the finite extensions
from their parameter/source fields to their full family fields.  Both
equivalences send every displayed coordinate to its matching coordinate. -/
def extensionEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCover.ExtensionEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField where
  baseEquiv := locusFunctionFieldEquivOfIdealEq
    (F.parameterSource_ideal_eq_of_ideal_eq G h)
  totalEquiv := locusFunctionFieldEquivOfIdealEq h
  commutes := by
    apply adjoin_algHom_ext k
    rintro _ ⟨i, rfl⟩
    change locusFunctionFieldEquivOfIdealEq h
          ⟨F.parameterSource i, _⟩ =
      IntermediateField.inclusion G.parameterSourceField_le_familyField
        (locusFunctionFieldEquivOfIdealEq
          (F.parameterSource_ideal_eq_of_ideal_eq G h)
          ⟨F.parameterSource i, _⟩)
    rw [locusFunctionFieldEquivOfIdealEq_apply
      (F.parameterSource_ideal_eq_of_ideal_eq G h) i]
    apply Subtype.ext
    have ht := congrArg Subtype.val
      (locusFunctionFieldEquivOfIdealEq_apply h i.castSucc)
    simpa [tuple] using ht

/-- On the parameter/source field, the extension comparison sends every
displayed prefix coordinate to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_base_apply
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (i : Fin (d + 1)) :
    (F.extensionEquivOfIdealEq G h).baseEquiv
        ⟨F.parameterSource i,
          subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨G.parameterSource i,
        subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply
    (F.parameterSource_ideal_eq_of_ideal_eq G h) i

/-- On the full family field, the extension comparison sends every
displayed family coordinate to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_total_apply
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (i : Fin (d + 2)) :
    (F.extensionEquivOfIdealEq G h).totalEquiv
        ⟨F.tuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨G.tuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply h i

/-- The canonical normal covers of equal complete family loci are
semilinearly equivalent over the induced parameter/source-field
equivalence. -/
noncomputable def normalExtensionEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCover.NormalExtensionEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField :=
  (F.extensionEquivOfIdealEq G h).normalLift

/-- The normal-cover comparison induced by equal family loci is semilinear
over the canonical parameter/source comparison. -/
theorem normalExtensionEquivOfIdealEq_commutes
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterSourceField) :
    (F.normalExtensionEquivOfIdealEq G h).normalEquiv
        (algebraMap (↥F.parameterSourceField)
          (↥(FiniteCover.canonicalNormalClosure
            F.parameterSourceField_le_familyField)) z) =
      algebraMap (↥G.parameterSourceField)
        (↥(FiniteCover.canonicalNormalClosure
          G.parameterSourceField_le_familyField))
        ((F.extensionEquivOfIdealEq G h).baseEquiv z) :=
  (F.normalExtensionEquivOfIdealEq G h).normal_commutes_apply z

/-- Equal family loci identify the concrete normal closures inside the
common algebraically closed ambient field. -/
noncomputable def normalCoverEquivOfIdealEq [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (↥(FiniteCover.normalClosureOver
      F.parameterSourceField_le_familyField)) ≃+*
      (↥(FiniteCover.normalClosureOver
        G.parameterSourceField_le_familyField)) := by
  letI : FiniteDimensional (↥F.parameterSourceField)
      (↥(extendScalars F.parameterSourceField_le_familyField)) :=
    F.familyOverParameterSource_finiteDimensional
  letI : FiniteDimensional (↥G.parameterSourceField)
      (↥(extendScalars G.parameterSourceField_le_familyField)) :=
    G.familyOverParameterSource_finiteDimensional
  let cF := FiniteCover.normalClosureOverEquivCanonical
    F.parameterSourceField_le_familyField
    (Algebra.IsAlgebraic.of_finite _ _)
  let cG := FiniteCover.normalClosureOverEquivCanonical
    G.parameterSourceField_le_familyField
    (Algebra.IsAlgebraic.of_finite _ _)
  exact cF.toRingEquiv |>.trans
    ((F.normalExtensionEquivOfIdealEq G h).normalEquiv.trans
      cG.symm.toRingEquiv)

/-- The concrete normal-cover comparison is semilinear over the canonical
parameter/source-field comparison. -/
@[simp] theorem normalCoverEquivOfIdealEq_algebraMap [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterSourceField) :
    F.normalCoverEquivOfIdealEq G h
        (algebraMap (↥F.parameterSourceField)
          (↥(FiniteCover.normalClosureOver
            F.parameterSourceField_le_familyField)) z) =
      algebraMap (↥G.parameterSourceField)
        (↥(FiniteCover.normalClosureOver
          G.parameterSourceField_le_familyField))
        ((F.extensionEquivOfIdealEq G h).baseEquiv z) := by
  simp [normalCoverEquivOfIdealEq, normalExtensionEquivOfIdealEq,
    extensionEquivOfIdealEq]

/-- Correct the raw normal-cover comparison by a target deck
transformation so that it preserves the literal selected family branch,
while retaining equivariance for the deck actions. -/
noncomputable def basedBranchEquivOfIdealEq [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCoverBasedBranchEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField := by
  apply finiteCoverBasedBranchEquivOfExtensionEquiv
    F.parameterSourceField_le_familyField
    G.parameterSourceField_le_familyField
    G.familyOverParameterSource_finiteDimensional
    (F.extensionEquivOfIdealEq G h)
    (F.normalCoverEquivOfIdealEq G h)
  apply RingHom.ext
  intro z
  exact F.normalCoverEquivOfIdealEq_algebraMap G h z

/-- The based comparison really sends the literal selected source branch
to the literal selected target branch. -/
@[simp] theorem basedBranchEquivOfIdealEq_selected [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (F.basedBranchEquivOfIdealEq G h).branchEquiv
        (finiteCoverSelectedBranch F.parameterSourceField_le_familyField) =
      finiteCoverSelectedBranch G.parameterSourceField_le_familyField :=
  (F.basedBranchEquivOfIdealEq G h).map_selected

end FiniteCorrespondenceFamilyMember

end


end AclGeom
