/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Correspondence.Family
import AclGeom.Correspondence.BranchGroupoid
import Mathlib.RingTheory.AlgebraicIndependent.AlgebraicClosure

/-!
# Finite normal covers of generic correspondence-family members

A generic family member is a tuple `(p,x,y)` in which `y` is algebraic
over the independent prefix `(p,x)`.  Hence its complete function field is
a finite extension of the parameter/source field.  Equality of two complete
family loci canonically identifies both levels of this extension and sends
every displayed coordinate to its counterpart.  The extension equivalence
then lifts to a semilinear equivalence of canonical normal covers.

This is the coefficient-aware comparison needed when two independently
relocated branches represent the same parameterized correspondence.  It
remembers the parameter block and the selected branch, unlike an abstract
equivalence of the endpoint rational function fields.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- Equality of two complete family loci with the same literal parameter
tuple descends to equality of the endpoint-pair ideals over the field
generated by that parameter.  The complete-locus equivalence fixes the
parameter field generator by generator and carries the displayed source
and target coordinates, so it transports every polynomial relation over
that field in both directions. -/
theorem pairIdeal_eq_over_commonParameter_of_familyIdeal_eq
    {d : ℕ} {p : Fin d → Ω} {x y x' y' : Ω}
    (h : idealOf k (Fin.snoc (Fin.snoc p x) y) =
      idealOf k (Fin.snoc (Fin.snoc p x') y')) :
    idealOf (↥(adjoin k (Set.range p))) ![x, y] =
      idealOf (↥(adjoin k (Set.range p))) ![x', y'] := by
  classical
  let E : IntermediateField k Ω := adjoin k (Set.range p)
  change idealOf (↥E) ![x, y] = idealOf (↥E) ![x', y']
  let t : Fin (d + 2) → Ω := Fin.snoc (Fin.snoc p x) y
  let t' : Fin (d + 2) → Ω := Fin.snoc (Fin.snoc p x') y'
  let L : IntermediateField k Ω := adjoin k (Set.range t)
  let L' : IntermediateField k Ω := adjoin k (Set.range t')
  have hEL : E ≤ L := by
    apply adjoin.mono
    rintro _ ⟨i, rfl⟩
    exact ⟨i.castSucc.castSucc, by simp [t]⟩
  have hEL' : E ≤ L' := by
    apply adjoin.mono
    rintro _ ⟨i, rfl⟩
    exact ⟨i.castSucc.castSucc, by simp [t']⟩
  letI : Algebra E L := (IntermediateField.inclusion hEL).toAlgebra
  letI : Algebra E L' := (IntermediateField.inclusion hEL').toAlgebra
  let e₀ : L ≃ₐ[k] L' := locusFunctionFieldEquivOfIdealEq h
  have he₀ : e₀.toAlgHom.comp (IntermediateField.inclusion hEL) =
      IntermediateField.inclusion hEL' := by
    apply adjoin_algHom_ext k
    rintro _ ⟨i, rfl⟩
    change e₀ ⟨p i, _⟩ = ⟨p i, _⟩
    simpa [e₀, t, t'] using
      (locusFunctionFieldEquivOfIdealEq_apply h i.castSucc.castSucc)
  let e : L ≃ₐ[E] L' :=
    { e₀.toRingEquiv with
      commutes' := fun z ↦ DFunLike.congr_fun he₀ z }
  let q : Fin 2 → L :=
    ![⟨x, subset_adjoin k _ ⟨(Fin.last d).castSucc, by simp [t]⟩⟩,
      ⟨y, subset_adjoin k _ ⟨Fin.last (d + 1), by simp [t]⟩⟩]
  let q' : Fin 2 → L' :=
    ![⟨x', subset_adjoin k _ ⟨(Fin.last d).castSucc, by simp [t']⟩⟩,
      ⟨y', subset_adjoin k _ ⟨Fin.last (d + 1), by simp [t']⟩⟩]
  have heq (i : Fin 2) : e (q i) = q' i := by
    fin_cases i
    · simpa [e, e₀, q, q', t, t'] using
        (locusFunctionFieldEquivOfIdealEq_apply h (Fin.last d).castSucc)
    · simpa [e, e₀, q, q', t, t'] using
        (locusFunctionFieldEquivOfIdealEq_apply h (Fin.last (d + 1)))
  let vL : L →ₐ[E] Ω :=
    { L.val.toRingHom with commutes' := fun _ ↦ rfl }
  let vL' : L' →ₐ[E] Ω :=
    { L'.val.toRingHom with commutes' := fun _ ↦ rfl }
  ext f
  rw [mem_idealOf_iff, mem_idealOf_iff]
  have hval : MvPolynomial.aeval ![x, y] f =
      L.val (MvPolynomial.aeval q f) := by
    have hqval : (fun i ↦ vL (q i)) = (![x, y] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x, y] f =
          MvPolynomial.aeval (fun i ↦ vL (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vL (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) vL f).symm
      _ = L.val (MvPolynomial.aeval q f) := rfl
  have hval' : MvPolynomial.aeval ![x', y'] f =
      L'.val (MvPolynomial.aeval q' f) := by
    have hqval : (fun i ↦ vL' (q' i)) = (![x', y'] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x', y'] f =
          MvPolynomial.aeval (fun i ↦ vL' (q' i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vL' (MvPolynomial.aeval q' f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q') vL' f).symm
      _ = L'.val (MvPolynomial.aeval q' f) := rfl
  have heval : MvPolynomial.aeval q' f =
      e (MvPolynomial.aeval q f) := by
    have hqeval : (fun i ↦ e.toAlgHom (q i)) = q' := by
      funext i
      exact heq i
    calc
      MvPolynomial.aeval q' f =
          MvPolynomial.aeval (fun i ↦ e.toAlgHom (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqeval.symm
      _ = e (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) e.toAlgHom f).symm
  rw [hval, hval', heval]
  constructor
  · intro hz
    have hzero : MvPolynomial.aeval q f = 0 := by
      exact L.val.injective hz
    rw [hzero, map_zero]
    rfl
  · intro hz
    have hzero : e (MvPolynomial.aeval q f) = 0 := by
      apply L'.val.injective
      simpa using hz
    have := e.injective (hzero.trans (map_zero e).symm)
    simpa using congrArg L.val this

/-- If an auxiliary tuple is jointly independent from a parameter/source
prefix, it remains independent after adjoining a target algebraic over that
prefix.  The conclusion is stated over the endpoint-pair field above the
parameter field, exactly as required by independent scalar extension. -/
theorem auxiliary_independent_over_parameterPairField
    {d n : ℕ} {p : Fin d → Ω} {r : Fin n → Ω} {x y : Ω}
    (hprx : AlgebraicIndependent k
      (Sum.elim r (Fin.snoc p x) : Fin n ⊕ Fin (d + 1) → Ω))
    (hy : y ∈ racl k (insert x (Set.range p))) :
    AlgebraicIndependent
      (↥(adjoin (↥(adjoin k (Set.range p)))
        (Set.range (![x, y] : Fin 2 → Ω)))) r := by
  classical
  let base : Fin (d + 1) → Ω := Fin.snoc p x
  let B : IntermediateField k Ω := adjoin k (Set.range base)
  let E : IntermediateField k Ω := adjoin k (Set.range p)
  let L : IntermediateField (↥E) Ω :=
    adjoin (↥E) (Set.range (![x, y] : Fin 2 → Ω))
  have hrB : AlgebraicIndependent (↥B) r := by
    change AlgebraicIndependent
      (↥(adjoin k (Set.range (Fin.snoc p x)))) r
    rw [IntermediateField.algebraicIndependent_adjoin_iff]
    exact (AlgebraicIndependent.sumElim_iff.1 hprx).2
  have hEB : E ≤ B := by
    apply adjoin.mono
    rintro _ ⟨i, rfl⟩
    exact ⟨i.castSucc, by simp [base]⟩
  have hBL : B ≤ L.restrictScalars k := by
    apply adjoin_le_iff.2
    rintro _ ⟨i, rfl⟩
    refine Fin.lastCases ?_ (fun j ↦ ?_) i
    · simpa [L, base] using
        (subset_adjoin (↥E)
          (Set.range (![x, y] : Fin 2 → Ω))
          (Set.mem_range_self (0 : Fin 2)))
    · simpa [L, base] using
        (IntermediateField.algebraMap_mem L
          ⟨p j, subset_adjoin k _ (Set.mem_range_self j)⟩)
  letI : Algebra B L := (IntermediateField.inclusion hBL).toAlgebra
  haveI : IsScalarTower B L Ω := IsScalarTower.of_algebraMap_eq' rfl
  have hLB : Algebra.IsAlgebraic (↥B) (↥L) := by
    constructor
    rintro ⟨z, hz⟩
    rw [← isAlgebraic_algHom_iff
      (IsScalarTower.toAlgHom (↥B) (↥L) Ω) Subtype.val_injective]
    change IsAlgebraic (↥B) z
    apply adjoin_induction (F := ↥E) (s := Set.range (![x, y] : Fin 2 → Ω))
        (p := fun z _ ↦ IsAlgebraic (↥B) z)
    · rintro _ ⟨i, rfl⟩
      fin_cases i
      · exact isAlgebraic_algebraMap (R := ↥B) (A := Ω)
          ⟨x, subset_adjoin k _ ⟨Fin.last d, by simp [base]⟩⟩
      · have hy' : IsAlgebraic (↥B) y := by
          change IsAlgebraic
            (↥(adjoin k (Set.range (Fin.snoc p x)))) y
          rw [Fin.range_snoc]
          exact (mem_racl_iff k).1 hy
        exact hy'
    · intro z
      exact isAlgebraic_algebraMap (R := ↥B) (A := Ω)
        ⟨z, hEB z.2⟩
    · exact fun _ _ _ _ hx hy ↦ hx.add hy
    · exact fun _ _ hx ↦ hx.inv
    · exact fun _ _ _ _ hx hy ↦ hx.mul hy
    · exact hz
  exact hrB.extendScalars L

set_option maxHeartbeats 800000 in
-- The nested coefficient-field transports elaborate above the default budget.
/-- Equality of endpoint-pair ideals survives adjoining a matching tuple
that is algebraically independent over both complete endpoint fields.  The
extended function-field equivalence fixes the enlarged coefficient field
and still carries both displayed endpoints. -/
theorem pairIdeal_eq_over_independentExtension_of_pairIdeal_eq
    {E : IntermediateField k Ω} {ι : Type*} {r : ι → Ω}
    {x y x' y' : Ω}
    (h : idealOf (↥E) ![x, y] = idealOf (↥E) ![x', y'])
    (hr : AlgebraicIndependent
      (↥(adjoin (↥E) (Set.range (![x, y] : Fin 2 → Ω)))) r)
    (hr' : AlgebraicIndependent
      (↥(adjoin (↥E) (Set.range (![x', y'] : Fin 2 → Ω)))) r) :
    idealOf
        (↥((adjoin (↥E) (Set.range r)).restrictScalars k)) ![x, y] =
      idealOf
        (↥((adjoin (↥E) (Set.range r)).restrictScalars k)) ![x', y'] := by
  classical
  let L : IntermediateField (↥E) Ω :=
    adjoin (↥E) (Set.range (![x, y] : Fin 2 → Ω))
  let L' : IntermediateField (↥E) Ω :=
    adjoin (↥E) (Set.range (![x', y'] : Fin 2 → Ω))
  let C : IntermediateField (↥E) Ω := adjoin (↥E) (Set.range r)
  let Ck : IntermediateField k Ω := C.restrictScalars k
  let M : IntermediateField (↥L) Ω := adjoin (↥L) (Set.range r)
  let M' : IntermediateField (↥L') Ω := adjoin (↥L') (Set.range r)
  let e₀ : L ≃ₐ[E] L' := locusFunctionFieldEquivOfIdealEq h
  let ex : M ≃ₐ[E] M' :=
    adjoinIndependentEquivOfEquiv e₀ hr hr'
  have hCM : C ≤ M.restrictScalars (↥E) := by
    apply adjoin_le_iff.2
    rintro _ ⟨i, rfl⟩
    exact subset_adjoin (↥L) _ (Set.mem_range_self i)
  have hCM' : C ≤ M'.restrictScalars (↥E) := by
    apply adjoin_le_iff.2
    rintro _ ⟨i, rfl⟩
    exact subset_adjoin (↥L') _ (Set.mem_range_self i)
  let iCkM : Ck →+* M :=
    { toFun := fun z ↦ ⟨z, hCM z.2⟩
      map_one' := rfl
      map_mul' := fun _ _ ↦ rfl
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  let iCkM' : Ck →+* M' :=
    { toFun := fun z ↦ ⟨z, hCM' z.2⟩
      map_one' := rfl
      map_mul' := fun _ _ ↦ rfl
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  letI : Algebra Ck M := iCkM.toAlgebra
  letI : Algebra Ck M' := iCkM'.toAlgebra
  have hexC : ex.toAlgHom.comp (IntermediateField.inclusion hCM) =
      IntermediateField.inclusion hCM' := by
    apply adjoin_algHom_ext (↥E)
    rintro _ ⟨i, rfl⟩
    change ex ⟨r i, _⟩ = ⟨r i, _⟩
    simpa [ex, M, M'] using
      (adjoinIndependentEquivOfEquiv_generator e₀ hr hr' i)
  let e : M ≃ₐ[Ck] M' :=
    { ex.toRingEquiv with
      commutes' := fun z ↦ by
        change ex ⟨z, hCM z.2⟩ = ⟨z, hCM' z.2⟩
        exact DFunLike.congr_fun hexC (⟨z, z.2⟩ : C) }
  let q : Fin 2 → M :=
    ![algebraMap L M
        ⟨x, subset_adjoin (↥E) _ (Set.mem_range_self 0)⟩,
      algebraMap L M
        ⟨y, subset_adjoin (↥E) _ (Set.mem_range_self 1)⟩]
  let q' : Fin 2 → M' :=
    ![algebraMap L' M'
        ⟨x', subset_adjoin (↥E) _ (Set.mem_range_self 0)⟩,
      algebraMap L' M'
        ⟨y', subset_adjoin (↥E) _ (Set.mem_range_self 1)⟩]
  have heq (i : Fin 2) : e (q i) = q' i := by
    fin_cases i
    · change ex (algebraMap L M ⟨x, _⟩) = algebraMap L' M' ⟨x', _⟩
      rw [adjoinIndependentEquivOfEquiv_algebraMap]
      exact congrArg (algebraMap L' M')
        (locusFunctionFieldEquivOfIdealEq_apply h 0)
    · change ex (algebraMap L M ⟨y, _⟩) = algebraMap L' M' ⟨y', _⟩
      rw [adjoinIndependentEquivOfEquiv_algebraMap]
      exact congrArg (algebraMap L' M')
        (locusFunctionFieldEquivOfIdealEq_apply h 1)
  let vM : M →ₐ[Ck] Ω :=
    { M.val.toRingHom with commutes' := fun _ ↦ rfl }
  let vM' : M' →ₐ[Ck] Ω :=
    { M'.val.toRingHom with commutes' := fun _ ↦ rfl }
  change idealOf (↥Ck) ![x, y] = idealOf (↥Ck) ![x', y']
  ext f
  rw [mem_idealOf_iff, mem_idealOf_iff]
  have hval : MvPolynomial.aeval ![x, y] f =
      M.val (MvPolynomial.aeval q f) := by
    have hqval : (fun i ↦ vM (q i)) = (![x, y] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x, y] f =
          MvPolynomial.aeval (fun i ↦ vM (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vM (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) vM f).symm
      _ = M.val (MvPolynomial.aeval q f) := rfl
  have hval' : MvPolynomial.aeval ![x', y'] f =
      M'.val (MvPolynomial.aeval q' f) := by
    have hqval : (fun i ↦ vM' (q' i)) = (![x', y'] : Fin 2 → Ω) := by
      funext i
      fin_cases i <;> rfl
    calc
      MvPolynomial.aeval ![x', y'] f =
          MvPolynomial.aeval (fun i ↦ vM' (q' i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqval.symm
      _ = vM' (MvPolynomial.aeval q' f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q') vM' f).symm
      _ = M'.val (MvPolynomial.aeval q' f) := rfl
  have heval : MvPolynomial.aeval q' f =
      e (MvPolynomial.aeval q f) := by
    have hqeval : (fun i ↦ e.toAlgHom (q i)) = q' := by
      funext i
      exact heq i
    calc
      MvPolynomial.aeval q' f =
          MvPolynomial.aeval (fun i ↦ e.toAlgHom (q i)) f := by
        exact congrArg (fun g ↦ MvPolynomial.aeval g f) hqeval.symm
      _ = e (MvPolynomial.aeval q f) := by
        exact (MvPolynomial.comp_aeval_apply (f := q) e.toAlgHom f).symm
  rw [hval, hval', heval]
  constructor
  · intro hz
    have hzero : MvPolynomial.aeval q f = 0 := M.val.injective hz
    rw [hzero, map_zero]
    rfl
  · intro hz
    have hzero : e (MvPolynomial.aeval q f) = 0 := by
      apply M'.val.injective
      simpa using hz
    have := e.injective (hzero.trans (map_zero e).symm)
    simpa using congrArg M.val this

namespace FiniteCorrespondenceFamilyMember

variable {d : ℕ}
  (F : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)

/-- The function field generated by the independent parameter/source
prefix of a generic family member. -/
def parameterSourceField : IntermediateField k Ω :=
  adjoin k (Set.range F.parameterSource)

/-- The function field generated by the complete family tuple. -/
def familyField : IntermediateField k Ω :=
  adjoin k (Set.range F.tuple)

/-- The parameter/source field embeds in the complete family field. -/
theorem parameterSourceField_le_familyField :
    F.parameterSourceField ≤ F.familyField := by
  apply adjoin.mono
  rintro _ ⟨i, rfl⟩
  exact ⟨i.castSucc, by simp [tuple]⟩

/-- The complete family field regarded as an extension of the independent
parameter/source field. -/
def familyOverParameterSource :
    IntermediateField (↥F.parameterSourceField) Ω :=
  extendScalars F.parameterSourceField_le_familyField

/-- Over the parameter/source field, the complete family field is generated
by the selected target coordinate. -/
theorem familyOverParameterSource_eq_adjoin_target :
    F.familyOverParameterSource =
      adjoin (↥F.parameterSourceField) {F.target} := by
  refine restrictScalars_injective k ?_
  unfold familyOverParameterSource parameterSourceField familyField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  simp only [tuple, Fin.range_snoc, Set.union_singleton]

/-- A generic family member determines a finite extension of its
parameter/source function field. -/
theorem familyOverParameterSource_finiteDimensional :
    FiniteDimensional (↥F.parameterSourceField)
      (↥F.familyOverParameterSource) := by
  rw [F.familyOverParameterSource_eq_adjoin_target]
  exact finiteDimensional_adjoin fun z hz ↦ by
    rw [Set.mem_singleton_iff] at hz
    subst z
    exact ((mem_racl_iff k).1 F.target_mem_parameterSource).isIntegral

/-- Equality of complete family loci restricts to equality of their
parameter/source loci. -/
theorem parameterSource_ideal_eq_of_ideal_eq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    idealOf k F.parameterSource = idealOf k G.parameterSource := by
  change idealOf k F.tuple = idealOf k G.tuple at h
  have hprefix := idealOf_comp_eq_of_idealOf_eq h
    (Fin.castSucc : Fin (d + 1) → Fin (d + 2))
  simpa [tuple] using hprefix

/-- Equal complete family loci canonically identify the finite extensions
from their parameter/source fields to their full family fields.  Both
equivalences send every displayed coordinate to its matching coordinate. -/
def extensionEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCover.ExtensionEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField where
  baseEquiv := locusFunctionFieldEquivOfIdealEq
    (F.parameterSource_ideal_eq_of_ideal_eq G h)
  totalEquiv := locusFunctionFieldEquivOfIdealEq h
  commutes := by
    apply adjoin_algHom_ext k
    rintro _ ⟨i, rfl⟩
    change locusFunctionFieldEquivOfIdealEq h
          ⟨F.parameterSource i, _⟩ =
      IntermediateField.inclusion G.parameterSourceField_le_familyField
        (locusFunctionFieldEquivOfIdealEq
          (F.parameterSource_ideal_eq_of_ideal_eq G h)
          ⟨F.parameterSource i, _⟩)
    rw [locusFunctionFieldEquivOfIdealEq_apply
      (F.parameterSource_ideal_eq_of_ideal_eq G h) i]
    apply Subtype.ext
    have ht := congrArg Subtype.val
      (locusFunctionFieldEquivOfIdealEq_apply h i.castSucc)
    simpa [tuple] using ht

/-- On the parameter/source field, the extension comparison sends every
displayed prefix coordinate to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_base_apply
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (i : Fin (d + 1)) :
    (F.extensionEquivOfIdealEq G h).baseEquiv
        ⟨F.parameterSource i,
          subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨G.parameterSource i,
        subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply
    (F.parameterSource_ideal_eq_of_ideal_eq G h) i

/-- On the full family field, the extension comparison sends every
displayed family coordinate to its counterpart. -/
@[simp] theorem extensionEquivOfIdealEq_total_apply
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (i : Fin (d + 2)) :
    (F.extensionEquivOfIdealEq G h).totalEquiv
        ⟨F.tuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ =
      ⟨G.tuple i, subset_adjoin k _ (Set.mem_range_self i)⟩ :=
  locusFunctionFieldEquivOfIdealEq_apply h i

/-- The canonical normal covers of equal complete family loci are
semilinearly equivalent over the induced parameter/source-field
equivalence. -/
noncomputable def normalExtensionEquivOfIdealEq
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCover.NormalExtensionEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField :=
  (F.extensionEquivOfIdealEq G h).normalLift

/-- The normal-cover comparison induced by equal family loci is semilinear
over the canonical parameter/source comparison. -/
theorem normalExtensionEquivOfIdealEq_commutes
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterSourceField) :
    (F.normalExtensionEquivOfIdealEq G h).normalEquiv
        (algebraMap (↥F.parameterSourceField)
          (↥(FiniteCover.canonicalNormalClosure
            F.parameterSourceField_le_familyField)) z) =
      algebraMap (↥G.parameterSourceField)
        (↥(FiniteCover.canonicalNormalClosure
          G.parameterSourceField_le_familyField))
        ((F.extensionEquivOfIdealEq G h).baseEquiv z) :=
  (F.normalExtensionEquivOfIdealEq G h).normal_commutes_apply z

/-- Equal family loci identify the concrete normal closures inside the
common algebraically closed ambient field. -/
noncomputable def normalCoverEquivOfIdealEq [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (↥(FiniteCover.normalClosureOver
      F.parameterSourceField_le_familyField)) ≃+*
      (↥(FiniteCover.normalClosureOver
        G.parameterSourceField_le_familyField)) := by
  letI : FiniteDimensional (↥F.parameterSourceField)
      (↥(extendScalars F.parameterSourceField_le_familyField)) :=
    F.familyOverParameterSource_finiteDimensional
  letI : FiniteDimensional (↥G.parameterSourceField)
      (↥(extendScalars G.parameterSourceField_le_familyField)) :=
    G.familyOverParameterSource_finiteDimensional
  let cF := FiniteCover.normalClosureOverEquivCanonical
    F.parameterSourceField_le_familyField
    (Algebra.IsAlgebraic.of_finite _ _)
  let cG := FiniteCover.normalClosureOverEquivCanonical
    G.parameterSourceField_le_familyField
    (Algebra.IsAlgebraic.of_finite _ _)
  exact cF.toRingEquiv |>.trans
    ((F.normalExtensionEquivOfIdealEq G h).normalEquiv.trans
      cG.symm.toRingEquiv)

/-- The concrete normal-cover comparison is semilinear over the canonical
parameter/source-field comparison. -/
@[simp] theorem normalCoverEquivOfIdealEq_algebraMap [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) (z : F.parameterSourceField) :
    F.normalCoverEquivOfIdealEq G h
        (algebraMap (↥F.parameterSourceField)
          (↥(FiniteCover.normalClosureOver
            F.parameterSourceField_le_familyField)) z) =
      algebraMap (↥G.parameterSourceField)
        (↥(FiniteCover.normalClosureOver
          G.parameterSourceField_le_familyField))
        ((F.extensionEquivOfIdealEq G h).baseEquiv z) := by
  simp [normalCoverEquivOfIdealEq, normalExtensionEquivOfIdealEq,
    extensionEquivOfIdealEq]

/-- Correct the raw normal-cover comparison by a target deck
transformation so that it preserves the literal selected family branch,
while retaining equivariance for the deck actions. -/
noncomputable def basedBranchEquivOfIdealEq [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    FiniteCoverBasedBranchEquiv
      F.parameterSourceField_le_familyField
      G.parameterSourceField_le_familyField := by
  apply finiteCoverBasedBranchEquivOfExtensionEquiv
    F.parameterSourceField_le_familyField
    G.parameterSourceField_le_familyField
    G.familyOverParameterSource_finiteDimensional
    (F.extensionEquivOfIdealEq G h)
    (F.normalCoverEquivOfIdealEq G h)
  apply RingHom.ext
  intro z
  exact F.normalCoverEquivOfIdealEq_algebraMap G h z

/-- The based comparison really sends the literal selected source branch
to the literal selected target branch. -/
@[simp] theorem basedBranchEquivOfIdealEq_selected [IsAlgClosed Ω]
    (G : FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) d)
    (h : F.ideal = G.ideal) :
    (F.basedBranchEquivOfIdealEq G h).branchEquiv
        (finiteCoverSelectedBranch F.parameterSourceField_le_familyField) =
      finiteCoverSelectedBranch G.parameterSourceField_le_familyField :=
  (F.basedBranchEquivOfIdealEq G h).map_selected

end FiniteCorrespondenceFamilyMember

end


end AclGeom
