/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Correspondence.Family
import AclGeom.Correspondence.FiniteCover

/-!
# Finite normalization of recoverable correspondence families

A one-parameter family member `(p,x,y)` is generically finite over its
endpoint pair when the parameter `p` is algebraic over `k(x,y)`.  This is
the precise field-theoretic content of saying that the family parameter is
recoverable up to finitely many choices from its generic graph.

`RecoverableFiniteCorrespondenceFamilyMember` adds this condition to the
varying-family interface.  Its full family field `k(p,x,y)` is then proved
finite over the endpoint field `k(x,y)`, and the selected extension is
placed in a finite normal closure.  The construction retains all conjugate
parameter branches; it does not identify a parameter with an automorphism
without the later selected-action argument.
-/

namespace AclGeom

open IntermediateField
open scoped IntermediateField.algebraAdjoinAdjoin

noncomputable section

variable {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

/-- A one-parameter finite-correspondence family whose parameter is
recoverable, up to algebraic ambiguity, from the two endpoints of its
generic member. -/
structure RecoverableFiniteCorrespondenceFamilyMember extends
    FiniteCorrespondenceFamilyMember (k := k) (Ω := Ω) 1 where
  /-- The family parameter is algebraic over the endpoint pair. -/
  parameter_mem_endpoints :
    parameter 0 ∈ racl k ({source, target} : Set Ω)

namespace RecoverableFiniteCorrespondenceFamilyMember

variable (F : RecoverableFiniteCorrespondenceFamilyMember (k := k) (Ω := Ω))

/-- The generic endpoint pair `(source,target)`. -/
def endpointTuple : Fin 2 → Ω := ![F.source, F.target]

/-- The field generated by the generic endpoint pair. -/
def endpointField : IntermediateField k Ω :=
  adjoin k (Set.range F.endpointTuple)

/-- The field generated by the parameter and both endpoints. -/
def familyField : IntermediateField k Ω :=
  adjoin k (Set.range F.toFiniteCorrespondenceFamilyMember.tuple)

/-- The endpoint field embeds in the full family field. -/
theorem endpointField_le_familyField : F.endpointField ≤ F.familyField := by
  apply adjoin.mono
  rintro _ ⟨i, rfl⟩
  fin_cases i
  · exact ⟨1, rfl⟩
  · exact ⟨2, rfl⟩

/-- The full family field, regarded as an extension of the endpoint field. -/
def familyOverEndpoints : IntermediateField (↥F.endpointField) Ω :=
  extendScalars F.endpointField_le_familyField

/-- Every coordinate of the full family tuple is algebraic over the
endpoint field. -/
theorem tuple_isAlgebraic_endpointField (i : Fin 3) :
    IsAlgebraic (↥F.endpointField)
      (F.toFiniteCorrespondenceFamilyMember.tuple i) := by
  rw [endpointField]
  apply (mem_racl_iff k).1
  fin_cases i
  · simpa [endpointTuple, FiniteCorrespondenceFamilyMember.tuple,
      FiniteCorrespondenceFamilyMember.parameterSource, Matrix.range_cons,
      Matrix.range_empty, Set.pair_comm] using F.parameter_mem_endpoints
  · exact subset_racl k _ ⟨0, rfl⟩
  · exact subset_racl k _ ⟨1, rfl⟩

/-- **Finite parameter recovery.**  The field generated by a recoverable
family member is finite-dimensional over the field generated by its
endpoint graph. -/
theorem familyOverEndpoints_finiteDimensional :
    FiniteDimensional (↥F.endpointField) (↥F.familyOverEndpoints) := by
  have key : F.familyOverEndpoints =
      adjoin (↥F.endpointField)
        (Set.range F.toFiniteCorrespondenceFamilyMember.tuple) := by
    refine restrictScalars_injective k ?_
    unfold familyOverEndpoints endpointField familyField
    rw [adjoin_adjoin_left, extendScalars_restrictScalars, adjoin_union]
    exact (sup_eq_right.2 F.endpointField_le_familyField).symm
  rw [key]
  letI : Fintype
      (Set.range F.toFiniteCorrespondenceFamilyMember.tuple) :=
    Set.Finite.fintype
      (Set.finite_range F.toFiniteCorrespondenceFamilyMember.tuple)
  exact finiteDimensional_adjoin fun _ hx ↦ by
    obtain ⟨i, rfl⟩ := hx
    exact (F.tuple_isAlgebraic_endpointField i).isIntegral

/-- The chosen normal closure of the recoverable family field over its
endpoint field. -/
def normalFamilyOverEndpoints : IntermediateField (↥F.endpointField) Ω :=
  FiniteCover.normalClosureOver F.endpointField_le_familyField

/-- The selected family extension embeds in its normal closure. -/
theorem familyOverEndpoints_le_normal :
    F.familyOverEndpoints ≤ F.normalFamilyOverEndpoints :=
  FiniteCover.extendScalars_le_normalClosureOver
    F.endpointField_le_familyField

/-- Normalization preserves finiteness over the endpoint field. -/
theorem normalFamilyOverEndpoints_finiteDimensional :
    FiniteDimensional (↥F.endpointField)
      (↥F.normalFamilyOverEndpoints) :=
  FiniteCover.normalClosureOver_finiteDimensional
    F.endpointField_le_familyField
    F.familyOverEndpoints_finiteDimensional

/-- Over an algebraically closed ambient field, the chosen finite cover is
normal over the endpoint field. -/
theorem normalFamilyOverEndpoints_normal [IsAlgClosed Ω] :
    Normal (↥F.endpointField) (↥F.normalFamilyOverEndpoints) := by
  letI := F.familyOverEndpoints_finiteDimensional
  exact FiniteCover.normalClosureOver_normal
    F.endpointField_le_familyField
    (Algebra.IsAlgebraic.of_finite
      (↥F.endpointField) (↥F.familyOverEndpoints))

end RecoverableFiniteCorrespondenceFamilyMember

end

end AclGeom
