/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex, Claude
-/
import AclGeom.Correspondence.CurveIdeal

/-!
# Uniformly bounded curve loci on a fixed equation

A nonzero planar equation `F` has at most `totalDegree F` vanishing ideals of pairs with a
transcendental first coordinate and a second coordinate algebraic over the first.  The prime
equation of each such pair divides `F`, so its ideal is generated by a prime factor of `F`.  Each
prime factor is nonconstant and total degree is additive, so there are at most `totalDegree F`
factors counted with multiplicity.

* `exists_curve_ideal_colors`: all these ideals lie in one finite set of at most
  `totalDegree F` ideals.
* `finite_curve_ideals_of_relation`: in particular, there are finitely many of them.

The named consumer is the finite-component selection in the multiplier-curve argument of the
corrected blueprint Lemma `affine-grid-extraction` (#27, L2).  The bound depends only on `F`, so
the number of relocations can be fixed from it before the coefficient field that colors them is
chosen.  No geometric primality after extending the coefficient field, stabilizer, action,
linearity or guarded completeness is assumed or proved.

**Status:** uniform curve-locus bound proved (#27, L2b).
Larger-base genericity, component/stabilizer linearity and guarded completeness remain open.
-/

namespace AclGeom

noncomputable section

open MvPolynomial

variable (k K : Type*) [Field k] [Field K] [Algebra k K]

/-- A nonzero planar polynomial has at most `totalDegree` prime factors, counted with
multiplicity: each factor is nonconstant and total degree is additive. -/
private theorem card_factors_le_totalDegree {F : MvPolynomial (Fin 2) k} (hF : F ≠ 0) :
    Multiset.card (UniqueFactorizationMonoid.factors F) ≤ F.totalDegree := by
  -- Every factor is irreducible, hence nonzero and nonconstant.
  have hfac : ∀ q ∈ UniqueFactorizationMonoid.factors F, q ≠ 0 ∧ 1 ≤ q.totalDegree := by
    intro q hq
    have hirr : Irreducible q := UniqueFactorizationMonoid.irreducible_of_factor q hq
    refine ⟨hirr.ne_zero, Nat.one_le_iff_ne_zero.2 fun h0 ↦ ?_⟩
    have hC : q = C (q.coeff 0) := totalDegree_eq_zero_iff_eq_C.1 h0
    have hc : q.coeff 0 ≠ 0 := fun hc0 ↦ hirr.ne_zero (by rw [hC, hc0, map_zero])
    exact hirr.not_isUnit (by rw [hC]; exact (isUnit_iff_ne_zero.2 hc).map C)
  -- Total degree is additive along a product of nonzero polynomials.
  have key : ∀ s : Multiset (MvPolynomial (Fin 2) k),
      (∀ q ∈ s, q ≠ 0 ∧ 1 ≤ q.totalDegree) →
        Multiset.card s ≤ s.prod.totalDegree ∧ s.prod ≠ 0 := by
    intro s
    induction s using Multiset.induction_on with
    | empty => exact fun _ ↦ ⟨by simp, by simp⟩
    | cons a s ih =>
      intro h
      obtain ⟨ha0, ha1⟩ := h a (Multiset.mem_cons_self a s)
      obtain ⟨hcard, hprod⟩ := ih fun q hq ↦ h q (Multiset.mem_cons_of_mem hq)
      rw [Multiset.card_cons, Multiset.prod_cons, totalDegree_mul_of_isDomain ha0 hprod]
      exact ⟨by omega, mul_ne_zero ha0 hprod⟩
  exact (key _ hfac).1.trans
    (totalDegree_le_of_dvd_of_isDomain (UniqueFactorizationMonoid.factors_prod hF).dvd hF)

/-- **Uniformly bounded curve colors.** The vanishing ideals of pairs with a transcendental first
coordinate and a second coordinate algebraic over the first, on which a fixed nonzero planar
equation `F` vanishes, all lie in one set of at most `totalDegree F` ideals. -/
theorem exists_curve_ideal_colors (F : MvPolynomial (Fin 2) k) (hF : F ≠ 0) :
    ∃ S : Finset (Ideal (MvPolynomial (Fin 2) k)), S.card ≤ F.totalDegree ∧
      ∀ u v : K, Transcendental k u → v ∈ racl k {u} → aeval ![u, v] F = 0 →
        idealOf k ![u, v] ∈ S := by
  classical
  refine ⟨(UniqueFactorizationMonoid.factors F).toFinset.image
      (fun q ↦ Ideal.span ({q} : Set (MvPolynomial (Fin 2) k))),
    (Finset.card_image_le.trans (Multiset.toFinset_card_le _)).trans
      (card_factors_le_totalDegree k hF), ?_⟩
  intro u v hu hv hz
  obtain ⟨G, hG, hI⟩ := exists_prime_span_idealOf k hu hv
  have hmem : F ∈ Ideal.span {G} := by
    rw [← hI]
    exact (mem_idealOf_iff k).2 hz
  obtain ⟨q, hq, hGq⟩ := UniqueFactorizationMonoid.exists_mem_factors_of_dvd hF hG.irreducible
    (Ideal.mem_span_singleton.1 hmem)
  exact Finset.mem_image.2 ⟨q, by simpa using hq,
    (hI.trans (Ideal.span_singleton_eq_span_singleton.2 hGq)).symm⟩

/-- A fixed nonzero planar equation has only finitely many curve ideals of pairs with a
transcendental first coordinate and a second coordinate algebraic over the first. -/
theorem finite_curve_ideals_of_relation (F : MvPolynomial (Fin 2) k) (hF : F ≠ 0) :
    Set.Finite {I : Ideal (MvPolynomial (Fin 2) k) |
      ∃ u v : K, Transcendental k u ∧ v ∈ racl k {u} ∧
        aeval ![u, v] F = 0 ∧ idealOf k ![u, v] = I} := by
  obtain ⟨S, -, hS⟩ := exists_curve_ideal_colors k K F hF
  refine S.finite_toSet.subset ?_
  rintro I ⟨u, v, hu, hv, hz, rfl⟩
  exact hS u v hu hv hz

end

end AclGeom
