/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz
-/
import AclGeom.Correspondence.Composition

/-!
# Finite covers carried by selected correspondence branches

A selected finite-correspondence pair `(x,y)` determines three concrete
subfields of the ambient algebraically closed field: `k(x)`, `k(y)`, and
`k(x,y)`.  Interalgebraicity says exactly that the joint branch field is a
finite extension of either endpoint field.  This is the field-theoretic
finite cover needed before passing to normal closures and gluing the
selected correspondence groupoid.

This module is part of the finite-cover integration in blueprint §8.1.
-/

namespace AclGeom

open IntermediateField

noncomputable section

variable {k : Type*} {Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

namespace FiniteCorrespondencePair

variable (P : FiniteCorrespondencePair k Ω)

/-- The one-variable function field generated by the source coordinate. -/
def sourceField : IntermediateField k Ω :=
  adjoin k {P.source}

/-- The one-variable function field generated by the target coordinate. -/
def targetField : IntermediateField k Ω :=
  adjoin k {P.target}

/-- The joint function field of the selected correspondence branch. -/
def branchField : IntermediateField k Ω :=
  adjoin k {P.source, P.target}

/-- The source function field embeds in the selected branch field. -/
theorem sourceField_le_branchField : P.sourceField ≤ P.branchField :=
  adjoin.mono k _ _ (by simp)

/-- The target function field embeds in the selected branch field. -/
theorem targetField_le_branchField : P.targetField ≤ P.branchField :=
  adjoin.mono k _ _ (by simp)

/-- The selected branch field regarded as a cover of its source field. -/
def branchOverSource : IntermediateField (↥P.sourceField) Ω :=
  extendScalars P.sourceField_le_branchField

/-- The selected branch field regarded as a cover of its target field. -/
def branchOverTarget : IntermediateField (↥P.targetField) Ω :=
  extendScalars P.targetField_le_branchField

/-- Over the source field, the branch field is generated by the target. -/
theorem branchOverSource_eq_adjoin_target :
    P.branchOverSource = adjoin (↥P.sourceField) {P.target} := by
  refine restrictScalars_injective k ?_
  unfold branchOverSource sourceField branchField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  simp only [Set.union_singleton, Set.pair_comm]

/-- Over the target field, the branch field is generated by the source. -/
theorem branchOverTarget_eq_adjoin_source :
    P.branchOverTarget = adjoin (↥P.targetField) {P.source} := by
  refine restrictScalars_injective k ?_
  unfold branchOverTarget targetField branchField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  simp only [Set.union_singleton]

/-- The selected branch is a finite cover of its source function field. -/
theorem branchOverSource_finiteDimensional :
    FiniteDimensional (↥P.sourceField) (↥P.branchOverSource) := by
  rw [P.branchOverSource_eq_adjoin_target]
  exact finiteDimensional_adjoin fun x hx ↦ by
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact ((mem_racl_iff k).1 P.target_mem_source).isIntegral

/-- The selected branch is a finite cover of its target function field. -/
theorem branchOverTarget_finiteDimensional :
    FiniteDimensional (↥P.targetField) (↥P.branchOverTarget) := by
  rw [P.branchOverTarget_eq_adjoin_source]
  exact finiteDimensional_adjoin fun x hx ↦ by
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact ((mem_racl_iff k).1 P.source_mem_target).isIntegral

/-- The joint field of two consecutive selected branches. -/
def chainField (Q : FiniteCorrespondencePair k Ω) :
    IntermediateField k Ω :=
  adjoin k {P.source, P.target, Q.target}

/-- The left branch field embeds in the joint chain field. -/
theorem branchField_le_chainField (Q : FiniteCorrespondencePair k Ω) :
    P.branchField ≤ P.chainField Q := by
  unfold branchField chainField
  apply adjoin.mono
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx ⊢
  rcases hx with rfl | rfl
  · exact Or.inl rfl
  · exact Or.inr (Or.inl rfl)

/-- When the middle coordinates agree, the right branch field embeds in
the joint chain field. -/
theorem rightBranchField_le_chainField
    (Q : FiniteCorrespondencePair k Ω) (h : P.target = Q.source) :
    Q.branchField ≤ P.chainField Q :=
  adjoin.mono k _ _ (by simp [← h])

/-- The endpoint branch selected by composition embeds in the joint chain
field. -/
theorem compositeBranchField_le_chainField
    (Q : FiniteCorrespondencePair k Ω) (h : P.target = Q.source) :
    (P.comp Q h).branchField ≤ P.chainField Q := by
  unfold branchField chainField
  apply adjoin.mono
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx ⊢
  rcases hx with rfl | rfl
  · exact Or.inl rfl
  · exact Or.inr (Or.inr rfl)

/-- The chain field as an extension of the left branch field. -/
def chainOverLeft (Q : FiniteCorrespondencePair k Ω) :
    IntermediateField (↥P.branchField) Ω :=
  extendScalars (P.branchField_le_chainField Q)

/-- The chain field as an extension of the right branch field. -/
def chainOverRight (Q : FiniteCorrespondencePair k Ω)
    (h : P.target = Q.source) : IntermediateField (↥Q.branchField) Ω :=
  extendScalars (P.rightBranchField_le_chainField Q h)

/-- The chain field as an extension of the composite endpoint branch. -/
def chainOverComposite (Q : FiniteCorrespondencePair k Ω)
    (h : P.target = Q.source) :
    IntermediateField (↥(P.comp Q h).branchField) Ω :=
  extendScalars (P.compositeBranchField_le_chainField Q h)

/-- Over the left branch, the chain field is generated by the final
coordinate. -/
theorem chainOverLeft_eq_adjoin_target
    (Q : FiniteCorrespondencePair k Ω) :
    P.chainOverLeft Q = adjoin (↥P.branchField) {Q.target} := by
  refine restrictScalars_injective k ?_
  unfold chainOverLeft branchField chainField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  congr 1
  ext x
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff, Set.mem_union]
  tauto

/-- Over the right branch, the chain field is generated by the initial
coordinate. -/
theorem chainOverRight_eq_adjoin_source
    (Q : FiniteCorrespondencePair k Ω) (h : P.target = Q.source) :
    P.chainOverRight Q h = adjoin (↥Q.branchField) {P.source} := by
  refine restrictScalars_injective k ?_
  unfold chainOverRight branchField chainField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  congr 1
  ext x
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff, Set.mem_union]
  rw [← h]
  tauto

/-- Over the composite endpoint branch, the chain field is generated by
the shared middle coordinate. -/
theorem chainOverComposite_eq_adjoin_middle
    (Q : FiniteCorrespondencePair k Ω) (h : P.target = Q.source) :
    P.chainOverComposite Q h =
      adjoin (↥(P.comp Q h).branchField) {P.target} := by
  refine restrictScalars_injective k ?_
  unfold chainOverComposite branchField chainField
  rw [adjoin_adjoin_left, extendScalars_restrictScalars]
  congr 1
  ext x
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff, Set.mem_union]
  tauto

/-- The joint chain field is finite over the left selected branch. -/
theorem chainOverLeft_finiteDimensional
    (Q : FiniteCorrespondencePair k Ω) (h : P.target = Q.source) :
    FiniteDimensional (↥P.branchField) (↥(P.chainOverLeft Q)) := by
  rw [P.chainOverLeft_eq_adjoin_target Q]
  exact finiteDimensional_adjoin fun x hx ↦ by
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact (isAlgebraic_of_le P.targetField_le_branchField
      (by
        unfold targetField
        rw [h]
        exact (mem_racl_iff k).1 Q.target_mem_source)).isIntegral

/-- The joint chain field is finite over the right selected branch. -/
theorem chainOverRight_finiteDimensional
    (Q : FiniteCorrespondencePair k Ω) (h : P.target = Q.source) :
    FiniteDimensional (↥Q.branchField) (↥(P.chainOverRight Q h)) := by
  rw [P.chainOverRight_eq_adjoin_source Q h]
  exact finiteDimensional_adjoin fun x hx ↦ by
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact (isAlgebraic_of_le Q.sourceField_le_branchField
      (by
        unfold sourceField
        rw [← h]
        exact (mem_racl_iff k).1 P.source_mem_target)).isIntegral

/-- The joint chain field is finite over the selected composite endpoint
branch. -/
theorem chainOverComposite_finiteDimensional
    (Q : FiniteCorrespondencePair k Ω) (h : P.target = Q.source) :
    FiniteDimensional (↥(P.comp Q h).branchField)
      (↥(P.chainOverComposite Q h)) := by
  rw [P.chainOverComposite_eq_adjoin_middle Q h]
  exact finiteDimensional_adjoin fun x hx ↦ by
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact (isAlgebraic_of_le
      (P.comp Q h).sourceField_le_branchField
      ((mem_racl_iff k).1 P.target_mem_source)).isIntegral

end FiniteCorrespondencePair

end

end AclGeom
