/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex
-/
import AclGeom.Correspondence.FiniteExtensionProjection
import AclGeom.Correspondence.FiniteCover
import AclGeom.Correspondence.RankTwoMultiplication

/-!
# Normalization of the rank-two four-arrow component

A four-arrow difference diagram starts with four independent rank-two
parameters, hence eight free coordinates, and selects four further rank-two
blocks by multiplication and division.  This file proves that all sixteen
displayed coordinates are algebraic over the eight input coordinates.  It
then packages the total coordinate field in one finite normal cover and
constructs its integral affine model.

This is a normalization of the full relational component.  It does not
assert that the final block is a single-valued rational function of any
smaller pair of inputs; that assertion requires the subsequent based-chart
cancellation argument.
-/

namespace AclGeom

open IntermediateField
open AlgebraicGeometry

noncomputable section

universe u

variable {k K : Type u} [Field k] [Field K] [Algebra k K]

/-- The sixteen coordinates of a four-arrow diagram: the four input blocks
`s,e,a,b`, followed by the selected blocks `u,sA,uB,c`. -/
def RankTwoFiniteCorrespondenceMultiplication.FourArrowDifferenceDiagram.totalTuple
    {M : RankTwoFiniteCorrespondenceMultiplication (k := k) (Ω := K)}
    {s a b e : Fin 2 → K}
    (D : M.FourArrowDifferenceDiagram s a b e) : Fin 16 → K :=
  ![s 0, s 1, e 0, e 1, a 0, a 1, b 0, b 1,
    D.u 0, D.u 1, D.sA 0, D.sA 1, D.uB 0, D.uB 1, D.c 0, D.c 1]

namespace RankTwoFiniteCorrespondenceMultiplication.FourArrowDifferenceDiagram

variable {M : RankTwoFiniteCorrespondenceMultiplication (k := k) (Ω := K)}
  {s a b e : Fin 2 → K}
  (D : M.FourArrowDifferenceDiagram s a b e)

/-- Each coordinate of the first selected output `u` is algebraic over the
eight input coordinates. -/
theorem u_mem_input_racl (i : Fin 2) :
    D.u i ∈ racl k (Set.range (rankTwoFourTuple s e a b)) := by
  refine racl_mono ?_ (D.se_u.output_mem_left_right i)
  rintro z ⟨j, rfl⟩
  fin_cases j
  · exact ⟨0, rfl⟩
  · exact ⟨1, rfl⟩
  · exact ⟨2, rfl⟩
  · exact ⟨3, rfl⟩

/-- Each coordinate of the selected left quotient `sA` is algebraic over
the eight input coordinates. -/
theorem sA_mem_input_racl (i : Fin 2) :
    D.sA i ∈ racl k (Set.range (rankTwoFourTuple s e a b)) := by
  refine racl_le_of_subset_racl ?_ (D.sA_a_u.left_mem_right_output i)
  rintro z ⟨j, rfl⟩
  fin_cases j
  · exact subset_racl k _ ⟨4, rfl⟩
  · exact subset_racl k _ ⟨5, rfl⟩
  · exact D.u_mem_input_racl 0
  · exact D.u_mem_input_racl 1

/-- Each coordinate of the second selected output `uB` is algebraic over
the eight input coordinates. -/
theorem uB_mem_input_racl (i : Fin 2) :
    D.uB i ∈ racl k (Set.range (rankTwoFourTuple s e a b)) := by
  refine racl_mono ?_ (D.s_b_uB.output_mem_left_right i)
  rintro z ⟨j, rfl⟩
  fin_cases j
  · exact ⟨0, rfl⟩
  · exact ⟨1, rfl⟩
  · exact ⟨6, rfl⟩
  · exact ⟨7, rfl⟩

/-- Each coordinate of the difference output `c` is algebraic over the
eight input coordinates. -/
theorem c_mem_input_racl (i : Fin 2) :
    D.c i ∈ racl k (Set.range (rankTwoFourTuple s e a b)) := by
  refine racl_le_of_subset_racl ?_ (D.sA_c_uB.right_mem_left_output i)
  rintro z ⟨j, rfl⟩
  fin_cases j
  · exact D.sA_mem_input_racl 0
  · exact D.sA_mem_input_racl 1
  · exact D.uB_mem_input_racl 0
  · exact D.uB_mem_input_racl 1

/-- Every displayed coordinate of the four-arrow component is algebraic
over its eight input coordinates. -/
theorem totalTuple_mem_input_racl (i : Fin 16) :
    D.totalTuple i ∈ racl k (Set.range (rankTwoFourTuple s e a b)) := by
  fin_cases i
  · exact subset_racl k _ ⟨0, rfl⟩
  · exact subset_racl k _ ⟨1, rfl⟩
  · exact subset_racl k _ ⟨2, rfl⟩
  · exact subset_racl k _ ⟨3, rfl⟩
  · exact subset_racl k _ ⟨4, rfl⟩
  · exact subset_racl k _ ⟨5, rfl⟩
  · exact subset_racl k _ ⟨6, rfl⟩
  · exact subset_racl k _ ⟨7, rfl⟩
  · exact D.u_mem_input_racl 0
  · exact D.u_mem_input_racl 1
  · exact D.sA_mem_input_racl 0
  · exact D.sA_mem_input_racl 1
  · exact D.uB_mem_input_racl 0
  · exact D.uB_mem_input_racl 1
  · exact D.c_mem_input_racl 0
  · exact D.c_mem_input_racl 1

/-- The function field of the eight free input coordinates. -/
def inputField
    (_D : M.FourArrowDifferenceDiagram s a b e) : IntermediateField k K :=
  adjoin k (Set.range (rankTwoFourTuple s e a b))

/-- The function field generated by all sixteen displayed coordinates. -/
def totalField : IntermediateField k K :=
  adjoin k (Set.range D.totalTuple)

/-- The input field embeds in the total four-arrow field. -/
theorem inputField_le_totalField : D.inputField ≤ D.totalField := by
  apply adjoin.mono
  rintro z ⟨i, rfl⟩
  fin_cases i
  · exact ⟨0, rfl⟩
  · exact ⟨1, rfl⟩
  · exact ⟨2, rfl⟩
  · exact ⟨3, rfl⟩
  · exact ⟨4, rfl⟩
  · exact ⟨5, rfl⟩
  · exact ⟨6, rfl⟩
  · exact ⟨7, rfl⟩

/-- The total four-arrow field as an extension of its eight-coordinate
input field. -/
def totalOverInput : IntermediateField (↥D.inputField) K :=
  extendScalars D.inputField_le_totalField

/-- The full four-arrow component is finite over its eight free input
coordinates. -/
theorem totalOverInput_finiteDimensional :
    FiniteDimensional (↥D.inputField) (↥D.totalOverInput) := by
  have key : D.totalOverInput =
      adjoin (↥D.inputField) (Set.range D.totalTuple) := by
    refine restrictScalars_injective k ?_
    unfold totalOverInput inputField totalField
    rw [adjoin_adjoin_left, extendScalars_restrictScalars, adjoin_union]
    exact (sup_eq_right.2 D.inputField_le_totalField).symm
  rw [key]
  letI : Fintype (Set.range D.totalTuple) :=
    Set.Finite.fintype (Set.finite_range D.totalTuple)
  exact finiteDimensional_adjoin fun x hx ↦ by
    obtain ⟨i, rfl⟩ := hx
    exact ((mem_racl_iff k).1 (D.totalTuple_mem_input_racl i)).isIntegral

/-- One normal closure containing the entire four-arrow component. -/
def normalCover : IntermediateField (↥D.inputField) K :=
  FiniteCover.normalClosureOver D.inputField_le_totalField

/-- The total four-arrow field embeds in its normal closure. -/
theorem totalOverInput_le_normalCover :
    D.totalOverInput ≤ D.normalCover :=
  FiniteCover.extendScalars_le_normalClosureOver D.inputField_le_totalField

/-- The normal four-arrow cover remains finite over the eight input
coordinates. -/
theorem normalCover_finiteDimensional :
    FiniteDimensional (↥D.inputField) (↥D.normalCover) :=
  FiniteCover.normalClosureOver_finiteDimensional
    D.inputField_le_totalField D.totalOverInput_finiteDimensional

/-- In an algebraically closed ambient field, the four-arrow cover is a
normal extension of the eight-coordinate input field. -/
theorem normalCover_normal [IsAlgClosed K] :
    Normal (↥D.inputField) (↥D.normalCover) := by
  letI := D.totalOverInput_finiteDimensional
  exact FiniteCover.normalClosureOver_normal D.inputField_le_totalField
    (Algebra.IsAlgebraic.of_finite (↥D.inputField) (↥D.totalOverInput))

/-- The eight free input coordinates, lifted into their generated field. -/
abbrev inputCoordinates : Fin 8 → D.inputField :=
  FiniteExtensionChart.liftedCoordinates (k := k)
    (rankTwoFourTuple s e a b)

/-- The input coordinates generate the complete eight-coordinate function
field. -/
theorem adjoin_inputCoordinates_eq_top :
    adjoin k (Set.range D.inputCoordinates) = ⊤ :=
  FiniteExtensionChart.adjoin_liftedCoordinates_eq_top
    (k := k) (rankTwoFourTuple s e a b)

/-- The integral affine chart attached to the normalized four-arrow
component over its eight free coordinates. -/
abbrev algebraicChart : Scheme := by
  letI := D.normalCover_finiteDimensional
  exact FiniteExtensionChart.scheme (k := k)
    (K := ↥D.inputField) (L := ↥D.normalCover) D.inputCoordinates

/-- The function field generated by one rank-two block. -/
def blockField (p : Fin 2 → K) : IntermediateField k K :=
  adjoin k (Set.range p)

/-- The two coordinates of a rank-two block, lifted into their generated
field. -/
abbrev blockCoordinates (p : Fin 2 → K) : Fin 2 → blockField (k := k) p :=
  FiniteExtensionChart.liftedCoordinates (k := k) p

/-- The two lifted coordinates generate the rank-two block field. -/
theorem adjoin_blockCoordinates_eq_top (p : Fin 2 → K) :
    adjoin k (Set.range (blockCoordinates (k := k) p)) = ⊤ :=
  FiniteExtensionChart.adjoin_liftedCoordinates_eq_top (k := k) p

/-- The integral affine chart of one displayed rank-two block. -/
abbrev blockAlgebraicChart (p : Fin 2 → K) : Scheme :=
  FiniteExtensionChart.scheme (k := k)
    (K := ↥(blockField (k := k) p))
    (L := ↥(blockField (k := k) p))
    (blockCoordinates (k := k) p)

/-- Any displayed block contained in the total coordinate field embeds in
the common normal four-arrow cover. -/
def blockFieldToNormalCover (p : Fin 2 → K)
    (hp : blockField (k := k) p ≤ D.totalField) :
    (↥(blockField (k := k) p)) →ₐ[k] (↥D.normalCover) := by
  let hle : (blockField (k := k) p).restrictScalars k ≤
      D.normalCover.restrictScalars k := by
    intro x hx
    apply D.totalOverInput_le_normalCover
    exact hp hx
  exact IntermediateField.inclusion hle

/-- A block projection from the normalized four-arrow component.  The
field-containment argument identifies which displayed block is selected. -/
def projectionToBlock (p : Fin 2 → K)
    (hp : blockField (k := k) p ≤ D.totalField) :
    Scheme.RationalMap D.algebraicChart (blockAlgebraicChart (k := k) p) := by
  letI := D.normalCover_finiteDimensional
  exact FiniteExtensionProjection.rationalMap
    D.inputCoordinates (blockCoordinates (k := k) p)
    D.adjoin_inputCoordinates_eq_top (D.blockFieldToNormalCover p hp)

instance projectionToBlock_isDominant (p : Fin 2 → K)
    (hp : blockField (k := k) p ≤ D.totalField) :
    (D.projectionToBlock p hp).IsDominant := by
  letI := D.normalCover_finiteDimensional
  unfold projectionToBlock
  infer_instance

/-- The `e` input block lies in the total four-arrow field. -/
theorem eBlockField_le_totalField :
    blockField (k := k) e ≤ D.totalField := by
  apply adjoin.mono
  rintro z ⟨i, rfl⟩
  fin_cases i
  · exact ⟨2, rfl⟩
  · exact ⟨3, rfl⟩

/-- The `a` input block lies in the total four-arrow field. -/
theorem aBlockField_le_totalField :
    blockField (k := k) a ≤ D.totalField := by
  apply adjoin.mono
  rintro z ⟨i, rfl⟩
  fin_cases i
  · exact ⟨4, rfl⟩
  · exact ⟨5, rfl⟩

/-- The `b` input block lies in the total four-arrow field. -/
theorem bBlockField_le_totalField :
    blockField (k := k) b ≤ D.totalField := by
  apply adjoin.mono
  rintro z ⟨i, rfl⟩
  fin_cases i
  · exact ⟨6, rfl⟩
  · exact ⟨7, rfl⟩

/-- The selected difference-output block lies in the total four-arrow
field. -/
theorem cBlockField_le_totalField :
    blockField (k := k) D.c ≤ D.totalField := by
  apply adjoin.mono
  rintro z ⟨i, rfl⟩
  fin_cases i
  · exact ⟨14, rfl⟩
  · exact ⟨15, rfl⟩

/-- Dominant rational projection to the first based input `e`. -/
abbrev toE : Scheme.RationalMap D.algebraicChart
    (blockAlgebraicChart (k := k) e) :=
  D.projectionToBlock e D.eBlockField_le_totalField

/-- Dominant rational projection to the inverse input `a`. -/
abbrev toA : Scheme.RationalMap D.algebraicChart
    (blockAlgebraicChart (k := k) a) :=
  D.projectionToBlock a D.aBlockField_le_totalField

/-- Dominant rational projection to the second based input `b`. -/
abbrev toB : Scheme.RationalMap D.algebraicChart
    (blockAlgebraicChart (k := k) b) :=
  D.projectionToBlock b D.bBlockField_le_totalField

/-- Dominant rational projection to the selected difference output `c`. -/
abbrev toC : Scheme.RationalMap D.algebraicChart
    (blockAlgebraicChart (k := k) D.c) :=
  D.projectionToBlock D.c D.cBlockField_le_totalField

instance toE_isDominant : D.toE.IsDominant := by infer_instance
instance toA_isDominant : D.toA.IsDominant := by infer_instance
instance toB_isDominant : D.toB.IsDominant := by infer_instance
instance toC_isDominant : D.toC.IsDominant := by infer_instance

end RankTwoFiniteCorrespondenceMultiplication.FourArrowDifferenceDiagram

end

end AclGeom
