/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Closure.Basic
import Mathlib.RingTheory.AlgebraicIndependent.Basic

/-!
# Loci of tuples and generic points

The ideal-theoretic dictionary underlying the hard kernel (blueprint §8):
for a tuple `a` of elements of an extension `Ω/k`,

* `idealOf k a`: the vanishing ideal `I(a/k)` — the kernel of evaluation at
  `a` on the polynomial ring, a prime ideal since evaluation lands in a
  field (blueprint §8, first paragraph);
* `mem_idealOf_iff`: the membership dictionary;
* `idealOf_eq_bot_iff`: `I(a/k) = ⊥` iff `a` is algebraically independent —
  "generic of the affine space";
* equivariance of `idealOf` under `k`-embeddings of the ambient field, the
  seed of blueprint Lemma `generic-extension` (b).

The locus `Loc_k(a)` of the blueprint is this prime ideal; its "dimension"
is `trdeg k k(a)`, and all statements about generic points of loci are
statements about the tuples themselves. Finite correspondences and their
composition build on this in later slices of checklist C2.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.

**Status:** in progress (M3a, checklist C2).
-/

namespace AclGeom

open MvPolynomial

noncomputable section

variable (k : Type*) {Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]

variable {ι : Type*}

/-- The vanishing ideal `I(a/k)` of a tuple (blueprint §8): polynomials over
`k` vanishing at `a`. Prime, because evaluation maps into a field. -/
def idealOf (a : ι → Ω) : Ideal (MvPolynomial ι k) :=
  RingHom.ker (aeval a).toRingHom

theorem mem_idealOf_iff {a : ι → Ω} {f : MvPolynomial ι k} :
    f ∈ idealOf k a ↔ aeval a f = 0 :=
  RingHom.mem_ker

instance idealOf_isPrime (a : ι → Ω) : (idealOf k a).IsPrime :=
  RingHom.ker_isPrime _

/-- The locus of `a` is all of affine space exactly when `a` is
algebraically independent over `k`. -/
theorem idealOf_eq_bot_iff {a : ι → Ω} :
    idealOf k a = ⊥ ↔ AlgebraicIndependent k a := by
  rw [AlgebraicIndependent, idealOf, ← RingHom.injective_iff_ker_eq_bot]
  exact Iff.rfl

/-- Equivariance: a `k`-algebra embedding of ambient fields preserves
vanishing ideals (the seed of blueprint Lemma `generic-extension`). -/
theorem idealOf_comp_algHom {Ω' : Type*} [Field Ω'] [Algebra k Ω']
    (σ : Ω →ₐ[k] Ω') (a : ι → Ω) :
    idealOf k (⇑σ ∘ a) = idealOf k a := by
  ext f
  rw [mem_idealOf_iff, mem_idealOf_iff]
  have hcomp : aeval (⇑σ ∘ a) f = σ (aeval a f) := by
    rw [Function.comp_def, ← comp_aeval_apply]
  rw [hcomp]
  exact ⟨fun h ↦ σ.injective (by rwa [map_zero]), fun h ↦ by rw [h, map_zero]⟩

/-- Repackage a relation-preservation statement (the output form of the
joint relocation) as an equality of vanishing ideals. -/
theorem idealOf_eq_of_aeval_iff {a b : ι → Ω}
    (H : ∀ f : MvPolynomial ι k, aeval a f = 0 ↔ aeval b f = 0) :
    idealOf k a = idealOf k b := by
  ext f
  rw [mem_idealOf_iff, mem_idealOf_iff]
  exact H f

/-- Two tuples with the same vanishing ideal have the same algebraic
relations; in particular the vanishing ideal detects equality of evaluated
polynomials. -/
theorem aeval_eq_aeval_of_idealOf_eq {a b : ι → Ω}
    (h : idealOf k a = idealOf k b) {f g : MvPolynomial ι k}
    (hfg : aeval a f = aeval a g) : aeval b f = aeval b g := by
  have : f - g ∈ idealOf k a := by
    rw [mem_idealOf_iff, map_sub, sub_eq_zero]
    exact hfg
  rw [h, mem_idealOf_iff, map_sub, sub_eq_zero] at this
  exact this

section RaclTransfer

open IntermediateField
open scoped IntermediateField.algebraAdjoinAdjoin

/-- The workhorse of the genericity bookkeeping in the curve-coset chain:
relative algebraic dependence among coordinates transfers between tuples with
equal vanishing ideals. If `a i` is algebraic over the subfield generated by
the `J`-coordinates of `a`, the same holds for `b`. -/
theorem mem_racl_image_of_idealOf_eq {a b : ι → Ω}
    (h : idealOf k a = idealOf k b) {J : Set ι} {i : ι}
    (ha : a i ∈ racl k (a '' J)) : b i ∈ racl k (b '' J) := by
  classical
  rw [mem_racl_iff] at ha ⊢
  -- Pass to the ring version: an annihilator whose coefficients are
  -- polynomial expressions in the `J`-coordinates of `a`.
  obtain ⟨p, hp0, hpz⟩ : IsAlgebraic (Algebra.adjoin k (a '' J)) (a i) :=
    (IsFractionRing.isAlgebraic_iff (Algebra.adjoin k (a '' J))
      (adjoin k (a '' J)) Ω).2 ha
  have hadj : ∀ c : ι → Ω,
      Algebra.adjoin k (c '' J) = (aeval (fun j : J ↦ c j)).range := fun c ↦ by
    rw [Set.image_eq_range, Algebra.adjoin_range_eq_range_aeval]
  have hrepr : ∀ m : ℕ, ∃ g : MvPolynomial J k,
      aeval (fun j : J ↦ a j) g = (p.coeff m : Ω) := fun m ↦
    (AlgHom.mem_range _).1 ((hadj a).le (p.coeff m).2)
  choose q hq using hrepr
  -- Fold the annihilator into a single joint polynomial relation.
  have hren : ∀ (c : ι → Ω) (m : ℕ),
      aeval c (rename (Subtype.val : J → ι) (q m)) =
        aeval (fun j : J ↦ c j) (q m) := by
    intro c m
    rw [aeval_rename]
    rfl
  set G : MvPolynomial ι k :=
    ∑ m ∈ p.support, rename (Subtype.val : J → ι) (q m) * X i ^ m with hG
  have hkey : ∀ c : ι → Ω, aeval c G =
      ∑ m ∈ p.support, aeval (fun j : J ↦ c j) (q m) * c i ^ m := by
    intro c
    rw [hG, map_sum]
    refine Finset.sum_congr rfl fun m _ ↦ ?_
    rw [map_mul, map_pow, aeval_X, hren]
  have hpa : ∑ m ∈ p.support, aeval (fun j : J ↦ a j) (q m) * a i ^ m = 0 := by
    have h0 := hpz
    rw [Polynomial.aeval_def, Polynomial.eval₂_eq_sum, Polynomial.sum_def] at h0
    calc ∑ m ∈ p.support, aeval (fun j : J ↦ a j) (q m) * a i ^ m
        = ∑ m ∈ p.support,
            algebraMap (↥(Algebra.adjoin k (a '' J))) Ω (p.coeff m) * a i ^ m :=
          Finset.sum_congr rfl fun m _ ↦ by rw [hq m]; rfl
      _ = 0 := h0
  -- Transfer the relation and one nonvanishing coefficient through `h`.
  have hGb : aeval b G = 0 := by
    have hmem : G ∈ idealOf k b := h ▸ (mem_idealOf_iff _).2 ((hkey a).trans hpa)
    exact (mem_idealOf_iff _).1 hmem
  obtain ⟨m₀, hm₀s⟩ := Polynomial.support_nonempty.2 hp0
  have hm₀ : p.coeff m₀ ≠ 0 := Polynomial.mem_support_iff.1 hm₀s
  have hqb0 : aeval (fun j : J ↦ b j) (q m₀) ≠ 0 := by
    intro h0
    have hb : rename (Subtype.val : J → ι) (q m₀) ∈ idealOf k b := by
      rw [mem_idealOf_iff, hren]
      exact h0
    rw [← h, mem_idealOf_iff, hren, hq m₀] at hb
    exact hm₀ (by exact_mod_cast hb)
  -- Reassemble an annihilator of `b i` over the `J`-coordinates of `b`.
  refine isAlgebraic_of_coeff_mem (p := ∑ m ∈ p.support,
      Polynomial.C (aeval (fun j : J ↦ b j) (q m)) * Polynomial.X ^ m) ?_ ?_ ?_
  · intro h0
    have hc : (∑ m ∈ p.support,
        Polynomial.C (aeval (fun j : J ↦ b j) (q m)) * Polynomial.X ^ m).coeff m₀ =
        aeval (fun j : J ↦ b j) (q m₀) := by
      rw [Polynomial.finsetSum_coeff]
      rw [Finset.sum_congr rfl fun m _ ↦
        Polynomial.coeff_C_mul_X_pow (aeval (fun j : J ↦ b j) (q m)) m m₀]
      rw [Finset.sum_ite_eq p.support m₀ fun m ↦ aeval (fun j : J ↦ b j) (q m)]
      exact if_pos hm₀s
    rw [h0, Polynomial.coeff_zero] at hc
    exact hqb0 hc.symm
  · calc (∑ m ∈ p.support,
          Polynomial.C (aeval (fun j : J ↦ b j) (q m)) * Polynomial.X ^ m).eval (b i)
        = ∑ m ∈ p.support, aeval (fun j : J ↦ b j) (q m) * b i ^ m := by
          rw [Polynomial.eval_finsetSum]
          exact Finset.sum_congr rfl fun m _ ↦ by
            rw [Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_pow,
              Polynomial.eval_X]
      _ = aeval b G := (hkey b).symm
      _ = 0 := hGb
  · intro m
    rw [Polynomial.finsetSum_coeff]
    refine sum_mem fun mm _ ↦ ?_
    rw [Polynomial.coeff_C_mul_X_pow]
    split
    · have hmem : aeval (fun j : J ↦ b j) (q mm) ∈ Algebra.adjoin k (b '' J) :=
        (hadj b).ge ((AlgHom.mem_range _).2 ⟨q mm, rfl⟩)
      exact algebra_adjoin_le_adjoin k _ hmem
    · exact zero_mem _

/-- Contrapositive form of `mem_racl_image_of_idealOf_eq`: relative
transcendence of a coordinate over other coordinates also transfers. -/
theorem notMem_racl_image_of_idealOf_eq {a b : ι → Ω}
    (h : idealOf k a = idealOf k b) {J : Set ι} {i : ι}
    (ha : a i ∉ racl k (a '' J)) : b i ∉ racl k (b '' J) :=
  fun hb ↦ ha (mem_racl_image_of_idealOf_eq k h.symm hb)

end RaclTransfer

/-- Transcendence of a coordinate transfers between tuples with equal
vanishing ideals. -/
theorem transcendental_of_idealOf_eq {a b : ι → Ω}
    (h : idealOf k a = idealOf k b) {j : ι}
    (ha : Transcendental k (a j)) : Transcendental k (b j) := by
  intro hb
  obtain ⟨p, hp0, hpz⟩ := hb
  -- Insert the annihilating polynomial into the `j`-th coordinate.
  set f : MvPolynomial ι k := Polynomial.aeval (X j : MvPolynomial ι k) p
    with hf
  have key : ∀ c : ι → Ω, aeval c f = Polynomial.aeval (c j) p := by
    intro c
    rw [hf]
    have hcomp : ((aeval c : MvPolynomial ι k →ₐ[k] Ω).comp
        (Polynomial.aeval (X j : MvPolynomial ι k) : Polynomial k →ₐ[k] _)) =
        Polynomial.aeval (c j) := by
      refine Polynomial.algHom_ext ?_
      simp
    exact congrArg (fun (g : Polynomial k →ₐ[k] Ω) ↦ g p) hcomp
  have hfb : f ∈ idealOf k b := by
    rw [mem_idealOf_iff, key, hpz]
  rw [← h, mem_idealOf_iff, key] at hfb
  exact ha ⟨p, hp0, hfb⟩


end

end AclGeom
