/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Codex, Claude
-/
import AclGeom.Correspondence.GeometricPrime
import AclGeom.Correspondence.FunctionField
import Mathlib.RingTheory.Flat.FaithfullyFlat.Algebra
import Mathlib.FieldTheory.LinearDisjoint
import Mathlib.RingTheory.Localization.Module

/-!
# Generic points after scalar extension

Blueprint Lemma `generic-extension` (a) asks for a generic point over an extension
with the original base-field relations and relative independence. The theorem here
constructs such a point in a quotient-fraction field over any extension `E/k` of an
algebraically closed `k`. Its ideal over `E` is exactly the extended original ideal,
and its ideal over `k` is exactly the original tuple's ideal.

Every coordinate subfamily that is independent over `k` remains independent over
`E`. Flatness preserves polynomial-evaluation injectivity, and tensor polynomial
and quotient equivalences identify the resulting map with evaluation at the new
point. This proves relative independence directly, without cancelling infinite
cardinals in the original absolute transcendence-degree equality. The inference
gap is reported on issue #5; the original source statement and proof are retained.

Genericity over `E` also forces full field freeness for every such point: the
explicit premise is equality of its `E`-ideal with the extended locus ideal.
Injective quotient evaluation transports tensor-factor linear disjointness to the
coordinate ring, and Mathlib's fraction-ring independence theorem promotes a basis
to the rational field generated by the point. This implication needs no algebraic
closedness assumption on the base or ambient fields.

Every private helper is consumed. The private validation consumers derive maximal
coordinate independence, test a dependent duplicated tuple, and derive genericity
from the constructive theorem before embedding the same point into an algebraic
closure and applying the universal field-freeness implication there. Explicit
rank/dimension bridges, ambient automorphisms and the full generic-extension lemma
remain separate obligations.

**Status:** constructive scalar-extension points with exact ideals and preservation
of every coordinate-independent subfamily, and the universal relation/field-freeness
implication for points generic over an extension (#5, `generic-extension` (a)).
-/

namespace AclGeom

open TensorProduct

noncomputable section

/-- The quotient-fraction tuple has exactly its defining ideal.
Consumed by `exists_genericPoint_baseChange`. -/
private theorem kernel_fraction_tuple {E : Type*} [Field E] {ι : Type*}
    (I : Ideal (MvPolynomial ι E)) [I.IsPrime] :
    let A := MvPolynomial ι E ⧸ I
    let F := FractionRing A
    let a : ι → F := fun i ↦ algebraMap A F (Ideal.Quotient.mk I (MvPolynomial.X i))
    AclGeom.idealOf E a = I := by
  classical
  dsimp only
  ext p
  rw [AclGeom.mem_idealOf_iff]
  have h : MvPolynomial.aeval
      (fun i ↦ algebraMap (MvPolynomial ι E ⧸ I) (FractionRing (MvPolynomial ι E ⧸ I))
        (Ideal.Quotient.mk I (MvPolynomial.X i))) p =
      algebraMap (MvPolynomial ι E ⧸ I) (FractionRing (MvPolynomial ι E ⧸ I))
        (Ideal.Quotient.mk I p) := by
    let φ : (MvPolynomial ι E ⧸ I) →ₐ[E] FractionRing (MvPolynomial ι E ⧸ I) :=
      IsScalarTower.toAlgHom E (MvPolynomial ι E ⧸ I) (FractionRing (MvPolynomial ι E ⧸ I))
    have hc : MvPolynomial.aeval
        (fun i ↦ algebraMap (MvPolynomial ι E ⧸ I) (FractionRing (MvPolynomial ι E ⧸ I))
          (Ideal.Quotient.mk I (MvPolynomial.X i))) = φ.comp (Ideal.Quotient.mkₐ E I) := by
      ext i
      simp [φ]
    exact congrArg (fun g ↦ g p) hc
  rw [h, map_eq_zero_iff _ (IsFractionRing.injective _ _), Ideal.Quotient.eq_zero_iff_mem]


/-- Scalar extension of any ideal contracts to the original ideal over a field.
Consumed by `exists_genericPoint_baseChange`; no primeness or ACF is required here. -/
private theorem contraction {k E : Type*} [Field k] [Field E] [Algebra k E]
    {ι : Type*} (I : Ideal (MvPolynomial ι k)) :
    (I.map (MvPolynomial.map (algebraMap k E))).comap
      (MvPolynomial.map (algebraMap k E)) = I := by
  let e := MvPolynomial.algebraTensorAlgEquiv k E (σ := ι)
  let J := I.map (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom
  let q : E ⊗[k] (MvPolynomial ι k ⧸ I) ≃ₐ[E] ((E ⊗[k] MvPolynomial ι k) ⧸ J) :=
    Algebra.TensorProduct.tensorQuotientEquiv (R := k) E (MvPolynomial ι k) E I
  have he : e.toRingHom.comp
      (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom =
      MvPolynomial.map (algebraMap k E) := by
    ext i <;> simp [e]
  have hi : I.map (MvPolynomial.map (algebraMap k E)) = J.map e.toRingHom := by
    change I.map (MvPolynomial.map (algebraMap k E)) =
      (I.map (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom).map e.toRingHom
    rw [Ideal.map_map, he]
  ext p
  rw [Ideal.mem_comap, hi]
  change MvPolynomial.map (algebraMap k E) p ∈ J.map e.toRingEquiv.toRingHom ↔ p ∈ I
  have hm : J.map e.toRingHom = J.comap e.symm.toRingHom :=
    Ideal.map_comap_of_equiv e.toRingEquiv
  rw [hm, Ideal.mem_comap]
  change e.symm (MvPolynomial.map (algebraMap k E) p) ∈ J ↔ p ∈ I
  rw [MvPolynomial.algebraTensorAlgEquiv_symm_map, ← Ideal.Quotient.eq_zero_iff_mem]
  have hz : q.symm (Ideal.Quotient.mk J ((1 : E) ⊗ₜ[k] p)) = 0 ↔
      Ideal.Quotient.mk J ((1 : E) ⊗ₜ[k] p) = 0 :=
    map_eq_zero_iff q.symm q.symm.injective
  rw [← hz]
  change (1 : E) ⊗ₜ[k] Ideal.Quotient.mk I p = 0 ↔ p ∈ I
  rw [Module.FaithfullyFlat.one_tmul_eq_zero_iff, Ideal.Quotient.eq_zero_iff_mem]


/-- Flat scalar extension preserves polynomial-evaluation injectivity.
Consumed by the coordinate-subfamily argument in `exists_genericPoint_baseChange`. -/
private theorem independent_tensor {k E A : Type*} [Field k] [CommRing E]
    [CommRing A] [Algebra k E] [Algebra k A] {ι : Type*} (x : ι → A)
    (hx : AlgebraicIndependent k x) :
    AlgebraicIndependent E (fun i ↦ (1 : E) ⊗ₜ[k] x i) := by
  let e := MvPolynomial.algebraTensorAlgEquiv k E (σ := ι)
  let f : E ⊗[k] MvPolynomial ι k →ₐ[E] E ⊗[k] A :=
    Algebra.TensorProduct.map (AlgHom.id E E) (MvPolynomial.aeval x)
  have hf : Function.Injective f :=
    Module.Flat.lTensor_preserves_injective_linearMap (M := E)
      (MvPolynomial.aeval x).toLinearMap hx
  have h : MvPolynomial.aeval (fun i ↦ (1 : E) ⊗ₜ[k] x i) =
      f.comp e.symm.toAlgHom := by
    ext i
    simp [f, e]
  rw [AlgebraicIndependent, h]
  exact hf.comp e.symm.injective

universe u v w z

/-- **Generic scalar-extension points preserve all coordinate-independent subfamilies.**
The constructed tuple has the exact extended ideal over `E` and the original ideal over `k`.
Only the base field must be algebraically closed; extension fields and variables are arbitrary. -/
theorem exists_genericPoint_baseChange {k : Type u} {E : Type v} {F : Type w}
    [Field k] [Field E] [Field F] [Algebra k E] [Algebra k F] [IsAlgClosed k]
    {ι : Type z} (a : ι → F) :
    ∃ (K : Type (max v z)) (_ : Field K) (_ : Algebra E K) (_ : Algebra k K)
      (_ : IsScalarTower k E K) (b : ι → K),
      idealOf E b = (idealOf k a).map (MvPolynomial.map (algebraMap k E)) ∧
      idealOf k b = idealOf k a ∧
      ∀ S : Set ι, AlgebraicIndependent k (fun j : S ↦ a j) →
        AlgebraicIndependent E (fun j : S ↦ b j) := by
  let I := idealOf k a
  let J := I.map (MvPolynomial.map (algebraMap k E))
  have : J.IsPrime := isPrime_map_of_isAlgClosed I
  let A := MvPolynomial ι E ⧸ J
  let K := FractionRing A
  let b : ι → K := fun i ↦ algebraMap A K (Ideal.Quotient.mk J (MvPolynomial.X i))
  have hE : idealOf E b = J := kernel_fraction_tuple J
  have hk : idealOf k b = I := by
    have hbase : idealOf k b = (idealOf E b).comap
        (MvPolynomial.map (algebraMap k E)) := by
      ext p
      rw [mem_idealOf_iff, Ideal.mem_comap, mem_idealOf_iff,
        MvPolynomial.aeval_map_algebraMap]
    rw [hbase, hE]
    exact contraction I
  refine ⟨K, inferInstance, inferInstance, inferInstance, inferInstance, b, hE, hk, ?_⟩
  intro S hS
  let C := MvPolynomial ι k ⧸ I
  let c : ι → C := fun i ↦ Ideal.Quotient.mk I (MvPolynomial.X i)
  have hc : AlgebraicIndependent k (fun j : S ↦ c j) := by
    apply AlgebraicIndependent.of_comp
      (Ideal.kerLiftAlg (MvPolynomial.aeval a : MvPolynomial ι k →ₐ[k] F))
    have hfun : (Ideal.kerLiftAlg (MvPolynomial.aeval a : MvPolynomial ι k →ₐ[k] F)) ∘
        (fun j : S ↦ c j) = fun j : S ↦ a j := by
      funext j
      exact (Ideal.kerLiftAlg_mk
        (MvPolynomial.aeval a : MvPolynomial ι k →ₐ[k] F) (MvPolynomial.X (j : ι))).trans
        (MvPolynomial.aeval_X (R := k) a (j : ι))
    rw [hfun]
    exact hS
  have ht := independent_tensor (E := E) (fun j : S ↦ c j) hc
  let e := MvPolynomial.algebraTensorAlgEquiv k E (σ := ι)
  let D := I.map (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom
  have he : e.toRingHom.comp
      (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom =
      MvPolynomial.map (algebraMap k E) := by
    ext i <;> simp [e]
  have hi : J = D.map (e : E ⊗[k] MvPolynomial ι k →+* MvPolynomial ι E) := by
    change I.map (MvPolynomial.map (algebraMap k E)) =
      (I.map (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom).map e.toRingHom
    rw [Ideal.map_map, he]
  let q : E ⊗[k] C ≃ₐ[E] A :=
    (Algebra.TensorProduct.tensorQuotientEquiv (R := k) E (MvPolynomial ι k) E I).trans
      (Ideal.quotientEquivAlg D J e hi)
  let φ : A →ₐ[E] K := IsScalarTower.toAlgHom E A K
  have hb := ht.map' (f := φ.comp q.toAlgHom)
    ((IsFractionRing.injective A K).comp q.injective)
  have hq (i : ι) : q ((1 : E) ⊗ₜ[k] c i) = Ideal.Quotient.mk J (MvPolynomial.X i) := by
    change Ideal.quotientEquivAlg D J e hi
      (Algebra.TensorProduct.tensorQuotientEquiv (R := k) E (MvPolynomial ι k) E I
        ((1 : E) ⊗ₜ[k] Ideal.Quotient.mk I (MvPolynomial.X i))) = _
    rw [Algebra.TensorProduct.tensorQuotientEquiv_apply_tmul]
    change Ideal.quotientEquivAlg D J e hi
      (Ideal.Quotient.mk D ((1 : E) ⊗ₜ[k] MvPolynomial.X i)) = _
    rw [Ideal.quotientEquivAlg_mk]
    simp [e]
  have hfun : (φ.comp q.toAlgHom) ∘ (fun j : S ↦ (1 : E) ⊗ₜ[k] c j) =
      fun j : S ↦ b j := by
    funext j
    change φ (q ((1 : E) ⊗ₜ[k] c j)) = b j
    rw [hq]
    rfl
  rw [hfun] at hb
  exact hb


open scoped IntermediateField.algebraAdjoinAdjoin

/-- Generic-over-extension quotient evaluation identifies two linearly disjoint subalgebras.
Consumed by `isGeneric_baseChange`, before passing from the coordinate ring
to its fraction field. -/
private theorem subalgebra_disjoint_of_generic {k E Ω : Type*}
    [Field k] [Field E] [Field Ω] [Algebra k E] [Algebra k Ω] [Algebra E Ω]
    [IsScalarTower k E Ω] {ι : Type*} {b : ι → Ω} {I : Ideal (MvPolynomial ι k)}
    (hgen : idealOf E b = I.map (MvPolynomial.map (algebraMap k E))) :
    (IsScalarTower.toAlgHom k E Ω).range.LinearDisjoint
      (Algebra.adjoin k (Set.range b)) := by
  let C := MvPolynomial ι k ⧸ I
  let J := I.map (MvPolynomial.map (algebraMap k E))
  let e := MvPolynomial.algebraTensorAlgEquiv k E (σ := ι)
  let D := I.map (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom
  have he : e.toRingHom.comp
      (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom =
      MvPolynomial.map (algebraMap k E) := by
    ext j <;> simp [e]
  have hJ : J = D.map (e : E ⊗[k] MvPolynomial ι k →+* MvPolynomial ι E) := by
    change I.map (MvPolynomial.map (algebraMap k E)) =
      (I.map (Algebra.TensorProduct.includeRight (A := E) (R := k)).toRingHom).map e.toRingHom
    rw [Ideal.map_map, he]
  let q : E ⊗[k] C ≃ₐ[E] (MvPolynomial ι E ⧸ idealOf E b) :=
    ((Algebra.TensorProduct.tensorQuotientEquiv (R := k) E (MvPolynomial ι k) E I).trans
      (Ideal.quotientEquivAlg D J e hJ)).trans
      (Ideal.quotientEquivAlgOfEq E hgen.symm)
  let φ := Ideal.kerLiftAlg (MvPolynomial.aeval b : MvPolynomial ι E →ₐ[E] Ω)
  let i : E ⊗[k] C →ₐ[k] Ω := (φ.comp q.toAlgHom).restrictScalars k
  have hi : Function.Injective i :=
    (Ideal.kerLiftAlg_injective (MvPolynomial.aeval b : MvPolynomial ι E →ₐ[E] Ω)).comp
      q.injective
  have hq (x : E) (p : MvPolynomial ι k) :
      q (x ⊗ₜ[k] Ideal.Quotient.mk I p) =
        Ideal.Quotient.mk (idealOf E b) (e (x ⊗ₜ[k] p)) := by
    change Ideal.quotientEquivAlgOfEq E hgen.symm
      (Ideal.quotientEquivAlg D J e hJ
        (Algebra.TensorProduct.tensorQuotientEquiv (R := k) E (MvPolynomial ι k) E I
          (x ⊗ₜ[k] Ideal.Quotient.mk I p))) = _
    rw [Algebra.TensorProduct.tensorQuotientEquiv_apply_tmul]
    change Ideal.quotientEquivAlgOfEq E hgen.symm
      (Ideal.quotientEquivAlg D J e hJ
        (Ideal.Quotient.mk D (x ⊗ₜ[k] p))) = _
    rw [Ideal.quotientEquivAlg_mk, Ideal.quotientEquivAlgOfEq_mk]
  have hit (x : E) (p : MvPolynomial ι k) :
      i (x ⊗ₜ[k] Ideal.Quotient.mk I p) = algebraMap E Ω x * MvPolynomial.aeval b p := by
    change φ (q (x ⊗ₜ[k] Ideal.Quotient.mk I p)) = _
    rw [hq]
    change Ideal.kerLiftAlg (MvPolynomial.aeval b : MvPolynomial ι E →ₐ[E] Ω)
      (Ideal.Quotient.mk (RingHom.ker (MvPolynomial.aeval b : MvPolynomial ι E →ₐ[E] Ω))
        (e (x ⊗ₜ[k] p))) = _
    rw [Ideal.kerLiftAlg_mk]
    change MvPolynomial.aeval b (MvPolynomial.algebraTensorAlgEquiv k E (x ⊗ₜ[k] p)) = _
    rw [MvPolynomial.algebraTensorAlgEquiv_tmul]
    rw [map_smul, MvPolynomial.aeval_map_algebraMap, Algebra.smul_def]
  have hleft : i.comp (Algebra.TensorProduct.includeLeft : E →ₐ[k] E ⊗[k] C) =
      IsScalarTower.toAlgHom k E Ω := by
    ext x
    change i (x ⊗ₜ[k] (1 : C)) = algebraMap E Ω x
    simpa using hit x 1
  have hright : (i.comp (Algebra.TensorProduct.includeRight : C →ₐ[k] E ⊗[k] C)).comp
      (Ideal.Quotient.mkₐ k I) = MvPolynomial.aeval b := by
    ext j
    simp only [AlgHom.comp_apply, Algebra.TensorProduct.includeRight_apply, MvPolynomial.aeval_X]
    change i ((1 : E) ⊗ₜ[k] Ideal.Quotient.mk I (MvPolynomial.X j)) = b j
    simpa using hit 1 (MvPolynomial.X j)
  have hR : (i.comp (Algebra.TensorProduct.includeRight : C →ₐ[k] E ⊗[k] C)).range =
      (MvPolynomial.aeval b : MvPolynomial ι k →ₐ[k] Ω).range := by
    have hm : (Ideal.Quotient.mkₐ k I).range = ⊤ :=
      (AlgHom.range_eq_top _).2 Ideal.Quotient.mk_surjective
    calc
      _ = ((i.comp Algebra.TensorProduct.includeRight).comp (Ideal.Quotient.mkₐ k I)).range := by
        rw [AlgHom.range_comp (Ideal.Quotient.mkₐ k I)
          (i.comp Algebra.TensorProduct.includeRight), hm, Algebra.map_top]
      _ = _ := congrArg AlgHom.range hright
  have H := (Subalgebra.LinearDisjoint.include_range k E C).map i hi
  rw [← AlgHom.range_comp, ← AlgHom.range_comp, hleft, hR,
    ← Algebra.adjoin_range_eq_range_aeval] at H
  exact H

/-- **Every point generic over an extension has the original relations and field freeness.**
The explicitly named `hgen` is genericity over `E`: its ideal is the extended locus ideal.
The base ideal contracts exactly, and the `E`-image is linearly disjoint from the field generated
by the point. All fields and variables are arbitrary; algebraic closedness is not required. -/
theorem isGeneric_baseChange {k E Ω : Type*}
    [Field k] [Field E] [Field Ω] [Algebra k E] [Algebra k Ω] [Algebra E Ω]
    [IsScalarTower k E Ω] {ι : Type*} {b : ι → Ω} {I : Ideal (MvPolynomial ι k)}
    (hgen : idealOf E b = I.map (MvPolynomial.map (algebraMap k E))) :
    idealOf k b = I ∧
      (IsScalarTower.toAlgHom k E Ω).fieldRange.LinearDisjoint
        (IntermediateField.adjoin k (Set.range b)) := by
  have hk : idealOf k b = I := by
    have hbase : idealOf k b = (idealOf E b).comap
        (MvPolynomial.map (algebraMap k E)) := by
      ext p
      rw [mem_idealOf_iff, Ideal.mem_comap, mem_idealOf_iff,
        MvPolynomial.aeval_map_algebraMap]
    rw [hbase, hgen]
    exact contraction I
  refine ⟨hk, ?_⟩
  let A := (IsScalarTower.toAlgHom k E Ω).fieldRange
  let a := Module.Free.chooseBasis k A
  have H : A.toSubalgebra.LinearDisjoint (Algebra.adjoin k (Set.range b)) :=
    subalgebra_disjoint_of_generic hgen
  have hring : LinearIndependent (Algebra.adjoin k (Set.range b)) (A.val ∘ a) :=
    H.linearIndependent_left_of_flat a.linearIndependent
  have hfield : LinearIndependent (IntermediateField.adjoin k (Set.range b)) (A.val ∘ a) :=
    (LinearIndependent.iff_fractionRing (Algebra.adjoin k (Set.range b))
      (IntermediateField.adjoin k (Set.range b))).mp hring
  exact IntermediateField.LinearDisjoint.of_basis_left a hfield

end

end AclGeom
