/-
Copyright (c) 2026 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz, Claude
-/
import AclGeom.Geometry.FiniteRank

/-!
# Acceptance test for milestone M1: rational function fields

The blueprint's acceptance test for M1: construct the lattice and point
geometry for the rational function field `k(t₁,…,tₙ)/k` and prove the
canonical lattice/closed-point-set round trips.

Concretely, with `K = FractionRing (MvPolynomial (Fin n) k)`:

* the complete lattice `𝒢(K/k)` and its atomistic structure instantiate;
* each variable `tᵢ` is transcendental over `k`, hence generates a point;
* the variables generate everything: `racl k (range t) = ⊤`, so the whole
  geometry has rank at most `n`;
* the round trips are `ClosedIF.pointSetIso`, instantiated here.

This module is part of the formalization of the Evans–Hrushovski–Gismatullin
reconstruction theorem; the source of truth is `sources/blueprint.tex`.
-/

namespace AclGeom.Test

open IntermediateField MvPolynomial AclGeom

noncomputable section

variable (k : Type*) [Field k] (n : ℕ)

/-- The rational function field `k(t₁,…,tₙ)`. -/
abbrev RatFn := FractionRing (MvPolynomial (Fin n) k)

/-- The lattice of relatively algebraically closed subextensions of
`k(t₁,…,tₙ)/k` is a complete lattice. -/
example : CompleteLattice (ClosedIF k (RatFn k n)) := inferInstance

/-- It is atomistic. -/
example : IsAtomistic (ClosedIF k (RatFn k n)) := inferInstance

/-- The canonical round trips: the closed lattice is order isomorphic to the
lattice of closed point sets. -/
example : ClosedIF k (RatFn k n) ≃o ClosedPointSet k (RatFn k n) :=
  ClosedIF.pointSetIso k (RatFn k n)

/-- The `i`-th variable, as an element of the rational function field. -/
def t (i : Fin n) : RatFn k n :=
  algebraMap (MvPolynomial (Fin n) k) (RatFn k n) (X i)

/-- The variables are algebraically independent over `k`. -/
theorem algebraicIndependent_t : AlgebraicIndependent k (t k n) := by
  have h := (MvPolynomial.algebraicIndependent_X (Fin n) k).map
    (f := IsScalarTower.toAlgHom k (MvPolynomial (Fin n) k) (RatFn k n))
    (Set.injOn_of_injective
      (IsFractionRing.injective (MvPolynomial (Fin n) k) (RatFn k n)))
  exact h

/-- Each variable is transcendental over `k`. -/
theorem transcendental_t (i : Fin n) : Transcendental k (t k n i) := by
  have h := (algebraicIndependent_t k n).comp (fun _ : Unit ↦ i)
    (fun a b _ ↦ Subsingleton.elim a b)
  exact algebraicIndependent_unique_type_iff.1 h

/-- Each variable generates a point of the geometry. -/
theorem t_notMem_bot (i : Fin n) : t k n i ∉ (⊥ : ClosedIF k (RatFn k n)) :=
  fun h ↦ transcendental_t k n i (ClosedIF.mem_bot_iff.1 h)

/-- The point of the `i`-th variable. -/
def tPoint (i : Fin n) : Point k (RatFn k n) :=
  Point.mk' k (t k n i) (t_notMem_bot k n i)

/-- The variables generate the field: `k(t₁,…,tₙ)` adjoined over `k` is
everything. -/
theorem adjoin_range_t : adjoin k (Set.range (t k n)) = ⊤ := by
  rw [eq_top_iff]
  intro z _
  obtain ⟨p, q, -, rfl⟩ := IsFractionRing.div_surjective (MvPolynomial (Fin n) k) z
  have key : ∀ p : MvPolynomial (Fin n) k,
      algebraMap (MvPolynomial (Fin n) k) (RatFn k n) p ∈ adjoin k (Set.range (t k n)) := by
    intro p
    have hp : p ∈ Algebra.adjoin k (Set.range (X : Fin n → MvPolynomial (Fin n) k)) := by
      rw [MvPolynomial.adjoin_range_X]
      trivial
    have himg : algebraMap (MvPolynomial (Fin n) k) (RatFn k n) p ∈
        (Algebra.adjoin k (Set.range (X : Fin n → MvPolynomial (Fin n) k))).map
          (IsScalarTower.toAlgHom k (MvPolynomial (Fin n) k) (RatFn k n)) :=
      ⟨p, hp, rfl⟩
    rw [AlgHom.map_adjoin (IsScalarTower.toAlgHom k (MvPolynomial (Fin n) k) (RatFn k n)),
      ← Set.range_comp] at himg
    exact algebra_adjoin_le_adjoin k _ himg
  exact div_mem (key p) (key q)

/-- The relative algebraic closure of the variables is everything. -/
theorem racl_range_t : racl k (Set.range (t k n)) = ⊤ := by
  rw [eq_top_iff, ← adjoin_range_t k n]
  exact adjoin_le_racl k _

/-- The whole geometry has rank at most `n` (blueprint acceptance: the
geometry of `k(t₁,…,tₙ)/k` is generated by the `n` points of the
variables). -/
theorem rankLE_top : RankLE n (⊤ : ClosedIF k (RatFn k n)) := by
  refine ⟨tPoint k n, ?_⟩
  have h1 : (⨆ i, (tPoint k n i).1) =
      sSup ((fun x ↦ ClosedIF.point k x) '' Set.range (t k n)) := by
    rw [iSup, ← Set.range_comp]
    rfl
  have h2 : (sSup ((fun x ↦ ClosedIF.point k x) '' Set.range (t k n))).1 = ⊤ := by
    rw [sSup_point_image, racl_range_t]
  rw [h1, ClosedIF.le_iff, ClosedIF.coe_top, h2]

end

end AclGeom.Test
